CREATE View [dbo].[CashflowByEntity]
as 
select 
NotePeriodicCalcByEntity_AutoID,
NotePeriodicCalcAutoID,
NoteID as NoteKey,
CRENoteID as NoteID,
EntityName,
PctAllocation,
PeriodEndDate,
[Month],
ActualCashFlows,
GAAPCashFlows,
EndingGAAPBookValue,
TotalGAAPIncomeforthePeriod,
InterestAccrualforthePeriod,
PIKInterestAccrualforthePeriod,
TotalAmortAccrualForPeriod,
AccumulatedAmort,
BeginningBalance,
TotalFutureAdvancesForThePeriod,
TotalDiscretionaryCurtailmentsforthePeriod,
InterestPaidOnPaymentDate,
TotalCouponStrippedforthePeriod,
CouponStrippedonPaymentDate,
ScheduledPrincipal,
PrincipalPaid,
BalloonPayment,
EndingBalance,

null as ExitFeeIncludedInLevelYield,
null as ExitFeeExcludedFromLevelYield,
null as AdditionalFeesIncludedInLevelYield,
null as AdditionalFeesExcludedFromLevelYield,
null as OriginationFeeStripping,
null as ExitFeeStrippingIncldinLevelYield,
null as ExitFeeStrippingExcldfromLevelYield,
null as AddlFeesStrippingIncldinLevelYield,
null as AddlFeesStrippingExcldfromLevelYield,

EndOfPeriodWAL,
PIKInterestFromPIKSourceNote,
PIKInterestTransferredToRelatedNote,
PIKInterestForThePeriod,
BeginningPIKBalanceNotInsideLoanBalance,
PIKInterestForPeriodNotInsideLoanBalance,
PIKBalanceBalloonPayment,
EndingPIKBalanceNotInsideLoanBalance,
CostBasis,
PreCapBasis,
BasisCap,
AmortAccrualLevelYield,
ScheduledPrincipalShortfall,
PrincipalShortfall,
PrincipalLoss,
InterestForPeriodShortfall,
InterestPaidOnPMTDateShortfall,
CumulativeInterestPaidOnPMTDateShortfall,
InterestShortfallLoss,
InterestShortfallRecovery,
BeginningFinancingBalance,
TotalFinancingDrawsCurtailmentsForPeriod,
FinancingBalloon,
EndingFinancingBalance,
FinancingInterestPaid,
FinancingFeesPaid,
PeriodLeveredYield,
OrigFeeAccrual ,
DiscountPremiumAccrual  ,
ExitFeeAccrual  ,
CreatedBy,
CreatedDate,
UpdatedBy,
UpdatedDate,
AllInCouponRate,
[CleanCost],
[GrossDeferredFees],
[DeferredFeesReceivable],
[CleanCostPrice],
[AmortizedCostPrice],
[AdditionalFeeAccrual],
[CapitalizedCostAccrual],
DailySpreadInterestbeforeStrippingRule,
DailyLiborInterestbeforeStrippingRule,
ReversalofPriorInterestAccrual,
InterestReceivedinCurrentPeriod,
CurrentPeriodInterestAccrual,
TotalGAAPInterestFortheCurrentPeriod,
AccruedInterestBI as AccruedInterest,
InvestmentBasis,
CurrentPeriodInterestAccrualPeriodEnddate,
LIBORPercentage,
SpreadPercentage,

AnalysisID,
AnalysisName,
FeeStrippedforthePeriod,
PIKInterestPercentage

From [DW].[NotePeriodicCalcByEntityBI]

Where AnalysisID = 'C10F3372-0FC2-4861-A9F5-148F1F80804F'


