Create View [dbo].[Staging_IntegartionCashFlow]
As


Select Scenario,
AnalysisID,
NoteKey,
NoteID,
PeriodEndDate,
In_EndingGAAPBookValue,
In_TotalAmortAccrualForPeriod,
In_AccumulatedAmort,
In_DiscountPremiumAccrual,
In_AccumaltedDiscountPremium,
In_CapitalizedCostAccrual,
In_AccumalatedCapitalizedCost,
In_CurrentPeriodInterestAccrualPeriodEnddate,
St_EndingGAAPBookValue,
St_TotalAmortAccrualForPeriod,
St_AccumulatedAmort,
St_DiscountPremiumAccrual,
St_AccumaltedDiscountPremium,
St_CapitalizedCostAccrual,
St_AccumalatedCapitalizedCost,
St_CurrentPeriodInterestAccrualPeriodEnddate 
from DW.Staging_IntegartionCashFlowBI
