--Update [CORE].RateSpreadSchedule set [CORE].RateSpreadSchedule.date = a.closingdate
--From(
--	Select rs.RateSpreadScheduleID,n.noteid,n.crenoteid,n.closingdate,e.effectivestartdate,rs.date as StartDate,LValueTypeID.name as ValueType
--	from [CORE].RateSpreadSchedule rs  
--	INNER JOIN [CORE].[Event] e on e.EventID = rs.EventId  
--	LEFT JOIN [CORE].[Lookup] LValueTypeID ON LValueTypeID.LookupID = rs.ValueTypeID  
--	LEFT JOIN [CORE].[Lookup] LIntCalcMethodID ON LIntCalcMethodID.LookupID = rs.IntCalcMethodID  
--	INNER JOIN [CORE].[Account] acc ON acc.AccountID = e.AccountID
--	INNER JOIN [CRE].[Note] n ON n.Account_AccountID = acc.AccountID
--	where e.StatusID = 1 and acc.isdeleted <> 1
--	and rs.date < n.closingdate
--	---order by n.crenoteid,n.closingdate,e.effectivestartdate,rs.date
--)a
--where [CORE].RateSpreadSchedule.RateSpreadScheduleID = a.RateSpreadScheduleID

