CREATE TABLE [Core].[AccountingClosePeriodicArchive] (
    [AccountingClosePeriodicArchiveID]             INT              IDENTITY (1, 1) NOT NULL,
    [PeriodID]                                     UNIQUEIDENTIFIER NULL,
    [NotePeriodicCalcID]                           UNIQUEIDENTIFIER NULL,
    [NoteID]                                       UNIQUEIDENTIFIER NULL,
    [PeriodEndDate]                                DATE             NULL,
    [Month]                                        INT              NULL,
    [ActualCashFlows]                              DECIMAL (28, 15) NULL,
    [GAAPCashFlows]                                DECIMAL (28, 15) NULL,
    [EndingGAAPBookValue]                          DECIMAL (28, 15) NULL,
    [TotalAmortAccrualForPeriod]                   DECIMAL (28, 15) NULL,
    [AccumulatedAmort]                             DECIMAL (28, 15) NULL,
    [BeginningBalance]                             DECIMAL (28, 15) NULL,
    [TotalFutureAdvancesForThePeriod]              DECIMAL (28, 15) NULL,
    [TotalDiscretionaryCurtailmentsforthePeriod]   DECIMAL (28, 15) NULL,
    [InterestPaidOnPaymentDate]                    DECIMAL (28, 15) NULL,
    [TotalCouponStrippedforthePeriod]              DECIMAL (28, 15) NULL,
    [CouponStrippedonPaymentDate]                  DECIMAL (28, 15) NULL,
    [ScheduledPrincipal]                           DECIMAL (28, 15) NULL,
    [PrincipalPaid]                                DECIMAL (28, 15) NULL,
    [BalloonPayment]                               DECIMAL (28, 15) NULL,
    [EndingBalance]                                DECIMAL (28, 15) NULL,
    [ExitFeeIncludedInLevelYield]                  DECIMAL (28, 15) NULL,
    [ExitFeeExcludedFromLevelYield]                DECIMAL (28, 15) NULL,
    [AdditionalFeesIncludedInLevelYield]           DECIMAL (28, 15) NULL,
    [AdditionalFeesExcludedFromLevelYield]         DECIMAL (28, 15) NULL,
    [OriginationFeeStripping]                      DECIMAL (28, 15) NULL,
    [ExitFeeStrippingIncldinLevelYield]            DECIMAL (28, 15) NULL,
    [ExitFeeStrippingExcldfromLevelYield]          DECIMAL (28, 15) NULL,
    [AddlFeesStrippingIncldinLevelYield]           DECIMAL (28, 15) NULL,
    [AddlFeesStrippingExcldfromLevelYield]         DECIMAL (28, 15) NULL,
    [EndOfPeriodWAL]                               DECIMAL (28, 15) NULL,
    [PIKInterestFromPIKSourceNote]                 DECIMAL (28, 15) NULL,
    [PIKInterestTransferredToRelatedNote]          DECIMAL (28, 15) NULL,
    [PIKInterestForThePeriod]                      DECIMAL (28, 15) NULL,
    [BeginningPIKBalanceNotInsideLoanBalance]      DECIMAL (28, 15) NULL,
    [PIKInterestForPeriodNotInsideLoanBalance]     DECIMAL (28, 15) NULL,
    [PIKBalanceBalloonPayment]                     DECIMAL (28, 15) NULL,
    [EndingPIKBalanceNotInsideLoanBalance]         DECIMAL (28, 15) NULL,
    [CostBasis]                                    DECIMAL (28, 15) NULL,
    [PreCapBasis]                                  DECIMAL (28, 15) NULL,
    [BasisCap]                                     DECIMAL (28, 15) NULL,
    [AmortAccrualLevelYield]                       DECIMAL (28, 15) NULL,
    [ScheduledPrincipalShortfall]                  DECIMAL (28, 15) NULL,
    [PrincipalShortfall]                           DECIMAL (28, 15) NULL,
    [PrincipalLoss]                                DECIMAL (28, 15) NULL,
    [InterestForPeriodShortfall]                   DECIMAL (28, 15) NULL,
    [InterestPaidOnPMTDateShortfall]               DECIMAL (28, 15) NULL,
    [CumulativeInterestPaidOnPMTDateShortfall]     DECIMAL (28, 15) NULL,
    [InterestShortfallLoss]                        DECIMAL (28, 15) NULL,
    [InterestShortfallRecovery]                    DECIMAL (28, 15) NULL,
    [BeginningFinancingBalance]                    DECIMAL (28, 15) NULL,
    [TotalFinancingDrawsCurtailmentsForPeriod]     DECIMAL (28, 15) NULL,
    [FinancingBalloon]                             DECIMAL (28, 15) NULL,
    [EndingFinancingBalance]                       DECIMAL (28, 15) NULL,
    [FinancingInterestPaid]                        DECIMAL (28, 15) NULL,
    [FinancingFeesPaid]                            DECIMAL (28, 15) NULL,
    [PeriodLeveredYield]                           DECIMAL (28, 15) NULL,
    [OrigFeeAccrual]                               DECIMAL (28, 15) NULL,
    [DiscountPremiumAccrual]                       DECIMAL (28, 15) NULL,
    [ExitFeeAccrual]                               DECIMAL (28, 15) NULL,
    [AllInCouponRate]                              DECIMAL (28, 15) NULL,
    [GrossDeferredFees]                            DECIMAL (28, 15) NULL,
    [DeferredFeesReceivable]                       DECIMAL (28, 15) NULL,
    [CleanCostPrice]                               DECIMAL (28, 15) NULL,
    [AmortizedCostPrice]                           DECIMAL (28, 15) NULL,
    [AdditionalFeeAccrual]                         DECIMAL (28, 15) NULL,
    [CapitalizedCostAccrual]                       DECIMAL (28, 15) NULL,
    [DailySpreadInterestbeforeStrippingRule]       DECIMAL (28, 15) NULL,
    [DailyLiborInterestbeforeStrippingRule]        DECIMAL (28, 15) NULL,
    [ReversalofPriorInterestAccrual]               DECIMAL (28, 15) NULL,
    [InterestReceivedinCurrentPeriod]              DECIMAL (28, 15) NULL,
    [CurrentPeriodInterestAccrual]                 DECIMAL (28, 15) NULL,
    [TotalGAAPInterestFortheCurrentPeriod]         DECIMAL (28, 15) NULL,
    [CleanCost]                                    DECIMAL (28, 15) NULL,
    [InvestmentBasis]                              DECIMAL (28, 15) NULL,
    [CurrentPeriodInterestAccrualPeriodEnddate]    DECIMAL (28, 15) NULL,
    [LIBORPercentage]                              DECIMAL (28, 15) NULL,
    [SpreadPercentage]                             DECIMAL (28, 15) NULL,
    [AnalysisID]                                   UNIQUEIDENTIFIER NULL,
    [FeeStrippedforthePeriod]                      DECIMAL (28, 15) NULL,
    [PIKInterestPercentage]                        DECIMAL (28, 15) NULL,
    [AmortizedCost]                                DECIMAL (28, 15) NULL,
    [InterestSuspenseAccountActivityforthePeriod]  DECIMAL (28, 15) NULL,
    [InterestSuspenseAccountBalance]               DECIMAL (28, 15) NULL,
    [AllInBasisValuation]                          DECIMAL (28, 15) NULL,
    [AllInPIKRate]                                 DECIMAL (28, 15) NULL,
    [CurrentPeriodPIKInterestAccrualPeriodEnddate] DECIMAL (28, 15) NULL,
    [PIKInterestPaidForThePeriod]                  DECIMAL (28, 15) NULL,
    [PIKInterestAppliedForThePeriod]               DECIMAL (28, 15) NULL,
    [EndingPreCapPVBasis]                          DECIMAL (28, 15) NULL,
    [LevelYieldIncomeForThePeriod]                 DECIMAL (28, 15) NULL,
    [PVAmortTotalIncomeMethod]                     DECIMAL (28, 15) NULL,
    [EndingCleanCostLY]                            DECIMAL (28, 15) NULL,
    [EndingAccumAmort]                             DECIMAL (28, 15) NULL,
    [PVAmortForThePeriod]                          DECIMAL (28, 15) NULL,
    [EndingSLBasis]                                DECIMAL (28, 15) NULL,
    [SLAmortForThePeriod]                          DECIMAL (28, 15) NULL,
    [SLAmortOfTotalFeesInclInLY]                   DECIMAL (28, 15) NULL,
    [SLAmortOfDiscountPremium]                     DECIMAL (28, 15) NULL,
    [SLAmortOfCapCost]                             DECIMAL (28, 15) NULL,
    [EndingAccumSLAmort]                           DECIMAL (28, 15) NULL,
    [EndingPreCapGAAPBasis]                        DECIMAL (28, 15) NULL,
    [PIKPrincipalPaidForThePeriod]                 DECIMAL (28, 15) NULL,
    [RemainingUnfundedCommitment]                  DECIMAL (28, 15) NULL,
    [CalcEngineType]                               INT              NULL,
    [levyld]                                       DECIMAL (28, 15) NULL,
    [cum_dailypikint]                              DECIMAL (28, 15) NULL,
    [cum_baladdon_am]                              DECIMAL (28, 15) NULL,
    [cum_baladdon_nonam]                           DECIMAL (28, 15) NULL,
    [cum_dailyint]                                 DECIMAL (28, 15) NULL,
    [cum_ddbaladdon]                               DECIMAL (28, 15) NULL,
    [cum_ddintdelta]                               DECIMAL (28, 15) NULL,
    [initbal]                                      DECIMAL (28, 15) NULL,
    [cum_fee_levyld]                               DECIMAL (28, 15) NULL,
    [period_ddintdelta_shifted]                    DECIMAL (28, 15) NULL,
    [intdeltabal]                                  DECIMAL (28, 15) NULL,
    [cum_exit_fee_excl_lv_yield]                   DECIMAL (28, 15) NULL,
    [IsDeleted]                                    INT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]                                    NVARCHAR (256)   NULL,
    [CreatedDate]                                  DATETIME         NULL,
    [UpdatedBy]                                    NVARCHAR (256)   NULL,
    [UpdatedDate]                                  DATETIME         NULL,
    [DropDateInterestDeltaBalance]                 DECIMAL (28, 15) NULL,
    [AccPeriodEnd]                                 DATE             NULL,
    [AccPeriodStart]                               DATE             NULL,
    [pmtdtnotadj]                                  DATE             NULL,
    [pmtdt]                                        DATE             NULL,
    [periodpikint]                                 DECIMAL (28, 15) NULL,
    [CurrentPeriodPIKInterestAccrual]              DECIMAL (28, 15) NULL,
    [DeferredFeeGAAPBasis]                         DECIMAL (28, 15) NULL,
    [CapitalizedCostLevelYield]                    DECIMAL (28, 15) NULL,
    [CapitalizedCostGAAPBasis]                     DECIMAL (28, 15) NULL,
    [CapitalizedCostAccumulatedAmort]              DECIMAL (28, 15) NULL,
    [DiscountPremiumLevelYield]                    DECIMAL (28, 15) NULL,
    [DiscountPremiumGAAPBasis]                     DECIMAL (28, 15) NULL,
    [DiscountPremiumAccumulatedAmort]              DECIMAL (28, 15) NULL,
    [InterestPastDue]                              DECIMAL (28, 15) NULL,
    [AverageDailyBalance]                          DECIMAL (28, 15) NULL,
	[cum_unusedfee]                                DECIMAL (28, 15) NULL,
    [PrincipalWriteoff]                            DECIMAL (28, 15) NULL,
    [NetPIKAmountForThePeriod]                     DECIMAL (28, 15) NULL,
    [ParentAccountID]                              UNIQUEIDENTIFIER NULL,
    [CashInterest]                                 DECIMAL (28, 15) NULL,
    [CapitalizedInterest]                          DECIMAL (28, 15) NULL,
    [CumulativeDailyPIKFromInterest]               DECIMAL (28, 15) NULL,
    [CumulativeDailyPIKCompounding]                DECIMAL (28, 15) NULL,
    [CumulativeDailyIntoPIK]                       DECIMAL (28, 15) NULL
    CONSTRAINT [PK_AccountingClosePeriodicArchiveID] PRIMARY KEY CLUSTERED ([AccountingClosePeriodicArchiveID] ASC)
);




