CREATE TABLE [Core].[AnalysisParameter] (
    [AnalysisParameterID]         UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [AnalysisID]                  UNIQUEIDENTIFIER NOT NULL,
    [CreatedBy]                   NVARCHAR (256)   NULL,
    [CreatedDate]                 DATETIME         NULL,
    [UpdatedBy]                   NVARCHAR (256)   NULL,
    [UpdatedDate]                 DATETIME         NULL,
    [MaturityScenarioOverrideID]  INT              NULL,
    [MaturityAdjustment]          INT              NULL,
    [FunctionName]                NVARCHAR (256)   NULL,
    [IndexScenarioOverride]       INT              NULL,
    [CalculationMode]             INT              NULL,
    [ExcludedForcastedPrePayment] INT              NULL,
    [AutoCalculationFrequency]    INT              NULL,
    [NextExecuteTime]             DATETIME         NULL,
    [UseActuals]                  INT              NULL,
	[UseBusinessDayAdjustment]    INT              NULL,
    JsonTemplateMasterID          int              NULL,
    [CalculationFrequency]             INT              NULL,
    CalcEngineType             INT              NULL,
    AllowCalcOverride             INT              NULL,
    AllowCalcAlongWithDefault             INT              NULL,
    AccountingClose INT null,
	CalculateLiability int,
    IncludeProjectedPrincipalWriteoff int,
	[UseFinancingMaturityDateOverride]    INT              NULL,
	[UseMaturityAdjustmentMonths]         INT     NULL,
    [IncludeInDiscrepancy]                INT       NULL,
    [LastCalculatedDate]                  DATETIME  NULL,
    OperationMode NVARCHAR (256)  NULL,
	EqDelayMonths INT            NULL,
	FinDelayMonths INT            NULL,
	MinEqBalForFinStart decimal(28,15)            NULL,
	SublineEqApplyMonths INT            NULL,
	SublineFinApplyMonths INT            NULL,
	DebtCallDaysOfTheMonth INT            NULL,
	CapitalCallDaysOfTheMonth INT            NULL,
    CONSTRAINT [PK_AnalysisParameterID] PRIMARY KEY CLUSTERED ([AnalysisParameterID] ASC),
    CONSTRAINT [FK_AnalysisParameter_AnalysisID] FOREIGN KEY ([AnalysisID]) REFERENCES [Core].[Analysis] ([AnalysisID])
);

GO
ALTER TABLE [Core].[AnalysisParameter] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO