using System;
using System.Collections.Generic;

namespace CRES.DataContract
{
    public class FNoteDataContract
    {
        public string NoteId { get; set; }
        public string ID { get; set; }
        public string AccountID { get; set; }
        public string CRENoteID { get; set; }
        public string ClientNoteID { get; set; }

        public DateTime? InitialInterestAccrualEndDate { get; set; }
        public int? AccrualFrequency { get; set; }
        public int? DeterminationDateLeadDays { get; set; }
        public int? DeterminationDateReferenceDayoftheMonth { get; set; }
        public int? DeterminationDateInterestAccrualPeriod { get; set; }
        public int? DeterminationDateHolidayList { get; set; }
        public string DeterminationDateHolidayListText { get; set; }
        public DateTime? FirstPaymentDate { get; set; }
        public DateTime? InitialMonthEndPMTDateBiWeekly { get; set; }
        public int? PaymentDateBusinessDayLag { get; set; }
        public int? IOTerm { get; set; }
        public int? AmortTerm { get; set; }
        public int? PIKSeparateCompounding { get; set; }
        public Decimal? MonthlyDSOverridewhenAmortizing { get; set; }
        public int? AccrualPeriodPaymentDayWhenNotEOMonth { get; set; }
        public Decimal? FirstPeriodInterestPaymentOverride { get; set; }
        public Decimal? FirstPeriodPrincipalPaymentOverride { get; set; }
        public DateTime? FinalInterestAccrualEndDateOverride { get; set; }

        public int? InterestDueAtMaturity { get; set; }
        public Decimal? RateIndexResetFreq { get; set; }
        public DateTime? FirstRateIndexResetDate { get; set; }
        public int? LoanPurchase { get; set; }
        public int? AmortIntCalcDayCount { get; set; }
        public int? StubPaidinAdvanceYN { get; set; }
        public int? FullPeriodInterestDueatMaturity { get; set; }
        public int? IsCapitalized { get; set; }
        public int? SelectedMaturityDateScenario { get; set; }
        public string SelectedMaturityDateScenarioText { get; set; }
        public DateTime? SelectedMaturityDate { get; set; }
        public DateTime? InitialMaturityDate { get; set; }
        public DateTime? ExpectedMaturityDate { get; set; }
        public DateTime? FullyExtendedMaturityDate { get; set; }
        public DateTime? OpenPrepaymentDate { get; set; }
        public Decimal? TotalToBeAmortized { get; set; }
        public Decimal? StubPeriodInterest { get; set; }
        public Decimal? PurchaseBalance { get; set; }
        public int? DaysofAccrued { get; set; }
        public Decimal? InterestRate { get; set; }
        public Decimal? PurchasedInterestCalc { get; set; }
        public int? ModelFinancingDrawsForFutureFundings { get; set; }
        public int? NumberOfBusinessDaysLagForFinancingDraw { get; set; }
        public Guid? FinancingFacilityID { get; set; }
        public string FinancingFacilityIDText { get; set; }
        public DateTime? FinancingInitialMaturityDate { get; set; }
        public DateTime? FinancingExtendedMaturityDate { get; set; }
        public int? FinancingPayFrequency { get; set; }
        public int? FinancingInterestPaymentDay { get; set; }
        public DateTime? ClosingDate { get; set; }
        public Decimal? InitialFundingAmount { get; set; }
        public Decimal? Discount { get; set; }
        public Decimal? OriginationFee { get; set; }
        public Decimal? CapitalizedClosingCosts { get; set; }
        public DateTime? PurchaseDate { get; set; }
        public Decimal? PurchaseAccruedFromDate { get; set; }
        public Decimal? PurchasedInterestOverride { get; set; }
        public Decimal? OngoingAnnualizedServicingFee { get; set; }
        public Decimal? DiscountRate { get; set; }
        public DateTime? ValuationDate { get; set; }
        public Decimal? FairValue { get; set; }
        public Decimal? DiscountRatePlus { get; set; }
        public Decimal? FairValuePlus { get; set; }
        public Decimal? DiscountRateMinus { get; set; }
        public Decimal? FairValueMinus { get; set; }
        public int? IncludeServicingPaymentOverrideinLevelYield { get; set; }
        public string IncludeServicingPaymentOverrideinLevelYieldText { get; set; }
        public string PIKSeparateCompoundingText { get; set; }
        public string LoanPurchaseYNText { get; set; }
        public string StubPaidinAdvanceYNText { get; set; }
        public string ModelFinancingDrawsForFutureFundingsText { get; set; }
        public decimal? InitialIndexValueOverride { get; set; }
        public int? StubInterestPaidonFutureAdvances { get; set; }
        public int? RoundingMethod { get; set; }
        public string RoundingMethodText { get; set; }
        public int? IndexRoundingRule { get; set; }
        public string StubOnFFtext { get; set; }
        public int? StubOnFF { get; set; }
        public decimal? StubInterestPurchased { get; set; }
        public int? BaseCurrencyID { get; set; }
        public int? PayFrequency { get; set; }
        public string LoanCurrency { get; set; }
        public Decimal? StubIntOverride { get; set; }
        public Decimal? PurchasedIntOverride { get; set; }
        public Decimal? ExitFeeFreePrepayAmt { get; set; }
        public Decimal? ExitFeeBaseAmountOverride { get; set; }
        public int? ExitFeeAmortCheck { get; set; }
        public string ExitFeeAmortCheckText { get; set; }
        public int? FixedAmortSchedule { get; set; }
        public string FixedAmortScheduleText { get; set; }
        public bool? UseIndexOverrides { get; set; }
        public int? IndexNameID { get; set; }
        public string IndexNameText { get; set; }
        public Decimal? UnusedFeeThresholdBalance { get; set; }
        public int UnusedFeePaymentFrequency { get; set; }
        public int NumberofDaysinPast { get; set; }
        public int NumberofDaysinFuture { get; set; }
        public DateTime? ExtendedMaturityScenario1 { get; set; }
        public DateTime? ExtendedMaturityScenario2 { get; set; }
        public DateTime? ExtendedMaturityScenario3 { get; set; }
        public DateTime? ActualPayoffDate { get; set; }
        public Decimal? TotalCommitmentExtensionFeeisBasedOn { get; set; }
        public string FullInterestAtPPayoffText { get; set; }
        public int? FullInterestAtPPayoff { get; set; }
        public int? NoofdaysrelPaymentDaterollnextpaymentcycle { get; set; }
        public Decimal? TotalCommitment { get; set; }
        public string MaturityScenarioOverrideText { get; set; }
        public List<PIKSchedule> NotePIKScheduleList { get; set; }
        public List<RateSpreadSchedule> RateSpreadScheduleList { get; set; }
        public List<MaturityScenariosDataContract> MaturityScenariosList { get; set; }
        public List<FStrippingScheduleDataContract> NoteStrippingList { get; set; }
        public List<DefaultScheduleDataContract> NoteDefaultScheduleList { get; set; }
        public List<PrepayAndAdditionalFeeScheduleDataContract> NotePrepayAndAdditionalFeeScheduleList { get; set; }
        public List<EffectiveDateList> EffectiveDateList { get; set; }
        public List<FFutureFundingScheduleTab> ListFutureFundingScheduleTab { get; set; }
        public List<PIKfromPIKSourceNoteTab> ListPIKfromPIKSourceNoteTab { get; set; }
        public List<FeeCouponStripReceivableTab> ListFeeCouponStripReceivable { get; set; }
        public List<LiborScheduleTab> ListLiborScheduleTab { get; set; }
        public List<FixedAmortScheduleTab> ListFixedAmortScheduleTab { get; set; }
        public List<NoteServicingFeeScheduleDataContract> NoteServicingFeeScheduleList { get; set; }
        public List<FinancingScheduleDataContract> NoteFinancingScheduleList { get; set; }
        public List<NotePeriodicOutputsDataContract> ListNotePeriodicOutputs { get; set; }
        public List<ServicingLogTab> ListServicingLogTab { get; set; }
        public List<NoteServicingLogDataContract> lstNoteServicingLog { get; set; }
        public List<Transaction> ListTransaction { get; set; }
        public List<Transaction> ListCalcValues { get; set; }
        public List<TransactionEntry> ListCashflowTransactionEntry { get; set; }
        public ScenarioParameterDataContract DefaultScenarioParameters { get; set; }
        public List<ServicingOneTimeFeesTableDataContract> ServicingOneTimeFeesTableList { get; set; }
        public List<FinancingFeeScheduleDataContract> ListFinancingFeeSchedule { get; set; }
        public List<PIKInterestTab> ListPIKInterestTab { get; set; }
        public List<PIKDistributionsDataContract> ListPIKDistribution { get; set; }

        public string NoteRule { get; set; }
        public string FunctionName { get; set; }

    }
}
