
---Update parentclient in QA only for now (After iris confirmation will update in prod)
--Need to update other tables too for workflow (Ask to Shahid)


--ALTER TABLE cre.FinancingSourceMaster ADD ParentClient_Old nvarchar(256)
--go

Update cre.FinancingSourceMaster set ParentClient_Old = ParentClient 
go

update cre.FinancingSourceMaster set ParentClient= 'ACP II' Where FinancingSourceName = 'ACP II – CONA Pool'
update cre.FinancingSourceMaster set ParentClient= 'AOC I' Where FinancingSourceName = 'ACSS – Churchill Repo'
update cre.FinancingSourceMaster set ParentClient= 'AOC II' Where FinancingSourceName = 'AOC II – Goldman Repo'
update cre.FinancingSourceMaster set ParentClient= 'AOC II' Where FinancingSourceName = 'ACP II TRS, LLC'
update cre.FinancingSourceMaster set ParentClient= 'Delphi Financial' Where FinancingSourceName = 'Delphi Warehouse Hold'
update cre.FinancingSourceMaster set ParentClient= 'Harel' Where FinancingSourceName = 'Harel Participation'
update cre.FinancingSourceMaster set ParentClient= 'KIC' Where FinancingSourceName = 'KIC'
update cre.FinancingSourceMaster set ParentClient= 'None' Where FinancingSourceName = 'None'
update cre.FinancingSourceMaster set ParentClient= 'None' Where FinancingSourceName = 'Cap One Subscription Line'
update cre.FinancingSourceMaster set ParentClient= 'Note Sale - ACP I' Where FinancingSourceName = 'Note Sale - ACORE Credit IV'
update cre.FinancingSourceMaster set ParentClient= 'Note Sale - ACP II' Where FinancingSourceName = 'Note Sale - ACORE Credit Partners II'
update cre.FinancingSourceMaster set ParentClient= 'Note Sale - AOC I' Where FinancingSourceName = 'Note Sale - ACORE Spec Sits'
update cre.FinancingSourceMaster set ParentClient= 'Refinance Program' Where FinancingSourceName = 'Refinance Program'
update cre.FinancingSourceMaster set ParentClient= 'Stepstone' Where FinancingSourceName = 'Stepstone ACSS Co-Invest'
update cre.FinancingSourceMaster set ParentClient= 'To be determined' Where FinancingSourceName = 'To be determined'
update cre.FinancingSourceMaster set ParentClient= 'TRE ACR' Where FinancingSourceName = 'TRE ACR GL allocations'
update cre.FinancingSourceMaster set ParentClient= 'Winthrop' Where FinancingSourceName = 'Winthrop - Participation'
update cre.FinancingSourceMaster set ParentClient= 'TRE ACR' Where FinancingSourceName = 'AFLAC US - C'
update cre.FinancingSourceMaster set ParentClient= 'Note Sale - Column Financial Inc' Where FinancingSourceName = 'Note Sale - Column Financial Inc'
update cre.FinancingSourceMaster set ParentClient= 'Wells Fargo Repo' Where FinancingSourceName = 'Wells Fargo Repo'
update cre.FinancingSourceMaster set ParentClient= 'Opportunistic Sale' Where FinancingSourceName = 'Opportunistic Sale'
update cre.FinancingSourceMaster set ParentClient= 'Morgan Stanley Repo' Where FinancingSourceName = 'Morgan Stanley Repo'
update cre.FinancingSourceMaster set ParentClient= '3rd Party Owned' Where FinancingSourceName = '3rd Party Owned'
update cre.FinancingSourceMaster set ParentClient= '3rd Party Owned' Where FinancingSourceName = 'Co-Fund'
update cre.FinancingSourceMaster set ParentClient= 'ACP I' Where FinancingSourceName = 'ACP I'
update cre.FinancingSourceMaster set ParentClient= 'ACP I' Where FinancingSourceName = 'ACP I - Axos NoN'
update cre.FinancingSourceMaster set ParentClient= 'ACP I' Where FinancingSourceName = 'ACP I - DB Repo'
update cre.FinancingSourceMaster set ParentClient= 'ACP I' Where FinancingSourceName = 'ACP I - GP'
update cre.FinancingSourceMaster set ParentClient= 'ACP I' Where FinancingSourceName = 'ACP I - GS 2018'
update cre.FinancingSourceMaster set ParentClient= 'ACP I' Where FinancingSourceName = 'ACP I - MS Repo'
update cre.FinancingSourceMaster set ParentClient= 'ACP I' Where FinancingSourceName = 'ACP I - Note Repo'
update cre.FinancingSourceMaster set ParentClient= 'ACP I' Where FinancingSourceName = 'ACP I - Prime Mort'
update cre.FinancingSourceMaster set ParentClient= 'ACP I' Where FinancingSourceName = 'ACP I - Sunwest NoN'
update cre.FinancingSourceMaster set ParentClient= 'ACP I' Where FinancingSourceName = 'ACP I - WF Repo'
update cre.FinancingSourceMaster set ParentClient= 'ACP I - Offshore' Where FinancingSourceName = 'ACP I - Axos O/S NoN'
update cre.FinancingSourceMaster set ParentClient= 'ACP I - Offshore' Where FinancingSourceName = 'ACP I - DB O/S Repo'
update cre.FinancingSourceMaster set ParentClient= 'ACP I - Offshore' Where FinancingSourceName = 'ACP I - GS 2018 Offshore'
update cre.FinancingSourceMaster set ParentClient= 'ACP I - Offshore' Where FinancingSourceName = 'ACP I - MS O/S Repo'
update cre.FinancingSourceMaster set ParentClient= 'ACP I - Offshore' Where FinancingSourceName = 'ACP I - O/S Note Repo'
update cre.FinancingSourceMaster set ParentClient= 'ACP I - Offshore' Where FinancingSourceName = 'ACP I - O/S Prime Mort'
update cre.FinancingSourceMaster set ParentClient= 'ACP I - Offshore' Where FinancingSourceName = 'ACP I - Offshore'
update cre.FinancingSourceMaster set ParentClient= 'ACP I - Offshore' Where FinancingSourceName = 'ACP I - WF O/S Repo'
update cre.FinancingSourceMaster set ParentClient= 'ACP II' Where FinancingSourceName = 'ACP II'
update cre.FinancingSourceMaster set ParentClient= 'ACP II' Where FinancingSourceName = 'ACP II - Axos NoN'
update cre.FinancingSourceMaster set ParentClient= 'ACP II' Where FinancingSourceName = 'ACP II - Cap One Repo'
update cre.FinancingSourceMaster set ParentClient= 'ACP II' Where FinancingSourceName = 'ACP II - CONA Pool'
update cre.FinancingSourceMaster set ParentClient= 'ACP II' Where FinancingSourceName = 'ACP II - Customer NoN'
update cre.FinancingSourceMaster set ParentClient= 'ACP II' Where FinancingSourceName = 'ACP II - GS Repo'
update cre.FinancingSourceMaster set ParentClient= 'ACP II' Where FinancingSourceName = 'ACP II - JPM Repo'
update cre.FinancingSourceMaster set ParentClient= 'ACP II' Where FinancingSourceName = 'ACP II - MS Repo'
update cre.FinancingSourceMaster set ParentClient= 'ACP II' Where FinancingSourceName = 'ACP II - WF Repo'
update cre.FinancingSourceMaster set ParentClient= 'ACP II Co-Invest' Where FinancingSourceName = 'ACP II Co-Invest'
update cre.FinancingSourceMaster set ParentClient= 'AFLAC US' Where FinancingSourceName = 'AFLAC US'
update cre.FinancingSourceMaster set ParentClient= 'AHIP' Where FinancingSourceName = 'ACORE Hospitality Investments'
update cre.FinancingSourceMaster set ParentClient= 'Aksia' Where FinancingSourceName = 'Aksia Sidecar'
update cre.FinancingSourceMaster set ParentClient= 'Aksia' Where FinancingSourceName = 'Aksia VRS'
update cre.FinancingSourceMaster set ParentClient= 'AOC I' Where FinancingSourceName = 'AOC I'
update cre.FinancingSourceMaster set ParentClient= 'AOC I' Where FinancingSourceName = 'AOC I - Axos NoN'
update cre.FinancingSourceMaster set ParentClient= 'AOC I' Where FinancingSourceName = 'AOC I - Churchill Repo'
update cre.FinancingSourceMaster set ParentClient= 'AOC I' Where FinancingSourceName = 'AOC I - Customers NoN'
update cre.FinancingSourceMaster set ParentClient= 'AOC II' Where FinancingSourceName = 'AOC II'
update cre.FinancingSourceMaster set ParentClient= 'AOC II' Where FinancingSourceName = 'AOC II - Goldman Repo'
update cre.FinancingSourceMaster set ParentClient= 'AOC II Co-Invest' Where FinancingSourceName = 'AOC II Co-Invest'
update cre.FinancingSourceMaster set ParentClient= 'BcIMC' Where FinancingSourceName = 'BcIMC Sidecar'
update cre.FinancingSourceMaster set ParentClient= 'Delaware Life' Where FinancingSourceName = 'Delaware Life'
update cre.FinancingSourceMaster set ParentClient= 'Delphi Fixed' Where FinancingSourceName = 'Delphi Fixed'
update cre.FinancingSourceMaster set ParentClient= 'Delphi Floating' Where FinancingSourceName = 'Delphi ACORE'
update cre.FinancingSourceMaster set ParentClient= 'Delphi Floating' Where FinancingSourceName = 'Delphi Portfolio'
update cre.FinancingSourceMaster set ParentClient= 'Delphi Floating' Where FinancingSourceName = 'Delphi Warehouse Line'
update cre.FinancingSourceMaster set ParentClient= 'Delphi Offshore' Where FinancingSourceName = 'Delphi Offshore'
update cre.FinancingSourceMaster set ParentClient= 'Delphi Offshore' Where FinancingSourceName = 'Delphi Offshore Sold'
update cre.FinancingSourceMaster set ParentClient= 'Equitrust' Where FinancingSourceName = 'Equitrust'
update cre.FinancingSourceMaster set ParentClient= 'Harel' Where FinancingSourceName = 'Harel'
update cre.FinancingSourceMaster set ParentClient= 'Note Sale' Where FinancingSourceName = 'Note Sale - Wells Fargo Bank'
update cre.FinancingSourceMaster set ParentClient= 'Note Sale - ACP I' Where FinancingSourceName = 'Note Sale - ACP I'
update cre.FinancingSourceMaster set ParentClient= 'Note Sale - ACP II' Where FinancingSourceName = 'Note Sale - ACP II'
update cre.FinancingSourceMaster set ParentClient= 'Note Sale - AOC I' Where FinancingSourceName = 'Note Sale - AOC I'
update cre.FinancingSourceMaster set ParentClient= 'Note Sale - Delphi Floating' Where FinancingSourceName = 'Note Sale'
update cre.FinancingSourceMaster set ParentClient= 'Note Sale - Delphi Floating' Where FinancingSourceName = 'Note Sale - Delphi ACORE'
update cre.FinancingSourceMaster set ParentClient= 'Note Sale - Delphi Floating' Where FinancingSourceName = 'Note Sale - Delphi Portfolio'
update cre.FinancingSourceMaster set ParentClient= 'Note Sale - Delphi Floating' Where FinancingSourceName = 'Note Sale - Delphi Warehouse'
update cre.FinancingSourceMaster set ParentClient= 'Note Sale - Delphi Offshore' Where FinancingSourceName = 'Note Sale - Delphi Offshore'
update cre.FinancingSourceMaster set ParentClient= 'TRE ACR' Where FinancingSourceName = 'TRE ACR Portfolio'
update cre.FinancingSourceMaster set ParentClient= 'TRE ACR' Where FinancingSourceName = 'TRE ACR Series II Portfolio'
update cre.FinancingSourceMaster set ParentClient= 'Winthrop' Where FinancingSourceName = 'SILAC Insurance'
