CREATE TABLE [dbo].[Lib_DebtRepoLine](
	[Debt Name] [nvarchar](255) NULL,
	[Descriptive Name] [nvarchar](255) NULL,
	[Debt Type] [nvarchar](255) NULL,
	[Status] [nvarchar](255) NULL,
	[Currency] [nvarchar](255) NULL,
	[Match Term] [nvarchar](255) NULL,
	[Is revolving] [nvarchar](255) NULL,
	[Funding Notice Business Days] [float] NULL,
	[Initial Funding Delay] [float] NULL,
	[Max Advance Rate] [float] NULL,
	[Target Advance Rate] [nvarchar](255) NULL,
	[Origination Date] [datetime] NULL,
	[Origination Fee] [float] NULL,
	[Rate Type] [nvarchar](255) NULL,
	[Paydown Delay] [nvarchar](255) NULL,
	[Effective Date] [datetime] NULL,
	[Commitment] [float] NULL,
	[Initial Maturity Date] [datetime] NULL,
	[Initial Interest Accrual End Date] [nvarchar](255) NULL,
	[Accrual Frequency] [nvarchar](255) NULL,
	[Payment Day of Month] [nvarchar](255) NULL,
	[Payment Date Business Day Lag] [nvarchar](255) NULL,
	[Determination Date Lead Days] [nvarchar](255) NULL,
	[Determination Date Reference Day of the month] [nvarchar](255) NULL,
	[Rounding method] [nvarchar](255) NULL,
	[Index Rounding Rule] [nvarchar](255) NULL,
	[Pay Frequency] [nvarchar](255) NULL,
	[Default Index Name] [nvarchar](255) NULL
) ON [PRIMARY]
GO