CREATE TABLE [DW].[InvoiceDetailBI] (
    [InvoiceDetailID] INT			   NULL,
    [InvoiceNo]       NVARCHAR (256)   NULL,
    [TaskID]          UNIQUEIDENTIFIER NULL,
    [ObjectTypeID]    INT              NULL,
    [ObjectID]        NVARCHAR (256)   NULL,
    [Amount]          DECIMAL (28, 15) NULL,
    [AmountPaid]      DECIMAL (28, 15) NULL,
    [PaymentDate]     DATETIME         NULL,
    [AmountAdj]       DECIMAL (28, 15) NULL,
    [AdjComments]     NVARCHAR (2000)  NULL,
    [FirstName]       NVARCHAR (256)   NULL,
    [LastName]        NVARCHAR (256)   NULL,
    [Designation]     NVARCHAR (256)   NULL,
    [CompanyName]     NVARCHAR (256)   NULL,
    [Address]         NVARCHAR (256)   NULL,
    [City]            NVARCHAR (256)   NULL,    
    [Zip]             NVARCHAR (256)   NULL,
    [Email1]          NVARCHAR (256)   NULL,
    [Email2]          NVARCHAR (256)   NULL,
    [PhoneNo]         NVARCHAR (256)   NULL,
    [AlternatePhone]  NVARCHAR (256)   NULL,
    [Comment]         NVARCHAR (2000)  NULL,
    [AutoSendInvoice] INT              NULL,
    [CreatedBy]       NVARCHAR (256)   NULL,
    [CreatedDate]     DATETIME         NULL,
    [UpdatedBy]       NVARCHAR (256)   NULL,
    [UpdatedDate]     DATETIME         NULL,
    [DrawFeeStatus]   INT              NULL,
    [FileName]        NVARCHAR (256)   NULL,
    [InvoiceTypeID]   INT              NULL,
	[StateID]         INT              NULL,
    [SystemInvoiceNo] NVARCHAR (256)   NULL,
	CreDealId NVARCHAR (256)   NULL,
	DealName NVARCHAR (256)   NULL,
	[Date] Date null,
	ObjectTypeBI NVARCHAR (256)   NULL,
	AutoSendInvoiceBI NVARCHAR (256)   NULL,
	DrawFeeStatusBI NVARCHAR (256)   NULL,
	InvoiceTypeBI NVARCHAR (256)   NULL,
	StatesName        NVARCHAR (256)   NULL,
	StatesAbbreviation NVARCHAR (20)   NULL,
);

