CREATE TABLE [DW].[L_DealBI] (
    [DealID]                        UNIQUEIDENTIFIER NOT NULL,
    [DealName]                      NVARCHAR (256)   NULL,
    [CREDealID]                     NVARCHAR (256)   NULL,
    [DealType]                      INT              NULL,
    [LoanProgram]                   INT              NULL,
    [LoanPurpose]                   INT              NULL,
    [Status]                        INT              NULL,
    [AppReceived]                   DATE             NULL,
    [EstClosingDate]                DATE             NULL,
    [BorrowerRequest]               NVARCHAR (256)   NULL,
    [RecommendedLoan]               DECIMAL (28, 15) NULL,
    [TotalFutureFunding]            DECIMAL (28, 15) NULL,
    [Source]                        INT              NULL,
    [BrokerageFirm]                 NVARCHAR (256)   NULL,
    [BrokerageContact]              NVARCHAR (256)   NULL,
    [Sponsor]                       NVARCHAR (256)   NULL,
    [Principal]                     NVARCHAR (256)   NULL,
    [NetWorth]                      DECIMAL (28, 15) NULL,
    [Liquidity]                     DECIMAL (28, 15) NULL,
    [ClientDealID]                  NVARCHAR (256)   NULL,
    [GeneratedBy]                   INT              NULL,
    [TotalCommitment]               DECIMAL (28, 15) NULL,
    [AdjustedTotalCommitment]       DECIMAL (28, 15) NULL,
    [AggregatedTotal]               DECIMAL (28, 15) NULL,
    [AssetManagerComment]           NVARCHAR (MAX)   NULL,
    [AssetManager]                  NVARCHAR (256)   NULL,
    [DealCity]                      NVARCHAR (256)   NULL,
    [DealState]                     NVARCHAR (256)   NULL,
    [DealPropertyType]              NVARCHAR (256)   NULL,
    [FullyExtMaturityDate]          DATE             NULL,
    [DealTypeBI]                    NVARCHAR (256)   NULL,
    [LoanProgramBI]                 NVARCHAR (256)   NULL,
    [LoanPurposeBI]                 NVARCHAR (256)   NULL,
    [DealStatusBI]                  NVARCHAR (256)   NULL,
    [SourceBI]                      NVARCHAR (256)   NULL,
    [CreatedBy]                     NVARCHAR (256)   NULL,
    [CreatedDate]                   DATETIME         NULL,
    [UpdatedBy]                     NVARCHAR (256)   NULL,
    [UpdatedDate]                   DATETIME         NULL,
    [UnderwritingStatus]            INT              NULL,
    [UnderwritingStatusBI]          NVARCHAR (256)   NULL,
    [AMTeamLeadUserID]              UNIQUEIDENTIFIER NULL,
    [AMSecondUserID]                UNIQUEIDENTIFIER NULL,
    [AMTeamLeadUserBI]              NVARCHAR (256)   NULL,
    [AMSecondUserBI]                NVARCHAR (256)   NULL,
    [AMUserID]                      UNIQUEIDENTIFIER NULL,
    [AMUserBI]                      NVARCHAR (256)   NULL,
    [DealTypeMasterID]              INT              NULL,
    [DealTypeMasterBI]              NVARCHAR (256)   NULL,
    [InquiryDate]                   DATETIME         NULL,
    [BalanceAware]                  BIT              NULL,
    [BS_CollateralStatusDesc]       NVARCHAR (256)   NULL,
    [BS_CollateralStatusDesclatest] NVARCHAR (256)   NULL,
    [PropertyTypeMajorID]           INT              NULL,
    [PropertyTypeMajorBI]           NVARCHAR (256)   NULL,
    [BSCity]                        NVARCHAR (256)   NULL,
    [BSState]                       NVARCHAR (256)   NULL,
    [MSA_NAME]                      NVARCHAR (256)   NULL,
    [LoanStatusID]                  INT              NULL,
    [LoanStatusBI]                  NVARCHAR (256)   NULL,
    [L_DealBI_AutoID]               INT              IDENTITY (1, 1) NOT NULL,
    WatchlistStatus nvarchar(256),
    [LiabilitySource]               NVarchar(255)              NULL,

    [LinkedDealID]                         NVARCHAR (256)   NULL,
    [EnableAutoSpread]                     BIT              NULL,
    [EnableAutoSpreadRepayments]           BIT              NULL,
    [ApplyNoteLevelPaydowns]               BIT              NULL,
    [CalcEngineType]                       INT              NULL,
    [CalcEngineTypeBI]                     NVARCHAR (256)   NULL
    CONSTRAINT [PK_L_DealBI_AutoID] PRIMARY KEY CLUSTERED ([L_DealBI_AutoID] ASC)
);



