CREATE TABLE [DW].[L_NoteBI] (
    [NoteID]                                                 UNIQUEIDENTIFIER NOT NULL,
    [AccountID]                                              UNIQUEIDENTIFIER NOT NULL,
    [DealID]                                                 UNIQUEIDENTIFIER NOT NULL,
    [CRENoteID]                                              NVARCHAR (256)   NULL,
    [ClientNoteID]                                           NVARCHAR (256)   NULL,
    [Comments]                                               NVARCHAR (256)   NULL,
    [InitialInterestAccrualEndDate]                          DATE             NULL,
    [AccrualFrequency]                                       INT              NULL,
    [DeterminationDateLeadDays]                              INT              NULL,
    [DeterminationDateReferenceDayoftheMonth]                INT              NULL,
    [DeterminationDateInterestAccrualPeriod]                 INT              NULL,
    [DeterminationDateHolidayList]                           INT              NULL,
    [FirstPaymentDate]                                       DATE             NULL,
    [InitialMonthEndPMTDateBiWeekly]                         DATE             NULL,
    [PaymentDateBusinessDayLag]                              INT              NULL,
    [IOTerm]                                                 INT              NULL,
    [AmortTerm]                                              INT              NULL,
    [PIKSeparateCompounding]                                 INT              NULL,
    [MonthlyDSOverridewhenAmortizing]                        DECIMAL (28, 15) NULL,
    [AccrualPeriodPaymentDayWhenNotEOMonth]                  INT              NULL,
    [FirstPeriodInterestPaymentOverride]                     DECIMAL (28, 15) NULL,
    [FirstPeriodPrincipalPaymentOverride]                    DECIMAL (28, 15) NULL,
    [FinalInterestAccrualEndDateOverride]                    DATE             NULL,
    [AmortType]                                              INT              NULL,
    [RateType]                                               INT              NULL,
    [ReAmortizeMonthly]                                      INT              NULL,
    [ReAmortizeatPMTReset]                                   INT              NULL,
    [StubPaidInArrears]                                      INT              NULL,
    [RelativePaymentMonth]                                   INT              NULL,
    [SettleWithAccrualFlag]                                  INT              NULL,
    [InterestDueAtMaturity]                                  INT              NULL,
    [RateIndexResetFreq]                                     INT              NULL,
    [FirstRateIndexResetDate]                                DATE             NULL,
    [LoanPurchase]                                           INT              NULL,
    [AmortIntCalcDayCount]                                   INT              NULL,
    [StubPaidinAdvanceYN]                                    INT              NULL,
    [FullPeriodInterestDueatMaturity]                        INT              NULL,
    [ProspectiveAccountingMode]                              INT              NULL,
    [IsCapitalized]                                          INT              NULL,
    [SelectedMaturityDateScenario]                           INT              NULL,
    [SelectedMaturityDate]                                   DATE             NULL,
    [InitialMaturityDate]                                    DATE             NULL,
    [ExpectedMaturityDate]                                   DATE             NULL,
    [OpenPrepaymentDate]                                     DATE             NULL,
    [CashflowEngineID]                                       NVARCHAR (256)   NULL,
    [LoanType]                                               INT              NULL,
    [Classification]                                         INT              NULL,
    [SubClassification]                                      INT              NULL,
    [GAAPDesignation]                                        INT              NULL,
    [PortfolioID]                                            INT              NULL,
    [GeographicLocation]                                     INT              NULL,
    [PropertyType]                                           INT              NULL,
    [RatingAgency]                                           INT              NULL,
    [RiskRating]                                             INT              NULL,
    [PurchasePrice]                                          DECIMAL (28, 15) NULL,
    [FutureFeesUsedforLevelYeild]                            DECIMAL (28, 15) NULL,
    [TotalToBeAmortized]                                     DECIMAL (28, 15) NULL,
    [StubPeriodInterest]                                     DECIMAL (28, 15) NULL,
    [WDPAssetMultiple]                                       DECIMAL (28, 15) NULL,
    [WDPEquityMultiple]                                      DECIMAL (28, 15) NULL,
    [PurchaseBalance]                                        DECIMAL (28, 15) NULL,
    [DaysofAccrued]                                          INT              NULL,
    [InterestRate]                                           DECIMAL (28, 15) NULL,
    [PurchasedInterestCalc]                                  DECIMAL (28, 15) NULL,
    [ModelFinancingDrawsForFutureFundings]                   INT              NULL,
    [NumberOfBusinessDaysLagForFinancingDraw]                INT              NULL,
    [FinancingFacilityID]                                    UNIQUEIDENTIFIER NULL,
    [FinancingInitialMaturityDate]                           DATE             NULL,
    [FinancingExtendedMaturityDate]                          DATE             NULL,
    [FinancingPayFrequency]                                  INT              NULL,
    [FinancingInterestPaymentDay]                            INT              NULL,
    [ClosingDate]                                            DATE             NULL,
    [InitialFundingAmount]                                   DECIMAL (28, 15) NULL,
    [Discount]                                               DECIMAL (28, 15) NULL,
    [OriginationFee]                                         DECIMAL (28, 15) NULL,
    [CapitalizedClosingCosts]                                DECIMAL (28, 15) NULL,
    [PurchaseDate]                                           DATE             NULL,
    [PurchaseAccruedFromDate]                                DECIMAL (28, 15) NULL,
    [PurchasedInterestOverride]                              DECIMAL (28, 15) NULL,
    [DiscountRate]                                           DECIMAL (28, 15) NULL,
    [ValuationDate]                                          DATE             NULL,
    [FairValue]                                              DECIMAL (28, 15) NULL,
    [DiscountRatePlus]                                       DECIMAL (28, 15) NULL,
    [FairValuePlus]                                          DECIMAL (28, 15) NULL,
    [DiscountRateMinus]                                      DECIMAL (28, 15) NULL,
    [FairValueMinus]                                         DECIMAL (28, 15) NULL,
    [InitialIndexValueOverride]                              DECIMAL (28, 15) NULL,
    [IncludeServicingPaymentOverrideinLevelYield]            INT              NULL,
    [OngoingAnnualizedServicingFee]                          DECIMAL (28, 15) NULL,
    [IndexRoundingRule]                                      INT              NULL,
    [RoundingMethod]                                         INT              NULL,
    [StubInterestPaidonFutureAdvances]                       INT              NULL,
    [TaxAmortCheck]                                          NVARCHAR (256)   NULL,
    [PIKWoCompCheck]                                         NVARCHAR (256)   NULL,
    [GAAPAmortCheck]                                         NVARCHAR (256)   NULL,
    [StubIntOverride]                                        DECIMAL (28, 15) NULL,
    [PurchasedIntOverride]                                   DECIMAL (28, 15) NULL,
    [ExitFeeFreePrepayAmt]                                   DECIMAL (28, 15) NULL,
    [ExitFeeBaseAmountOverride]                              DECIMAL (28, 15) NULL,
    [ExitFeeAmortCheck]                                      INT              NULL,
    [FixedAmortScheduleCheck]                                INT              NULL,
    [GeneratedBy]                                            INT              NULL,
    [UseRuletoDetermineNoteFunding]                          INT              NULL,
    [NoteFundingRule]                                        INT              NULL,
    [FundingPriority]                                        INT              NULL,
    [NoteBalanceCap]                                         DECIMAL (28, 15) NULL,
    [RepaymentPriority]                                      INT              NULL,
    [NoofdaysrelPaymentDaterollnextpaymentcycle]             INT              NULL,
    [UseIndexOverrides]                                      BIT              NULL,
    [IndexNameID]                                            INT              NULL,
    [ServicerID]                                             NVARCHAR (256)   NULL,
    [TotalCommitment]                                        DECIMAL (28, 15) NULL,
    [DeterminationDateHolidayListBI]                         NVARCHAR (256)   NULL,
    [RateTypeBI]                                             NVARCHAR (256)   NULL,
    [ReAmortizeMonthlyBI]                                    NVARCHAR (256)   NULL,
    [ReAmortizeatPMTResetBI]                                 NVARCHAR (256)   NULL,
    [StubPaidInArrearsBI]                                    NVARCHAR (256)   NULL,
    [RelativePaymentMonthBI]                                 NVARCHAR (256)   NULL,
    [SettleWithAccrualFlagBI]                                NVARCHAR (256)   NULL,
    [InterestDueAtMaturityBI]                                NVARCHAR (256)   NULL,
    [LoanPurchaseBI]                                         NVARCHAR (256)   NULL,
    [StubPaidinAdvanceYNBI]                                  NVARCHAR (256)   NULL,
    [ProspectiveAccountingModeBI]                            NVARCHAR (256)   NULL,
    [IsCapitalizedBI]                                        NVARCHAR (256)   NULL,
    [ClassificationBI]                                       NVARCHAR (256)   NULL,
    [SubClassificationBI]                                    NVARCHAR (256)   NULL,
    [GAAPDesignationBI]                                      NVARCHAR (256)   NULL,
    [GeographicLocationBI]                                   NVARCHAR (256)   NULL,
    [PropertyTypeBI]                                         NVARCHAR (256)   NULL,
    [RatingAgencyBI]                                         NVARCHAR (256)   NULL,
    [RiskRatingBI]                                           NVARCHAR (256)   NULL,
    [ModelFinancingDrawsForFutureFundingsBI]                 NVARCHAR (256)   NULL,
    [NumberOfBusinessDaysLagForFinancingDrawBI]              NVARCHAR (256)   NULL,
    [FinancingFacilityBI]                                    NVARCHAR (256)   NULL,
    [FinancingPayFrequencyBI]                                NVARCHAR (256)   NULL,
    [IncludeServicingPaymentOverrideinLevelYieldBI]          NVARCHAR (256)   NULL,
    [RoundingMethodBI]                                       NVARCHAR (256)   NULL,
    [StubInterestPaidonFutureAdvancesBI]                     NVARCHAR (256)   NULL,
    [ExitFeeAmortCheckBI]                                    NVARCHAR (256)   NULL,
    [FixedAmortScheduleCheckBI]                              NVARCHAR (256)   NULL,
    [IndexNameBI]                                            NVARCHAR (256)   NULL,
    [StatusID]                                               INT              NULL,
    [StatusBI]                                               NVARCHAR (256)   NULL,
    [Name]                                                   NVARCHAR (256)   NULL,
    [BaseCurrencyID]                                         INT              NULL,
    [BaseCurrencyBI]                                         NVARCHAR (256)   NULL,
    [PayFrequency]                                           INT              NULL,
    [ClientName]                                             NVARCHAR (256)   NULL,
    [Portfolio]                                              NVARCHAR (256)   NULL,
    [Tag1]                                                   NVARCHAR (256)   NULL,
    [Tag2]                                                   NVARCHAR (256)   NULL,
    [Tag3]                                                   NVARCHAR (256)   NULL,
    [Tag4]                                                   NVARCHAR (256)   NULL,
    [CreatedBy]                                              NVARCHAR (256)   NULL,
    [CreatedDate]                                            DATETIME         NULL,
    [UpdatedBy]                                              NVARCHAR (256)   NULL,
    [UpdatedDate]                                            DATETIME         NULL,
    [lienposition]                                           INT              NULL,
    [lienpositionBI]                                         NVARCHAR (256)   NULL,
    [priority]                                               INT              NULL,
    [ExtendedMaturityScenario1]                              DATE             NULL,
    [ExtendedMaturityScenario2]                              DATE             NULL,
    [ExtendedMaturityScenario3]                              DATE             NULL,
    [ActualPayoffDate]                                       DATE             NULL,
    [FullyExtendedMaturityDate]                              DATE             NULL,
    [TotalCommitmentExtensionFeeisBasedOn]                   DECIMAL (28, 15) NULL,
    [LienPriority]                                           INT              NULL,
    [UnusedFeeThresholdBalance]                              DECIMAL (28, 15) NULL,
    [UnusedFeePaymentFrequency]                              INT              NULL,
    [Servicer]                                               INT              NULL,
    [FullInterestAtPPayoff]                                  INT              NULL,
    [ServicerBI]                                             NVARCHAR (256)   NULL,
    [ClientID]                                               INT              NULL,
    [FinancingSourceID]                                      INT              NULL,
    [DebtTypeID]                                             INT              NULL,
    [BillingNotesID]                                         INT              NULL,
    [CapStack]                                               INT              NULL,
    [ClientBI]                                               NVARCHAR (256)   NULL,
    [FinancingSourceBI]                                      NVARCHAR (256)   NULL,
    [DebtTypeBI]                                             NVARCHAR (256)   NULL,
    [BillingNotesBI]                                         NVARCHAR (256)   NULL,
    [CapStackBI]                                             NVARCHAR (256)   NULL,
    [FundID]                                                 INT              NULL,
    [FundBI]                                                 NVARCHAR (256)   NULL,
    [PoolID]                                                 INT              NULL,
    [PoolBI]                                                 NVARCHAR (256)   NULL,
    [ServicerNameID]                                         INT              NULL,
    [ServicerNameBI]                                         NVARCHAR (256)   NULL,
    [InterestCalculationRuleForPaydowns]                     INT              NULL,
    [InterestCalculationRuleForPaydownsBI]                   NVARCHAR (256)   NULL,
    [PIKInterestAddedToBalanceBasedOnBusinessAdjustedDate]   INT              NULL,
    [PIKInterestAddedToBalanceBasedOnBusinessAdjustedDateBI] NVARCHAR (256)   NULL,
    [BusinessdaylafrelativetoPMTDate]                        INT              NULL,
    [DayoftheMonth]                                          INT              NULL,
    [FundedAndOwnedByThirdParty]                             BIT              DEFAULT ((0)) NULL,
    [InterestCalculationRuleForPaydownsAmort]                INT              NULL,
    [InterestCalculationRuleForPaydownsAmortBI]              NVARCHAR (256)   NULL,
    [Pik_NonPIK]                                             NVARCHAR (256)   NULL,
    [HasFundingRepayment]                                    NVARCHAR (256)   NULL,
    [FullAccrualHasRepayment]                                NVARCHAR (256)   NULL,
    [HasAmortTerm_Or_FixedAmort]                             NVARCHAR (256)   NULL,
    [HasAmortTerm]                                           NVARCHAR (256)   NULL,
    [HasOnlyRepayment]                                       NVARCHAR (256)   NULL,
    [HasFixedAmort]                                          NVARCHAR (256)   NULL,
    [OriginationFeePercentageRP]                             DECIMAL (28, 15) NULL,
    [HasScheduledPrincipal]                                  NVARCHAR (100)   NULL,
    [HasPIkPrincipalpaid]                                    NVARCHAR (100)   NULL,
    [HasPIkInterestpaid]                                     NVARCHAR (100)   NULL,
    [InitialFundingEquCommit]                                NVARCHAR (100)   NULL,
    [HasDSMonthlyOverride]                                   NVARCHAR (100)   NULL,
    [FixedPIK]                                               NVARCHAR (100)   NULL,
    [FloatingPIK]                                            NVARCHAR (100)   NULL,
    [FinancingSourceGroup]                                   NVARCHAR (256)   NULL,
    [L_NoteBI_AutoID]                                        INT              IDENTITY (1, 1) NOT NULL,
    [ImpactCommitmentCalc] INT NULL ,
    [ImpactCommitmentCalcBI] nvarchar(10) NULL ,
    FirstIndexDeterminationDateOverride date null,

     NoteType int,
    EnableM61Calculations int,
    NoteTypeBI nvarchar(256),
    EnableM61CalculationsBI nvarchar(256),
    RepaymentDayoftheMonth int
);



