CREATE TABLE [DW].[L_UwPropertyBI] (
    [PropertyId]                                INT              NULL,
    [ControlId_F]                               NVARCHAR (256)   NULL,
    [PropertyNumber]                            NVARCHAR (20)    NULL,
    [PropertyName]                              NVARCHAR (100)   NULL,
    [PropertyTypeMajorCd_F]                     NVARCHAR (256)   NULL,
    [PropertyTypeMinorCd_F]                     NVARCHAR (256)   NULL,
    [SecondaryPropTypeMajCd_F]                  NVARCHAR (256)   NULL,
    [ManagementCoId_F]                          NVARCHAR (256)   NULL,
    [FeeLeaseHoldCd_F]                          NVARCHAR (256)   NULL,
    [StreetAddress]                             NVARCHAR (150)   NULL,
    [City]                                      NVARCHAR (50)    NULL,
    [State]                                     NVARCHAR (10)    NULL,
    [ZipCode]                                   NVARCHAR (15)    NULL,
    [County]                                    NVARCHAR (50)    NULL,
    [Country]                                   NVARCHAR (50)    NULL,
    [InspectionDate]                            DATETIME         NULL,
    [LandArea]                                  FLOAT (53)       NULL,
    [UnitMeasurePrimary]                        NVARCHAR (10)    NULL,
    [NumberOfUnitsPrimary]                      INT              NULL,
    [GSFPrimary]                                INT              NULL,
    [NRSFPrimary]                               INT              NULL,
    [UnitMeasureSecondary]                      NVARCHAR (10)    NULL,
    [NumberOfUnitsSecondary]                    INT              NULL,
    [GSFSecondary]                              INT              NULL,
    [NRSFSecondary]                             INT              NULL,
    [NumberOfBuildings]                         INT              NULL,
    [NumberOfStories]                           INT              NULL,
    [NumberOfPads]                              INT              NULL,
    [NumberOfElevators]                         INT              NULL,
    [NumberOfParkingSpaces]                     INT              NULL,
    [Security]                                  NVARCHAR (3)     NULL,
    [OnSiteMan]                                 NVARCHAR (10)    NULL,
    [Tenancy]                                   NVARCHAR (10)    NULL,
    [PercentOwnOcc]                             FLOAT (53)       NULL,
    [LocationType]                              NVARCHAR (10)    NULL,
    [DateAcquired]                              DATETIME         NULL,
    [YearBuilt]                                 INT              NULL,
    [YearRenovated]                             INT              NULL,
    [Zoning]                                    VARCHAR (1000)   NULL,
    [LegallyConformingUse]                      NVARCHAR (3)     NULL,
    [PropertyPositionCd_F]                      NVARCHAR (256)   NULL,
    [PropertyPositionStatus]                    NVARCHAR (500)   NULL,
    [AcquisitionAmount]                         DECIMAL (28, 15) NULL,
    [BorrowerEquity]                            DECIMAL (28, 15) NULL,
    [TitleCompany]                              NVARCHAR (100)   NULL,
    [TitleVesting]                              NVARCHAR (50)    NULL,
    [TitlePolicyDate]                           DATETIME         NULL,
    [TitleARMEndorsement]                       NVARCHAR (3)     NULL,
    [PolicyAmount]                              FLOAT (53)       NULL,
    [TitleNegAmortizationEnd]                   NVARCHAR (3)     NULL,
    [TitleFutAdvancesEnd]                       NVARCHAR (3)     NULL,
    [OwnershipInterest]                         NVARCHAR (15)    NULL,
    [GroundLeaseFlag]                           NVARCHAR (3)     NULL,
    [CrossCollateralized]                       NVARCHAR (3)     NULL,
    [NumberGroundLeases]                        INT              NULL,
    [CrossDefaulted]                            NVARCHAR (3)     NULL,
    [CrossDefaultedComment]                     NVARCHAR (MAX)   NULL,
    [DescriptionOfOtherLiens]                   NVARCHAR (255)   NULL,
    [DescriptionOfAddCollateral]                NVARCHAR (255)   NULL,
    [TitlePolicyType]                           NVARCHAR (20)    NULL,
    [TitleCom]                                  NVARCHAR (255)   NULL,
    [LienPosition]                              NVARCHAR (25)    NULL,
    [SubFin]                                    NVARCHAR (50)    NULL,
    [UnsecDebtAllow]                            NVARCHAR (5)     NULL,
    [PropertyComment]                           NVARCHAR (MAX)   NULL,
    [DealAllocationAmt]                         DECIMAL (28, 15) NULL,
    [DealAllocatedPctSecondary]                 FLOAT (53)       NULL,
    [PropertyClass]                             NVARCHAR (20)    NULL,
    [NewConstruction]                           NVARCHAR (3)     NULL,
    [SingleTennant]                             NVARCHAR (3)     NULL,
    [EstValue]                                  DECIMAL (28, 15) NULL,
    [EstNCF]                                    DECIMAL (28, 15) NULL,
    [EstNOI]                                    DECIMAL (28, 15) NULL,
    [WindHailInsSw]                             NVARCHAR (3)     NULL,
    [WindHailInsAmt]                            DECIMAL (28, 15) NULL,
    [FloodInsSw]                                NVARCHAR (3)     NULL,
    [FloodInsAmt]                               DECIMAL (28, 15) NULL,
    [HurricaneInsSw]                            NVARCHAR (3)     NULL,
    [HurricaneInsAmt]                           DECIMAL (28, 15) NULL,
    [NonConformingComment]                      NVARCHAR (MAX)   NULL,
    [OccupancyVsMarket]                         NVARCHAR (20)    NULL,
    [MarketForecast]                            NVARCHAR (20)    NULL,
    [EstimatedMarketValue]                      DECIMAL (28, 15) NULL,
    [LandOInsuranceReq]                         NVARCHAR (3)     NULL,
    [ProjectedMoodysCapRate]                    FLOAT (53)       NULL,
    [ActualMoodysCapRate]                       FLOAT (53)       NULL,
    [ApprovedNCF]                               DECIMAL (28, 15) NULL,
    [ApprovedBy_UserId_F]                       NVARCHAR (256)   NULL,
    [ApprovalDate]                              DATETIME         NULL,
    [AlliedStressPct]                           FLOAT (53)       NULL,
    [DefaultRiskRating]                         SMALLINT         NULL,
    [HardEquity]                                DECIMAL (28, 15) NULL,
    [LenderPropertyIdentifier]                  NVARCHAR (20)    NULL,
    [ManRelated]                                NVARCHAR (3)     NULL,
    [ManAgreeAssgnable]                         NVARCHAR (3)     NULL,
    [ManAgreeExpireDate]                        DATETIME         NULL,
    [ManAgreeFee]                               FLOAT (53)       NULL,
    [ManFeeCollectedOn]                         NVARCHAR (30)    NULL,
    [ManAgreeSubordinate]                       NVARCHAR (3)     NULL,
    [ManAgreeCure]                              NVARCHAR (3)     NULL,
    [ManLeasingAgent]                           NVARCHAR (30)    NULL,
    [ManLeasingCommission]                      NVARCHAR (MAX)   NULL,
    [ManAgreementComment]                       NVARCHAR (MAX)   NULL,
    [ManContactName]                            NVARCHAR (30)    NULL,
    [ManYearsManageProp]                        INT              NULL,
    [ManAgreementDate]                          DATETIME         NULL,
    [ManAgreementRenewal]                       NVARCHAR (50)    NULL,
    [ManOwnerRightToTerminate]                  NVARCHAR (3)     NULL,
    [ManTerminationCond]                        NVARCHAR (MAX)   NULL,
    [ManLenderRightToTerminate]                 NVARCHAR (3)     NULL,
    [ManIncentiveFee]                           NVARCHAR (3)     NULL,
    [ManChangeConditions]                       NVARCHAR (3)     NULL,
    [ManChangeConditionsComment]                NVARCHAR (MAX)   NULL,
    [ManIncentiveFeeSub]                        NVARCHAR (3)     NULL,
    [ManIncentiveFeeComment]                    NVARCHAR (MAX)   NULL,
    [LoanCondVacancyAllowance]                  NVARCHAR (30)    NULL,
    [LoanCondManagementFee]                     FLOAT (53)       NULL,
    [LoanCondFranchiseFee]                      FLOAT (53)       NULL,
    [LoanCondAdvertisingFee]                    FLOAT (53)       NULL,
    [LoanCondReplacementReserves]               NVARCHAR (MAX)   NULL,
    [LoanCondRolloverCosts]                     NVARCHAR (MAX)   NULL,
    [MpDueOnSale]                               NVARCHAR (3)     NULL,
    [MpDueOnSaleDesc]                           NVARCHAR (MAX)   NULL,
    [MpDueOnEncumbrance]                        NVARCHAR (3)     NULL,
    [MpDueOnEncumbranceDesc]                    NVARCHAR (MAX)   NULL,
    [MpCashAudit]                               NVARCHAR (3)     NULL,
    [MpCashAuditDesc]                           NVARCHAR (MAX)   NULL,
    [MpPartialRelease]                          NVARCHAR (3)     NULL,
    [MpPartialReleaseDesc]                      NVARCHAR (MAX)   NULL,
    [MpPartialReleaseAmt]                       DECIMAL (28, 15) NULL,
    [MpRightToInspectProperty]                  NVARCHAR (100)   NULL,
    [MpOpStatementFrequency]                    NVARCHAR (100)   NULL,
    [MpRentRollFrequency]                       NVARCHAR (100)   NULL,
    [MpUnsecuredDebtAllowed]                    NVARCHAR (3)     NULL,
    [MpMaxUnsecuredDebtAmt]                     DECIMAL (28, 15) NULL,
    [MpTradePayablesMaxAmt]                     DECIMAL (28, 15) NULL,
    [MpTradePayablesDaysOut]                    INT              NULL,
    [MpComment]                                 NVARCHAR (MAX)   NULL,
    [MarketCapRate]                             FLOAT (53)       NULL,
    [LenderCapRate]                             FLOAT (53)       NULL,
    [PhotoLink]                                 NVARCHAR (100)   NULL,
    [DirctionsLink]                             NVARCHAR (MAX)   NULL,
    [AuditAddDate]                              DATETIME         NULL,
    [AuditAddUserId]                            NVARCHAR (150)   NULL,
    [AuditUpdateDate]                           DATETIME         NULL,
    [AuditUpdateUserId]                         NVARCHAR (150)   NULL,
    [DealAllocationAmtPCT]                      FLOAT (53)       NULL,
    [PropertyCurrencyCD_F]                      NVARCHAR (256)   NULL,
    [CeilingHeight]                             DECIMAL (18)     NULL,
    [RegionCD_F]                                NVARCHAR (256)   NULL,
    [TerrorInsSw]                               NVARCHAR (3)     NULL,
    [TerrorInsAmt]                              DECIMAL (28, 15) NULL,
    [MarketCd_F]                                NVARCHAR (256)   NULL,
    [ReleaseCollateralSW]                       BIT              NULL,
    [TotalCostBasis]                            DECIMAL (18)     NULL,
    [ExternalPropertyNumber]                    NVARCHAR (20)    NULL,
    [MpSubstitutionAllowed]                     NVARCHAR (3)     NULL,
    [MpSubstitutionAllowedDesc]                 NVARCHAR (MAX)   NULL,
    [ManAgreeAmount]                            DECIMAL (28, 15) NULL,
    [SubMarketManComment]                       NVARCHAR (MAX)   NULL,
    [ManFeeType]                                NVARCHAR (3)     NULL,
    [ParkingSpacesCovered]                      INT              NULL,
    [ParkingSpacesUncovered]                    INT              NULL,
    [MANSFUnitsRmsUnderManinSubMarket]          BIGINT           NULL,
    [SubMarketId_F]                             NVARCHAR (256)   NULL,
    [Latitude]                                  DECIMAL (18)     NULL,
    [Longitude]                                 DECIMAL (18)     NULL,
    [UnderwrittenManagementFee]                 FLOAT (53)       NULL,
    [ClientIdentifier]                          NVARCHAR (50)    NULL,
    [DealAllocationTotalCommitmentAmt]          DECIMAL (30, 15) NULL,
    [BorrowerId_F]                              NVARCHAR (256)   NULL,
    [AllocatedNoteID_F]                         NVARCHAR (256)   NULL,
    [DealAllocationTotalCommitmentAmtConverted] DECIMAL (30, 15) NULL,
    [DealAllocationAmtConverted]                DECIMAL (30, 15) NULL,
    [PropertyForSale]                           NVARCHAR (3)     NULL,
    [BrokerOrgId_F]                             NVARCHAR (256)   NULL,
    [PreliminarySponsorOrgId_F]                 NVARCHAR (256)   NULL,
    [DepositAmount]                             DECIMAL (28, 15) NULL,
    [ProspectivePropertySaleDate]               DATETIME         NULL,
    [ManagementCo_ContactID_F]                  NVARCHAR (256)   NULL,
    [PropertyPositionLastChangedDate]           DATETIME         NULL,
    [ExcludeProperty]                           BIT              NULL,
    [DownPaymentSourceCD_F]                     NVARCHAR (256)   NULL,
    [ExistingDebt]                              DECIMAL (28, 15) NULL,
    [L_UwPropertyBI_AutoID]                     INT              IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_L_UwPropertyBI_AutoID] PRIMARY KEY CLUSTERED ([L_UwPropertyBI_AutoID] ASC)
);



