CREATE TABLE [DW].[L_UwNoteBI] (
    [NoteId]                          INT              NULL,
    [ControlId_F]                     NVARCHAR (10)    NULL,
    [PrimaryDebtFlag]                 NVARCHAR (3)     NULL,
    [LienPositionCd_F]                NVARCHAR (256)   NULL,
    [IntCalcMethodCd_F]               NVARCHAR (256)   NULL,
    [RateTypeCd_F]                    NVARCHAR (256)   NULL,
    [PaymentFreqCd_F]                 NVARCHAR (256)   NULL,
    [InterestCollectionTypeCd_F]      NVARCHAR (256)   NULL,
    [AmortizationCd_F]                NVARCHAR (256)   NULL,
    [InterimServ_OrgId_F]             NVARCHAR (256)   NULL,
    [InterimCustodian_OrgId_F]        NVARCHAR (256)   NULL,
    [NoteName]                        NVARCHAR (60)    NULL,
    [NoteDate]                        DATETIME         NULL,
    [NoteDateApproximateSw]           BIT              NULL,
    [Priority]                        INT              NULL,
    [ProjectedFundingDate]            DATETIME         NULL,
    [IndexName]                       NVARCHAR (20)    NULL,
    [IndexSource]                     NVARCHAR (30)    NULL,
    [IndexPercent]                    FLOAT (53)       NULL,
    [IndexAsOfDate]                   DATETIME         NULL,
    [HyerAmortizationFlag]            NVARCHAR (3)     NULL,
    [HyperAmortizationTerm]           INT              NULL,
    [HyperAmortizationDate]           DATETIME         NULL,
    [OrigLoanAmount]                  DECIMAL (28, 15) NULL,
    [FirstPIPaymentDate]              DATETIME         NULL,
    [InterestSpread]                  FLOAT (53)       NULL,
    [OrigIntRate]                     FLOAT (53)       NULL,
    [InterestRateForAmortization]     FLOAT (53)       NULL,
    [MonthlyDebtService]              DECIMAL (28, 15) NULL,
    [PaymentOverride]                 BIT              NULL,
    [PaymentOverrideAmount]           DECIMAL (28, 15) NULL,
    [DSCROverride]                    BIT              NULL,
    [DSCROverrideAmount]              DECIMAL (28, 15) NULL,
    [LoanTerm]                        INT              NULL,
    [ARDTerm]                         INT              NULL,
    [ARDLoanBalance]                  DECIMAL (28, 15) NULL,
    [StatedMaturityDate]              DATETIME         NULL,
    [LoanConstant]                    FLOAT (53)       NULL,
    [MaxIntAmount]                    DECIMAL (28, 15) NULL,
    [AmountToBeFunded]                DECIMAL (28, 15) NULL,
    [BalloonARDAmount]                DECIMAL (28, 15) NULL,
    [FutureFundingPurpose]            NVARCHAR (50)    NULL,
    [PrincipalBalance]                DECIMAL (28, 15) NULL,
    [AmortizationTerm]                INT              NULL,
    [AmortizationComments]            NVARCHAR (256)   NULL,
    [HyperAmortComments]              NVARCHAR (MAX)   NULL,
    [AmortFixedDefaultIfNotPaidSw]    NVARCHAR (3)     NULL,
    [AmortFixedDefaultIfNotPaidAmt]   DECIMAL (28, 15) NULL,
    [AmortIOPeriod]                   INT              NULL,
    [AmortFixedPrincipleAmt]          DECIMAL (28, 15) NULL,
    [OriginationFee]                  DECIMAL (28, 15) NULL,
    [OriginationFeePct]               FLOAT (53)       NULL,
    [InterestRateLock]                NVARCHAR (3)     NULL,
    [InterestRateLockDate]            DATETIME         NULL,
    [InterestRateFloorSw]             NVARCHAR (3)     NULL,
    [InterestRateFloorPct]            FLOAT (53)       NULL,
    [InterestRateFloorPortion]        FLOAT (53)       NULL,
    [InterestRateFloorComments]       NVARCHAR (MAX)   NULL,
    [InterestRateLockExpiration]      DATETIME         NULL,
    [MatrixSpreadAtClose]             FLOAT (53)       NULL,
    [MatrixSpreadAtCloseComments]     NVARCHAR (MAX)   NULL,
    [ServicingStrip]                  FLOAT (53)       NULL,
    [InitialIoInterestRate]           FLOAT (53)       NULL,
    [InterimServFee]                  FLOAT (53)       NULL,
    [InterimServType]                 NVARCHAR (15)    NULL,
    [PayAndAccrueSw]                  NVARCHAR (3)     NULL,
    [PayRate]                         FLOAT (53)       NULL,
    [PayAndAccrueComment]             NVARCHAR (MAX)   NULL,
    [TrapExcessCasflowSw]             NVARCHAR (3)     NULL,
    [TrapExcessCashflowComments]      NVARCHAR (MAX)   NULL,
    [PerformanceHoldbackType]         NVARCHAR (150)   NULL,
    [SecondayFinancing]               NVARCHAR (3)     NULL,
    [ExitFee]                         DECIMAL (28, 15) NULL,
    [ExitFeePct]                      FLOAT (53)       NULL,
    [ExitFeeReducedIfFinSw]           NVARCHAR (3)     NULL,
    [ExitFeeReducedIfFinComment]      NVARCHAR (MAX)   NULL,
    [MpCallOption]                    NVARCHAR (3)     NULL,
    [MpCallOptionDesc]                NVARCHAR (MAX)   NULL,
    [MpAllowFutAdvances]              NVARCHAR (3)     NULL,
    [MpAllowFutAdvancesDesc]          NVARCHAR (MAX)   NULL,
    [MpStandstill]                    NVARCHAR (3)     NULL,
    [MpComment]                       NVARCHAR (MAX)   NULL,
    [ArmLoanInternallyCappedSw]       NVARCHAR (3)     NULL,
    [ArmInterestRateCappedReqSw]      NVARCHAR (3)     NULL,
    [ArmLiborCap]                     FLOAT (53)       NULL,
    [ArmIntRateCapDesc]               NVARCHAR (MAX)   NULL,
    [ArmLiborDefinition]              NVARCHAR (MAX)   NULL,
    [ArmLiborDeterminationDate]       NVARCHAR (MAX)   NULL,
    [GCM_Cusip]                       NVARCHAR (9)     NULL,
    [GCM_TradeAccount]                NVARCHAR (5)     NULL,
    [GCM_IkonBoxNum]                  INT              NULL,
    [GCM_IkonCopyStatus]              NVARCHAR (50)    NULL,
    [GCM_OriginalsOutDate]            DATETIME         NULL,
    [GCM_AccountantsCopyDate]         DATETIME         NULL,
    [GCM_SandPCopyDate]               DATETIME         NULL,
    [GCM_FitchCopyDate]               DATETIME         NULL,
    [GCM_MoodysCopyDate]              DATETIME         NULL,
    [GCM_BBuyerCopyDate]              DATETIME         NULL,
    [GCM_ServicerCopyDate]            DATETIME         NULL,
    [GCM_TabNumber]                   INT              NULL,
    [GCM_BoxContent]                  NVARCHAR (MAX)   NULL,
    [GCM_BoxNumber]                   INT              NULL,
    [GCM_ArchieveSerialNumber]        INT              NULL,
    [GCM_ArchieveDate]                DATETIME         NULL,
    [GCM_DestroyedDate]               DATETIME         NULL,
    [GCM_InternalComments]            NVARCHAR (MAX)   NULL,
    [AuditAddDate]                    DATETIME         NULL,
    [AuditAddUserId]                  NVARCHAR (150)   NULL,
    [AuditUpdateDate]                 DATETIME         NULL,
    [AuditUpdateUserId]               NVARCHAR (150)   NULL,
    [DaysofFreeLock]                  INT              NULL,
    [NoteComments]                    NVARCHAR (MAX)   NULL,
    [AverageLife]                     DECIMAL (28, 15) NULL,
    [Duration]                        DECIMAL (28, 15) NULL,
    [FundingDate]                     DATETIME         NULL,
    [AltIndexName]                    NVARCHAR (20)    NULL,
    [AltIntPct]                       FLOAT (53)       NULL,
    [BondEquivPct]                    FLOAT (53)       NULL,
    [IOCostPct]                       FLOAT (53)       NULL,
    [AMBenefitPct]                    FLOAT (53)       NULL,
    [FloorBenefitPct]                 FLOAT (53)       NULL,
    [MiscSpreadPct]                   FLOAT (53)       NULL,
    [FreeRLPct]                       FLOAT (53)       NULL,
    [RLChargeBenefitPct]              FLOAT (53)       NULL,
    [fundedAmount]                    DECIMAL (28, 15) NULL,
    [NoteNumber]                      NVARCHAR (20)    NULL,
    [InterestRateLockedPercent]       DECIMAL (28, 15) NULL,
    [DV01Amount]                      DECIMAL (28, 15) NULL,
    [TolRel2InitDepositPct]           FLOAT (53)       NULL,
    [CurrentDepositAmount]            DECIMAL (28, 15) NULL,
    [NoteCurrencyCD_F]                NVARCHAR (256)   NULL,
    [InterimServContact_UserID_F]     INT              NULL,
    [SyndicateSell]                   DECIMAL (28, 15) NULL,
    [DMCDO]                           FLOAT (53)       NULL,
    [DMREPO]                          FLOAT (53)       NULL,
    [Controlling]                     BIT              NULL,
    [InterimServicer_ContactID_F]     NVARCHAR (256)   NULL,
    [MonthlyDebtServiceIO]            DECIMAL (28, 15) NULL,
    [MonthlyDebtServiceFinal]         DECIMAL (28, 15) NULL,
    [isLocked]                        INT              NULL,
    [FinancingSource]                 NVARCHAR (50)    NULL,
    [AdvanceRate]                     FLOAT (53)       NULL,
    [CovenantISCR]                    DECIMAL (28, 15) NULL,
    [CovenantDSCR]                    DECIMAL (28, 15) NULL,
    [LTV]                             FLOAT (53)       NULL,
    [LTC]                             FLOAT (53)       NULL,
    [ELClass]                         INT              NULL,
    [IRRBaselI]                       FLOAT (53)       NULL,
    [IRRBaselII]                      FLOAT (53)       NULL,
    [LGD]                             FLOAT (53)       NULL,
    [LTVCovenantAsStabilized]         FLOAT (53)       NULL,
    [LTCCovenantAsStabilized]         FLOAT (53)       NULL,
    [DSCRCovenantAsIsStressed]        DECIMAL (28, 15) NULL,
    [DSCRCovenantAsStabilized]        DECIMAL (28, 15) NULL,
    [ISCRCovenantAsStabilized]        DECIMAL (28, 15) NULL,
    [MinimumDebtYield]                FLOAT (53)       NULL,
    [LGDPct]                          FLOAT (53)       NULL,
    [ELPct]                           FLOAT (53)       NULL,
    [AgentBank_OrgId_F]               NVARCHAR (256)   NULL,
    [AgentBank_ContactId_F]           NVARCHAR (256)   NULL,
    [CoAgentBank_OrgId_F]             NVARCHAR (256)   NULL,
    [CoAgentBank_ContactId_F]         NVARCHAR (256)   NULL,
    [LoanAdminCostRate]               FLOAT (53)       NULL,
    [InvestmentGrade]                 NVARCHAR (3)     NULL,
    [StartLTV]                        FLOAT (53)       NULL,
    [StartLTC]                        FLOAT (53)       NULL,
    [StartDSCR]                       DECIMAL (28, 15) NULL,
    [StartISCR]                       DECIMAL (28, 15) NULL,
    [ASRNoteComments]                 NVARCHAR (MAX)   NULL,
    [ActualRepaymentDate]             DATETIME         NULL,
    [StubInterestAmt]                 DECIMAL (28, 15) NULL,
    [NegAmTreatmentCd_F]              NVARCHAR (256)   NULL,
    [MpCallOptionDate]                DATETIME         NULL,
    [MonthlyDebtServiceIOFinal]       DECIMAL (28, 15) NULL,
    [ModifiedNoteSw]                  BIT              NULL,
    [ModificationParentNoteId_F]      INT              NULL,
    [SystemCodeCd_F]                  NVARCHAR (256)   NULL,
    [FacilityTypeCd_F]                NVARCHAR (256)   NULL,
    [isPrimaryDebtFlag]               INT              NULL,
    [EstFundDate]                     DATETIME         NULL,
    [ClientIdentifier]                NVARCHAR (200)   NULL,
    [PropertyContainerID_F]           NVARCHAR (256)   NULL,
    [InitialFixedPeriod]              NVARCHAR (20)    NULL,
    [FacilityTypeOtherCd_F]           NVARCHAR (256)   NULL,
    [IncrementalRenewalRevenue]       DECIMAL (28, 15) NULL,
    [InterestRateForUnderwritingSave] DECIMAL (28, 15) NULL,
    [NoteIDAsString]                  NVARCHAR (26)    NULL,
    [PreviousNoteDate]                DATETIME         NULL,
    [ExtensionFee]                    FLOAT (53)       NULL,
    [AllocationDate]                  DATE             NULL,
    [OrigFundingDate]                 DATE             NULL,
    [StubAmortSchedDate]              DATE             NULL,
    [StubAmortInterestAmt]            FLOAT (53)       NULL,
    [StubAmortDaysInPeriod]           INT              NULL,
    [StubAmortInterestRate]           FLOAT (53)       NULL,
    [StubAmortBalanceAmt]             FLOAT (53)       NULL,
    [InvestorSpread]                  FLOAT (53)       NULL,
    [ClientNoteName]                  NVARCHAR (60)    NULL,
    [SyncFundingDate]                 INT              NULL,
    [TotalCommitment]                 DECIMAL (28, 15) NULL,
    [TotalCurrentAdjustedCommitment]  DECIMAL (28, 15) NULL,
    [PastFunding]                     DECIMAL (28, 15) NULL,
    [FutureFunding]                   DECIMAL (28, 15) NULL
);

