CREATE TABLE [DW].[L_UwDealBI] (
    [ControlId]                                NVARCHAR (10)    NOT NULL,
    [LoanNumber]                               NVARCHAR (25)    NULL,
    [LoanStatusCd_F]                           NVARCHAR (256)   NULL,
    [BrokerName_OrgId_F]                       NVARCHAR (256)   NULL,
    [LendorName_OrgId_F]                       NVARCHAR (256)   NULL,
    [LawFirm_OrgId_F]                          NVARCHAR (256)   NULL,
    [Office_OrgId_F]                           NVARCHAR (256)   NULL,
    [DealRelatedId_F]                          NVARCHAR (256)   NULL,
    [Competition_Org_Id_F]                     NVARCHAR (256)   NULL,
    [DueDiligenceProvider_OrgId_F]             NVARCHAR (256)   NULL,
    [OriginalDataSource_F]                     NVARCHAR (256)   NULL,
    [MinimumDSCR]                              FLOAT (53)       NULL,
    [MinimumDSCRatConstant]                    FLOAT (53)       NULL,
    [MaximumLTV]                               FLOAT (53)       NULL,
    [MinimumConstantDeal]                      FLOAT (53)       NULL,
    [PrimaryBanker_UserId_F]                   INT              NULL,
    [SecondaryBanker_UserId_F]                 INT              NULL,
    [Underwriter_UserID_F]                     INT              NULL,
    [ServicersLoanNumber]                      NVARCHAR (30)    NULL,
    [DealName]                                 NVARCHAR (75)    NOT NULL,
    [CreditApprovedBy]                         VARCHAR (50)     NULL,
    [CreditApprovedComment]                    NVARCHAR (MAX)   NULL,
    [SpreadApprovedBy]                         VARCHAR (50)     NULL,
    [SpreadApprovedComment]                    NVARCHAR (MAX)   NULL,
    [Correspondent]                            NVARCHAR (50)    NULL,
    [CorrUW]                                   NVARCHAR (50)    NULL,
    [CollateralType]                           NVARCHAR (30)    NULL,
    [DebtServiceAllocated]                     NVARCHAR (255)   NULL,
    [LoanPurpose]                              NVARCHAR (25)    NULL,
    [LoanProbability]                          FLOAT (53)       NULL,
    [ApplicationReceiveDate]                   DATETIME         NULL,
    [ApplicationDate]                          DATETIME         NULL,
    [LenderRightToMatch]                       NVARCHAR (3)     NULL,
    [ApplicationDeposit]                       DECIMAL (28, 15) NULL,
    [LockBox]                                  NVARCHAR (50)    NULL,
    [LockBoxComment]                           NVARCHAR (MAX)   NULL,
    [HardCashManagement]                       NVARCHAR (25)    NULL,
    [Recourse]                                 NVARCHAR (3)     NULL,
    [ClosingConditions]                        NVARCHAR (MAX)   NULL,
    [EstClosingCosts]                          DECIMAL (28, 15) NULL,
    [EarnOut]                                  NVARCHAR (3)     NULL,
    [IndDirectorReqSw]                         NVARCHAR (3)     NULL,
    [NonConsolOpinionReqSw]                    NVARCHAR (3)     NULL,
    [OwnershipComments]                        NVARCHAR (MAX)   NULL,
    [BrokerFees]                               DECIMAL (28, 15) NULL,
    [Cashout]                                  NVARCHAR (3)     NULL,
    [PreliminarySponsor]                       NVARCHAR (600)   NULL,
    [OngoingDSCRTest]                          NVARCHAR (MAX)   NULL,
    [SpecialPricingNotes]                      NVARCHAR (MAX)   NULL,
    [HardEquityComment]                        NVARCHAR (MAX)   NULL,
    [MatrixSpreadAtClose]                      FLOAT (53)       NULL,
    [MatrixSpreadAtCloseComments]              NVARCHAR (MAX)   NULL,
    [CommitmentExpDate]                        DATETIME         NULL,
    [Comments]                                 NVARCHAR (MAX)   NULL,
    [TICSw]                                    BIT              NULL,
    [MpIsLoanAssumable]                        NVARCHAR (3)     NULL,
    [MpIsLoanAssumableDesc]                    NVARCHAR (MAX)   NULL,
    [MpEquityParticipation]                    NVARCHAR (3)     NULL,
    [MpEquityParticipationDesc]                NVARCHAR (MAX)   NULL,
    [MpAllowFutAdvances]                       NVARCHAR (3)     NULL,
    [MpAllowFutAdvancesDesc]                   NVARCHAR (MAX)   NULL,
    [MpMaxFutureAdvances]                      DECIMAL (28, 15) NULL,
    [MpFutAdvancesToDate]                      DECIMAL (28, 15) NULL,
    [MpAssumptionFeePct]                       FLOAT (53)       NULL,
    [MpAssumptionFeeAmt]                       DECIMAL (28, 15) NULL,
    [MpAssumptionFee]                          FLOAT (53)       NULL,
    [MpAssumptionFeeDesc]                      NVARCHAR (MAX)   NULL,
    [MpParticipationPercent]                   FLOAT (53)       NULL,
    [MpParticipationPercentDesc]               NVARCHAR (MAX)   NULL,
    [MpRightToInspectRecords]                  NVARCHAR (MAX)   NULL,
    [MpUnsecuredDebtAllowed]                   NVARCHAR (3)     NULL,
    [MpMaxUnsecuredDebtAmt]                    DECIMAL (28, 15) NULL,
    [MpTradePayablesMaxAmt]                    DECIMAL (28, 15) NULL,
    [MpTradePayablesDaysOut]                   INT              NULL,
    [MpPartialReleasePercent]                  FLOAT (53)       NULL,
    [MpPartialReleaseDesc]                     NVARCHAR (MAX)   NULL,
    [MpComment]                                NVARCHAR (MAX)   NULL,
    [GCM_DealCounterpartyCode]                 NVARCHAR (10)    NULL,
    [AuditAddDate]                             DATETIME         NOT NULL,
    [AuditAddUserId]                           NVARCHAR (150)   NULL,
    [AuditUpdateDate]                          DATETIME         NULL,
    [AuditUpdateUserId]                        NVARCHAR (150)   NULL,
    [PatriotActApprovedSw]                     BIT              NULL,
    [OwnerOrgId_F]                             NVARCHAR (256)   NULL,
    [BrokerFeesComment]                        NVARCHAR (MAX)   NULL,
    [ArchiveInvestorFileSw]                    BIT              NULL,
    [ArchiveLegalBinderSw]                     BIT              NULL,
    [ArchiveComment]                           NVARCHAR (MAX)   NULL,
    [LoanProgramCD_F]                          NVARCHAR (256)   NULL,
    [LenderRoleCD_F]                           NVARCHAR (256)   NULL,
    [TargetLoan]                               DECIMAL (28, 15) NULL,
    [EstAppraisedCollateralValue]              DECIMAL (28, 15) NULL,
    [EstStressedCollateralValue]               DECIMAL (28, 15) NULL,
    [AcquisitionCostofCollateral]              DECIMAL (28, 15) NULL,
    [Matrix]                                   NVARCHAR (10)    NULL,
    [CompetitionComments]                      NVARCHAR (MAX)   NULL,
    [HardEquityAmount]                         DECIMAL (28, 15) NULL,
    [DealLocked]                               BIT              NULL,
    [DealCurrencyCD_F]                         NVARCHAR (256)   NULL,
    [Originator]                               VARCHAR (50)     NULL,
    [SourceUsesComment]                        NVARCHAR (MAX)   NULL,
    [StartLTV]                                 FLOAT (53)       NULL,
    [FirstLossComment]                         NVARCHAR (MAX)   NULL,
    [Change2TicAfterCloseSw]                   NVARCHAR (3)     NULL,
    [SpringingLockBoxComment]                  NVARCHAR (MAX)   NULL,
    [BrokerFeesPct]                            FLOAT (53)       NULL,
    [CommitmentAmount]                         DECIMAL (28, 15) NULL,
    [Analyst_UserId_F]                         INT              NULL,
    [LoanTypeCD_F]                             NVARCHAR (256)   NULL,
    [CreditApprovedDate]                       DATETIME         NULL,
    [SpreadApprovedDate]                       DATETIME         NULL,
    [DDP_ContactID_F]                          NVARCHAR (256)   NULL,
    [Broker_ContactID_F]                       NVARCHAR (256)   NULL,
    [Cocounsel_ContactID_F]                    NVARCHAR (256)   NULL,
    [Counsel_ContactID_F]                      NVARCHAR (256)   NULL,
    [Paralegal_ContactID_F]                    NVARCHAR (256)   NULL,
    [RequestedLoanTerm]                        INT              NULL,
    [RequestedAmortTerm]                       INT              NULL,
    [RequestedSpread]                          FLOAT (53)       NULL,
    [RequestedIndex]                           NVARCHAR (20)    NULL,
    [RequestedLTV]                             FLOAT (53)       NULL,
    [RequestedLTC]                             FLOAT (53)       NULL,
    [TransactionManager_Userid_F]              INT              NULL,
    [HUDLoanNumber]                            NVARCHAR (35)    NULL,
    [ApprovalLevel]                            INT              NULL,
    [ExistingDebt]                             NVARCHAR (3)     NULL,
    [ExistingDebtLender]                       NVARCHAR (50)    NULL,
    [ExistingDebtAmount]                       DECIMAL (28, 15) NULL,
    [EarnOutAmount]                            DECIMAL (28, 15) NULL,
    [MarketEquityComments]                     NVARCHAR (MAX)   NULL,
    [BookingLocation_OrgId_F]                  NVARCHAR (256)   NULL,
    [PortfolioManager_Userid_F]                INT              NULL,
    [PrivateSW]                                BIT              NULL,
    [CMBSLoanStatusCd_F]                       NVARCHAR (256)   NULL,
    [CMBSDealGUID]                             UNIQUEIDENTIFIER NULL,
    [MPFutureAdditionalDebtPermitted]          NVARCHAR (3)     NULL,
    [NDCApprovedCd_F]                          NVARCHAR (256)   NULL,
    [NDCApprovedBy]                            NVARCHAR (50)    NULL,
    [NDCApprovedComment]                       NVARCHAR (MAX)   NULL,
    [NDCSecuritization]                        NVARCHAR (3)     NULL,
    [NDCSyndication]                           NVARCHAR (3)     NULL,
    [NDCApprovedDate]                          DATETIME         NULL,
    [CreditApproved]                           NVARCHAR (5)     NULL,
    [SpreadApproved]                           NVARCHAR (5)     NULL,
    [SecondaryPortfolioManager_UserId_F]       INT              NULL,
    [Legal_UserId_F]                           INT              NULL,
    [IRRBaselI]                                FLOAT (53)       NULL,
    [IRRBaselII]                               FLOAT (53)       NULL,
    [ListedCompany]                            NVARCHAR (3)     NULL,
    [PriceSensitive]                           NVARCHAR (3)     NULL,
    [Confidentiality]                          NVARCHAR (3)     NULL,
    [Exclusivity]                              NVARCHAR (3)     NULL,
    [ShareDeal]                                NVARCHAR (3)     NULL,
    [RequestedPaymentFreqCd_F]                 NVARCHAR (256)   NULL,
    [RequestedIOTerm]                          INT              NULL,
    [RequestedLTVasStabilzed]                  FLOAT (53)       NULL,
    [RequestedRateTypeCd_F]                    NVARCHAR (256)   NULL,
    [BorrowerImputedEquity]                    DECIMAL (28, 15) NULL,
    [LoanSizer_UserId_F]                       INT              NULL,
    [ConstructionManager_UserId_F]             INT              NULL,
    [InsuranceManager_UserId_F]                INT              NULL,
    [DealIntroducedById_F]                     INT              NULL,
    [CoCounselCompany_OrgId_F]                 NVARCHAR (256)   NULL,
    [CoCounselCompany_ContactId_F]             NVARCHAR (256)   NULL,
    [SecondaryLawFirm_OrgId_F]                 NVARCHAR (256)   NULL,
    [SecondaryCounsel_ContactID_F]             NVARCHAR (256)   NULL,
    [SpecificDealTeamRequest]                  NVARCHAR (MAX)   NULL,
    [QCAnalyst_UserID_F]                       INT              NULL,
    [OriginatorAssociate]                      NVARCHAR (100)   NULL,
    [ClosingCoordinator_UserID_F]              INT              NULL,
    [AssetManager_UserID_F]                    INT              NULL,
    [NDCSecuritizationRequiredAmt]             DECIMAL (28, 15) NULL,
    [NDCSyndicationRequiredAmt]                DECIMAL (28, 15) NULL,
    [BrokeredDeal]                             NVARCHAR (3)     NULL,
    [DataTapeFootNotes]                        NVARCHAR (MAX)   NULL,
    [MortgageOriginatingEntityCD_F]            NVARCHAR (256)   NULL,
    [DealSourceCD_F]                           NVARCHAR (256)   NULL,
    [ProgramManager_UserId_F]                  INT              NULL,
    [SmallLoanPM_UserId_F]                     INT              NULL,
    [UnderwritingManager_UserId_F]             INT              NULL,
    [Servicer_UserId_F]                        INT              NULL,
    [QALead_UserId_F]                          INT              NULL,
    [QAAssociate_UserId_F]                     INT              NULL,
    [ReportManager_UserId_F]                   INT              NULL,
    [BorrowerLawFirm_OrgId_F]                  NVARCHAR (256)   NULL,
    [BorrowerInsuranceCo_OrgId_F]              NVARCHAR (256)   NULL,
    [BorrowerCounsel_ContactID_F]              NVARCHAR (256)   NULL,
    [BorrowerInsAgent_ContactID_F]             NVARCHAR (256)   NULL,
    [Holdback]                                 NVARCHAR (3)     NULL,
    [HoldbackAmount]                           DECIMAL (18)     NULL,
    [EstimatedCreditDate]                      DATETIME         NULL,
    [Secondary_BrokerName_OrgId_F]             NVARCHAR (256)   NULL,
    [Secondary_Broker_ContactID_F]             NVARCHAR (256)   NULL,
    [RepeatSponsorComment]                     NVARCHAR (MAX)   NULL,
    [KickOffEmailSent]                         BIT              NULL,
    [ExpirationStatus]                         TINYINT          NULL,
    [ApplicationDepositFeePct]                 FLOAT (53)       NULL,
    [EarnOutComment]                           NVARCHAR (MAX)   NULL,
    [RealizedLossToTrust]                      DECIMAL (28, 15) NULL,
    [NonRecoverability]                        NVARCHAR (3)     NULL,
    [LastSetupChangeDate]                      DATETIME         NULL,
    [LastLoanContributionDate]                 DATETIME         NULL,
    [LastPropContributionDate]                 DATETIME         NULL,
    [AssumptionDate]                           DATETIME         NULL,
    [LockBoxAtClosing]                         NVARCHAR (3)     NULL,
    [BrokerFeesPctTypeCd_F]                    NVARCHAR (256)   NULL,
    [BrokerFeesPctPaymentCd_F]                 NVARCHAR (256)   NULL,
    [ControlMasterID]                          INT              NULL,
    [Recovery]                                 DECIMAL (28, 15) NULL,
    [USTL_UserId_F]                            INT              NULL,
    [USQCAnalyst_UserId_F]                     INT              NULL,
    [Sponsor_OrgId_F]                          NVARCHAR (256)   NULL,
    [AvailabilityCd_F]                         NVARCHAR (256)   NULL,
    [AvailabilityDate]                         DATETIME         NULL,
    [ForeignInvestorsMore]                     NVARCHAR (3)     NULL,
    [PCAccountingContact]                      NVARCHAR (50)    NULL,
    [PCAccountingContactNumber]                NVARCHAR (50)    NULL,
    [PCServicingContact]                       NVARCHAR (50)    NULL,
    [PCServicingContactNumber]                 NVARCHAR (50)    NULL,
    [MinimumNCF]                               DECIMAL (28, 15) NULL,
    [AssetManagementStatusCd_F]                NCHAR (20)       NULL,
    [ConditionalCommitmentDeposit]             DECIMAL (28, 15) NULL,
    [CouponCurrent]                            FLOAT (53)       NULL,
    [CouponBase]                               FLOAT (53)       NULL,
    [CouponStress]                             FLOAT (53)       NULL,
    [ConstantCurrent]                          FLOAT (53)       NULL,
    [ConstantBase]                             FLOAT (53)       NULL,
    [ConstantStress]                           FLOAT (53)       NULL,
    [StressedCapRate]                          FLOAT (53)       NULL,
    [StressedConstant]                         FLOAT (53)       NULL,
    [BankNumberCD_F]                           NVARCHAR (115)   NULL,
    [OCCLoanPurposeCD_F]                       NVARCHAR (256)   NULL,
    [GeneralLedgerCD_F]                        NVARCHAR (256)   NULL,
    [CustomerId_F]                             NVARCHAR (256)   NULL,
    [NextAnnualReviewDate]                     DATETIME         NULL,
    [Exempt]                                   BIT              NULL,
    [First12MonthsRevenue]                     DECIMAL (28, 15) NULL,
    [LastAnnualReviewDate]                     DATETIME         NULL,
    [BusinessLineManager_UserId_F]             INT              NULL,
    [WDP]                                      DECIMAL (28, 15) NULL,
    [WDPx]                                     FLOAT (53)       NULL,
    [AdditionalCollateral]                     DECIMAL (28, 15) NULL,
    [InvestmentLeverage]                       FLOAT (53)       NULL,
    [BorrowerSecondaryLawFirm_OrgId_F]         NVARCHAR (256)   NULL,
    [BorrowerSecondaryCounsel_ContactId_F]     NVARCHAR (256)   NULL,
    [PROOwnerInvestor_OrgId_F]                 NVARCHAR (256)   NULL,
    [PROSponsorDeveloper_OrgId_F]              NVARCHAR (256)   NULL,
    [PROBrokerDebt_OrgId_F]                    NVARCHAR (256)   NULL,
    [PROBrokerEquity_OrgId_F]                  NVARCHAR (256)   NULL,
    [PROBrokerLeasing_OrgId_F]                 NVARCHAR (256)   NULL,
    [PROLender_OrgId_F]                        NVARCHAR (256)   NULL,
    [PRODueDiligence_OrgId_F]                  NVARCHAR (256)   NULL,
    [PROAppraiser_OrgId_F]                     NVARCHAR (256)   NULL,
    [PROLawFirm_OrgId_F]                       NVARCHAR (256)   NULL,
    [SecondaryOfficeCd_F]                      NVARCHAR (256)   NULL,
    [LoanPurposeComments]                      NVARCHAR (MAX)   NULL,
    [AdditionalCollateralTypeCd_F]             NVARCHAR (256)   NULL,
    [DealLevelMarketComments]                  NVARCHAR (MAX)   NULL,
    [UnderwritingGuidelineDeviationComments]   NVARCHAR (MAX)   NULL,
    [AdministrationVarianceComments]           NVARCHAR (MAX)   NULL,
    [Active]                                   NVARCHAR (3)     NULL,
    [StabilizedDebtYield]                      FLOAT (53)       NULL,
    [WorkflowTemplateTypeCd_F]                 NVARCHAR (256)   NULL,
    [ExistingDebtMaturityDate]                 DATETIME         NULL,
    [Market]                                   NVARCHAR (100)   NULL,
    [MarketTotalSF]                            NUMERIC (18)     NULL,
    [MarketVacancy]                            NUMERIC (18)     NULL,
    [PurchasePrice]                            FLOAT (53)       NULL,
    [TILC]                                     FLOAT (53)       NULL,
    [Capex]                                    FLOAT (53)       NULL,
    [ClosingCosts]                             FLOAT (53)       NULL,
    [ROA]                                      DECIMAL (18)     NULL,
    [LPDRCD_F]                                 NVARCHAR (10)    NULL,
    [SPDRCD_F]                                 NVARCHAR (10)    NULL,
    [AssetManagementStatusColorCd_F]           NVARCHAR (256)   NULL,
    [CommunityLendingDevelopmentPurposeCd_F]   NVARCHAR (256)   NULL,
    [AlternateDealNumber]                      NVARCHAR (50)    NULL,
    [MortgageLoanOriginator_OrgId_F]           NVARCHAR (256)   NULL,
    [MortgageLoanSeller_OrgId_F]               NVARCHAR (256)   NULL,
    [SEREFAllocation]                          FLOAT (53)       NULL,
    [StarFinAllocation]                        FLOAT (53)       NULL,
    [SEREFStarFinIRR]                          FLOAT (53)       NULL,
    [ServicerWillSpreadFinancials]             NVARCHAR (3)     NULL,
    [FirmProductionDate]                       DATETIME         NULL,
    [CreditRiskApprovalDate]                   DATETIME         NULL,
    [CreditRiskDeniedDate]                     DATETIME         NULL,
    [ReferralFee]                              FLOAT (53)       NULL,
    [FANumber]                                 VARCHAR (20)     NULL,
    [LegalFeeAmount]                           DECIMAL (28, 15) NULL,
    [QuotedDate]                               DATETIME         NULL,
    [PrelimPricingBucket]                      VARCHAR (50)     NULL,
    [PrelimPricingBucketComments]              NVARCHAR (MAX)   NULL,
    [ReferralIDNumber]                         NVARCHAR (50)    NULL,
    [CopyDealOptionCd_F]                       NVARCHAR (10)    NULL,
    [CurrentLPDRCD_F]                          NVARCHAR (10)    NULL,
    [GPDRCD_F]                                 NVARCHAR (10)    NULL,
    [ProbabilityCD_F]                          NVARCHAR (50)    NULL,
    [CapitalMarketProductSW]                   BIT              NOT NULL,
    [MortgageBroker_OrgId_F]                   NVARCHAR (256)   NULL,
    [DealSponsor_OrgId_F]                      NVARCHAR (256)   NULL,
    [MortgageBroker_ContactId_F]               NVARCHAR (256)   NULL,
    [isMUV]                                    NVARCHAR (3)     NULL,
    [ClientIdentifier]                         NVARCHAR (100)   NULL,
    [DueDiligencePeriod]                       INT              NULL,
    [PrincipalNetWorthGreaterThanLoan]         BIT              NULL,
    [PrincipalLiquidityGreaterThanDebtService] BIT              NULL,
    [PrincipalsFreeOfBankruptcyForeclosureDIL] BIT              NULL,
    [PrincipalsFreeOfLitigation]               BIT              NULL,
    [WithholdingTaxExemptionRequired]          BIT              NULL,
    [DealSourceFirm]                           INT              NULL,
    [DealSourceContact]                        INT              NULL,
    [CMBSControlMasterID]                      BIGINT           NULL,
    [TeamLeader_UserID_F]                      INT              NULL,
    [SecondaryCounsel_Contact2ID_F]            NVARCHAR (256)   NULL,
    [SecondaryCounsel_Contact3ID_F]            NVARCHAR (256)   NULL,
    [BorrowerCounsel_Contact2ID_F]             NVARCHAR (256)   NULL,
    [BorrowerCounsel_Contact3ID_F]             NVARCHAR (256)   NULL,
    [SecondaryBorrowerFirm_OrgId_F]            NVARCHAR (256)   NULL,
    [SecondaryBorrowerFirm_ContactID_F]        NVARCHAR (256)   NULL,
    [MasterServicer_OrgId_F]                   NVARCHAR (256)   NULL,
    [DealBorrower_OrgId_F]                     NVARCHAR (256)   NULL,
    [TertiaryLawFirm_OrgId_F]                  NVARCHAR (256)   NULL,
    [DealBorrowerContact1_ContactId_F]         NVARCHAR (256)   NULL,
    [DealBorrowerContact2_ContactId_F]         NVARCHAR (256)   NULL,
    [DealBorrowerContact3_ContactId_F]         NVARCHAR (256)   NULL,
    [DealBorrowerContact4_ContactId_F]         NVARCHAR (256)   NULL,
    [DealBorrowerContact5_ContactId_F]         NVARCHAR (256)   NULL,
    [DealBorrowerContact6_ContactId_F]         NVARCHAR (256)   NULL,
    [TertiaryCounsel_ContactId_F]              NVARCHAR (256)   NULL,
    [TertiaryCoCounsel_ContactId_F]            NVARCHAR (256)   NULL,
    [UnleveredMultipleNetAtOrigination]        DECIMAL (28, 15) NULL,
    [LeveredIRRGrossAtOrigination]             DECIMAL (28, 15) NULL,
    [LeveredIRRNetAtOrigination]               DECIMAL (28, 15) NULL,
    [LeveredProfitGrossAtOrigination]          DECIMAL (28, 15) NULL,
    [LeveredProfitNetAtOrigination]            DECIMAL (28, 15) NULL,
    [LeveredMultipleGrossAtOrigination]        DECIMAL (28, 15) NULL,
    [LeveredMultipleNetAtOrigination]          DECIMAL (28, 15) NULL,
    [InitialDebtYield]                         FLOAT (53)       NULL,
    [ClosedDealLockSW]                         BIT              NULL,
    [StrategyTypeCD_F]                         NVARCHAR (20)    NULL,
    [PNAStatus]                                NVARCHAR (10)    NULL,
    [LoanDefaultDate]                          DATETIME         NULL,
    [DefaultLetterSentDate]                    DATETIME         NULL,
    [ForclosureFiledExpectedDate]              DATETIME         NULL,
    [LastPatriotActChecked]                    DATETIME         NULL,
    [FreeofJrSubDebt]                          NVARCHAR (3)     NULL,
    [AnticipatedPayoffComment]                 NVARCHAR (MAX)   NULL,
    [AnticipatedActualCofODate]                DATETIME         NULL,
    [OrganizationDealStatusID_F]               INT              NULL,
    [RiskMatrixCd_F]                           NVARCHAR (10)    NULL,
    [DispositionMethodCd_F]                    NVARCHAR (10)    NULL,
    [PriorOutlookColorCd_F]                    NVARCHAR (10)    NULL,
    [AssetManagementLTVorLTC]                  NVARCHAR (3)     NULL,
    [BusinessPlanCd_F]                         NVARCHAR (256)   NULL,
    [AssetMgmtMarketCd_F]                      NVARCHAR (256)   NULL,
    [ReviewRotationCd_F]                       NVARCHAR (256)   NULL,
    [AssetManagementRecourseCd_F]              NVARCHAR (256)   NULL,
    [PipelineReportReview]                     NVARCHAR (3)     NULL,
    [DACABank_OrgId_F]                         NVARCHAR (256)   NULL,
    [CMABank_OrgId_F]                          NVARCHAR (256)   NULL,
    [LenderCashMgmtSuspended]                  NVARCHAR (3)     NULL,
    [LenderCashMgmtSuspendedUntilDate]         DATETIME         NULL,
    [TriggersEventOfDefault]                   NVARCHAR (3)     NULL,
    [TriggersDSCROperator]                     NVARCHAR (2)     NULL,
    [TriggersDSCRValue]                        FLOAT (53)       NULL,
    [TriggersDebtYieldOperator]                NVARCHAR (2)     NULL,
    [TriggersDebtYieldValue]                   FLOAT (53)       NULL,
    [TriggersOtherCondition1]                  NVARCHAR (MAX)   NULL,
    [CureEventOfDefault]                       NVARCHAR (3)     NULL,
    [CureDSCROperator]                         NVARCHAR (2)     NULL,
    [CureDSCRValue]                            FLOAT (53)       NULL,
    [CureDSCRNumOfConsecutivePeriods]          INT              NULL,
    [CureDSCRDurationCd_F]                     NVARCHAR (10)    NULL,
    [CureDebtYieldOperator]                    NVARCHAR (2)     NULL,
    [CureDebtYieldValue]                       FLOAT (53)       NULL,
    [CureDebtYieldNumOfConsecutivePeriods]     INT              NULL,
    [CureDebtYieldDurationCd_F]                NVARCHAR (10)    NULL,
    [CureOtherCondition1]                      NVARCHAR (MAX)   NULL,
    [CureOtherCondition2]                      NVARCHAR (MAX)   NULL,
    [CureOtherCondition3]                      NVARCHAR (MAX)   NULL,
    [TriggersOtherCondition2]                  NVARCHAR (MAX)   NULL,
    [TriggersOtherCondition3]                  NVARCHAR (MAX)   NULL,
    [DealBorrower2_OrgId_F]                    NVARCHAR (256)   NULL,
    [DealBorrower3_OrgId_F]                    NVARCHAR (256)   NULL,
    [DealBorrower4_OrgId_F]                    NVARCHAR (256)   NULL,
    [DealBorrower5_OrgId_F]                    NVARCHAR (256)   NULL,
    [DealBorrower6_OrgId_F]                    NVARCHAR (256)   NULL,
    [REITPropertyTypeCd_F]                     NVARCHAR (256)   NULL,
    [REITSectorTypeCd_F]                       NVARCHAR (10)    NULL,
    [UWLTCatOrigination]                       NVARCHAR (30)    NULL,
    [UWLTVatOrigination]                       NVARCHAR (30)    NULL,
    [DSCRatOrigination]                        NVARCHAR (30)    NULL,
    [DebtYieldAsIs]                            NVARCHAR (30)    NULL,
    [UnleveredIRRGross]                        NVARCHAR (30)    NULL,
    [UnleveredProfitGross]                     NVARCHAR (30)    NULL,
    [UnleveredMultipleGross]                   NVARCHAR (30)    NULL,
    [LeveredIRRGross]                          NVARCHAR (30)    NULL,
    [LeveredProfitGross]                       NVARCHAR (30)    NULL,
    [LeveredMultipleGross]                     NVARCHAR (30)    NULL,
    [StabilizedLTV]                            NVARCHAR (50)    NULL,
    [StabilizedLTC]                            NVARCHAR (50)    NULL,
    [SecuritizationID_F]                       INT              NULL,
    [InvestmentTypeCD_F]                       INT              NULL,
    [LTCFullyFunded]                           FLOAT (53)       NULL,
    [LTVAtStab]                                FLOAT (53)       NULL,
    [AllocationDate]                           DATE             NULL,
    [AcoreRating]                              NVARCHAR (500)   NULL,
    [OrigFundingDate]                          DATE             NULL,
    [ModifiedFrom]                             VARCHAR (10)     NULL,
    [GLStatusDate]                             DATETIME         NULL,
    [CurrentLPDRDate]                          DATETIME         NULL,
    [ReferredByUsername]                       NVARCHAR (10)    NULL,
    [InitialLTCPct]                            FLOAT (53)       NULL,
    [EndLTCPct]                                FLOAT (53)       NULL,
    [NonRefundableProcessingFee]               DECIMAL (28, 15) NULL,
    [TermSheetExclusivePeriod]                 INT              NULL,
    [BreakUpFee]                               DECIMAL (28, 15) NULL,
    [PrincipalGuarantee]                       DECIMAL (28, 15) NULL,
    [ClosingEquityRequired]                    DECIMAL (28, 15) NULL,
    [ReferralChannel]                          NVARCHAR (10)    NULL,
    [HMDASw]                                   BIT              NOT NULL,
    [RecourseTypeCD_F]                         NVARCHAR (10)    NULL,
    [ApprovedByCd_F]                           NVARCHAR (10)    NULL,
    [EstimateCashOut]                          DECIMAL (28, 15) NULL,
    [ChangesInConditionalApproval]             NVARCHAR (3)     NULL,
    [ChangesInTermsAndConditions]              NVARCHAR (3)     NULL,
    [SeniorReportManager_UserId_F]             INT              NULL,
    [CoLendApprovedSw]                         BIT              NOT NULL,
    [PropertyAQR]                              FLOAT (53)       NULL,
    [GuarantorAQR]                             FLOAT (53)       NULL,
    [DealAQR]                                  FLOAT (53)       NULL,
    [OriginalLoanTerm]                         NVARCHAR (50)    NULL,
    [DebtYieldStabilization]                   NVARCHAR (100)   NULL,
    [AMTeamLeader_UserId_F]                    INT              NULL
);

