CREATE TABLE [DW].[NoteMatrixBI_Test] (
    [DealID]                   NVARCHAR (256)   NULL,
    [DealGroupID]              NVARCHAR (256)   NULL,
    [NoteID]                   NVARCHAR (256)   NULL,
    [Pri]                      INT              NULL,
    [DealName]                 NVARCHAR (256)   NULL,
    [NoteName]                 NVARCHAR (256)   NULL,
    [LoanStatus]               NVARCHAR (256)   NULL,
    [Client]                   NVARCHAR (256)   NULL,
    [Fund]                     NVARCHAR (256)   NULL,
    [AssetManager]             NVARCHAR (256)   NULL,
    [Banker]                   NVARCHAR (256)   NULL,
    [Credit]                   NVARCHAR (256)   NULL,
    [Pool]                     NVARCHAR (256)   NULL,
    [FinancingSource]          NVARCHAR (256)   NULL,
    [DebtType]                 NVARCHAR (256)   NULL,
    [CapStack]                 NVARCHAR (256)   NULL,
    [BillingNote]              NVARCHAR (256)   NULL,
    [Commitment]               DECIMAL (28, 15) NULL,
    [Spread]                   DECIMAL (28, 15) NULL,
    [IndexforStub]             DECIMAL (28, 15) NULL,
    [Floor]                    DECIMAL (28, 15) NULL,
    [AllInRate]                DECIMAL (28, 15) NULL,
    [Type]                     NVARCHAR (256)   NULL,
    [InitialFunding]           DATE             NULL,
    [InitialMaturity]          DATE             NULL,
    [ExtendedMaturity]         DATE             NULL,
    [ExtendedMaturity1]        DATE             NULL,
    [ExtendedMaturity2]        DATE             NULL,
    [ExtendedMaturity3]        DATE             NULL,
    [ExtendedMaturity4]        DATE             NULL,
    [FullyExtendedMaturity]    DATE             NULL,
    [CurrentMaturityDate]      DATE             NULL,
    [CurrentMaturity]          NVARCHAR (256)   NULL,
    [PaidOffSold]              DATE             NULL,
    [FeesStart]                NVARCHAR (256)   NULL,
    [RSLIC]                    DECIMAL (28, 15) NULL,
    [SNCC]                     DECIMAL (28, 15) NULL,
    [PIIC]                     DECIMAL (28, 15) NULL,
    [TMR]                      DECIMAL (28, 15) NULL,
    [HCC]                      DECIMAL (28, 15) NULL,
    [USSIC]                    DECIMAL (28, 15) NULL,
    [TMNF]                     DECIMAL (28, 15) NULL,
    [HAIH]                     DECIMAL (28, 15) NULL,
    [Check]                    DECIMAL (28, 15) NULL,
    [CAMRA]                    NVARCHAR (256)   NULL,
    [Servicer]                 NVARCHAR (256)   NULL,
    [ServicerID]               NVARCHAR (256)   NULL,
    [PremDisc]                 DECIMAL (28, 15) NULL,
    [OriginationFee]           DECIMAL (28, 15) NULL,
    [FutureFundingsatParor99]  NVARCHAR (256)   NULL,
    [PaydownPayoffConvention]  INT              NULL,
    [Other]                    DECIMAL (28, 15) NULL,
    [NoteClassification]       NVARCHAR (256)   NULL,
    [ExitFee]                  DECIMAL (28, 15) NULL,
    [WholeLoanSpread]          DECIMAL (28, 15) NULL,
    [ExtensionFee1]            DECIMAL (28, 15) NULL,
    [ExtensionFee2]            DECIMAL (28, 15) NULL,
    [ExtensionFee3]            DECIMAL (28, 15) NULL,
    [ExtensionFee4]            DECIMAL (28, 15) NULL,
    [SeniorLoanSpread]         DECIMAL (28, 15) NULL,
    [SubLoanSpread]            DECIMAL (28, 15) NULL,
    [PaymentDate]              INT              NULL,
    [NoteMatrixBI_Test_AutoID] INT              IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_NoteMatrixBI_Test_AutoID] PRIMARY KEY CLUSTERED ([NoteMatrixBI_Test_AutoID] ASC)
);



