CREATE TABLE [DW].[PropertyBI] (
    [PropertyID]                UNIQUEIDENTIFIER NOT NULL,
    [Deal_DealID]               UNIQUEIDENTIFIER NOT NULL,
    [PropertyName]              NVARCHAR (256)   NULL,
    [Address]                   NVARCHAR (256)   NULL,
    [City]                      NVARCHAR (256)   NULL,
    [State]                     INT              NULL,
    [Zip]                       INT              NULL,
    [UWNCF]                     DECIMAL (28, 15) NULL,
    [SQFT]                      DECIMAL (28, 15) NULL,
    [PropertyType]              INT              NULL,
    [PropertyTypeBI]            NVARCHAR (256)   NULL,
    [AllocDebtPer]              DECIMAL (28, 15) NULL,
    [PropertySubtype]           INT              NULL,
    [NumberofUnitsorSF]         INT              NULL,
    [Occ]                       DECIMAL (28, 15) NULL,
    [Class]                     NVARCHAR (256)   NULL,
    [YearBuilt]                 NVARCHAR (256)   NULL,
    [Renovated]                 NVARCHAR (256)   NULL,
    [Bldgs]                     INT              NULL,
    [Acres]                     NVARCHAR (256)   NULL,
    [CreatedBy]                 NVARCHAR (256)   NULL,
    [CreatedDate]               DATETIME         NULL,
    [UpdatedBy]                 NVARCHAR (256)   NULL,
    [UpdatedDate]               DATETIME         NULL,
    [ProjectName]               NVARCHAR (256)   NULL,
    [HOUSESTREET1]              NVARCHAR (256)   NULL,
    [VILLAGE]                   NVARCHAR (256)   NULL,
    [ZIPCODE]                   NVARCHAR (256)   NULL,
    [OwnerOccupied]             NVARCHAR (256)   NULL,
    [PROPDESCCODE]              NVARCHAR (256)   NULL,
    [SALESPRICE]                INT              NULL,
    [ConstructionDate]          DATETIME         NULL,
    [NumberofStories]           DECIMAL (28, 15) NULL,
    [MeasuredIn]                NVARCHAR (256)   NULL,
    [TotalSquareFeet]           DECIMAL (28, 15) NULL,
    [TotalRentableSqFt]         DECIMAL (28, 15) NULL,
    [TotalNumberofUnits]        DECIMAL (28, 15) NULL,
    [OverallCondition]          NVARCHAR (256)   NULL,
    [RenovationDate]            DATETIME         NULL,
    [NextInspectionDate]        DATE             NULL,
    [GroundLease]               NVARCHAR (256)   NULL,
    [NumberOfTenants]           INT              NULL,
    [VacancyFactor]             DECIMAL (28, 15) NULL,
    [Allocation]                DECIMAL (28, 15) NULL,
    [LIENPosition]              INT              NULL,
    [CMSAProperyType]           NVARCHAR (256)   NULL,
    [PState]                    NVARCHAR (256)   NULL,
    [country]                   NVARCHAR (256)   NULL,
    [DealAllocationAmtPCT]      FLOAT (53)       NULL,
    [PropertyRollUpSW]          BIT              NULL,
    [IsDeleted]                 BIT              CONSTRAINT [DF__PropertyB__IsDel__0FA2421A] DEFAULT ((0)) NULL,
    [ReportDate]                DATE             NULL,
    [ValuationDate]             DATE             NULL,
    [ReconciledValue]           DECIMAL (28, 15) NULL,
    [AsCompletedDate]           DATE             NULL,
    [AsCompletedValue]          DECIMAL (28, 15) NULL,
    [AsStabilizedValuationDate] DATE             NULL,
    [AsStabilizedValue]         DECIMAL (28, 15) NULL,
    [LandValue]                 DECIMAL (28, 15) NULL,
    [Comment]                   NVARCHAR (MAX)   NULL,
    [HighlightComment]          NVARCHAR (MAX)   NULL,
    [PropertyAutoID]            INT              NOT NULL,
    [DealName]                  NVARCHAR (256)   NULL,
    [CREDealID]                 NVARCHAR (256)   NULL,
    [PropertyTypeMajorCd_F]     NVARCHAR (50)    NULL,
    [PropertyBI_AutoID]         INT              IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_PropertyBI_AutoID] PRIMARY KEY CLUSTERED ([PropertyBI_AutoID] ASC)
);



