CREATE TABLE [DW].[ReconciliationDetailBI] (
    [ReconciliationDetailId]                 INT              IDENTITY (1, 1) NOT NULL,
    [NoteId]                                 NVARCHAR (256)   NOT NULL,
    [DealId]                                 NVARCHAR (256)   NULL,
    [DealName]                               NVARCHAR (256)   NULL,
    [NoteName]                               NVARCHAR (256)   NULL,
    [ServicersLoanNumber]                    NVARCHAR (256)   NULL,
    [ServicerName]                           NVARCHAR (256)   NULL,
    [BackshopFinancingSourceCode]            NVARCHAR (256)   NULL,
    [BackshopFinancingCodeSourceName]        NVARCHAR (256)   NULL,
    [M61FinancingCodeSourceName]             NVARCHAR (256)   NULL,
    [PaidOff/Active]                         NVARCHAR (256)   NULL,
    [OrigLoanAmount]                         DECIMAL (28, 15) NULL,
    [TotalCommitment]                        DECIMAL (28, 15) NULL,
    [TotalCurrentAdjustedCommitment]         DECIMAL (28, 15) NULL,
    [PastFunding]                            DECIMAL (28, 15) NULL,
    [FutureFunding]                          DECIMAL (28, 15) NULL,
    [CurrentBalance]                         DECIMAL (28, 15) NULL,
    [EndingBalance]                          DECIMAL (28, 15) NULL,
    [CurCommitCurrBalRFFunding]              DECIMAL (28, 15) NULL,
    [RemainingFutureFundingPropertyRelease]  DECIMAL (28, 15) NULL,
    [RemainingFutureFundingPayoffs]          DECIMAL (28, 15) NULL,
    [RemainingFutureFundingLoanAmortization] DECIMAL (28, 15) NULL,
    [RemainingFutureFundingDifference]       DECIMAL (28, 15) NULL,
    [PercentofNote]                          DECIMAL (28, 15) NULL,
    [StatedMaturityDate]                     DATETIME         NULL,
    [FundingDate]                            DATETIME         NULL,
    [PeriodEndDate]                          DATETIME         NULL,
    [ActualPayoffDate]                       DATETIME         NULL,
    [LastUpdateDate]                         DATETIME         NOT NULL,
    [BackshopCurrentInterestRate]            DECIMAL (28, 15) NULL,
    [ServicerBalance]                        DECIMAL (28, 15) NULL,
    [ServicerInterestRate]                   DECIMAL (28, 15) NULL,
    [ServicerCurrentPaidToDate]              DATETIME         NULL,
    [AllInCouponRate]                        DECIMAL (28, 15) NULL,
    [CumulativePIKFunding]                   DECIMAL (28, 15) NULL,
    [FuturePIKFunding]                       DECIMAL (28, 15) NULL,
    M61Commitment   DECIMAL (28, 15) NULL,
    M61AdjustedCommitment   DECIMAL (28, 15) NULL
    CONSTRAINT [PK_ReconciliationDetailId] PRIMARY KEY CLUSTERED ([ReconciliationDetailId] ASC)
);

