CREATE TABLE [DW].[ServicingTransactionBI] (
    [TransactionDate]               DATE             NULL,
    [CurrentPaymentDate]            DATE             NULL,
    [CurrentInterestPaidToDate]     DATE             NULL,
    [CurrentAllInInterestRate]      DECIMAL (28, 15) NULL,
    [CurrentInterestRateAdjDate]    DATE             NULL,
    [BeginningBalance]              DECIMAL (28, 15) NULL,
    [TotalScheduledP&IDue]          DECIMAL (28, 15) NULL,
    [SchedulePrincipalPaid]         DECIMAL (28, 15) NULL,
    [BegBalLessPRNPayment]          DECIMAL (28, 15) NULL,
    [NoteID]                        NVARCHAR (256)   NULL,
    [ServicerID]                    INT              NULL,
    [EntryNo]                       INT              NULL,
    [TransactionType]               NVARCHAR (256)   NULL,
    [CurrentIndexRate]              DECIMAL (28, 15) NULL,
    [DateDue]                       DATE             NULL,
    [IntRatefromReceivable]         DECIMAL (28, 15) NULL,
    [Principal]                     DECIMAL (28, 15) NULL,
    [InterestPayment]               DECIMAL (28, 15) NULL,
    [LateChargePayment]             DECIMAL (28, 15) NULL,
    [NewIndexRate]                  DECIMAL (28, 15) NULL,
    [NewInterestRate]               DECIMAL (28, 15) NULL,
    [NextPaymentAdjDate]            DATE             NULL,
    [EffectiveDate]                 DATE             NULL,
    [TransactionAmount]             DECIMAL (28, 15) NULL,
    [TaxEscrowAmount]               DECIMAL (28, 15) NULL,
    [InsuranceEscrowAmount]         DECIMAL (28, 15) NULL,
    [ReserveEscrowAmount]           DECIMAL (28, 15) NULL,
    [Suspense]                      DECIMAL (28, 15) NULL,
    [BalanceafterFundingTransacton] DECIMAL (28, 15) NULL,
    [PrincipalWriteOff]             DECIMAL (28, 15) NULL,
    [PaymentStatus]                 NVARCHAR (256)   NULL,
    [ServicingTransactionBI_AutoID] INT              IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_ServicingTransactionBI_AutoID] PRIMARY KEY CLUSTERED ([ServicingTransactionBI_AutoID] ASC)
);



