CREATE TABLE [DW].[TransactionActuals] (
    [TransactionActualsID] INT              IDENTITY (1, 1) NOT NULL,
    [NoteId]               NVARCHAR (256)   NULL,
    [Name]                 NVARCHAR (256)   NULL,
    [DealID]               NVARCHAR (256)   NULL,
    [DealName]             NVARCHAR (256)   NULL,
    [Date]                 DATE             NULL,
    [DueDate]              DATE             NULL,
    [RemitDate]            DATE             NULL,
    [TransactionDate]      DATE             NULL,
    [TransactionType]      NVARCHAR (256)   NULL,
    [CalculatedAmount]     DECIMAL (28, 15) NULL,
    [ServicingAmount]      DECIMAL (28, 15) NULL,
    [OverrideValue]        DECIMAL (28, 15) NULL,
    [CalculateDelta]       DECIMAL (28, 15) NULL,
    [Adjustment]           DECIMAL (28, 15) NULL,
    [M61]                  BIT              NULL,
    [Servicer]             BIT              NULL,
    [Ignore]               BIT              NULL,
    [Exception]            NVARCHAR (256)   NULL,
    [comments]             NVARCHAR (256)   NULL,
    [SourceType]           NVARCHAR (256)   NULL,
    [UsedInCalc]           DECIMAL (28, 15) NULL,
    [ActualDelta]          DECIMAL (28, 15) NULL,
    [ServicerName]         NVARCHAR (256)   NULL,
    [Status]               NVARCHAR (256)   NULL,
    [OverrideReason]       NVARCHAR (256)   NULL,
    [CapitalizedInterest]  DECIMAL (28, 15) NULL,
    [CashInterest]         DECIMAL (28, 15) NULL,
    [BatchLogID]           INT              NULL,
    [FileName]             NVARCHAR (256)   NULL,
    [FinancingSource]      NVARCHAR (256)   NULL,
    [SpreadPercentage]     DECIMAL (28, 15) NULL,
    [OriginalIndex]        DECIMAL (28, 15) NULL,
    [EffectiveRate]        DECIMAL (28, 15) NULL,
    [IndexValue]           DECIMAL (28, 15) NULL,
    [WatchlistStatus]      NVARCHAR (256)   NULL,
    PIKType Nvarchar(256)
    CONSTRAINT [PK_TransactionActualsID] PRIMARY KEY CLUSTERED ([TransactionActualsID] ASC)
);
GO

