CREATE TABLE [DW].[TransactionEntryLiabilityBI](
	[TransactionEntryLiabilityID] [uniqueidentifier] NOT NULL,
	[TransactionEntryLiabilityAutoID] [int] NOT NULL,
	[LiabilityAccountID] [uniqueidentifier] NULL,
	[LiabilityTypeName] [nvarchar](256) NULL,
	[LiabilityNoteAccountID] [uniqueidentifier] NULL,
	[LiabilityNoteID] [nvarchar](256) NULL,
	[Date] [date] NULL,
	[Amount] [decimal](28, 15) NULL,
	[TransactionType] [nvarchar](max) NULL,
	[AnalysisID] [uniqueidentifier] NULL,
	[AnalysisName] [nvarchar](256) NULL,
	[EndingBalance] [decimal](28, 15) NULL,
	[AssetAccountID] [uniqueidentifier] NULL,
	[NoteID] [nvarchar](256) NULL,
	[AssetDate] [date] NULL,
	[AssetAmount] [decimal](28, 15) NULL,
	[AssetTransactionType] [nvarchar](256) NULL,
	[CreatedBy] [nvarchar](256) NULL,
	[CreatedDate] [datetime] NULL,
	[UpdatedBy] [nvarchar](256) NULL,
	[UpdatedDate] [datetime] NULL,
	[ParentAccountId] [uniqueidentifier] NULL,
	[Flag] [nvarchar](256) NULL,
	NoteEndingBalance [decimal](28, 15) NULL,
	NotePIKBalance [decimal](28, 15) NULL
)