CREATE TABLE [DW].[WellsTrialBalanceDataTap] (
	[WellsTrialBalanceDataTapID] INT IDENTITY (1, 1) NOT NULL,
	LOAN_NUMBER	nvarchar(256)	    ,
	INVESTOR_LOANNUMBER	nvarchar(256)	    ,
	BORROWER_NAME	nvarchar(256)	    ,
	PROSUP	nvarchar(256)	    ,
	PROPERTY_NAME	nvarchar(256)	    ,
	NOTE_TYPE	nvarchar(256)	    ,
	ORIGINAL_BALANCE	decimal(28,15)	    ,
	CURRENT_BALANCE	decimal(28,15)	    ,
	FUTURE_FUNDING_BALANCE	decimal(28,15)	    ,
	PROPERTY_TYPE	nvarchar(256)	    ,
	INTEREST_RATE	decimal(28,15)	    ,
	FIRST_PAYMENT_DATE	Date	    ,
	NEXT_PAYMENT_DATE	Date	    ,
	NOTE_DATE	Date	    ,
	MATURITY_DATE	Date	    ,
	GRACE_DAYS	int	    ,
	PAYMENT_TYPE	nvarchar(256)	    ,
	STREET_ADDRESS	nvarchar(256)	    ,
	PROPERTY_CITY	nvarchar(256)	    ,
	PROPERTY_STATE	nvarchar(256)	    ,
	ZIP_CODE	nvarchar(256)	    ,
	INTEREST_ACCRUAL_CODE	nvarchar(256)	    ,
	SUBSERVICER_NAME	nvarchar(256)	    ,
	HOLDE_CODE123	nvarchar(256)	    ,
	LATE_CHARGE_BALANCE	decimal(28,15)	    ,
	SUSPENSE_BAL_AMT	decimal(28,15)	    ,
	TAX_BALANCE	decimal(28,15)	    ,
	INS_BALANCE	decimal(28,15)	    ,
	TAX_CONSTANT	decimal(28,15)	    ,
	INS_CONSTANT	decimal(28,15)	    ,
	PI_CONST	decimal(28,15)	    ,
	PMT_FREQ	int	    ,
	PRINCIPAL_AMOUNT	decimal(28,15)	    ,
	INTEREST_AMOUNT	decimal(28,15)	    ,
	TOTAL_PAYMENT_AMOUNT	decimal(28,15)	    ,
	AMORT_TERM	int	    ,
	ORIGINAL_TERM	int	    ,
	LOCKOUT_MONTHS	int	    ,
	DEFESANCE_MONTHS	int	    ,
	YM_MONTHS	int	    ,
	OPEN_MONTHS	int	    ,
	ARA_DATE	Date	    ,
	LOCKBOX	int	    ,
	LETTER_OF_CREDIT_AMOUNT	decimal(28,15)	    ,
	SUB_FEE	decimal(28,15)	    ,
	ASSUMABLE	nvarchar(256)	    ,
	ASSUMPTION_FEE	decimal(28,15)	    ,
	ASSUMPTION_WAVIER_DESC	nvarchar(256)	    ,
	CROSS_COLLATERAL_FLAG	nvarchar(256)	    ,
	LOAN_ORIGINATOR	nvarchar(256)	    ,
	GROUND_LEASE	nvarchar(256)	    ,
	IN_AUTODRAFT	nvarchar(256)	    ,
	Reserve_Name	nvarchar(256)	    ,
	RESERVE_CONSTANT	nvarchar(256)	    ,
	RESERVE_BALANCE	decimal(28,15)	    ,
	OTHER_DESCRIPTION	nvarchar(256)	       
    CONSTRAINT [PK_WellsTrialBalanceDataTapID] PRIMARY KEY CLUSTERED ([WellsTrialBalanceDataTapID] ASC)
);



