# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
   exclude:
     - master
   include:
      - Integration
  paths:
    include:
      -  CRES.DBScript/*

pool:
  vmImage: 'windows-2019'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: VSBuild@1
            displayName: 'Build Integration Database'
            inputs:
              configuration: release
              solution: 'CRES.DBScript/CRES.DBScript.sqlproj'
 
          - task: CopyFiles@2
            displayName: Copy DACPAC
            inputs:
              contents: '**/bin/Release/*.dacpac'
              targetFolder: '$(Build.ArtifactStagingDirectory)'
              flattenFolders: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
 


  - stage: CopyandRestoreDB
    jobs:
      - deployment: DeployDatabaseInt
        displayName: Create new DB from Prod to Int
        environment: Int_Recon
        strategy:
         runOnce:
           deploy:
             steps: 
                - task: SqlAzureDacpacDeployment@1
                  displayName: 'Deploy Azure SQL Database'
                  inputs:
                    azureSubscription: 'iTechsol(021c83fc-1e2a-4da6-92dd-8e1d74c0e1cb)'
                    serverName: 'b0xesubcki1.database.windows.net'
                    databaseName: 'CRES4_QA_TEST1'
                    sqlUsername: 'CREAdmin'
                    sqlPassword: '@ah/g&6`+KwLExfs'
                    dacpacFile: '$(Pipeline.Workspace)/**/*.dacpac'
                    additionalArguments: '/p:BlockOnPossibleDataLoss=$(BlockDataLoss) /p:DropObjectsNotInSource=false /p:ExcludeObjectTypes=Users;DatabaseRoles;RoleMembership;Logins;ExternalDataSources;ExternalTables;DatabaseScopedCredentials;Permissions;Rules;ExternalFileFormats;ExtendedProperties'

                    