CREATE TABLE [IO].[IN_AcctNote] (
    [ControlId]              NVARCHAR (10)    NOT NULL,
    [NoteId]                 INT              NULL,
    [NoteName]               NVARCHAR (MAX)   NULL,
    [FundingDate]            DATE             NULL,
    [TotalCommitment]        DECIMAL (28, 12) NULL,
    [FirstPIPaymentDate]     DATE             NULL,
    [StatedMaturityDate]     DATE             NULL,
    [OrigLoanAmount]         DECIMAL (28, 12) NULL,
    [OriginationFee]         DECIMAL (28, 12) NULL,
    [LiborFloor]             DECIMAL (28, 12) NULL,
    [OriginationFeePct]      DECIMAL (28, 12) NULL,
    [InterestSpread]         DECIMAL (28, 12) NULL,
    [AmortIOPeriod]          INT              NULL,
    [AmortizationTerm]       INT              NULL,
    [PaymentFreqCd_F]        INT              NULL,
    [PaymentFreqDesc]        NVARCHAR (MAX)   NULL,
    [IntCalcMethodDesc]      NVARCHAR (MAX)   NULL,
    [AccrualRate]            DECIMAL (28, 12) NULL,
    [DeterminationMethodDay] INT              NULL,
    [DeterminationDate]      INT              NULL,
    [RoundingType]           NVARCHAR (MAX)   NULL,
    [RoundingDenominator]    INT              NULL,
    [ShardName]              NVARCHAR (MAX)   NULL,
    [lienposition]           NVARCHAR (MAX)   NULL,
    [priority]               INT              NULL
);

