CREATE TABLE [IO].[IN_UnderwritingProperty] (
    [CREDealID]            NVARCHAR (256)   NULL,
    [PropertyName]         NVARCHAR (256)   NULL,
    [CompanyName]          NVARCHAR (256)   NULL,
    [FirstName]            NVARCHAR (256)   NULL,
    [LastName]             NVARCHAR (256)   NULL,
    [Relationship]         NVARCHAR (256)   NULL,
    [VendorLoanNumber]     NVARCHAR (256)   NULL,
    [ProjectName]          NVARCHAR (256)   NULL,
    [HOUSESTREET1]         NVARCHAR (256)   NULL,
    [VILLAGE]              NVARCHAR (256)   NULL,
    [ZIPCODE]              NVARCHAR (256)   NULL,
    [OwnerOccupied]        NVARCHAR (20)    NULL,
    [PROPDESCCODE]         NVARCHAR (256)   NULL,
    [SALESPRICE]           INT              NULL,
    [ConstructionDate]     DATETIME         NULL,
    [NumberofStories]      DECIMAL (28, 15) NULL,
    [MeasuredIn]           NVARCHAR (20)    NULL,
    [TotalSquareFeet]      DECIMAL (28, 15) NULL,
    [TotalRentableSqFt]    DECIMAL (28, 15) NULL,
    [TotalNumberofUnits]   DECIMAL (28, 15) NULL,
    [OverallCondition]     NVARCHAR (20)    NULL,
    [RenovationDate]       DATETIME         NULL,
    [NextInspectionDate]   DATE             NULL,
    [GroundLease]          NVARCHAR (256)   NULL,
    [NumberOfTenants]      INT              NULL,
    [VacancyFactor]        DECIMAL (28, 15) NULL,
    [Allocation]           DECIMAL (28, 15) NULL,
    [LIENPosition]         INT              NULL,
    [CMSAProperyType]      NVARCHAR (256)   NULL,
    [PState]               NVARCHAR (256)   NULL,
    [country]              NVARCHAR (256)   NULL,
    [DealAllocationAmtPCT] FLOAT (53)       NULL,
    [dealid]               UNIQUEIDENTIFIER NULL,
    [PropertyTypeID]       INT              NULL,
    [PropertyRollUpSW]     BIT              NULL, 
    [PropertyTypeMajorCd_F] NVARCHAR(50) NULL,
    City NVARCHAR(256) NULL,
    [Address] NVARCHAR(256) NULL,
    BSPropertyID int null,
    IN_UnderwritingProperty_AutoID int IDENTITY(1,1)
);


go
ALTER TABLE [IO].[IN_UnderwritingProperty]
ADD CONSTRAINT PK_IN_UnderwritingProperty_IN_UnderwritingPropertyID PRIMARY KEY (IN_UnderwritingProperty_AutoID);