CREATE TABLE [IO].[IN_UnderwritingNote] (
    [IN_UnderwritingNoteID]                   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [IN_UnderwritingAccountID]                UNIQUEIDENTIFIER NOT NULL,
    [IN_UnderwritingDealID]                   UNIQUEIDENTIFIER NOT NULL,
    [ClientNoteID]                            NVARCHAR (256)   NULL,
    [ClientDealID]                            NVARCHAR (256)   NULL,
    [ClosingDate]                             DATE             NULL,
    [FirstPaymentDate]                        DATE             NULL,
    [SelectedMaturityDate]                    DATE             NULL,
    [InitialFundingAmount]                    DECIMAL (28, 15) NULL,
    [OriginationFee]                          DECIMAL (28, 15) NULL,
    [OriginationFeePct]                       FLOAT (53)       NULL,
    [IOTerm]                                  INT              NULL,
    [AmortTerm]                               INT              NULL,
    [DeterminationDateLeadDays]               INT              NULL,
    [DeterminationDateReferenceDayoftheMonth] INT              NULL,
    [RoundingMethod]                          INT              NULL,
    [IndexRoundingRule]                       INT              NULL,
    [StatusID]                                INT              NULL,
    [CreatedBy]                               NVARCHAR (256)   NULL,
    [CreatedDate]                             DATETIME         NULL,
    [UpdatedBy]                               NVARCHAR (256)   NULL,
    [UpdatedDate]                             DATETIME         NULL,
    [ExpectedMaturityDate]                    DATE             NULL,
    [ExtendedMaturityScenario1]               DATE             NULL,
    [ExtendedMaturityScenario2]               DATE             NULL,
    [ExtendedMaturityScenario3]               DATE             NULL,
    [TotalCommitment]                         DECIMAL (28, 15) NULL,
    [lienposition]                            INT              NULL,
    [priority]                                INT              NULL,
    CONSTRAINT [PK_IN_UnderwritingNoteID] PRIMARY KEY CLUSTERED ([IN_UnderwritingNoteID] ASC),
    CONSTRAINT [FK_IN_UnderwritingNote_IN_UnderwritingAccountID] FOREIGN KEY ([IN_UnderwritingAccountID]) REFERENCES [IO].[IN_UnderwritingAccount] ([IN_UnderwritingAccountID]),
    CONSTRAINT [FK_IN_UnderwritingNote_IN_UnderwritingDealID] FOREIGN KEY ([IN_UnderwritingDealID]) REFERENCES [IO].[IN_UnderwritingDeal] ([IN_UnderwritingDealID])
);

