CREATE TABLE [IO].[L_Berkadia] (
    [LandingID]                   UNIQUEIDENTIFIER CONSTRAINT [DF__L_Berkadi__Landi__60DD3190] DEFAULT (newid()) NOT NULL,
    [FileBatchlogid]              INT              NULL,
    [OwnerParticipant]            NVARCHAR (256)   NULL,
    [Participant]                 NVARCHAR (256)   NULL,
    [RemitDate]                   DATETIME         NULL,
    [LoanNo]                      NVARCHAR (256)   NULL,
    [NoteID]                      NVARCHAR (256)   NULL,
    [DealName]                    NVARCHAR (256)   NULL,
    [DueDate]                     DATETIME         NULL,
    [DatePaid]                    DATETIME         NULL,
    [TranDate]                    DATETIME         NULL,
    [BegBalance]                  DECIMAL (28, 15) NULL,
    [InterestRate]                DECIMAL (28, 15) NULL,
    [Spread]                      DECIMAL (28, 15) NULL,
    [LIBORIndex]                  DECIMAL (28, 15) NULL,
    [RoundedLIBOR]                NVARCHAR (512)   NULL,
    [ServiceFeeRate]              DECIMAL (28, 15) NULL,
    [InvestorNetYield]            DECIMAL (28, 15) NULL,
    [PLDue]                       DECIMAL (28, 15) NULL,
    [EscrowOther]                 DECIMAL (28, 15) NULL,
    [CashInterest]                DECIMAL (28, 15) NULL,
    [CapitalizedInterest]         DECIMAL (28, 15) NULL,
    [ServicingFeeCredit]          DECIMAL (28, 15) NULL,
    [ExitFee]                     DECIMAL (28, 15) NULL,
    [ExtensionFee]                DECIMAL (28, 15) NULL,
    [PrepaymentYMFeesMaintenance] DECIMAL (28, 15) NULL,
    [UnusedFee]                   DECIMAL (28, 15) NULL,
    [ServiceFee]                  DECIMAL (28, 15) NULL,
    [OtherFees]                   DECIMAL (28, 15) NULL,
    [NetInterest]                 DECIMAL (28, 15) NULL,
    [PrincipalAdj]                DECIMAL (28, 15) NULL,
    [LateCharge]                  DECIMAL (28, 15) NULL,
    [TotalRemit]                  DECIMAL (28, 15) NULL,
    [Receivable]                  DECIMAL (28, 15) NULL,
    [EndingBalance]               DECIMAL (28, 15) NULL,
    [TransactionDescription]      NVARCHAR (256)   NULL,
    [Exception]                   NVARCHAR (256)   NULL,
    [AddlInt]                     DECIMAL (28, 15) NULL,
    [ExceptionFee]                NVARCHAR (256)   NULL
);

