CREATE TABLE [IO].[L_DailyExtract] (
    [LandingID]            UNIQUEIDENTIFIER CONSTRAINT [DF__L_DailyEx__Landi__6991A7CB] DEFAULT (newid()) NOT NULL,
    [InvestorNo]           NVARCHAR (256)   NULL,
    [GROUPNUMBER]          NVARCHAR (256)   NULL,
    [LoanNo]               NVARCHAR (256)   NULL,
    [NoteID]               NVARCHAR (256)   NULL,
    [BorrowerName]         NVARCHAR (256)   NULL,
    [DueDate]              DATETIME         NULL,
    [NextPmtDue]           DATETIME         NULL,
    [BegBalance]           DECIMAL (28, 15) NULL,
    [PIDue]                DECIMAL (28, 15) NULL,
    [Principal]            DECIMAL (28, 15) NULL,
    [Interest]             DECIMAL (28, 15) NULL,
    [InterestRate]         DECIMAL (28, 15) NULL,
    [ServiceFeeRate]       DECIMAL (28, 15) NULL,
    [NetYield]             DECIMAL (28, 15) NULL,
    [ServiceFee]           DECIMAL (28, 15) NULL,
    [NetInterest]          DECIMAL (28, 15) NULL,
    [ExitExtensionFees]    DECIMAL (28, 15) NULL,
    [PrepaymentYMFees]     DECIMAL (28, 15) NULL,
    [OtherFees]            DECIMAL (28, 15) NULL,
    [AddlPrincipal]        DECIMAL (28, 15) NULL,
    [FeePayback]           DECIMAL (28, 15) NULL,
    [AddlInt]              DECIMAL (28, 15) NULL,
    [FloatIntCR]           DECIMAL (28, 15) NULL,
    [TotalRemit]           DECIMAL (28, 15) NULL,
    [PrincipalAdjNonCash]  DECIMAL (28, 15) NULL,
    [EndingBalance]        DECIMAL (28, 15) NULL,
    [TranDate]             DATETIME         NULL,
    [AccrualDays]          INT              NULL,
    [IntRateType]          NVARCHAR (256)   NULL,
    [NOTEDATE]             DATETIME         NULL,
    [MaturityDate]         DATETIME         NULL,
    [Comments]             NVARCHAR (256)   NULL,
    [DIALBeginningBalance] DECIMAL (28, 15) NULL,
    [CurrentDIAL]          DECIMAL (28, 15) NULL,
    [EndingDIALBalance]    DECIMAL (28, 15) NULL,
    [LIBORIndex]           DECIMAL (28, 15) NULL,
    [RoundedLIBOR]         DECIMAL (28, 15) NULL,
    [PropertyName]         NVARCHAR (512)   NULL,
    [Spread]               DECIMAL (28, 15) NULL,
    [RemitDate]            DATETIME         NULL,
    DailyExtract_AutoID int IDENTITY(1,1)
);


go
ALTER TABLE [IO].[L_DailyExtract]
ADD CONSTRAINT PK_L_DailyExtract_DailyExtract_AutoID PRIMARY KEY (DailyExtract_AutoID);