CREATE TABLE [VAL].[SECMastHolding] (    

	SECMastHoldingID    INT    IDENTITY (1, 1) NOT NULL,	
	MarkedDateMasterID int,

	--InvestorID	int	 ,
	--ManagerName	nvarchar(256)	 ,
	--MortgageType	nvarchar(256)	 ,
	--AsofDate	Date	 ,
	Ticker	nvarchar(256)	 ,
	LoanID	nvarchar(256)	 ,
	--ClientID	nvarchar(256)	 ,
	Description	nvarchar(256)	 ,
	--Currency	nvarchar(256)	 ,
	--LoanType	nvarchar(256)	 ,
	--LoanPurpose	nvarchar(256)	 ,
	FinancingSource	nvarchar(256)	 ,
	--Borrower	nvarchar(256)	 ,
	--Sponsor	nvarchar(256)	 ,
	--Guaranteed	nvarchar(256)	 ,
	--FundID	nvarchar(256)	 ,
	NoteName	nvarchar(256)	 ,
	--LienPosition	nvarchar(256)	 ,
	Priority	int	 ,
	--SeniorDebt	int	 ,
	OriginationDate	Date	 ,
	--AccruedStartDate	Date	 ,
	--FirstCouponDate	Date	 ,
	--MaturityDate	Date	 ,
	--FixedorFloating	nvarchar(256)	 ,
	--AmortizationType	nvarchar(256)	 ,
	--Interestonlyperiod	int	 ,
	--ModandRefiDate	Date	 ,
	--LoanTerm	int	 ,
	FullyExtendedMaturityDate	Date	 ,
	--FullyExtendedTerm_mos	int	 ,
	--CurrentCouponEffectiveDate	Date	 ,
	--LastPaymentDate	Date	 ,
	--NextResetDate	Date	 ,
	--DaysPastDue	int	 ,
	--PaymentFrequency	nvarchar(256)	 ,
	--DayCount	nvarchar(256)	 ,
	PaymentDay	int	 ,
	--IndexName	nvarchar(256)	 ,
	--IndexRate_Rounded	decimal(28,15)	 ,
	--Spread	decimal(28,15)	 ,
	InterestRate	decimal(28,15)	 ,
	InitialFunding	decimal(28,15)	 ,
	OriginalAmountofLoan	decimal(28,15)	 ,
	AdjustedCommitment	decimal(28,15)	 ,
	AmountofLoanOutstanding	decimal(28,15)	 ,
	--ValueofLandandBuildings	decimal(28,15)	 ,
	--Servicer	nvarchar(256)	 ,
	--PropertyType	nvarchar(256)	 ,
	--NumberofProperties	int	 ,
	--CrossCollateralization	nvarchar(256)	 ,
	--CrossCollateralizationIdentifier	nvarchar(256)	 ,
	--City	nvarchar(256)	 ,
	--State	nvarchar(256)	 ,
	--PostalCode	nvarchar(256)	 ,
	--Region	nvarchar(256)	 ,
	--MSA	nvarchar(256)	 ,
	--NonConstruction_HardCostUses	decimal(28,15)	 ,
	--TotalCapStack_includesequity	decimal(28,15)	 ,
	--NonConstruction	decimal(28,15)	 ,
	--Construction	nvarchar(256)	 ,
	--LastAppraisalDate	Date	 ,
	--LastAppraisalSource	nvarchar(256)	 ,
	--AsIsValue	decimal(28,15)	 ,
	--InitialLTV	decimal(28,15)	 ,
	--AsStabilizedValue	decimal(28,15)	 ,
	--StabilizedLTV	decimal(28,15)	 ,
	--AsIsCashFlow	decimal(28,15)	 ,
	--AsStabCashFlow	decimal(28,15)	 ,
	--AsIsDSCR	decimal(28,15)	 ,
	--AsStabDSCR	decimal(28,15)	 ,
	--InitialDebtYield	decimal(28,15)	 ,
	--StabilizedDebtYield	decimal(28,15)	 ,
	--PayRate	decimal(28,15)	 ,
	--MortgageLoanTrancheType	nvarchar(256)	 ,
	IndexFloor	decimal(28,15)	 ,
	--RSLIC	decimal(28,15)	 ,
	--SNCC	decimal(28,15)	 ,
	--PIIC	decimal(28,15)	 ,
	--TMR	decimal(28,15)	 ,
	--HCC	decimal(28,15)	 ,
	--USSIC	decimal(28,15)	 ,
	--TMDDL	decimal(28,15)	 ,
	--HAIH	decimal(28,15)	 ,
	--TotalParticipationPer	decimal(28,15)	 ,
	--AccruedPIKBalanceAmount	decimal(28,15)	 ,
	--RSLICValLBPct	decimal(28,15)	 ,
	--SNCCValLBPct	decimal(28,15)	 ,
	--PIICValLBPct	decimal(28,15)	 ,
	--TMRValLBPct	decimal(28,15)	 ,
	--HCCValLBPct	decimal(28,15)	 ,
	--USSICValLBPct	decimal(28,15)	 ,
	--TMNFValLBPct	decimal(28,15)	 ,
	--HAIHValLBPct	decimal(28,15)	 ,
	--TotalParticipationMod2	decimal(28,15)	 ,
	--FHLBPledged	decimal(28,15)	 ,
	--NOISecondPriorYear	decimal(28,15)	 ,
	--NOIPriorYear	decimal(28,15)	 ,
	--NOI	decimal(28,15)	 ,
	--TTM	decimal(28,15)	 ,
	--RollingAverageNOI	decimal(28,15)	 ,
	--RollingAverageNOIGrid	decimal(28,15)	 ,
	--LTV	decimal(28,15)	 ,
	--RBCDSR	decimal(28,15)	 ,
	--CMRATING	nvarchar(256)	 ,
	--NOTCHED	nvarchar(256)	 ,
	--RBCCharge	decimal(28,15)	 ,
	--StabLTVNumerator	decimal(28,15)	 ,
	--ASISLTVDENOMINATOR	decimal(28,15)	 ,
	--UsingRollup	decimal(28,15)	 ,
	--AsIsLTVNumerator	decimal(28,15)	 ,
	--ASSTABLTVDENOMINATOR	decimal(28,15)	 ,
	--asisdebtservice	decimal(28,15)	 ,
	--asstabdebtservice	decimal(28,15)	 ,

	CreatedBy	nvarchar(256),
	CreatedDate	Datetime,
	UpdateBy	nvarchar(256),
	UpdatedDate	Datetime

    CONSTRAINT [PK_SECMastHolding_SECMastHoldingID] PRIMARY KEY CLUSTERED ([SECMastHoldingID] ASC)
);





