
CREATE TYPE [dbo].[tbltype_CalcV1DataFrame_V1] AS TABLE (
Date	Date	null,
Note	nvarchar(256)	null,
initbal	decimal(28,15)	null,
funding_fundpydn	decimal(28,15)	null,
schprin	decimal(28,15)	null,
balloon	decimal(28,15)	null,
endbal	decimal(28,15)	null,
fee_amount	decimal(28,15)	null,
fee_stripped	decimal(28,15)	null,
fee_strip_received	decimal(28,15)	null,
fee_incl_lv_yield	decimal(28,15)	null,
fee_excl_lv_yield	decimal(28,15)	null,
dailyint	decimal(28,15)	null,
stubint	decimal(28,15)	null,
periodint	decimal(28,15)	null,
clsdt	Date	null,
totalcmt	decimal(28,15)	null,
initmatdt	Date	null,
initaccenddt	Date	null,
initpmtdt	Date	null,
ioterm	int	null,
amterm	int	null,
rate_valtype	int	null,
rate_val	decimal(28,15)	null,
rate_intcalcdays	int	null,
rate_adj_factor	decimal(28,15)	null,
amort_rate_val	decimal(28,15)	null,
amort_rate_intcalcdays	int	null,
amort_rate_adj_factor	decimal(28,15)	null,
periodstart	Date	null,
periodend	Date	null,
term	int	null,
io_term_end_date	Date	null,
rem_term	int	null,
prev_endbal	decimal(28,15)	null,
float_dailyint	decimal(28,15)	null,
cum_dailyint	decimal(28,15)	null,
levyld	decimal(28,15)	null,
gaapbasis	decimal(28,15)	null,
feeamort	decimal(28,15)	null
  
);
