CREATE TYPE [dbo].[tempNotePeriodicCalcVSTO] AS TABLE (
    [BatchDetailAsyncCalcVSTOId]                   INT              NULL,
    [CRENoteID]                                    NVARCHAR (256)   NULL,
    [PeriodEndDate]                                DATE             NULL,
    [Month]                                        INT              NULL,
    [ActualCashFlows]                              DECIMAL (28, 15) NULL,
    [GAAPCashFlows]                                DECIMAL (28, 15) NULL,
    [EndingGAAPBookValue]                          DECIMAL (28, 15) NULL,
    [PIKInterestAccrualforthePeriod]               DECIMAL (28, 15) NULL,
    [TotalAmortAccrualForPeriod]                   DECIMAL (28, 15) NULL,
    [AccumulatedAmort]                             DECIMAL (28, 15) NULL,
    [BeginningBalance]                             DECIMAL (28, 15) NULL,
    [TotalFutureAdvancesForThePeriod]              DECIMAL (28, 15) NULL,
    [TotalDiscretionaryCurtailmentsforthePeriod]   DECIMAL (28, 15) NULL,
    [TotalCouponStrippedforthePeriod]              DECIMAL (28, 15) NULL,
    [CouponStrippedonPaymentDate]                  DECIMAL (28, 15) NULL,
    [ScheduledPrincipal]                           DECIMAL (28, 15) NULL,
    [PrincipalPaid]                                DECIMAL (28, 15) NULL,
    [BalloonPayment]                               DECIMAL (28, 15) NULL,
    [EndingBalance]                                DECIMAL (28, 15) NULL,
    [EndOfPeriodWAL]                               DECIMAL (28, 15) NULL,
    [PIKInterestFromPIKSourceNote]                 DECIMAL (28, 15) NULL,
    [PIKInterestTransferredToRelatedNote]          DECIMAL (28, 15) NULL,
    [PIKInterestForThePeriod]                      DECIMAL (28, 15) NULL,
    [BeginningPIKBalanceNotInsideLoanBalance]      DECIMAL (28, 15) NULL,
    [PIKInterestForPeriodNotInsideLoanBalance]     DECIMAL (28, 15) NULL,
    [PIKBalanceBalloonPayment]                     DECIMAL (28, 15) NULL,
    [EndingPIKBalanceNotInsideLoanBalance]         DECIMAL (28, 15) NULL,
    [AmortAccrualLevelYield]                       DECIMAL (28, 15) NULL,
    [ScheduledPrincipalShortfall]                  DECIMAL (28, 15) NULL,
    [PrincipalShortfall]                           DECIMAL (28, 15) NULL,
    [PrincipalLoss]                                DECIMAL (28, 15) NULL,
    [InterestForPeriodShortfall]                   DECIMAL (28, 15) NULL,
    [InterestPaidOnPMTDateShortfall]               DECIMAL (28, 15) NULL,
    [CumulativeInterestPaidOnPMTDateShortfall]     DECIMAL (28, 15) NULL,
    [InterestShortfallLoss]                        DECIMAL (28, 15) NULL,
    [InterestShortfallRecovery]                    DECIMAL (28, 15) NULL,
    [BeginningFinancingBalance]                    DECIMAL (28, 15) NULL,
    [TotalFinancingDrawsCurtailmentsForPeriod]     DECIMAL (28, 15) NULL,
    [FinancingBalloon]                             DECIMAL (28, 15) NULL,
    [EndingFinancingBalance]                       DECIMAL (28, 15) NULL,
    [FinancingInterestPaid]                        DECIMAL (28, 15) NULL,
    [FinancingFeesPaid]                            DECIMAL (28, 15) NULL,
    [PeriodLeveredYield]                           DECIMAL (28, 15) NULL,
    [OrigFeeAccrual]                               DECIMAL (28, 15) NULL,
    [DiscountPremiumAccrual]                       DECIMAL (28, 15) NULL,
    [ExitFeeAccrual]                               DECIMAL (28, 15) NULL,
    [AllInCouponRate]                              DECIMAL (28, 15) NULL,
    [CreatedBy]                                    NVARCHAR (256)   NULL,
    [CreatedDate]                                  DATETIME         NULL,
    [UpdatedBy]                                    NVARCHAR (256)   NULL,
    [UpdatedDate]                                  DATETIME         NULL,
    [CleanCost]                                    DECIMAL (28, 15) NULL,
    [GrossDeferredFees]                            DECIMAL (28, 15) NULL,
    [DeferredFeesReceivable]                       DECIMAL (28, 15) NULL,
    [CleanCostPrice]                               DECIMAL (28, 15) NULL,
    [AmortizedCostPrice]                           DECIMAL (28, 15) NULL,
    [AdditionalFeeAccrual]                         DECIMAL (28, 15) NULL,
    [CapitalizedCostAccrual]                       DECIMAL (28, 15) NULL,
    [ReversalofPriorInterestAccrual]               DECIMAL (28, 15) NULL,
    [InterestReceivedinCurrentPeriod]              DECIMAL (28, 15) NULL,
    [CurrentPeriodInterestAccrual]                 DECIMAL (28, 15) NULL,
    [TotalGAAPInterestFortheCurrentPeriod]         DECIMAL (28, 15) NULL,
    [InvestmentBasis]                              DECIMAL (28, 15) NULL,
    [CurrentPeriodInterestAccrualPeriodEnddate]    DECIMAL (28, 15) NULL,
    [LIBORPercentage]                              DECIMAL (28, 15) NULL,
    [SpreadPercentage]                             DECIMAL (28, 15) NULL,
    [AnalysisID]                                   UNIQUEIDENTIFIER NULL,
    [FeeStrippedforthePeriod]                      DECIMAL (28, 15) NULL,
    [PIKInterestPercentage]                        DECIMAL (28, 15) NULL,
    [AmortizedCost]                                DECIMAL (28, 15) NULL,
    [InterestSuspenseAccountActivityforthePeriod]  DECIMAL (28, 15) NULL,
    [InterestSuspenseAccountBalance]               DECIMAL (28, 15) NULL,
    [AllInBasisValuation]                          DECIMAL (28, 15) NULL,
    [AllInPIKRate]                                 DECIMAL (28, 15) NULL,
    [CurrentPeriodPIKInterestAccrualPeriodEnddate] DECIMAL (28, 15) NULL,
    [PIKInterestPaidForThePeriod]                  DECIMAL (28, 15) NULL,
    [PIKInterestAppliedForThePeriod]               DECIMAL (28, 15) NULL,
	SizerScenario                                  nvarchar(256) null
		);

