CREATE TYPE [dbo].[TableTypeNoteEditPIKSchedule] AS TABLE (
    [ScheduleID]           UNIQUEIDENTIFIER,
    [AccountID]            UNIQUEIDENTIFIER,
	[EffectiveDate]        DATE            ,
    [SourceAccountID]      UNIQUEIDENTIFIER NULL,
    [TargetAccountID]      UNIQUEIDENTIFIER NULL,
    [AdditionalIntRate]    DECIMAL (28, 15) NULL,
    [AdditionalSpread]     DECIMAL (28, 15) NULL,
    [IndexFloor]           DECIMAL (28, 15) NULL,
    [IntCompoundingRate]   DECIMAL (28, 15) NULL,
    [IntCompoundingSpread] DECIMAL (28, 15) NULL,
    [StartDate]            DATE             NULL,
    [EndDate]              DATE             NULL,
    [IntCapAmt]            DECIMAL (28, 15) NULL,
    [PurBal]               DECIMAL (28, 15) NULL,
    [AccCapBal]            DECIMAL (28, 15) NULL,
    [PIKReasonCodeID]      INT              NULL,
    [PIKComments]          NVARCHAR (MAX)   NULL,
    [PIKIntCalcMethodID]   INT              NULL,
    PeriodicRateCapAmount  decimal(28,15),
    PeriodicRateCapPercent decimal(28,15),
	[PIKPercentage]        DECIMAL (28, 15) NULL,
	[PIKSetUp]             INT              NULL,
	[IsDeleted]            BIT,
	[PIKCurrentPayRate]    DECIMAL (28, 15) NULL,
	[PIKSeparateCompounding]   INT          NULL
	);