CREATE TABLE [Core].[tblNoteAdditionalListForCalculator] (
    [NoteId]               UNIQUEIDENTIFIER NULL,
    [EffectiveDate]        DATETIME         NULL,
    [Date]                 DATE             NULL,
    [SelectedMaturityDate] DATE             NULL,
    [EndDate]              DATE             NULL,
    [ValueTypeID]          INT              NULL,
    [Value]                DECIMAL (28, 12) NULL,
    [IntCalcMethodID]      INT              NULL,
    [IncludedLevelYield]   DECIMAL (28, 12) NULL,
    [IncludedBasis]        DECIMAL (28, 12) NULL,
    [MaxFeeAmt]            DECIMAL (28, 12) NULL,
    [IndexTypeID]          INT              NULL,
    [CurrencyCode]         INT              NULL,
    [IsCapitalized]        INT              NULL,
    [SourceAccountID]      NVARCHAR (256)   NULL,
    [SourceAccountText]    NVARCHAR (256)   NULL,
    [TargetAccountID]      NVARCHAR (256)   NULL,
    [TargetAccountText]    NVARCHAR (256)   NULL,
    [AdditionalIntRate]    DECIMAL (28, 12) NULL,
    [AdditionalSpread]     DECIMAL (28, 12) NULL,
    [IndexFloor]           DECIMAL (28, 12) NULL,
    [IntCompoundingRate]   DECIMAL (28, 12) NULL,
    [IntCompoundingSpread] DECIMAL (28, 12) NULL,
    [StartDate]            DATE             NULL,
    [ScheduleStartDate]    DATE             NULL,
    [IntCapAmt]            DECIMAL (28, 12) NULL,
    [PurBal]               DECIMAL (28, 12) NULL,
    [AccCapBal]            DECIMAL (28, 12) NULL,
    [ValueTypeText]        NVARCHAR (256)   NULL,
    [IntCalcMethodText]    NVARCHAR (256)   NULL,
    [CurrencyCodeText]     NVARCHAR (256)   NULL,
    [IndexTypeText]        NVARCHAR (256)   NULL,
    [IsCapitalizedText]    NVARCHAR (256)   NULL,
    [ModuleId]             INT              NULL,
    [CreatedBy]            NVARCHAR (256)   NULL,
    [CreatedDate]          DATETIME         NULL,
    [UpdatedBy]            NVARCHAR (256)   NULL,
    [UpdatedDate]          DATETIME         NULL
);

