
CREATE PROCEDURE [DW].[usp_ImportUwDeal]
	@BatchLogId int,@LastBatchStart datetime, @CurrentBatchStart datetime
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO [DW].BatchDetail (BatchLogId,LandingTableName,LandingStartTime)
	VALUES (@BatchLogId,'L_UwDealBI',GETDATE())

	DECLARE @id int,@RowCount int
	SET @id = (SELECT @@IDENTITY)


IF(@LastBatchStart is null)
BEGIN

	Declare @minUpdatedDatesrcTable as table
	(
		[MinUpdatedDate] datetime null,
		ShardName nvarchar(max)  NULL
	)
	insert into @minUpdatedDatesrcTable([MinUpdatedDate],ShardName)
	EXEC sp_execute_remote @data_source_name  = N'RemoteReferenceData', @stmt = N'Select MIN(AuditaddDate) as AuditaddDate from tblCOntrolMaster '


	SET @LastBatchStart = (Select [MinUpdatedDate] from @minUpdatedDatesrcTable)
END


DECLARE @query nvarchar(MAX) = N'
Select 
cm.ControlId,
cm.LoanNumber,
Lstatus.LoanStatusDesc as LoanStatusCd_F,
orgBrk.OrganizationName as BrokerName_OrgId_F,
orgLendorName.OrganizationName as LendorName_OrgId_F,
orgLawFirm.OrganizationName as LawFirm_OrgId_F,
orgOffice.OrganizationName as Office_OrgId_F,
dealRela.RollupName as DealRelatedId_F,
orgCompetition.OrganizationName as Competition_Org_Id_F,
orgDueDiligenceProvider.OrganizationName as DueDiligenceProvider_OrgId_F,
OriDS.OriginalDataSourceDesc as OriginalDataSource_F,
cm.MinimumDSCR,
cm.MinimumDSCRatConstant,
cm.MaximumLTV,
cm.MinimumConstantDeal,
cm.PrimaryBanker_UserId_F,
cm.SecondaryBanker_UserId_F,
cm.Underwriter_UserID_F,
cm.ServicersLoanNumber,
cm.DealName,
cm.CreditApprovedBy,
Cast(cm.CreditApprovedComment as nvarchar(max)) as CreditApprovedComment,
cm.SpreadApprovedBy,
Cast(cm.SpreadApprovedComment  as nvarchar(max)) as SpreadApprovedComment,
cm.Correspondent,
cm.CorrUW,
cm.CollateralType,
cm.DebtServiceAllocated,
cm.LoanPurpose,
cm.LoanProbability,
cm.ApplicationReceiveDate,
cm.ApplicationDate,
cm.LenderRightToMatch,
cm.ApplicationDeposit,
cm.LockBox,
Cast(cm.LockBoxComment as nvarchar(max)) as LockBoxComment,
cm.HardCashManagement,
cm.Recourse,
Cast(cm.ClosingConditions as nvarchar(max)) as ClosingConditions,
cm.EstClosingCosts,
cm.EarnOut,
cm.IndDirectorReqSw,
cm.NonConsolOpinionReqSw,
Cast(cm.OwnershipComments as nvarchar(max)) as OwnershipComments,
cm.BrokerFees,
cm.Cashout,
cm.PreliminarySponsor,
Cast(cm.OngoingDSCRTest as nvarchar(max)) as OngoingDSCRTest,
Cast(cm.SpecialPricingNotes as nvarchar(max)) as SpecialPricingNotes,
Cast(cm.HardEquityComment as nvarchar(max)) as HardEquityComment,
cm.MatrixSpreadAtClose,
Cast(cm.MatrixSpreadAtCloseComments as nvarchar(max)) as MatrixSpreadAtCloseComments,
cm.CommitmentExpDate,
Cast(cm.Comments as nvarchar(max)) as Comments,
cm.TICSw,
cm.MpIsLoanAssumable,
Cast(cm.MpIsLoanAssumableDesc as nvarchar(max)) as MpIsLoanAssumableDesc,
cm.MpEquityParticipation,
Cast(cm.MpEquityParticipationDesc as nvarchar(max)) as MpEquityParticipationDesc,
cm.MpAllowFutAdvances,
Cast(cm.MpAllowFutAdvancesDesc as nvarchar(max)) as MpAllowFutAdvancesDesc,
cm.MpMaxFutureAdvances,
cm.MpFutAdvancesToDate,
cm.MpAssumptionFeePct,
cm.MpAssumptionFeeAmt,
cm.MpAssumptionFee,
Cast(cm.MpAssumptionFeeDesc as nvarchar(max)) as MpAssumptionFeeDesc,
cm.MpParticipationPercent,
Cast(cm.MpParticipationPercentDesc as nvarchar(max)) as MpParticipationPercentDesc,
Cast(cm.MpRightToInspectRecords as nvarchar(max)) as MpRightToInspectRecords,
cm.MpUnsecuredDebtAllowed,
cm.MpMaxUnsecuredDebtAmt,
cm.MpTradePayablesMaxAmt,
cm.MpTradePayablesDaysOut,
cm.MpPartialReleasePercent,
Cast(cm.MpPartialReleaseDesc as nvarchar(max)) as MpPartialReleaseDesc,
Cast(cm.MpComment as nvarchar(max)) as MpComment,
cm.GCM_DealCounterpartyCode,
cm.AuditAddDate,
cm.AuditAddUserId,
cm.AuditUpdateDate,
cm.AuditUpdateUserId,
cm.PatriotActApprovedSw,
orgOwner.OrganizationName as OwnerOrgId_F,
Cast(cm.BrokerFeesComment as nvarchar(max)) as BrokerFeesComment,
cm.ArchiveInvestorFileSw,
cm.ArchiveLegalBinderSw,
Cast(cm.ArchiveComment as nvarchar(max)) as ArchiveComment,
LProg.LoanProgramDesc as LoanProgramCD_F,
LendRole.LenderRoleDesc as LenderRoleCD_F,
cm.TargetLoan,
cm.EstAppraisedCollateralValue,
cm.EstStressedCollateralValue,
cm.AcquisitionCostofCollateral,
cm.Matrix,
Cast(cm.CompetitionComments as nvarchar(max)) as CompetitionComments,
cm.HardEquityAmount,
cm.DealLocked,
curr.CurrencyDesc as DealCurrencyCD_F,
cm.Originator,
Cast(cm.SourceUsesComment as nvarchar(max)) as SourceUsesComment,
cm.StartLTV,
Cast(cm.FirstLossComment as nvarchar(max)) as FirstLossComment,
cm.Change2TicAfterCloseSw,
Cast(cm.SpringingLockBoxComment as nvarchar(max)) as SpringingLockBoxComment,
cm.BrokerFeesPct,
cm.CommitmentAmount,
cm.Analyst_UserId_F,
LType.LoanTypeDesc as LoanTypeCD_F,
cm.CreditApprovedDate,
cm.SpreadApprovedDate,
DDPContactID.FirstName+'' ''+DDPContactID.LastName as DDP_ContactID_F,
BroContactID.FirstName+'' ''+BroContactID.LastName as Broker_ContactID_F,
CocoContactID.FirstName+'' ''+CocoContactID.LastName as Cocounsel_ContactID_F,
CounselContactID.FirstName+'' ''+CounselContactID.LastName as Counsel_ContactID_F,
ParalegalContactID.FirstName+'' ''+ParalegalContactID.LastName as Paralegal_ContactID_F,
cm.RequestedLoanTerm,
cm.RequestedAmortTerm,
cm.RequestedSpread,
cm.RequestedIndex,
cm.RequestedLTV,
cm.RequestedLTC,
cm.TransactionManager_Userid_F,
cm.HUDLoanNumber,
cm.ApprovalLevel,
cm.ExistingDebt,
cm.ExistingDebtLender,
cm.ExistingDebtAmount,
cm.EarnOutAmount,
Cast(cm.MarketEquityComments as nvarchar(max)) as MarketEquityComments,
orgBookingLocation.OrganizationName as BookingLocation_OrgId_F,
cm.PortfolioManager_Userid_F,
cm.PrivateSW,
LCMBSLoanStatusCd.LoanStatusDesc as CMBSLoanStatusCd_F,
cm.CMBSDealGUID,
cm.MPFutureAdditionalDebtPermitted,
LNDCApprovedCd.ApprovalTypeDesc as NDCApprovedCd_F,
cm.NDCApprovedBy,
Cast(cm.NDCApprovedComment as nvarchar(max)) as NDCApprovedComment,
cm.NDCSecuritization,
cm.NDCSyndication,
cm.NDCApprovedDate,
cm.CreditApproved,
cm.SpreadApproved,
cm.SecondaryPortfolioManager_UserId_F,
cm.Legal_UserId_F,
cm.IRRBaselI,
cm.IRRBaselII,
cm.ListedCompany,
cm.PriceSensitive,
cm.Confidentiality,
cm.Exclusivity,
cm.ShareDeal,
LRequestedPaymentFreqCd.PaymentFreqDesc as RequestedPaymentFreqCd_F,
cm.RequestedIOTerm,
cm.RequestedLTVasStabilzed,
LRequestedRateTypeCd_F.RateTypeDesc as RequestedRateTypeCd_F,
cm.BorrowerImputedEquity,
cm.LoanSizer_UserId_F,
cm.ConstructionManager_UserId_F,
cm.InsuranceManager_UserId_F,
cm.DealIntroducedById_F,
orgCoCounselCompany_OrgId_F.OrganizationName as CoCounselCompany_OrgId_F,
LCoCounselCompany_ContactId_F.FirstName+'' ''+LCoCounselCompany_ContactId_F.LastName as CoCounselCompany_ContactId_F,
orgSecondaryLawFirm_OrgId_F.OrganizationName as SecondaryLawFirm_OrgId_F,
LSecondaryCounsel_ContactID_F.FirstName+'' ''+LSecondaryCounsel_ContactID_F.LastName as SecondaryCounsel_ContactID_F,
Cast(cm.SpecificDealTeamRequest as nvarchar(max)) as SpecificDealTeamRequest,
cm.QCAnalyst_UserID_F,
cm.OriginatorAssociate,
cm.ClosingCoordinator_UserID_F,
cm.AssetManager_UserID_F,
cm.NDCSecuritizationRequiredAmt,
cm.NDCSyndicationRequiredAmt,
cm.BrokeredDeal,
Cast(cm.DataTapeFootNotes as nvarchar(max)) as DataTapeFootNotes,
LMortgageOriginatingEntityCD_F.MortgageOriginatingEntityDesc as MortgageOriginatingEntityCD_F,
LDealSourceCD_F.DealSourceDesc as DealSourceCD_F,
cm.ProgramManager_UserId_F,
cm.SmallLoanPM_UserId_F,
cm.UnderwritingManager_UserId_F,
cm.Servicer_UserId_F,
cm.QALead_UserId_F,
cm.QAAssociate_UserId_F,
cm.ReportManager_UserId_F,
cm.BorrowerLawFirm_OrgId_F,
cm.BorrowerInsuranceCo_OrgId_F,
cm.BorrowerCounsel_ContactID_F,
cm.BorrowerInsAgent_ContactID_F,
cm.Holdback,
cm.HoldbackAmount,
cm.EstimatedCreditDate,
cm.Secondary_BrokerName_OrgId_F,
cm.Secondary_Broker_ContactID_F,
Cast(cm.RepeatSponsorComment as nvarchar(max)) as NDCApprovedComment,
cm.KickOffEmailSent,
cm.ExpirationStatus,
cm.ApplicationDepositFeePct,
Cast(cm.EarnOutComment as nvarchar(max)) as EarnOutComment,
cm.RealizedLossToTrust,
cm.NonRecoverability,
cm.LastSetupChangeDate,
cm.LastLoanContributionDate,
cm.LastPropContributionDate,
cm.AssumptionDate,
cm.LockBoxAtClosing,
cm.BrokerFeesPctTypeCd_F,
cm.BrokerFeesPctPaymentCd_F,
cm.ControlMasterID,
cm.Recovery,
cm.USTL_UserId_F,
cm.USQCAnalyst_UserId_F,
cm.Sponsor_OrgId_F,
cm.AvailabilityCd_F,
cm.AvailabilityDate,
cm.ForeignInvestorsMore,
cm.PCAccountingContact,
cm.PCAccountingContactNumber,
cm.PCServicingContact,
cm.PCServicingContactNumber,
cm.MinimumNCF,
cm.AssetManagementStatusCd_F,
cm.ConditionalCommitmentDeposit,
cm.CouponCurrent,
cm.CouponBase,
cm.CouponStress,
cm.ConstantCurrent,
cm.ConstantBase,
cm.ConstantStress,
cm.StressedCapRate,
cm.StressedConstant,
cm.BankNumberCD_F,
cm.OCCLoanPurposeCD_F,
cm.GeneralLedgerCD_F,
cm.CustomerId_F,
cm.NextAnnualReviewDate,
cm.Exempt,
cm.First12MonthsRevenue,
cm.LastAnnualReviewDate,
cm.BusinessLineManager_UserId_F,
cm.WDP,
cm.WDPx,
cm.AdditionalCollateral,
cm.InvestmentLeverage,
cm.BorrowerSecondaryLawFirm_OrgId_F,
cm.BorrowerSecondaryCounsel_ContactId_F,
cm.PROOwnerInvestor_OrgId_F,
cm.PROSponsorDeveloper_OrgId_F,
cm.PROBrokerDebt_OrgId_F,
cm.PROBrokerEquity_OrgId_F,
cm.PROBrokerLeasing_OrgId_F,
cm.PROLender_OrgId_F,
cm.PRODueDiligence_OrgId_F,
cm.PROAppraiser_OrgId_F,
cm.PROLawFirm_OrgId_F,
cm.SecondaryOfficeCd_F,
Cast(cm.LoanPurposeComments as nvarchar(max)) as LoanPurposeComments,
cm.AdditionalCollateralTypeCd_F,
Cast(cm.DealLevelMarketComments as nvarchar(max)) as DealLevelMarketComments,
Cast(cm.UnderwritingGuidelineDeviationComments as nvarchar(max)) as UnderwritingGuidelineDeviationComments,
Cast(cm.AdministrationVarianceComments as nvarchar(max)) as AdministrationVarianceComments,
cm.Active,
cm.StabilizedDebtYield,
--cm.WorkflowTemplateTypeCd_F,
cm.ExistingDebtMaturityDate,
cm.Market,
cm.MarketTotalSF,
cm.MarketVacancy,
cm.PurchasePrice,
cm.TILC,
cm.Capex,
cm.ClosingCosts,
cm.ROA,
cm.LPDRCD_F,
cm.SPDRCD_F,
cm.AssetManagementStatusColorCd_F,
cm.CommunityLendingDevelopmentPurposeCd_F,
cm.AlternateDealNumber,
cm.MortgageLoanOriginator_OrgId_F,
cm.MortgageLoanSeller_OrgId_F,
cm.SEREFAllocation,
cm.StarFinAllocation,
cm.SEREFStarFinIRR,
cm.ServicerWillSpreadFinancials,
cm.FirmProductionDate,
cm.CreditRiskApprovalDate,
cm.CreditRiskDeniedDate,
cm.ReferralFee,
cm.FANumber,
cm.LegalFeeAmount,
cm.QuotedDate,
cm.PrelimPricingBucket,
Cast(cm.PrelimPricingBucketComments as nvarchar(max)) as PrelimPricingBucketComments,
cm.ReferralIDNumber,
cm.CopyDealOptionCd_F,
cm.CurrentLPDRCD_F,
cm.GPDRCD_F,
cm.ProbabilityCD_F,
cm.CapitalMarketProductSW,
cm.MortgageBroker_OrgId_F,
cm.DealSponsor_OrgId_F,
cm.MortgageBroker_ContactId_F,
cm.isMUV,
cm.ClientIdentifier,
cm.DueDiligencePeriod,
cm.PrincipalNetWorthGreaterThanLoan,
cm.PrincipalLiquidityGreaterThanDebtService,
cm.PrincipalsFreeOfBankruptcyForeclosureDIL,
cm.PrincipalsFreeOfLitigation,
cm.WithholdingTaxExemptionRequired,
cm.DealSourceFirm,
cm.DealSourceContact,
cm.CMBSControlMasterID,
cm.TeamLeader_UserID_F,
cm.SecondaryCounsel_Contact2ID_F,
cm.SecondaryCounsel_Contact3ID_F,
cm.BorrowerCounsel_Contact2ID_F,
cm.BorrowerCounsel_Contact3ID_F,
cm.SecondaryBorrowerFirm_OrgId_F,
cm.SecondaryBorrowerFirm_ContactID_F,
cm.MasterServicer_OrgId_F,
cm.DealBorrower_OrgId_F,
cm.TertiaryLawFirm_OrgId_F,
cm.DealBorrowerContact1_ContactId_F,
cm.DealBorrowerContact2_ContactId_F,
cm.DealBorrowerContact3_ContactId_F,
cm.DealBorrowerContact4_ContactId_F,
cm.DealBorrowerContact5_ContactId_F,
cm.DealBorrowerContact6_ContactId_F,
cm.TertiaryCounsel_ContactId_F,
cm.TertiaryCoCounsel_ContactId_F,
cm.UnleveredMultipleNetAtOrigination,
cm.LeveredIRRGrossAtOrigination,
cm.LeveredIRRNetAtOrigination,
cm.LeveredProfitGrossAtOrigination,
cm.LeveredProfitNetAtOrigination,
cm.LeveredMultipleGrossAtOrigination,
cm.LeveredMultipleNetAtOrigination,
cm.InitialDebtYield,
cm.ClosedDealLockSW,
cm.StrategyTypeCD_F,
cm.PNAStatus,
cm.LoanDefaultDate,
cm.DefaultLetterSentDate,
cm.ForclosureFiledExpectedDate,
cm.LastPatriotActChecked,
cm.FreeofJrSubDebt,
Cast(cm.AnticipatedPayoffComment as nvarchar(max)) as AnticipatedPayoffComment,
cm.AnticipatedActualCofODate,
cm.OrganizationDealStatusID_F,
cm.RiskMatrixCd_F,
cm.DispositionMethodCd_F,
cm.PriorOutlookColorCd_F,
cm.AssetManagementLTVorLTC,
cm.BusinessPlanCd_F,
cm.AssetMgmtMarketCd_F,
cm.ReviewRotationCd_F,
cm.AssetManagementRecourseCd_F,
cm.PipelineReportReview,
cm.DACABank_OrgId_F,
cm.CMABank_OrgId_F,
cm.LenderCashMgmtSuspended,
cm.LenderCashMgmtSuspendedUntilDate,
cm.TriggersEventOfDefault,
cm.TriggersDSCROperator,
cm.TriggersDSCRValue,
cm.TriggersDebtYieldOperator,
cm.TriggersDebtYieldValue,
Cast(cm.TriggersOtherCondition1 as nvarchar(max)) as TriggersOtherCondition1,
cm.CureEventOfDefault,
cm.CureDSCROperator,
cm.CureDSCRValue,
cm.CureDSCRNumOfConsecutivePeriods,
cm.CureDSCRDurationCd_F,
cm.CureDebtYieldOperator,
cm.CureDebtYieldValue,
cm.CureDebtYieldNumOfConsecutivePeriods,
cm.CureDebtYieldDurationCd_F,
Cast(cm.CureOtherCondition1 as nvarchar(max)) as CureOtherCondition1,
Cast(cm.CureOtherCondition2 as nvarchar(max)) as CureOtherCondition2,
Cast(cm.CureOtherCondition3 as nvarchar(max)) as CureOtherCondition3,
Cast(cm.TriggersOtherCondition2 as nvarchar(max)) as TriggersOtherCondition2,
Cast(cm.TriggersOtherCondition3 as nvarchar(max)) as TriggersOtherCondition3,
cm.DealBorrower2_OrgId_F,
cm.DealBorrower3_OrgId_F,
cm.DealBorrower4_OrgId_F,
cm.DealBorrower5_OrgId_F,
cm.DealBorrower6_OrgId_F,
cm.REITPropertyTypeCd_F,
cm.REITSectorTypeCd_F,
cm.UWLTCatOrigination,
cm.UWLTVatOrigination,
cm.DSCRatOrigination,
cm.DebtYieldAsIs,
cm.UnleveredIRRGross,
cm.UnleveredProfitGross,
cm.UnleveredMultipleGross,
cm.LeveredIRRGross,
cm.LeveredProfitGross,
cm.LeveredMultipleGross,
cm.StabilizedLTV,
cm.StabilizedLTC,
cm.SecuritizationID_F,
cm.InvestmentTypeCD_F,
cm.LTCFullyFunded,
cm.LTVAtStab,
cm.AllocationDate,
cm.AcoreRating,
cm.OrigFundingDate,
cm.ModifiedFrom,
cm.GLStatusDate,
cm.CurrentLPDRDate,
cm.ReferredByUsername,
cm.InitialLTCPct,
cm.EndLTCPct,
cm.NonRefundableProcessingFee,
cm.TermSheetExclusivePeriod,
cm.BreakUpFee,
cm.PrincipalGuarantee,
cm.ClosingEquityRequired,
cm.ReferralChannel,
cm.HMDASw,
cm.RecourseTypeCD_F,
cm.ApprovedByCd_F,
cm.EstimateCashOut,
cm.ChangesInConditionalApproval,
cm.ChangesInTermsAndConditions,
cm.SeniorReportManager_UserId_F,
cm.CoLendApprovedSw,
cm.PropertyAQR,
cm.GuarantorAQR,
cm.DealAQR,
cm.OriginalLoanTerm,
cm.DebtYieldStabilization,
cm.AMTeamLeader_UserId_F
from tblcontrolmaster cm
left join tblzCdLoanStatus Lstatus on Lstatus.LoanStatusCd = cm.LoanStatusCd_F
left join tblOrganization orgBrk on orgBrk.OrganizationID = cm.BrokerName_OrgId_F
left join tblOrganization orgLendorName on orgLendorName.OrganizationID = cm.LendorName_OrgId_F
left join tblOrganization orgLawFirm on orgLawFirm.OrganizationID = cm.LawFirm_OrgId_F
left join tblOrganization orgOffice on orgOffice.OrganizationID = cm.Office_OrgId_F
left join tblOrganization orgCompetition on orgCompetition.OrganizationID = cm.Competition_Org_Id_F
left join tblOrganization orgDueDiligenceProvider on orgDueDiligenceProvider.OrganizationID = cm.DueDiligenceProvider_OrgId_F
left join tblDealRelated dealRela on dealRela.DealRelatedID = cm.DealRelatedID_F
left join tblzCdOriginalDataSource OriDS on OriDS.OriginalDataSourceCd = cm.OriginalDataSource_F
left join tblOrganization orgOwner on orgOwner.OrganizationID = cm.OwnerOrgId_F
left join tblzCdLoanProgram LProg on LProg.LoanProgramCD = cm.LoanProgramCD_F
left join tblzCdLenderRole LendRole on LendRole.LenderRoleCD = cm.LenderRoleCD_F
left join tblzCDCurrencyCd curr on curr.CurrencyCd = cm.DealCurrencyCD_F
left join tblzCDLoanType LType on LType.LoanTypeCD_F = cm.LoanTypeCD_F
left join tblContact DDPContactID on DDPContactID.contactid = cm.DDP_ContactID_F 
left join tblContact BroContactID on BroContactID.contactid = cm.Broker_ContactID_F
left join tblContact CocoContactID on CocoContactID.contactid = cm.Cocounsel_ContactID_F	
left join tblContact CounselContactID on CounselContactID.contactid = cm.Counsel_ContactID_F
left join tblContact ParalegalContactID on ParalegalContactID.contactid = cm.Paralegal_ContactID_F
left join tblOrganization orgBookingLocation on orgBookingLocation.OrganizationID = cm.BookingLocation_OrgId_F
left join tblzCdLoanStatus LCMBSLoanStatusCd on LCMBSLoanStatusCd.LoanStatusCd = cm.CMBSLoanStatusCd_F
left join tblzCdApprovalType LNDCApprovedCd on LNDCApprovedCd.ApprovalTypeCD = cm.NDCApprovedCd_F
left join tblzCdPaymentFreq LRequestedPaymentFreqCd on LRequestedPaymentFreqCd.PaymentFreqCd = cm.RequestedPaymentFreqCd_F
left join tblzCdRateType LRequestedRateTypeCd_F on LRequestedRateTypeCd_F.RateTypeCode = cm.RequestedRateTypeCd_F
left join tblOrganization orgCoCounselCompany_OrgId_F on orgCoCounselCompany_OrgId_F.OrganizationID = cm.CoCounselCompany_OrgId_F
left join tblContact LCoCounselCompany_ContactId_F on LCoCounselCompany_ContactId_F.contactid = cm.CoCounselCompany_ContactId_F	  
left join tblOrganization orgSecondaryLawFirm_OrgId_F on orgSecondaryLawFirm_OrgId_F.OrganizationID = cm.SecondaryLawFirm_OrgId_F
left join tblContact LSecondaryCounsel_ContactID_F on LSecondaryCounsel_ContactID_F.contactid = cm.SecondaryCounsel_ContactID_F
left join tblzCdMortgageOriginatingEntity LMortgageOriginatingEntityCD_F on LMortgageOriginatingEntityCD_F.MortgageOriginatingEntityCD = cm.MortgageOriginatingEntityCD_F
left join tblzCdDealSource LDealSourceCD_F on LDealSourceCD_F.DealSourceCD = cm.DealSourceCD_F
WHERE  (cm.AuditAddDate > '''+Convert(Nvarchar(max),@LastBatchStart,121)+'''
				and cm.AuditAddDate <  '''+Convert(Nvarchar(max),@CurrentBatchStart,121)+'''  ) 
				OR 
				(cm.AuditUpdateDate > '''+Convert(Nvarchar(max),@LastBatchStart,121)+'''
				and cm.AuditUpdateDate < '''+Convert(Nvarchar(max),@CurrentBatchStart,121)+''' )
'
--===================================
Declare @BSDeal as Table(
ControlId	 nvarchar(10)  NOT NULL ,
LoanNumber	 nvarchar(25)  NULL ,
LoanStatusCd_F	 nvarchar(256)  NULL ,
BrokerName_OrgId_F	 nvarchar(256)  NULL ,
LendorName_OrgId_F	 nvarchar(256)  NULL ,
LawFirm_OrgId_F	 nvarchar(256)  NULL ,
Office_OrgId_F	 nvarchar(256)  NULL ,
DealRelatedId_F	 nvarchar(256)  NULL ,
Competition_Org_Id_F	 nvarchar(256)  NULL ,
DueDiligenceProvider_OrgId_F	 nvarchar(256)  NULL ,
OriginalDataSource_F	 nvarchar(256)  NULL ,
MinimumDSCR	 float  NULL ,
MinimumDSCRatConstant	 float  NULL ,
MaximumLTV	 float  NULL ,
MinimumConstantDeal	 float  NULL ,
PrimaryBanker_UserId_F	 int  NULL ,
SecondaryBanker_UserId_F	 int  NULL ,
Underwriter_UserID_F	 int  NULL ,
ServicersLoanNumber	 nvarchar(30)  NULL ,
DealName	 nvarchar(75)  NOT NULL ,
CreditApprovedBy	 varchar(50)  NULL ,
CreditApprovedComment	 nvarchar(max) NULL ,
SpreadApprovedBy	 varchar(50)  NULL ,
SpreadApprovedComment	 nvarchar(max) NULL ,
Correspondent	 nvarchar(50)  NULL ,
CorrUW	 nvarchar(50)  NULL ,
CollateralType	 nvarchar(30)  NULL ,
DebtServiceAllocated	 nvarchar(255)  NULL ,
LoanPurpose	 nvarchar(25)  NULL ,
LoanProbability	 float  NULL ,
ApplicationReceiveDate	 datetime  NULL ,
ApplicationDate	 datetime  NULL ,
LenderRightToMatch	 nvarchar(3)  NULL ,
ApplicationDeposit	 decimal(28,15)  NULL ,
LockBox	 nvarchar(50)  NULL ,
LockBoxComment	 nvarchar(max) NULL ,
HardCashManagement	 nvarchar(25)  NULL ,
Recourse	 nvarchar(3)  NULL ,
ClosingConditions	 nvarchar(max) NULL ,
EstClosingCosts	 decimal(28,15)  NULL ,
EarnOut	 nvarchar(3)  NULL ,
IndDirectorReqSw	 nvarchar(3)  NULL ,
NonConsolOpinionReqSw	 nvarchar(3)  NULL ,
OwnershipComments	 nvarchar(max) NULL ,
BrokerFees	 decimal(28,15)  NULL ,
Cashout	 nvarchar(3)  NULL ,
PreliminarySponsor	 nvarchar(600)  NULL ,
OngoingDSCRTest	 nvarchar(max) NULL ,
SpecialPricingNotes	 nvarchar(max) NULL ,
HardEquityComment	 nvarchar(max) NULL ,
MatrixSpreadAtClose	 float  NULL ,
MatrixSpreadAtCloseComments	 nvarchar(max) NULL ,
CommitmentExpDate	 datetime  NULL ,
Comments	 nvarchar(max) NULL ,
TICSw	 bit  NULL ,
MpIsLoanAssumable	 nvarchar(3)  NULL ,
MpIsLoanAssumableDesc	 nvarchar(max) NULL ,
MpEquityParticipation	 nvarchar(3)  NULL ,
MpEquityParticipationDesc	 nvarchar(max) NULL ,
MpAllowFutAdvances	 nvarchar(3)  NULL ,
MpAllowFutAdvancesDesc	 nvarchar(max) NULL ,
MpMaxFutureAdvances	 decimal(28,15)  NULL ,
MpFutAdvancesToDate	 decimal(28,15)  NULL ,
MpAssumptionFeePct	 float  NULL ,
MpAssumptionFeeAmt	 decimal(28,15)  NULL ,
MpAssumptionFee	 float  NULL ,
MpAssumptionFeeDesc	 nvarchar(max) NULL ,
MpParticipationPercent	 float  NULL ,
MpParticipationPercentDesc	 nvarchar(max) NULL ,
MpRightToInspectRecords	 nvarchar(max) NULL ,
MpUnsecuredDebtAllowed	 nvarchar(3)  NULL ,
MpMaxUnsecuredDebtAmt	 decimal(28,15)  NULL ,
MpTradePayablesMaxAmt	 decimal(28,15)  NULL ,
MpTradePayablesDaysOut	 int  NULL ,
MpPartialReleasePercent	 float  NULL ,
MpPartialReleaseDesc	 nvarchar(max) NULL ,
MpComment	 nvarchar(max) NULL ,
GCM_DealCounterpartyCode	 nvarchar(10)  NULL ,
AuditAddDate	 datetime  NOT NULL ,
AuditAddUserId	 nvarchar(150)  NULL ,
AuditUpdateDate	 datetime  NULL ,
AuditUpdateUserId	 nvarchar(150)  NULL ,
PatriotActApprovedSw	 bit  NULL ,
OwnerOrgId_F	 nvarchar(256)  NULL ,
BrokerFeesComment	 nvarchar(max) NULL ,
ArchiveInvestorFileSw	 bit  NULL ,
ArchiveLegalBinderSw	 bit  NULL ,
ArchiveComment	 nvarchar(max) NULL ,
LoanProgramCD_F	 nvarchar(256)  NULL ,
LenderRoleCD_F	 nvarchar(256)  NULL ,
TargetLoan	 decimal(28,15)  NULL ,
EstAppraisedCollateralValue	 decimal(28,15)  NULL ,
EstStressedCollateralValue	 decimal(28,15)  NULL ,
AcquisitionCostofCollateral	 decimal(28,15)  NULL ,
Matrix	 nvarchar(10)  NULL ,
CompetitionComments	 nvarchar(max) NULL ,
HardEquityAmount	 decimal(28,15)  NULL ,
DealLocked	 bit  NULL ,
DealCurrencyCD_F	 nvarchar(256)  NULL ,
Originator	 varchar(50)  NULL ,
SourceUsesComment	 nvarchar(max) NULL ,
StartLTV	 float  NULL ,
FirstLossComment	 nvarchar(max) NULL ,
Change2TicAfterCloseSw	 nvarchar(3)  NULL ,
SpringingLockBoxComment	 nvarchar(max) NULL ,
BrokerFeesPct	 float  NULL ,
CommitmentAmount	 decimal(28,15)  NULL ,
Analyst_UserId_F	 int  NULL ,
LoanTypeCD_F	 nvarchar(256)  NULL ,
CreditApprovedDate	 datetime  NULL ,
SpreadApprovedDate	 datetime  NULL ,
DDP_ContactID_F	 nvarchar(256)  NULL ,
Broker_ContactID_F	 nvarchar(256)  NULL ,
Cocounsel_ContactID_F	 nvarchar(256)  NULL ,
Counsel_ContactID_F	 nvarchar(256)  NULL ,
Paralegal_ContactID_F	 nvarchar(256)  NULL ,
RequestedLoanTerm	 int  NULL ,
RequestedAmortTerm	 int  NULL ,
RequestedSpread	 float  NULL ,
RequestedIndex	 nvarchar(20)  NULL ,
RequestedLTV	 float  NULL ,
RequestedLTC	 float  NULL ,
TransactionManager_Userid_F	 int  NULL ,
HUDLoanNumber	 nvarchar(35)  NULL ,
ApprovalLevel	 int  NULL ,
ExistingDebt	 nvarchar(3)  NULL ,
ExistingDebtLender	 nvarchar(50)  NULL ,
ExistingDebtAmount	 decimal(28,15)  NULL ,
EarnOutAmount	 decimal(28,15)  NULL ,
MarketEquityComments	 nvarchar(max) NULL ,
BookingLocation_OrgId_F	 nvarchar(256)  NULL ,
PortfolioManager_Userid_F	 int  NULL ,
PrivateSW	 bit  NULL ,
CMBSLoanStatusCd_F	 nvarchar(256)  NULL ,
CMBSDealGUID	 uniqueidentifier  NULL ,
MPFutureAdditionalDebtPermitted	 nvarchar(3)  NULL ,
NDCApprovedCd_F	 nvarchar(256)  NULL ,
NDCApprovedBy	 nvarchar(50)  NULL ,
NDCApprovedComment	 nvarchar(max) NULL ,
NDCSecuritization	 nvarchar(3)  NULL ,
NDCSyndication	 nvarchar(3)  NULL ,
NDCApprovedDate	 datetime  NULL ,
CreditApproved	 nvarchar(5)  NULL ,
SpreadApproved	 nvarchar(5)  NULL ,
SecondaryPortfolioManager_UserId_F	 int  NULL ,
Legal_UserId_F	 int  NULL ,
IRRBaselI	 float  NULL ,
IRRBaselII	 float  NULL ,
ListedCompany	 nvarchar(3)  NULL ,
PriceSensitive	 nvarchar(3)  NULL ,
Confidentiality	 nvarchar(3)  NULL ,
Exclusivity	 nvarchar(3)  NULL ,
ShareDeal	 nvarchar(3)  NULL ,
RequestedPaymentFreqCd_F	 nvarchar(256)  NULL ,
RequestedIOTerm	 int  NULL ,
RequestedLTVasStabilzed	 float  NULL ,
RequestedRateTypeCd_F	 nvarchar(256)  NULL ,
BorrowerImputedEquity	 decimal(28,15)  NULL ,
LoanSizer_UserId_F	 int  NULL ,
ConstructionManager_UserId_F	 int  NULL ,
InsuranceManager_UserId_F	 int  NULL ,
DealIntroducedById_F	 int  NULL ,
CoCounselCompany_OrgId_F	 nvarchar(256)  NULL ,
CoCounselCompany_ContactId_F	 nvarchar(256)  NULL ,
SecondaryLawFirm_OrgId_F	 nvarchar(256)  NULL ,
SecondaryCounsel_ContactID_F	 nvarchar(256)  NULL ,
SpecificDealTeamRequest	 nvarchar(max) NULL ,
QCAnalyst_UserID_F	 int  NULL ,
OriginatorAssociate	 nvarchar(100)  NULL ,
ClosingCoordinator_UserID_F	 int  NULL ,
AssetManager_UserID_F	 int  NULL ,
NDCSecuritizationRequiredAmt	 decimal(28,15)  NULL ,
NDCSyndicationRequiredAmt	 decimal(28,15)  NULL ,
BrokeredDeal	 nvarchar(3)  NULL ,
DataTapeFootNotes	 nvarchar(max) NULL ,
MortgageOriginatingEntityCD_F	 nvarchar(256)  NULL ,
DealSourceCD_F	 nvarchar(256)  NULL ,
ProgramManager_UserId_F	 int  NULL ,
SmallLoanPM_UserId_F	 int  NULL ,
UnderwritingManager_UserId_F	 int  NULL ,
Servicer_UserId_F	 int  NULL ,
QALead_UserId_F	 int  NULL ,
QAAssociate_UserId_F	 int  NULL ,
ReportManager_UserId_F	 int  NULL ,
BorrowerLawFirm_OrgId_F	 nvarchar(256)  NULL ,
BorrowerInsuranceCo_OrgId_F	 nvarchar(256)  NULL ,
BorrowerCounsel_ContactID_F	 nvarchar(256)  NULL ,
BorrowerInsAgent_ContactID_F	 nvarchar(256)  NULL ,
Holdback	 nvarchar(3)  NULL ,
HoldbackAmount	 decimal  NULL ,
EstimatedCreditDate	 datetime  NULL ,
Secondary_BrokerName_OrgId_F	 nvarchar(256)  NULL ,
Secondary_Broker_ContactID_F	 nvarchar(256)  NULL ,
RepeatSponsorComment	 nvarchar(max) NULL ,
KickOffEmailSent	 bit  NULL ,
ExpirationStatus	 tinyint  NULL ,
ApplicationDepositFeePct	 float  NULL ,
EarnOutComment	 nvarchar(max) NULL ,
RealizedLossToTrust	 decimal(28,15)  NULL ,
NonRecoverability	 nvarchar(3)  NULL ,
LastSetupChangeDate	 datetime  NULL ,
LastLoanContributionDate	 datetime  NULL ,
LastPropContributionDate	 datetime  NULL ,
AssumptionDate	 datetime  NULL ,
LockBoxAtClosing	 nvarchar(3)  NULL ,
BrokerFeesPctTypeCd_F	 nvarchar(256)  NULL ,
BrokerFeesPctPaymentCd_F	 nvarchar(256)  NULL ,
ControlMasterID	 int  NULL ,
Recovery	 decimal(28,15)  NULL ,
USTL_UserId_F	 int  NULL ,
USQCAnalyst_UserId_F	 int  NULL ,
Sponsor_OrgId_F	 nvarchar(256)  NULL ,
AvailabilityCd_F	 nvarchar(256)  NULL ,
AvailabilityDate	 datetime  NULL ,
ForeignInvestorsMore	 nvarchar(3)  NULL ,
PCAccountingContact	 nvarchar(50)  NULL ,
PCAccountingContactNumber	 nvarchar(50)  NULL ,
PCServicingContact	 nvarchar(50)  NULL ,
PCServicingContactNumber	 nvarchar(50)  NULL ,
MinimumNCF	 decimal(28,15)  NULL ,
AssetManagementStatusCd_F	 nchar(20)  NULL ,
ConditionalCommitmentDeposit	 decimal(28,15)  NULL ,
CouponCurrent	 float  NULL ,
CouponBase	 float  NULL ,
CouponStress	 float  NULL ,
ConstantCurrent	 float  NULL ,
ConstantBase	 float  NULL ,
ConstantStress	 float  NULL ,
StressedCapRate	 float  NULL ,
StressedConstant	 float  NULL ,
BankNumberCD_F	 nvarchar(115)  NULL ,
OCCLoanPurposeCD_F	 nvarchar(256)  NULL ,
GeneralLedgerCD_F	 nvarchar(256)  NULL ,
CustomerId_F	 nvarchar(256)  NULL ,
NextAnnualReviewDate	 datetime  NULL ,
Exempt	 bit  NULL ,
First12MonthsRevenue	 decimal(28,15)  NULL ,
LastAnnualReviewDate	 datetime  NULL ,
BusinessLineManager_UserId_F	 int  NULL ,
WDP	 decimal(28,15)  NULL ,
WDPx	 float  NULL ,
AdditionalCollateral	 decimal(28,15)  NULL ,
InvestmentLeverage	 float  NULL ,
BorrowerSecondaryLawFirm_OrgId_F	 nvarchar(256)  NULL ,
BorrowerSecondaryCounsel_ContactId_F	 nvarchar(256)  NULL ,
PROOwnerInvestor_OrgId_F	 nvarchar(256)  NULL ,
PROSponsorDeveloper_OrgId_F	 nvarchar(256)  NULL ,
PROBrokerDebt_OrgId_F	 nvarchar(256)  NULL ,
PROBrokerEquity_OrgId_F	 nvarchar(256)  NULL ,
PROBrokerLeasing_OrgId_F	 nvarchar(256)  NULL ,
PROLender_OrgId_F	 nvarchar(256)  NULL ,
PRODueDiligence_OrgId_F	 nvarchar(256)  NULL ,
PROAppraiser_OrgId_F	 nvarchar(256)  NULL ,
PROLawFirm_OrgId_F	 nvarchar(256)  NULL ,
SecondaryOfficeCd_F	 nvarchar(256)  NULL ,
LoanPurposeComments	nvarchar(max) NULL ,
AdditionalCollateralTypeCd_F	 nvarchar(256)  NULL ,
DealLevelMarketComments	nvarchar(max) NULL ,
UnderwritingGuidelineDeviationComments	nvarchar(max) NULL ,
AdministrationVarianceComments	nvarchar(max) NULL ,
Active	 nvarchar(3)  NULL ,
StabilizedDebtYield	 float  NULL ,
--WorkflowTemplateTypeCd_F	 nvarchar(256)  NULL ,
ExistingDebtMaturityDate	 datetime  NULL ,
Market	 nvarchar(100)  NULL ,
MarketTotalSF	 numeric  NULL ,
MarketVacancy	 numeric  NULL ,
PurchasePrice	 float  NULL ,
TILC	 float  NULL ,
Capex	 float  NULL ,
ClosingCosts	 float  NULL ,
ROA	 decimal  NULL ,
LPDRCD_F	 nvarchar(10)  NULL ,
SPDRCD_F	 nvarchar(10)  NULL ,
AssetManagementStatusColorCd_F	 nvarchar(256)  NULL ,
CommunityLendingDevelopmentPurposeCd_F	 nvarchar(256)  NULL ,
AlternateDealNumber	 nvarchar(50)  NULL ,
MortgageLoanOriginator_OrgId_F	 nvarchar(256)  NULL ,
MortgageLoanSeller_OrgId_F	 nvarchar(256)  NULL ,
SEREFAllocation	 float  NULL ,
StarFinAllocation	 float  NULL ,
SEREFStarFinIRR	 float  NULL ,
ServicerWillSpreadFinancials	 nvarchar(3)  NULL ,
FirmProductionDate	 datetime  NULL ,
CreditRiskApprovalDate	 datetime  NULL ,
CreditRiskDeniedDate	 datetime  NULL ,
ReferralFee	 float  NULL ,
FANumber	 varchar(20)  NULL ,
LegalFeeAmount	 decimal(28,15)  NULL ,
QuotedDate	 datetime  NULL ,
PrelimPricingBucket	 varchar(50)  NULL ,
PrelimPricingBucketComments	 nvarchar(max) NULL ,
ReferralIDNumber	 nvarchar(50)  NULL ,
CopyDealOptionCd_F	 nvarchar(10)  NULL ,
CurrentLPDRCD_F	 nvarchar(10)  NULL ,
GPDRCD_F	 nvarchar(10)  NULL ,
ProbabilityCD_F	 nvarchar(50)  NULL ,
CapitalMarketProductSW	 bit  NOT NULL ,
MortgageBroker_OrgId_F	 nvarchar(256)  NULL ,
DealSponsor_OrgId_F	 nvarchar(256)  NULL ,
MortgageBroker_ContactId_F	 nvarchar(256)  NULL ,
isMUV	 nvarchar(3)  NULL ,
ClientIdentifier	 nvarchar(100)  NULL ,
DueDiligencePeriod	 int  NULL ,
PrincipalNetWorthGreaterThanLoan	 bit  NULL ,
PrincipalLiquidityGreaterThanDebtService	 bit  NULL ,
PrincipalsFreeOfBankruptcyForeclosureDIL	 bit  NULL ,
PrincipalsFreeOfLitigation	 bit  NULL ,
WithholdingTaxExemptionRequired	 bit  NULL ,
DealSourceFirm	 int  NULL ,
DealSourceContact	 int  NULL ,
CMBSControlMasterID	 bigint  NULL ,
TeamLeader_UserID_F	 int  NULL ,
SecondaryCounsel_Contact2ID_F	 nvarchar(256)  NULL ,
SecondaryCounsel_Contact3ID_F	 nvarchar(256)  NULL ,
BorrowerCounsel_Contact2ID_F	 nvarchar(256)  NULL ,
BorrowerCounsel_Contact3ID_F	 nvarchar(256)  NULL ,
SecondaryBorrowerFirm_OrgId_F	 nvarchar(256)  NULL ,
SecondaryBorrowerFirm_ContactID_F	 nvarchar(256)  NULL ,
MasterServicer_OrgId_F	 nvarchar(256)  NULL ,
DealBorrower_OrgId_F	 nvarchar(256)  NULL ,
TertiaryLawFirm_OrgId_F	 nvarchar(256)  NULL ,
DealBorrowerContact1_ContactId_F	 nvarchar(256)  NULL ,
DealBorrowerContact2_ContactId_F	 nvarchar(256)  NULL ,
DealBorrowerContact3_ContactId_F	 nvarchar(256)  NULL ,
DealBorrowerContact4_ContactId_F	 nvarchar(256)  NULL ,
DealBorrowerContact5_ContactId_F	 nvarchar(256)  NULL ,
DealBorrowerContact6_ContactId_F	 nvarchar(256)  NULL ,
TertiaryCounsel_ContactId_F	 nvarchar(256)  NULL ,
TertiaryCoCounsel_ContactId_F	 nvarchar(256)  NULL ,
UnleveredMultipleNetAtOrigination	 decimal(28,15)  NULL ,
LeveredIRRGrossAtOrigination	 decimal(28,15)  NULL ,
LeveredIRRNetAtOrigination	 decimal(28,15)  NULL ,
LeveredProfitGrossAtOrigination	 decimal(28,15)  NULL ,
LeveredProfitNetAtOrigination	 decimal(28,15)  NULL ,
LeveredMultipleGrossAtOrigination	 decimal(28,15)  NULL ,
LeveredMultipleNetAtOrigination	 decimal(28,15)  NULL ,
InitialDebtYield	 float  NULL ,
ClosedDealLockSW	 bit  NULL ,
StrategyTypeCD_F	 nvarchar(20)  NULL ,
PNAStatus	 nvarchar(10)  NULL ,
LoanDefaultDate	 datetime  NULL ,
DefaultLetterSentDate	 datetime  NULL ,
ForclosureFiledExpectedDate	 datetime  NULL ,
LastPatriotActChecked	 datetime  NULL ,
FreeofJrSubDebt	 nvarchar(3)  NULL ,
AnticipatedPayoffComment	 nvarchar(max) NULL ,
AnticipatedActualCofODate	 datetime  NULL ,
OrganizationDealStatusID_F	 int  NULL ,
RiskMatrixCd_F	 nvarchar(10)  NULL ,
DispositionMethodCd_F	 nvarchar(10)  NULL ,
PriorOutlookColorCd_F	 nvarchar(10)  NULL ,
AssetManagementLTVorLTC	 nvarchar(3)  NULL ,
BusinessPlanCd_F	 nvarchar(256)  NULL ,
AssetMgmtMarketCd_F	 nvarchar(256)  NULL ,
ReviewRotationCd_F	 nvarchar(256)  NULL ,
AssetManagementRecourseCd_F	 nvarchar(256)  NULL ,
PipelineReportReview	 nvarchar(3)  NULL ,
DACABank_OrgId_F	 nvarchar(256)  NULL ,
CMABank_OrgId_F	 nvarchar(256)  NULL ,
LenderCashMgmtSuspended	 nvarchar(3)  NULL ,
LenderCashMgmtSuspendedUntilDate	 datetime  NULL ,
TriggersEventOfDefault	 nvarchar(3)  NULL ,
TriggersDSCROperator	 nvarchar(2)  NULL ,
TriggersDSCRValue	 float  NULL ,
TriggersDebtYieldOperator	 nvarchar(2)  NULL ,
TriggersDebtYieldValue	 float  NULL ,
TriggersOtherCondition1	 nvarchar(max) NULL ,
CureEventOfDefault	 nvarchar(3)  NULL ,
CureDSCROperator	 nvarchar(2)  NULL ,
CureDSCRValue	 float  NULL ,
CureDSCRNumOfConsecutivePeriods	 int  NULL ,
CureDSCRDurationCd_F	 nvarchar(10)  NULL ,
CureDebtYieldOperator	 nvarchar(2)  NULL ,
CureDebtYieldValue	 float  NULL ,
CureDebtYieldNumOfConsecutivePeriods	 int  NULL ,
CureDebtYieldDurationCd_F	 nvarchar(10)  NULL ,
CureOtherCondition1	 nvarchar(max) NULL ,
CureOtherCondition2	 nvarchar(max) NULL ,
CureOtherCondition3	 nvarchar(max) NULL ,
TriggersOtherCondition2	 nvarchar(max) NULL ,
TriggersOtherCondition3	 nvarchar(max) NULL ,
DealBorrower2_OrgId_F	 nvarchar(256)  NULL ,
DealBorrower3_OrgId_F	 nvarchar(256)  NULL ,
DealBorrower4_OrgId_F	 nvarchar(256)  NULL ,
DealBorrower5_OrgId_F	 nvarchar(256)  NULL ,
DealBorrower6_OrgId_F	 nvarchar(256)  NULL ,
REITPropertyTypeCd_F	 nvarchar(256)  NULL ,
REITSectorTypeCd_F	 nvarchar(10)  NULL ,
UWLTCatOrigination	 nvarchar(30)  NULL ,
UWLTVatOrigination	 nvarchar(30)  NULL ,
DSCRatOrigination	 nvarchar(30)  NULL ,
DebtYieldAsIs	 nvarchar(30)  NULL ,
UnleveredIRRGross	 nvarchar(30)  NULL ,
UnleveredProfitGross	 nvarchar(30)  NULL ,
UnleveredMultipleGross	 nvarchar(30)  NULL ,
LeveredIRRGross	 nvarchar(30)  NULL ,
LeveredProfitGross	 nvarchar(30)  NULL ,
LeveredMultipleGross	 nvarchar(30)  NULL ,
StabilizedLTV	 nvarchar(50)  NULL ,
StabilizedLTC	 nvarchar(50)  NULL ,
SecuritizationID_F	 int  NULL ,
InvestmentTypeCD_F	 int  NULL ,
LTCFullyFunded	 float  NULL ,
LTVAtStab	 float  NULL ,
AllocationDate	 date  NULL ,
AcoreRating	 nvarchar(500)  NULL ,
OrigFundingDate	 date  NULL ,
ModifiedFrom	 varchar(10)  NULL ,
GLStatusDate	 datetime  NULL ,
CurrentLPDRDate	 datetime  NULL ,
ReferredByUsername	 nvarchar(10)  NULL ,
InitialLTCPct	 float  NULL ,
EndLTCPct	 float  NULL ,
NonRefundableProcessingFee	 decimal(28,15)  NULL ,
TermSheetExclusivePeriod	 int  NULL ,
BreakUpFee	 decimal(28,15)  NULL ,
PrincipalGuarantee	 decimal(28,15)  NULL ,
ClosingEquityRequired	 decimal(28,15)  NULL ,
ReferralChannel	 nvarchar(10)  NULL ,
HMDASw	 bit  NOT NULL ,
RecourseTypeCD_F	 nvarchar(10)  NULL ,
ApprovedByCd_F	 nvarchar(10)  NULL ,
EstimateCashOut	 decimal(28,15)  NULL ,
ChangesInConditionalApproval	 nvarchar(3)  NULL ,
ChangesInTermsAndConditions	 nvarchar(3)  NULL ,
SeniorReportManager_UserId_F	 int  NULL ,
CoLendApprovedSw	 bit  NOT NULL ,
PropertyAQR	 float  NULL ,
GuarantorAQR	 float  NULL ,
DealAQR	 float  NULL ,
OriginalLoanTerm	 nvarchar(50)  NULL ,
DebtYieldStabilization	 nvarchar(100)  NULL ,
AMTeamLeader_UserId_F	 int  NULL ,
ShardName nvarchar(max)  NULL 
)
INSERT INTO @BSDeal
(
ControlId	,
LoanNumber	,
LoanStatusCd_F	,
BrokerName_OrgId_F	,
LendorName_OrgId_F	,
LawFirm_OrgId_F	,
Office_OrgId_F	,
DealRelatedId_F	,
Competition_Org_Id_F	,
DueDiligenceProvider_OrgId_F	,
OriginalDataSource_F	,
MinimumDSCR	,
MinimumDSCRatConstant	,
MaximumLTV	,
MinimumConstantDeal	,
PrimaryBanker_UserId_F	,
SecondaryBanker_UserId_F	,
Underwriter_UserID_F	,
ServicersLoanNumber	,
DealName	,
CreditApprovedBy	,
CreditApprovedComment	,
SpreadApprovedBy	,
SpreadApprovedComment	,
Correspondent	,
CorrUW	,
CollateralType	,
DebtServiceAllocated	,
LoanPurpose	,
LoanProbability	,
ApplicationReceiveDate	,
ApplicationDate	,
LenderRightToMatch	,
ApplicationDeposit	,
LockBox	,
LockBoxComment	,
HardCashManagement	,
Recourse	,
ClosingConditions	,
EstClosingCosts	,
EarnOut	,
IndDirectorReqSw	,
NonConsolOpinionReqSw	,
OwnershipComments	,
BrokerFees	,
Cashout	,
PreliminarySponsor	,
OngoingDSCRTest	,
SpecialPricingNotes	,
HardEquityComment	,
MatrixSpreadAtClose	,
MatrixSpreadAtCloseComments	,
CommitmentExpDate	,
Comments	,
TICSw	,
MpIsLoanAssumable	,
MpIsLoanAssumableDesc	,
MpEquityParticipation	,
MpEquityParticipationDesc	,
MpAllowFutAdvances	,
MpAllowFutAdvancesDesc	,
MpMaxFutureAdvances	,
MpFutAdvancesToDate	,
MpAssumptionFeePct	,
MpAssumptionFeeAmt	,
MpAssumptionFee	,
MpAssumptionFeeDesc	,
MpParticipationPercent	,
MpParticipationPercentDesc	,
MpRightToInspectRecords	,
MpUnsecuredDebtAllowed	,
MpMaxUnsecuredDebtAmt	,
MpTradePayablesMaxAmt	,
MpTradePayablesDaysOut	,
MpPartialReleasePercent	,
MpPartialReleaseDesc	,
MpComment	,
GCM_DealCounterpartyCode	,
AuditAddDate	,
AuditAddUserId	,
AuditUpdateDate	,
AuditUpdateUserId	,
PatriotActApprovedSw	,
OwnerOrgId_F	,
BrokerFeesComment	,
ArchiveInvestorFileSw	,
ArchiveLegalBinderSw	,
ArchiveComment	,
LoanProgramCD_F	,
LenderRoleCD_F	,
TargetLoan	,
EstAppraisedCollateralValue	,
EstStressedCollateralValue	,
AcquisitionCostofCollateral	,
Matrix	,
CompetitionComments	,
HardEquityAmount	,
DealLocked	,
DealCurrencyCD_F	,
Originator	,
SourceUsesComment	,
StartLTV	,
FirstLossComment	,
Change2TicAfterCloseSw	,
SpringingLockBoxComment	,
BrokerFeesPct	,
CommitmentAmount	,
Analyst_UserId_F	,
LoanTypeCD_F	,
CreditApprovedDate	,
SpreadApprovedDate	,
DDP_ContactID_F	,
Broker_ContactID_F	,
Cocounsel_ContactID_F	,
Counsel_ContactID_F	,
Paralegal_ContactID_F	,
RequestedLoanTerm	,
RequestedAmortTerm	,
RequestedSpread	,
RequestedIndex	,
RequestedLTV	,
RequestedLTC	,
TransactionManager_Userid_F	,
HUDLoanNumber	,
ApprovalLevel	,
ExistingDebt	,
ExistingDebtLender	,
ExistingDebtAmount	,
EarnOutAmount	,
MarketEquityComments	,
BookingLocation_OrgId_F	,
PortfolioManager_Userid_F	,
PrivateSW	,
CMBSLoanStatusCd_F	,
CMBSDealGUID	,
MPFutureAdditionalDebtPermitted	,
NDCApprovedCd_F	,
NDCApprovedBy	,
NDCApprovedComment	,
NDCSecuritization	,
NDCSyndication	,
NDCApprovedDate	,
CreditApproved	,
SpreadApproved	,
SecondaryPortfolioManager_UserId_F	,
Legal_UserId_F	,
IRRBaselI	,
IRRBaselII	,
ListedCompany	,
PriceSensitive	,
Confidentiality	,
Exclusivity	,
ShareDeal	,
RequestedPaymentFreqCd_F	,
RequestedIOTerm	,
RequestedLTVasStabilzed	,
RequestedRateTypeCd_F	,
BorrowerImputedEquity	,
LoanSizer_UserId_F	,
ConstructionManager_UserId_F	,
InsuranceManager_UserId_F	,
DealIntroducedById_F	,
CoCounselCompany_OrgId_F	,
CoCounselCompany_ContactId_F	,
SecondaryLawFirm_OrgId_F	,
SecondaryCounsel_ContactID_F	,
SpecificDealTeamRequest	,
QCAnalyst_UserID_F	,
OriginatorAssociate	,
ClosingCoordinator_UserID_F	,
AssetManager_UserID_F	,
NDCSecuritizationRequiredAmt	,
NDCSyndicationRequiredAmt	,
BrokeredDeal	,
DataTapeFootNotes	,
MortgageOriginatingEntityCD_F	,
DealSourceCD_F	,
ProgramManager_UserId_F	,
SmallLoanPM_UserId_F	,
UnderwritingManager_UserId_F	,
Servicer_UserId_F	,
QALead_UserId_F	,
QAAssociate_UserId_F	,
ReportManager_UserId_F	,
BorrowerLawFirm_OrgId_F	,
BorrowerInsuranceCo_OrgId_F	,
BorrowerCounsel_ContactID_F	,
BorrowerInsAgent_ContactID_F	,
Holdback	,
HoldbackAmount	,
EstimatedCreditDate	,
Secondary_BrokerName_OrgId_F	,
Secondary_Broker_ContactID_F	,
RepeatSponsorComment	,
KickOffEmailSent	,
ExpirationStatus	,
ApplicationDepositFeePct	,
EarnOutComment	,
RealizedLossToTrust	,
NonRecoverability	,
LastSetupChangeDate	,
LastLoanContributionDate	,
LastPropContributionDate	,
AssumptionDate	,
LockBoxAtClosing	,
BrokerFeesPctTypeCd_F	,
BrokerFeesPctPaymentCd_F	,
ControlMasterID	,
Recovery	,
USTL_UserId_F	,
USQCAnalyst_UserId_F	,
Sponsor_OrgId_F	,
AvailabilityCd_F	,
AvailabilityDate	,
ForeignInvestorsMore	,
PCAccountingContact	,
PCAccountingContactNumber	,
PCServicingContact	,
PCServicingContactNumber	,
MinimumNCF	,
AssetManagementStatusCd_F	,
ConditionalCommitmentDeposit	,
CouponCurrent	,
CouponBase	,
CouponStress	,
ConstantCurrent	,
ConstantBase	,
ConstantStress	,
StressedCapRate	,
StressedConstant	,
BankNumberCD_F	,
OCCLoanPurposeCD_F	,
GeneralLedgerCD_F	,
CustomerId_F	,
NextAnnualReviewDate	,
Exempt	,
First12MonthsRevenue	,
LastAnnualReviewDate	,
BusinessLineManager_UserId_F	,
WDP	,
WDPx	,
AdditionalCollateral	,
InvestmentLeverage	,
BorrowerSecondaryLawFirm_OrgId_F	,
BorrowerSecondaryCounsel_ContactId_F	,
PROOwnerInvestor_OrgId_F	,
PROSponsorDeveloper_OrgId_F	,
PROBrokerDebt_OrgId_F	,
PROBrokerEquity_OrgId_F	,
PROBrokerLeasing_OrgId_F	,
PROLender_OrgId_F	,
PRODueDiligence_OrgId_F	,
PROAppraiser_OrgId_F	,
PROLawFirm_OrgId_F	,
SecondaryOfficeCd_F	,
LoanPurposeComments	,
AdditionalCollateralTypeCd_F	,
DealLevelMarketComments	,
UnderwritingGuidelineDeviationComments	,
AdministrationVarianceComments	,
Active	,
StabilizedDebtYield	,
--WorkflowTemplateTypeCd_F	,
ExistingDebtMaturityDate	,
Market	,
MarketTotalSF	,
MarketVacancy	,
PurchasePrice	,
TILC	,
Capex	,
ClosingCosts	,
ROA	,
LPDRCD_F	,
SPDRCD_F	,
AssetManagementStatusColorCd_F	,
CommunityLendingDevelopmentPurposeCd_F	,
AlternateDealNumber	,
MortgageLoanOriginator_OrgId_F	,
MortgageLoanSeller_OrgId_F	,
SEREFAllocation	,
StarFinAllocation	,
SEREFStarFinIRR	,
ServicerWillSpreadFinancials	,
FirmProductionDate	,
CreditRiskApprovalDate	,
CreditRiskDeniedDate	,
ReferralFee	,
FANumber	,
LegalFeeAmount	,
QuotedDate	,
PrelimPricingBucket	,
PrelimPricingBucketComments	,
ReferralIDNumber	,
CopyDealOptionCd_F	,
CurrentLPDRCD_F	,
GPDRCD_F	,
ProbabilityCD_F	,
CapitalMarketProductSW	,
MortgageBroker_OrgId_F	,
DealSponsor_OrgId_F	,
MortgageBroker_ContactId_F	,
isMUV	,
ClientIdentifier	,
DueDiligencePeriod	,
PrincipalNetWorthGreaterThanLoan	,
PrincipalLiquidityGreaterThanDebtService	,
PrincipalsFreeOfBankruptcyForeclosureDIL	,
PrincipalsFreeOfLitigation	,
WithholdingTaxExemptionRequired	,
DealSourceFirm	,
DealSourceContact	,
CMBSControlMasterID	,
TeamLeader_UserID_F	,
SecondaryCounsel_Contact2ID_F	,
SecondaryCounsel_Contact3ID_F	,
BorrowerCounsel_Contact2ID_F	,
BorrowerCounsel_Contact3ID_F	,
SecondaryBorrowerFirm_OrgId_F	,
SecondaryBorrowerFirm_ContactID_F	,
MasterServicer_OrgId_F	,
DealBorrower_OrgId_F	,
TertiaryLawFirm_OrgId_F	,
DealBorrowerContact1_ContactId_F	,
DealBorrowerContact2_ContactId_F	,
DealBorrowerContact3_ContactId_F	,
DealBorrowerContact4_ContactId_F	,
DealBorrowerContact5_ContactId_F	,
DealBorrowerContact6_ContactId_F	,
TertiaryCounsel_ContactId_F	,
TertiaryCoCounsel_ContactId_F	,
UnleveredMultipleNetAtOrigination	,
LeveredIRRGrossAtOrigination	,
LeveredIRRNetAtOrigination	,
LeveredProfitGrossAtOrigination	,
LeveredProfitNetAtOrigination	,
LeveredMultipleGrossAtOrigination	,
LeveredMultipleNetAtOrigination	,
InitialDebtYield	,
ClosedDealLockSW	,
StrategyTypeCD_F	,
PNAStatus	,
LoanDefaultDate	,
DefaultLetterSentDate	,
ForclosureFiledExpectedDate	,
LastPatriotActChecked	,
FreeofJrSubDebt	,
AnticipatedPayoffComment	,
AnticipatedActualCofODate	,
OrganizationDealStatusID_F	,
RiskMatrixCd_F	,
DispositionMethodCd_F	,
PriorOutlookColorCd_F	,
AssetManagementLTVorLTC	,
BusinessPlanCd_F	,
AssetMgmtMarketCd_F	,
ReviewRotationCd_F	,
AssetManagementRecourseCd_F	,
PipelineReportReview	,
DACABank_OrgId_F	,
CMABank_OrgId_F	,
LenderCashMgmtSuspended	,
LenderCashMgmtSuspendedUntilDate	,
TriggersEventOfDefault	,
TriggersDSCROperator	,
TriggersDSCRValue	,
TriggersDebtYieldOperator	,
TriggersDebtYieldValue	,
TriggersOtherCondition1	,
CureEventOfDefault	,
CureDSCROperator	,
CureDSCRValue	,
CureDSCRNumOfConsecutivePeriods	,
CureDSCRDurationCd_F	,
CureDebtYieldOperator	,
CureDebtYieldValue	,
CureDebtYieldNumOfConsecutivePeriods	,
CureDebtYieldDurationCd_F	,
CureOtherCondition1	,
CureOtherCondition2	,
CureOtherCondition3	,
TriggersOtherCondition2	,
TriggersOtherCondition3	,
DealBorrower2_OrgId_F	,
DealBorrower3_OrgId_F	,
DealBorrower4_OrgId_F	,
DealBorrower5_OrgId_F	,
DealBorrower6_OrgId_F	,
REITPropertyTypeCd_F	,
REITSectorTypeCd_F	,
UWLTCatOrigination	,
UWLTVatOrigination	,
DSCRatOrigination	,
DebtYieldAsIs	,
UnleveredIRRGross	,
UnleveredProfitGross	,
UnleveredMultipleGross	,
LeveredIRRGross	,
LeveredProfitGross	,
LeveredMultipleGross	,
StabilizedLTV	,
StabilizedLTC	,
SecuritizationID_F	,
InvestmentTypeCD_F	,
LTCFullyFunded	,
LTVAtStab	,
AllocationDate	,
AcoreRating	,
OrigFundingDate	,
ModifiedFrom	,
GLStatusDate	,
CurrentLPDRDate	,
ReferredByUsername	,
InitialLTCPct	,
EndLTCPct	,
NonRefundableProcessingFee	,
TermSheetExclusivePeriod	,
BreakUpFee	,
PrincipalGuarantee	,
ClosingEquityRequired	,
ReferralChannel	,
HMDASw	,
RecourseTypeCD_F	,
ApprovedByCd_F	,
EstimateCashOut	,
ChangesInConditionalApproval	,
ChangesInTermsAndConditions	,
SeniorReportManager_UserId_F	,
CoLendApprovedSw	,
PropertyAQR	,
GuarantorAQR	,
DealAQR	,
OriginalLoanTerm	,
DebtYieldStabilization	,
AMTeamLeader_UserId_F	,
ShardName

)
EXEC sp_execute_remote @data_source_name  = N'RemoteReferenceData', @stmt = @query

--===================================



Truncate table [DW].[L_UwDealBI]

INSERT INTO [DW].[L_UwDealBI]
        (ControlId	,
LoanNumber	,
LoanStatusCd_F	,
BrokerName_OrgId_F	,
LendorName_OrgId_F	,
LawFirm_OrgId_F	,
Office_OrgId_F	,
DealRelatedId_F	,
Competition_Org_Id_F	,
DueDiligenceProvider_OrgId_F	,
OriginalDataSource_F	,
MinimumDSCR	,
MinimumDSCRatConstant	,
MaximumLTV	,
MinimumConstantDeal	,
PrimaryBanker_UserId_F	,
SecondaryBanker_UserId_F	,
Underwriter_UserID_F	,
ServicersLoanNumber	,
DealName	,
CreditApprovedBy	,
CreditApprovedComment	,
SpreadApprovedBy	,
SpreadApprovedComment	,
Correspondent	,
CorrUW	,
CollateralType	,
DebtServiceAllocated	,
LoanPurpose	,
LoanProbability	,
ApplicationReceiveDate	,
ApplicationDate	,
LenderRightToMatch	,
ApplicationDeposit	,
LockBox	,
LockBoxComment	,
HardCashManagement	,
Recourse	,
ClosingConditions	,
EstClosingCosts	,
EarnOut	,
IndDirectorReqSw	,
NonConsolOpinionReqSw	,
OwnershipComments	,
BrokerFees	,
Cashout	,
PreliminarySponsor	,
OngoingDSCRTest	,
SpecialPricingNotes	,
HardEquityComment	,
MatrixSpreadAtClose	,
MatrixSpreadAtCloseComments	,
CommitmentExpDate	,
Comments	,
TICSw	,
MpIsLoanAssumable	,
MpIsLoanAssumableDesc	,
MpEquityParticipation	,
MpEquityParticipationDesc	,
MpAllowFutAdvances	,
MpAllowFutAdvancesDesc	,
MpMaxFutureAdvances	,
MpFutAdvancesToDate	,
MpAssumptionFeePct	,
MpAssumptionFeeAmt	,
MpAssumptionFee	,
MpAssumptionFeeDesc	,
MpParticipationPercent	,
MpParticipationPercentDesc	,
MpRightToInspectRecords	,
MpUnsecuredDebtAllowed	,
MpMaxUnsecuredDebtAmt	,
MpTradePayablesMaxAmt	,
MpTradePayablesDaysOut	,
MpPartialReleasePercent	,
MpPartialReleaseDesc	,
MpComment	,
GCM_DealCounterpartyCode	,
AuditAddDate	,
AuditAddUserId	,
AuditUpdateDate	,
AuditUpdateUserId	,
PatriotActApprovedSw	,
OwnerOrgId_F	,
BrokerFeesComment	,
ArchiveInvestorFileSw	,
ArchiveLegalBinderSw	,
ArchiveComment	,
LoanProgramCD_F	,
LenderRoleCD_F	,
TargetLoan	,
EstAppraisedCollateralValue	,
EstStressedCollateralValue	,
AcquisitionCostofCollateral	,
Matrix	,
CompetitionComments	,
HardEquityAmount	,
DealLocked	,
DealCurrencyCD_F	,
Originator	,
SourceUsesComment	,
StartLTV	,
FirstLossComment	,
Change2TicAfterCloseSw	,
SpringingLockBoxComment	,
BrokerFeesPct	,
CommitmentAmount	,
Analyst_UserId_F	,
LoanTypeCD_F	,
CreditApprovedDate	,
SpreadApprovedDate	,
DDP_ContactID_F	,
Broker_ContactID_F	,
Cocounsel_ContactID_F	,
Counsel_ContactID_F	,
Paralegal_ContactID_F	,
RequestedLoanTerm	,
RequestedAmortTerm	,
RequestedSpread	,
RequestedIndex	,
RequestedLTV	,
RequestedLTC	,
TransactionManager_Userid_F	,
HUDLoanNumber	,
ApprovalLevel	,
ExistingDebt	,
ExistingDebtLender	,
ExistingDebtAmount	,
EarnOutAmount	,
MarketEquityComments	,
BookingLocation_OrgId_F	,
PortfolioManager_Userid_F	,
PrivateSW	,
CMBSLoanStatusCd_F	,
CMBSDealGUID	,
MPFutureAdditionalDebtPermitted	,
NDCApprovedCd_F	,
NDCApprovedBy	,
NDCApprovedComment	,
NDCSecuritization	,
NDCSyndication	,
NDCApprovedDate	,
CreditApproved	,
SpreadApproved	,
SecondaryPortfolioManager_UserId_F	,
Legal_UserId_F	,
IRRBaselI	,
IRRBaselII	,
ListedCompany	,
PriceSensitive	,
Confidentiality	,
Exclusivity	,
ShareDeal	,
RequestedPaymentFreqCd_F	,
RequestedIOTerm	,
RequestedLTVasStabilzed	,
RequestedRateTypeCd_F	,
BorrowerImputedEquity	,
LoanSizer_UserId_F	,
ConstructionManager_UserId_F	,
InsuranceManager_UserId_F	,
DealIntroducedById_F	,
CoCounselCompany_OrgId_F	,
CoCounselCompany_ContactId_F	,
SecondaryLawFirm_OrgId_F	,
SecondaryCounsel_ContactID_F	,
SpecificDealTeamRequest	,
QCAnalyst_UserID_F	,
OriginatorAssociate	,
ClosingCoordinator_UserID_F	,
AssetManager_UserID_F	,
NDCSecuritizationRequiredAmt	,
NDCSyndicationRequiredAmt	,
BrokeredDeal	,
DataTapeFootNotes	,
MortgageOriginatingEntityCD_F	,
DealSourceCD_F	,
ProgramManager_UserId_F	,
SmallLoanPM_UserId_F	,
UnderwritingManager_UserId_F	,
Servicer_UserId_F	,
QALead_UserId_F	,
QAAssociate_UserId_F	,
ReportManager_UserId_F	,
BorrowerLawFirm_OrgId_F	,
BorrowerInsuranceCo_OrgId_F	,
BorrowerCounsel_ContactID_F	,
BorrowerInsAgent_ContactID_F	,
Holdback	,
HoldbackAmount	,
EstimatedCreditDate	,
Secondary_BrokerName_OrgId_F	,
Secondary_Broker_ContactID_F	,
RepeatSponsorComment	,
KickOffEmailSent	,
ExpirationStatus	,
ApplicationDepositFeePct	,
EarnOutComment	,
RealizedLossToTrust	,
NonRecoverability	,
LastSetupChangeDate	,
LastLoanContributionDate	,
LastPropContributionDate	,
AssumptionDate	,
LockBoxAtClosing	,
BrokerFeesPctTypeCd_F	,
BrokerFeesPctPaymentCd_F	,
ControlMasterID	,
Recovery	,
USTL_UserId_F	,
USQCAnalyst_UserId_F	,
Sponsor_OrgId_F	,
AvailabilityCd_F	,
AvailabilityDate	,
ForeignInvestorsMore	,
PCAccountingContact	,
PCAccountingContactNumber	,
PCServicingContact	,
PCServicingContactNumber	,
MinimumNCF	,
AssetManagementStatusCd_F	,
ConditionalCommitmentDeposit	,
CouponCurrent	,
CouponBase	,
CouponStress	,
ConstantCurrent	,
ConstantBase	,
ConstantStress	,
StressedCapRate	,
StressedConstant	,
BankNumberCD_F	,
OCCLoanPurposeCD_F	,
GeneralLedgerCD_F	,
CustomerId_F	,
NextAnnualReviewDate	,
Exempt	,
First12MonthsRevenue	,
LastAnnualReviewDate	,
BusinessLineManager_UserId_F	,
WDP	,
WDPx	,
AdditionalCollateral	,
InvestmentLeverage	,
BorrowerSecondaryLawFirm_OrgId_F	,
BorrowerSecondaryCounsel_ContactId_F	,
PROOwnerInvestor_OrgId_F	,
PROSponsorDeveloper_OrgId_F	,
PROBrokerDebt_OrgId_F	,
PROBrokerEquity_OrgId_F	,
PROBrokerLeasing_OrgId_F	,
PROLender_OrgId_F	,
PRODueDiligence_OrgId_F	,
PROAppraiser_OrgId_F	,
PROLawFirm_OrgId_F	,
SecondaryOfficeCd_F	,
LoanPurposeComments	,
AdditionalCollateralTypeCd_F	,
DealLevelMarketComments	,
UnderwritingGuidelineDeviationComments	,
AdministrationVarianceComments	,
Active	,
StabilizedDebtYield	,
WorkflowTemplateTypeCd_F	,
ExistingDebtMaturityDate	,
Market	,
MarketTotalSF	,
MarketVacancy	,
PurchasePrice	,
TILC	,
Capex	,
ClosingCosts	,
ROA	,
LPDRCD_F	,
SPDRCD_F	,
AssetManagementStatusColorCd_F	,
CommunityLendingDevelopmentPurposeCd_F	,
AlternateDealNumber	,
MortgageLoanOriginator_OrgId_F	,
MortgageLoanSeller_OrgId_F	,
SEREFAllocation	,
StarFinAllocation	,
SEREFStarFinIRR	,
ServicerWillSpreadFinancials	,
FirmProductionDate	,
CreditRiskApprovalDate	,
CreditRiskDeniedDate	,
ReferralFee	,
FANumber	,
LegalFeeAmount	,
QuotedDate	,
PrelimPricingBucket	,
PrelimPricingBucketComments	,
ReferralIDNumber	,
CopyDealOptionCd_F	,
CurrentLPDRCD_F	,
GPDRCD_F	,
ProbabilityCD_F	,
CapitalMarketProductSW	,
MortgageBroker_OrgId_F	,
DealSponsor_OrgId_F	,
MortgageBroker_ContactId_F	,
isMUV	,
ClientIdentifier	,
DueDiligencePeriod	,
PrincipalNetWorthGreaterThanLoan	,
PrincipalLiquidityGreaterThanDebtService	,
PrincipalsFreeOfBankruptcyForeclosureDIL	,
PrincipalsFreeOfLitigation	,
WithholdingTaxExemptionRequired	,
DealSourceFirm	,
DealSourceContact	,
CMBSControlMasterID	,
TeamLeader_UserID_F	,
SecondaryCounsel_Contact2ID_F	,
SecondaryCounsel_Contact3ID_F	,
BorrowerCounsel_Contact2ID_F	,
BorrowerCounsel_Contact3ID_F	,
SecondaryBorrowerFirm_OrgId_F	,
SecondaryBorrowerFirm_ContactID_F	,
MasterServicer_OrgId_F	,
DealBorrower_OrgId_F	,
TertiaryLawFirm_OrgId_F	,
DealBorrowerContact1_ContactId_F	,
DealBorrowerContact2_ContactId_F	,
DealBorrowerContact3_ContactId_F	,
DealBorrowerContact4_ContactId_F	,
DealBorrowerContact5_ContactId_F	,
DealBorrowerContact6_ContactId_F	,
TertiaryCounsel_ContactId_F	,
TertiaryCoCounsel_ContactId_F	,
UnleveredMultipleNetAtOrigination	,
LeveredIRRGrossAtOrigination	,
LeveredIRRNetAtOrigination	,
LeveredProfitGrossAtOrigination	,
LeveredProfitNetAtOrigination	,
LeveredMultipleGrossAtOrigination	,
LeveredMultipleNetAtOrigination	,
InitialDebtYield	,
ClosedDealLockSW	,
StrategyTypeCD_F	,
PNAStatus	,
LoanDefaultDate	,
DefaultLetterSentDate	,
ForclosureFiledExpectedDate	,
LastPatriotActChecked	,
FreeofJrSubDebt	,
AnticipatedPayoffComment	,
AnticipatedActualCofODate	,
OrganizationDealStatusID_F	,
RiskMatrixCd_F	,
DispositionMethodCd_F	,
PriorOutlookColorCd_F	,
AssetManagementLTVorLTC	,
BusinessPlanCd_F	,
AssetMgmtMarketCd_F	,
ReviewRotationCd_F	,
AssetManagementRecourseCd_F	,
PipelineReportReview	,
DACABank_OrgId_F	,
CMABank_OrgId_F	,
LenderCashMgmtSuspended	,
LenderCashMgmtSuspendedUntilDate	,
TriggersEventOfDefault	,
TriggersDSCROperator	,
TriggersDSCRValue	,
TriggersDebtYieldOperator	,
TriggersDebtYieldValue	,
TriggersOtherCondition1	,
CureEventOfDefault	,
CureDSCROperator	,
CureDSCRValue	,
CureDSCRNumOfConsecutivePeriods	,
CureDSCRDurationCd_F	,
CureDebtYieldOperator	,
CureDebtYieldValue	,
CureDebtYieldNumOfConsecutivePeriods	,
CureDebtYieldDurationCd_F	,
CureOtherCondition1	,
CureOtherCondition2	,
CureOtherCondition3	,
TriggersOtherCondition2	,
TriggersOtherCondition3	,
DealBorrower2_OrgId_F	,
DealBorrower3_OrgId_F	,
DealBorrower4_OrgId_F	,
DealBorrower5_OrgId_F	,
DealBorrower6_OrgId_F	,
REITPropertyTypeCd_F	,
REITSectorTypeCd_F	,
UWLTCatOrigination	,
UWLTVatOrigination	,
DSCRatOrigination	,
DebtYieldAsIs	,
UnleveredIRRGross	,
UnleveredProfitGross	,
UnleveredMultipleGross	,
LeveredIRRGross	,
LeveredProfitGross	,
LeveredMultipleGross	,
StabilizedLTV	,
StabilizedLTC	,
SecuritizationID_F	,
InvestmentTypeCD_F	,
LTCFullyFunded	,
LTVAtStab	,
AllocationDate	,
AcoreRating	,
OrigFundingDate	,
ModifiedFrom	,
GLStatusDate	,
CurrentLPDRDate	,
ReferredByUsername	,
InitialLTCPct	,
EndLTCPct	,
NonRefundableProcessingFee	,
TermSheetExclusivePeriod	,
BreakUpFee	,
PrincipalGuarantee	,
ClosingEquityRequired	,
ReferralChannel	,
HMDASw	,
RecourseTypeCD_F	,
ApprovedByCd_F	,
EstimateCashOut	,
ChangesInConditionalApproval	,
ChangesInTermsAndConditions	,
SeniorReportManager_UserId_F	,
CoLendApprovedSw	,
PropertyAQR	,
GuarantorAQR	,
DealAQR	,
OriginalLoanTerm	,
DebtYieldStabilization	,
AMTeamLeader_UserId_F	)

Select
		ControlId	,
LoanNumber	,
LoanStatusCd_F	,
BrokerName_OrgId_F	,
LendorName_OrgId_F	,
LawFirm_OrgId_F	,
Office_OrgId_F	,
DealRelatedId_F	,
Competition_Org_Id_F	,
DueDiligenceProvider_OrgId_F	,
OriginalDataSource_F	,
MinimumDSCR	,
MinimumDSCRatConstant	,
MaximumLTV	,
MinimumConstantDeal	,
PrimaryBanker_UserId_F	,
SecondaryBanker_UserId_F	,
Underwriter_UserID_F	,
ServicersLoanNumber	,
DealName	,
CreditApprovedBy	,
CreditApprovedComment	,
SpreadApprovedBy	,
SpreadApprovedComment	,
Correspondent	,
CorrUW	,
CollateralType	,
DebtServiceAllocated	,
LoanPurpose	,
LoanProbability	,
ApplicationReceiveDate	,
ApplicationDate	,
LenderRightToMatch	,
ApplicationDeposit	,
LockBox	,
LockBoxComment	,
HardCashManagement	,
Recourse	,
ClosingConditions	,
EstClosingCosts	,
EarnOut	,
IndDirectorReqSw	,
NonConsolOpinionReqSw	,
OwnershipComments	,
BrokerFees	,
Cashout	,
PreliminarySponsor	,
OngoingDSCRTest	,
SpecialPricingNotes	,
HardEquityComment	,
MatrixSpreadAtClose	,
MatrixSpreadAtCloseComments	,
CommitmentExpDate	,
Comments	,
TICSw	,
MpIsLoanAssumable	,
MpIsLoanAssumableDesc	,
MpEquityParticipation	,
MpEquityParticipationDesc	,
MpAllowFutAdvances	,
MpAllowFutAdvancesDesc	,
MpMaxFutureAdvances	,
MpFutAdvancesToDate	,
MpAssumptionFeePct	,
MpAssumptionFeeAmt	,
MpAssumptionFee	,
MpAssumptionFeeDesc	,
MpParticipationPercent	,
MpParticipationPercentDesc	,
MpRightToInspectRecords	,
MpUnsecuredDebtAllowed	,
MpMaxUnsecuredDebtAmt	,
MpTradePayablesMaxAmt	,
MpTradePayablesDaysOut	,
MpPartialReleasePercent	,
MpPartialReleaseDesc	,
MpComment	,
GCM_DealCounterpartyCode	,
AuditAddDate	,
AuditAddUserId	,
AuditUpdateDate	,
AuditUpdateUserId	,
PatriotActApprovedSw	,
OwnerOrgId_F	,
BrokerFeesComment	,
ArchiveInvestorFileSw	,
ArchiveLegalBinderSw	,
ArchiveComment	,
LoanProgramCD_F	,
LenderRoleCD_F	,
TargetLoan	,
EstAppraisedCollateralValue	,
EstStressedCollateralValue	,
AcquisitionCostofCollateral	,
Matrix	,
CompetitionComments	,
HardEquityAmount	,
DealLocked	,
DealCurrencyCD_F	,
Originator	,
SourceUsesComment	,
StartLTV	,
FirstLossComment	,
Change2TicAfterCloseSw	,
SpringingLockBoxComment	,
BrokerFeesPct	,
CommitmentAmount	,
Analyst_UserId_F	,
LoanTypeCD_F	,
CreditApprovedDate	,
SpreadApprovedDate	,
DDP_ContactID_F	,
Broker_ContactID_F	,
Cocounsel_ContactID_F	,
Counsel_ContactID_F	,
Paralegal_ContactID_F	,
RequestedLoanTerm	,
RequestedAmortTerm	,
RequestedSpread	,
RequestedIndex	,
RequestedLTV	,
RequestedLTC	,
TransactionManager_Userid_F	,
HUDLoanNumber	,
ApprovalLevel	,
ExistingDebt	,
ExistingDebtLender	,
ExistingDebtAmount	,
EarnOutAmount	,
MarketEquityComments	,
BookingLocation_OrgId_F	,
PortfolioManager_Userid_F	,
PrivateSW	,
CMBSLoanStatusCd_F	,
CMBSDealGUID	,
MPFutureAdditionalDebtPermitted	,
NDCApprovedCd_F	,
NDCApprovedBy	,
NDCApprovedComment	,
NDCSecuritization	,
NDCSyndication	,
NDCApprovedDate	,
CreditApproved	,
SpreadApproved	,
SecondaryPortfolioManager_UserId_F	,
Legal_UserId_F	,
IRRBaselI	,
IRRBaselII	,
ListedCompany	,
PriceSensitive	,
Confidentiality	,
Exclusivity	,
ShareDeal	,
RequestedPaymentFreqCd_F	,
RequestedIOTerm	,
RequestedLTVasStabilzed	,
RequestedRateTypeCd_F	,
BorrowerImputedEquity	,
LoanSizer_UserId_F	,
ConstructionManager_UserId_F	,
InsuranceManager_UserId_F	,
DealIntroducedById_F	,
CoCounselCompany_OrgId_F	,
CoCounselCompany_ContactId_F	,
SecondaryLawFirm_OrgId_F	,
SecondaryCounsel_ContactID_F	,
SpecificDealTeamRequest	,
QCAnalyst_UserID_F	,
OriginatorAssociate	,
ClosingCoordinator_UserID_F	,
AssetManager_UserID_F	,
NDCSecuritizationRequiredAmt	,
NDCSyndicationRequiredAmt	,
BrokeredDeal	,
DataTapeFootNotes	,
MortgageOriginatingEntityCD_F	,
DealSourceCD_F	,
ProgramManager_UserId_F	,
SmallLoanPM_UserId_F	,
UnderwritingManager_UserId_F	,
Servicer_UserId_F	,
QALead_UserId_F	,
QAAssociate_UserId_F	,
ReportManager_UserId_F	,
BorrowerLawFirm_OrgId_F	,
BorrowerInsuranceCo_OrgId_F	,
BorrowerCounsel_ContactID_F	,
BorrowerInsAgent_ContactID_F	,
Holdback	,
HoldbackAmount	,
EstimatedCreditDate	,
Secondary_BrokerName_OrgId_F	,
Secondary_Broker_ContactID_F	,
RepeatSponsorComment	,
KickOffEmailSent	,
ExpirationStatus	,
ApplicationDepositFeePct	,
EarnOutComment	,
RealizedLossToTrust	,
NonRecoverability	,
LastSetupChangeDate	,
LastLoanContributionDate	,
LastPropContributionDate	,
AssumptionDate	,
LockBoxAtClosing	,
BrokerFeesPctTypeCd_F	,
BrokerFeesPctPaymentCd_F	,
ControlMasterID	,
Recovery	,
USTL_UserId_F	,
USQCAnalyst_UserId_F	,
Sponsor_OrgId_F	,
AvailabilityCd_F	,
AvailabilityDate	,
ForeignInvestorsMore	,
PCAccountingContact	,
PCAccountingContactNumber	,
PCServicingContact	,
PCServicingContactNumber	,
MinimumNCF	,
AssetManagementStatusCd_F	,
ConditionalCommitmentDeposit	,
CouponCurrent	,
CouponBase	,
CouponStress	,
ConstantCurrent	,
ConstantBase	,
ConstantStress	,
StressedCapRate	,
StressedConstant	,
BankNumberCD_F	,
OCCLoanPurposeCD_F	,
GeneralLedgerCD_F	,
CustomerId_F	,
NextAnnualReviewDate	,
Exempt	,
First12MonthsRevenue	,
LastAnnualReviewDate	,
BusinessLineManager_UserId_F	,
WDP	,
WDPx	,
AdditionalCollateral	,
InvestmentLeverage	,
BorrowerSecondaryLawFirm_OrgId_F	,
BorrowerSecondaryCounsel_ContactId_F	,
PROOwnerInvestor_OrgId_F	,
PROSponsorDeveloper_OrgId_F	,
PROBrokerDebt_OrgId_F	,
PROBrokerEquity_OrgId_F	,
PROBrokerLeasing_OrgId_F	,
PROLender_OrgId_F	,
PRODueDiligence_OrgId_F	,
PROAppraiser_OrgId_F	,
PROLawFirm_OrgId_F	,
SecondaryOfficeCd_F	,
LoanPurposeComments	,
AdditionalCollateralTypeCd_F	,
DealLevelMarketComments	,
UnderwritingGuidelineDeviationComments	,
AdministrationVarianceComments	,
Active	,
StabilizedDebtYield	,
null WorkflowTemplateTypeCd_F	, --need to checck
ExistingDebtMaturityDate	,
Market	,
MarketTotalSF	,
MarketVacancy	,
PurchasePrice	,
TILC	,
Capex	,
ClosingCosts	,
ROA	,
LPDRCD_F	,
SPDRCD_F	,
AssetManagementStatusColorCd_F	,
CommunityLendingDevelopmentPurposeCd_F	,
AlternateDealNumber	,
MortgageLoanOriginator_OrgId_F	,
MortgageLoanSeller_OrgId_F	,
SEREFAllocation	,
StarFinAllocation	,
SEREFStarFinIRR	,
ServicerWillSpreadFinancials	,
FirmProductionDate	,
CreditRiskApprovalDate	,
CreditRiskDeniedDate	,
ReferralFee	,
FANumber	,
LegalFeeAmount	,
QuotedDate	,
PrelimPricingBucket	,
PrelimPricingBucketComments	,
ReferralIDNumber	,
CopyDealOptionCd_F	,
CurrentLPDRCD_F	,
GPDRCD_F	,
ProbabilityCD_F	,
CapitalMarketProductSW	,
MortgageBroker_OrgId_F	,
DealSponsor_OrgId_F	,
MortgageBroker_ContactId_F	,
isMUV	,
ClientIdentifier	,
DueDiligencePeriod	,
PrincipalNetWorthGreaterThanLoan	,
PrincipalLiquidityGreaterThanDebtService	,
PrincipalsFreeOfBankruptcyForeclosureDIL	,
PrincipalsFreeOfLitigation	,
WithholdingTaxExemptionRequired	,
DealSourceFirm	,
DealSourceContact	,
CMBSControlMasterID	,
TeamLeader_UserID_F	,
SecondaryCounsel_Contact2ID_F	,
SecondaryCounsel_Contact3ID_F	,
BorrowerCounsel_Contact2ID_F	,
BorrowerCounsel_Contact3ID_F	,
SecondaryBorrowerFirm_OrgId_F	,
SecondaryBorrowerFirm_ContactID_F	,
MasterServicer_OrgId_F	,
DealBorrower_OrgId_F	,
TertiaryLawFirm_OrgId_F	,
DealBorrowerContact1_ContactId_F	,
DealBorrowerContact2_ContactId_F	,
DealBorrowerContact3_ContactId_F	,
DealBorrowerContact4_ContactId_F	,
DealBorrowerContact5_ContactId_F	,
DealBorrowerContact6_ContactId_F	,
TertiaryCounsel_ContactId_F	,
TertiaryCoCounsel_ContactId_F	,
UnleveredMultipleNetAtOrigination	,
LeveredIRRGrossAtOrigination	,
LeveredIRRNetAtOrigination	,
LeveredProfitGrossAtOrigination	,
LeveredProfitNetAtOrigination	,
LeveredMultipleGrossAtOrigination	,
LeveredMultipleNetAtOrigination	,
InitialDebtYield	,
ClosedDealLockSW	,
StrategyTypeCD_F	,
PNAStatus	,
LoanDefaultDate	,
DefaultLetterSentDate	,
ForclosureFiledExpectedDate	,
LastPatriotActChecked	,
FreeofJrSubDebt	,
AnticipatedPayoffComment	,
AnticipatedActualCofODate	,
OrganizationDealStatusID_F	,
RiskMatrixCd_F	,
DispositionMethodCd_F	,
PriorOutlookColorCd_F	,
AssetManagementLTVorLTC	,
BusinessPlanCd_F	,
AssetMgmtMarketCd_F	,
ReviewRotationCd_F	,
AssetManagementRecourseCd_F	,
PipelineReportReview	,
DACABank_OrgId_F	,
CMABank_OrgId_F	,
LenderCashMgmtSuspended	,
LenderCashMgmtSuspendedUntilDate	,
TriggersEventOfDefault	,
TriggersDSCROperator	,
TriggersDSCRValue	,
TriggersDebtYieldOperator	,
TriggersDebtYieldValue	,
TriggersOtherCondition1	,
CureEventOfDefault	,
CureDSCROperator	,
CureDSCRValue	,
CureDSCRNumOfConsecutivePeriods	,
CureDSCRDurationCd_F	,
CureDebtYieldOperator	,
CureDebtYieldValue	,
CureDebtYieldNumOfConsecutivePeriods	,
CureDebtYieldDurationCd_F	,
CureOtherCondition1	,
CureOtherCondition2	,
CureOtherCondition3	,
TriggersOtherCondition2	,
TriggersOtherCondition3	,
DealBorrower2_OrgId_F	,
DealBorrower3_OrgId_F	,
DealBorrower4_OrgId_F	,
DealBorrower5_OrgId_F	,
DealBorrower6_OrgId_F	,
REITPropertyTypeCd_F	,
REITSectorTypeCd_F	,
UWLTCatOrigination	,
UWLTVatOrigination	,
DSCRatOrigination	,
DebtYieldAsIs	,
UnleveredIRRGross	,
UnleveredProfitGross	,
UnleveredMultipleGross	,
LeveredIRRGross	,
LeveredProfitGross	,
LeveredMultipleGross	,
StabilizedLTV	,
StabilizedLTC	,
SecuritizationID_F	,
InvestmentTypeCD_F	,
LTCFullyFunded	,
LTVAtStab	,
AllocationDate	,
AcoreRating	,
OrigFundingDate	,
ModifiedFrom	,
GLStatusDate	,
CurrentLPDRDate	,
ReferredByUsername	,
InitialLTCPct	,
EndLTCPct	,
NonRefundableProcessingFee	,
TermSheetExclusivePeriod	,
BreakUpFee	,
PrincipalGuarantee	,
ClosingEquityRequired	,
ReferralChannel	,
HMDASw	,
RecourseTypeCD_F	,
ApprovedByCd_F	,
EstimateCashOut	,
ChangesInConditionalApproval	,
ChangesInTermsAndConditions	,
SeniorReportManager_UserId_F	,
CoLendApprovedSw	,
PropertyAQR	,
GuarantorAQR	,
DealAQR	,
OriginalLoanTerm	,
DebtYieldStabilization	,
AMTeamLeader_UserId_F	
From @BSDeal d

--WHERE (d.AuditAddDate > @LastBatchStart 
--				and d.AuditAddDate < @CurrentBatchStart) 
--				OR 
--				(d.AuditUpdateDate > @LastBatchStart 
--				and d.AuditUpdateDate < @CurrentBatchStart)
				


SET @RowCount = @@ROWCOUNT
Print(char(9) +'usp_ImportUwDeal - ROWCOUNT = '+cast(@RowCount  as varchar(100)));





UPDATE [DW].BatchDetail
SET
LandingEndTime = GETDATE(),
LandingRecordCount = @RowCount
WHERE BatchDetailId = @id





END


