


CREATE PROCEDURE [DW].[usp_InsertTREACRNoteMatrixBI] 
@DealID	nvarchar(256)	,
@DealGroupID	nvarchar(256)	,
@NoteID	nvarchar(256)	,
@Pri	int	,
@DealName	nvarchar(256)	,
@NoteName	nvarchar(256)	,
@LoanStatus	nvarchar(256)	,
@Client	nvarchar(256)	,
@Fund	nvarchar(256)	,
@AssetManager	nvarchar(256)	,
@Banker	nvarchar(256)	,
@Credit	nvarchar(256)	,
@Pool	nvarchar(256)	,
@FinancingSource	nvarchar(256)	,
@DebtType	nvarchar(256)	,
@CapStack	nvarchar(256)	,
@BillingNote	nvarchar(256)	,
@Commitment	decimal(28, 15)	,
@Spread	decimal(28, 15)	,

@IndexforStub decimal(28, 15),

@Floor	decimal(28, 15)	,
@AllInRate  decimal(28, 15)	,

@Type	nvarchar(256)	,
@InitialFunding	date	,
@InitialMaturity	date	,

--@ExtendedMaturity	date	,
@ExtendedMaturity1 date,
@ExtendedMaturity2 date,
@ExtendedMaturity3 date,
@ExtendedMaturity4 date,
@FullyExtendedMaturity date,
@CurrentMaturityDate date,
@CurrentMaturity  [nvarchar](256),

@PaidOffSold	date	,
@CAMRA	nvarchar(256)	,
@Servicer	nvarchar(256)	,
@ServicerID	nvarchar(256),
@PaydownPayoffConvention int ,
@PaymentDate int ,
@WholeLoanSpread [decimal](28, 15) ,
@ExtensionFee1 [decimal](28, 15) ,
@ExtensionFee2 [decimal](28, 15) ,
@ExtensionFee3 [decimal](28, 15) ,
@ExtensionFee4 [decimal](28, 15) ,
@AcoreOrig  [decimal](28, 15) ,
@ProductType [nvarchar](256) ,
@MSA [nvarchar](256) ,
@State [nvarchar](256) ,
@DealType [nvarchar](256) ,
@InquiryYear int ,
@Location	[nvarchar](256) ,
--@UnderwrittenReturn  [decimal](28, 15) 
@WLInitialMaturity  [decimal](28, 15),
@WLFullyExtended  [decimal](28, 15)

AS
BEGIN
     SET NOCOUNT ON;

INSERT INTO [DW].[NoteMatrixBI]
(
[DealID],
[DealGroupID],
[NoteID],
[Pri],
[DealName],
[NoteName],
[LoanStatus],
[Client],
[Fund],
[AssetManager],
[Banker],
[Credit],
[Pool],
[FinancingSource],
[DebtType],
[CapStack],
[BillingNote],
[Commitment],
[Spread],
IndexforStub,
[Floor],

AllInRate,

[Type],
[InitialFunding],
[InitialMaturity],

--[ExtendedMaturity],
ExtendedMaturity1,
ExtendedMaturity2,
ExtendedMaturity3,
ExtendedMaturity4,
FullyExtendedMaturity,
CurrentMaturityDate,
CurrentMaturity,
[PaidOffSold],
[CAMRA],
[Servicer],
[ServicerID],
PaydownPayoffConvention,
PaymentDate,
WholeLoanSpread,
ExtensionFee1,
ExtensionFee2,
ExtensionFee3,
ExtensionFee4,
AcoreOrig,
ProductType,
MSA,
State,	
DealType,
[InquiryYear],
[Location],
--[UnderwrittenReturn]
WLInitialMaturity,
WLFullyExtended
)

Values(
@DealID	,
@DealGroupID	,
@NoteID	,
@Pri	,
@DealName	,
@NoteName	,
@LoanStatus	,
@Client	,
@Fund	,
@AssetManager	,
@Banker	,
@Credit	,
@Pool	,
@FinancingSource	,
@DebtType	,
@CapStack	,
@BillingNote	,
@Commitment	,
@Spread	,
@IndexforStub,
@Floor	,
@AllInRate,
@Type	,
@InitialFunding	,
@InitialMaturity	,

--@ExtendedMaturity	,
@ExtendedMaturity1,
@ExtendedMaturity2,
@ExtendedMaturity3,
@ExtendedMaturity4,
@FullyExtendedMaturity,
@CurrentMaturityDate,
@CurrentMaturity,

@PaidOffSold	,

@CAMRA	,


@Servicer	,
@ServicerID,
@PaydownPayoffConvention,
@PaymentDate,
@WholeLoanSpread,
@ExtensionFee1,
@ExtensionFee2,
@ExtensionFee3,
@ExtensionFee4,
@AcoreOrig,
@ProductType,
@MSA,
@State,	
@DealType,
@InquiryYear,
@Location,
--@UnderwrittenReturn
@WLInitialMaturity,
@WLFullyExtended
)

END
