  
  
  
CREATE PROCEDURE [DW].[usp_InsertACORECreditIVNoteMatrix]   
@DealID nvarchar(256) ,  
@DealGroupID nvarchar(256) ,  
@NoteID nvarchar(256) ,  
@Pri int ,  
@DealName nvarchar(256) ,  
@NoteName nvarchar(256) ,  
@LoanStatus nvarchar(256) ,  
@Client nvarchar(256) ,  
@Fund nvarchar(256) ,  
@AssetManager nvarchar(256) ,  
@Banker nvarchar(256) ,  
@Credit nvarchar(256) ,  
@Pool nvarchar(256) ,  
@FinancingSource nvarchar(256) ,  
  
@CurrentEntity nvarchar(256) ,  
@CapStack nvarchar(256) ,  
@BillingNote nvarchar(256) ,  
@Commitment decimal(28, 15) ,  
@Spread decimal(28, 15) ,  
@IndexforStub decimal(28, 15) ,  
@Floor decimal(28, 15) ,  

@AllInRate decimal(28, 15) ,  

@Type nvarchar(256) ,  
@InitialFunding date ,  
@InitialMaturity date ,  
@ExtendedMaturity1 date,  
@ExtendedMaturity2 date,  
@ExtendedMaturity3 date,  
@ExtendedMaturity4 date,  
@FullyExtendedMaturity date,  
@CurrentMaturityDate date,  
@CurrentMaturity  [nvarchar](256),  
@PaidOffSold date ,  
--------------------------------  
@FeesStart nvarchar(256) ,  
@RSLIC decimal(28, 15) ,  
@SNCC decimal(28, 15) ,  
@PIIC decimal(28, 15) ,  
@TMR decimal(28, 15) ,  
@HCC decimal(28, 15) ,  
@USSIC decimal(28, 15) ,  
@TMNF decimal(28, 15) ,  
@HAIH decimal(28, 15) ,  
@Check decimal(28, 15) ,  
@CAMRA nvarchar(256) ,  
@Servicer nvarchar(256) ,  
@ServicerID nvarchar(256),  
  
@PremDisc decimal(28, 15) ,  
  
@OriginationFee decimal(28, 15) ,  
@ExitFee decimal(28, 15) ,  
@PaydownPayoffConvention int ,  
@PaymentDate int ,  
@WholeLoanSpread [decimal](28, 15) ,  
@ExtensionFee1 [decimal](28, 15) ,  
@ExtensionFee2 [decimal](28, 15) ,  
@ExtensionFee3 [decimal](28, 15) ,  
@ExtensionFee4 [decimal](28, 15) ,  

@AcoreOrig decimal(28, 15) ,  

@ProductType [nvarchar](256) ,  
@MSA [nvarchar](256) ,  
@State [nvarchar](256) ,  
@DealType [nvarchar](256) ,  
@InquiryYear int ,  
@Location [nvarchar](256) ,  
--@UnderwrittenReturn  [decimal](28, 15)   

@WLInitialMaturity   DECIMAL (28, 15) ,
@WLFullyExtended DECIMAL (28, 15) ,
@SubDebtFullyExtended    DECIMAL (28, 15) 
  
AS  
BEGIN  
     SET NOCOUNT ON;  
  
INSERT INTO [DW].[NoteMatrixBI]  
(  
[DealID],  
[DealGroupID],  
[NoteID],  
[Pri],  
[DealName],  
[NoteName],  
[LoanStatus],  
[Client],  
[Fund],  
[AssetManager],  
[Banker],  
[Credit],  
[Pool],  
[FinancingSource],  
CurrentEntity,  
[CapStack],  
[BillingNote],  
[Commitment],  
[Spread],  
IndexforStub,  
[Floor],  

AllInRate,

[Type],  
[InitialFunding],  
[InitialMaturity],  
ExtendedMaturity1,  
ExtendedMaturity2,  
ExtendedMaturity3,  
ExtendedMaturity4,  
FullyExtendedMaturity,  
CurrentMaturityDate,  
CurrentMaturity,  
[PaidOffSold],  
[FeesStart],  
[RSLIC],  
[SNCC],  
[PIIC],  
[TMR],  
[HCC],  
[USSIC],  
[TMNF],  
[HAIH],  
[Check],  
[CAMRA],  
[Servicer],  
[ServicerID],  
[PremDisc],  
OriginationFee,  
ExitFee,  
PaydownPayoffConvention,  
PaymentDate,  
WholeLoanSpread,  
ExtensionFee1,  
ExtensionFee2,  
ExtensionFee3,  
ExtensionFee4,  
AcoreOrig,
ProductType,  
MSA,  
[State],   
DealType,  
[InquiryYear],  
[Location],  
--[UnderwrittenReturn]  

WLInitialMaturity,
WLFullyExtended ,
SubDebtFullyExtended

)  
  
Values(  
@DealID ,  
@DealGroupID ,  
@NoteID ,  
@Pri ,  
@DealName ,  
@NoteName ,  
@LoanStatus ,  
@Client ,  
@Fund ,  
@AssetManager ,  
@Banker ,  
@Credit ,  
@Pool ,  
@FinancingSource ,  
  
@CurrentEntity,  
@CapStack ,  
@BillingNote ,  
@Commitment ,  
@Spread ,  
@IndexforStub,  
@Floor , 

@AllInRate,
 
@Type ,  
@InitialFunding ,  
@InitialMaturity ,  
@ExtendedMaturity1,  
@ExtendedMaturity2,  
@ExtendedMaturity3,  
@ExtendedMaturity4,  
@FullyExtendedMaturity,  
@CurrentMaturityDate,  
@CurrentMaturity,  
  
@PaidOffSold ,  
  
@FeesStart ,  
@RSLIC ,  
@SNCC ,  
@PIIC ,  
@TMR ,  
@HCC ,  
@USSIC ,  
@TMNF ,  
@HAIH ,  
@Check ,  
@CAMRA ,  
@Servicer ,  
@ServicerID ,  
@PremDisc ,  
  
@OriginationFee,  
@ExitFee,  
@PaydownPayoffConvention,  
@PaymentDate,  
@WholeLoanSpread,  
@ExtensionFee1,  
@ExtensionFee2,  
@ExtensionFee3,  
@ExtensionFee4, 

@AcoreOrig,
 
@ProductType,  
@MSA,  
@State,   
@DealType,  
@InquiryYear,  
@Location,  
--@UnderwrittenReturn  
@WLInitialMaturity,
@WLFullyExtended ,
@SubDebtFullyExtended
  
)  
  
END
