

CREATE PROCEDURE [DW].[usp_MergeUwNote]

@BatchLogId int

AS
BEGIN

SET NOCOUNT ON


UPDATE [DW].BatchDetail
SET
BITableName = 'UwNoteBI',
BIStartTime = GETDATE()
WHERE BatchLogId = @BatchLogId and LandingTableName = 'L_UwNoteBI'


MERGE [DW].UwNoteBI NB
USING [DW].L_UwNoteBI LNB
ON NB.noteid = LNB.noteid
WHEN MATCHED THEN
UPDATE 
	SET 
NB.ControlId_F =LNB.ControlId_F,
NB.PrimaryDebtFlag =LNB.PrimaryDebtFlag,
NB.LienPositionCd_F =LNB.LienPositionCd_F,
NB.IntCalcMethodCd_F =LNB.IntCalcMethodCd_F,
NB.RateTypeCd_F =LNB.RateTypeCd_F,
NB.PaymentFreqCd_F =LNB.PaymentFreqCd_F,
NB.InterestCollectionTypeCd_F =LNB.InterestCollectionTypeCd_F,
NB.AmortizationCd_F =LNB.AmortizationCd_F,
NB.InterimServ_OrgId_F =LNB.InterimServ_OrgId_F,
NB.InterimCustodian_OrgId_F =LNB.InterimCustodian_OrgId_F,
NB.NoteName =LNB.NoteName,
NB.NoteDate =LNB.NoteDate,
NB.NoteDateApproximateSw =LNB.NoteDateApproximateSw,
NB.Priority =LNB.Priority,
NB.ProjectedFundingDate =LNB.ProjectedFundingDate,
NB.IndexName =LNB.IndexName,
NB.IndexSource =LNB.IndexSource,
NB.IndexPercent =LNB.IndexPercent,
NB.IndexAsOfDate =LNB.IndexAsOfDate,
NB.HyerAmortizationFlag =LNB.HyerAmortizationFlag,
NB.HyperAmortizationTerm =LNB.HyperAmortizationTerm,
NB.HyperAmortizationDate =LNB.HyperAmortizationDate,
NB.OrigLoanAmount =LNB.OrigLoanAmount,
NB.FirstPIPaymentDate =LNB.FirstPIPaymentDate,
NB.InterestSpread =LNB.InterestSpread,
NB.OrigIntRate =LNB.OrigIntRate,
NB.InterestRateForAmortization =LNB.InterestRateForAmortization,
NB.MonthlyDebtService =LNB.MonthlyDebtService,
NB.PaymentOverride =LNB.PaymentOverride,
NB.PaymentOverrideAmount =LNB.PaymentOverrideAmount,
NB.DSCROverride =LNB.DSCROverride,
NB.DSCROverrideAmount =LNB.DSCROverrideAmount,
NB.LoanTerm =LNB.LoanTerm,
NB.ARDTerm =LNB.ARDTerm,
NB.ARDLoanBalance =LNB.ARDLoanBalance,
NB.StatedMaturityDate =LNB.StatedMaturityDate,
NB.LoanConstant =LNB.LoanConstant,
NB.MaxIntAmount =LNB.MaxIntAmount,
NB.AmountToBeFunded =LNB.AmountToBeFunded,
NB.BalloonARDAmount =LNB.BalloonARDAmount,
NB.FutureFundingPurpose =LNB.FutureFundingPurpose,
NB.PrincipalBalance =LNB.PrincipalBalance,
NB.AmortizationTerm =LNB.AmortizationTerm,
NB.AmortizationComments =LNB.AmortizationComments,
NB.HyperAmortComments =LNB.HyperAmortComments,
NB.AmortFixedDefaultIfNotPaidSw =LNB.AmortFixedDefaultIfNotPaidSw,
NB.AmortFixedDefaultIfNotPaidAmt =LNB.AmortFixedDefaultIfNotPaidAmt,
NB.AmortIOPeriod =LNB.AmortIOPeriod,
NB.AmortFixedPrincipleAmt =LNB.AmortFixedPrincipleAmt,
NB.OriginationFee =LNB.OriginationFee,
NB.OriginationFeePct =LNB.OriginationFeePct,
NB.InterestRateLock =LNB.InterestRateLock,
NB.InterestRateLockDate =LNB.InterestRateLockDate,
NB.InterestRateFloorSw =LNB.InterestRateFloorSw,
NB.InterestRateFloorPct =LNB.InterestRateFloorPct,
NB.InterestRateFloorPortion =LNB.InterestRateFloorPortion,
NB.InterestRateFloorComments =LNB.InterestRateFloorComments,
NB.InterestRateLockExpiration =LNB.InterestRateLockExpiration,
NB.MatrixSpreadAtClose =LNB.MatrixSpreadAtClose,
NB.MatrixSpreadAtCloseComments =LNB.MatrixSpreadAtCloseComments,
NB.ServicingStrip =LNB.ServicingStrip,
NB.InitialIoInterestRate =LNB.InitialIoInterestRate,
NB.InterimServFee =LNB.InterimServFee,
NB.InterimServType =LNB.InterimServType,
NB.PayAndAccrueSw =LNB.PayAndAccrueSw,
NB.PayRate =LNB.PayRate,
NB.PayAndAccrueComment =LNB.PayAndAccrueComment,
NB.TrapExcessCasflowSw =LNB.TrapExcessCasflowSw,
NB.TrapExcessCashflowComments =LNB.TrapExcessCashflowComments,
NB.PerformanceHoldbackType =LNB.PerformanceHoldbackType,
NB.SecondayFinancing =LNB.SecondayFinancing,
NB.ExitFee =LNB.ExitFee,
NB.ExitFeePct =LNB.ExitFeePct,
NB.ExitFeeReducedIfFinSw =LNB.ExitFeeReducedIfFinSw,
NB.ExitFeeReducedIfFinComment =LNB.ExitFeeReducedIfFinComment,
NB.MpCallOption =LNB.MpCallOption,
NB.MpCallOptionDesc =LNB.MpCallOptionDesc,
NB.MpAllowFutAdvances =LNB.MpAllowFutAdvances,
NB.MpAllowFutAdvancesDesc =LNB.MpAllowFutAdvancesDesc,
NB.MpStandstill =LNB.MpStandstill,
NB.MpComment =LNB.MpComment,
NB.ArmLoanInternallyCappedSw =LNB.ArmLoanInternallyCappedSw,
NB.ArmInterestRateCappedReqSw =LNB.ArmInterestRateCappedReqSw,
NB.ArmLiborCap =LNB.ArmLiborCap,
NB.ArmIntRateCapDesc =LNB.ArmIntRateCapDesc,
NB.ArmLiborDefinition =LNB.ArmLiborDefinition,
NB.ArmLiborDeterminationDate =LNB.ArmLiborDeterminationDate,
NB.GCM_Cusip =LNB.GCM_Cusip,
NB.GCM_TradeAccount =LNB.GCM_TradeAccount,
NB.GCM_IkonBoxNum =LNB.GCM_IkonBoxNum,
NB.GCM_IkonCopyStatus =LNB.GCM_IkonCopyStatus,
NB.GCM_OriginalsOutDate =LNB.GCM_OriginalsOutDate,
NB.GCM_AccountantsCopyDate =LNB.GCM_AccountantsCopyDate,
NB.GCM_SandPCopyDate =LNB.GCM_SandPCopyDate,
NB.GCM_FitchCopyDate =LNB.GCM_FitchCopyDate,
NB.GCM_MoodysCopyDate =LNB.GCM_MoodysCopyDate,
NB.GCM_BBuyerCopyDate =LNB.GCM_BBuyerCopyDate,
NB.GCM_ServicerCopyDate =LNB.GCM_ServicerCopyDate,
NB.GCM_TabNumber =LNB.GCM_TabNumber,
NB.GCM_BoxContent =LNB.GCM_BoxContent,
NB.GCM_BoxNumber =LNB.GCM_BoxNumber,
NB.GCM_ArchieveSerialNumber =LNB.GCM_ArchieveSerialNumber,
NB.GCM_ArchieveDate =LNB.GCM_ArchieveDate,
NB.GCM_DestroyedDate =LNB.GCM_DestroyedDate,
NB.GCM_InternalComments =LNB.GCM_InternalComments,
NB.AuditAddDate =LNB.AuditAddDate,
NB.AuditAddUserId =LNB.AuditAddUserId,
NB.AuditUpdateDate =LNB.AuditUpdateDate,
NB.AuditUpdateUserId =LNB.AuditUpdateUserId,
NB.DaysofFreeLock =LNB.DaysofFreeLock,
NB.NoteComments =LNB.NoteComments,
NB.AverageLife =LNB.AverageLife,
NB.Duration =LNB.Duration,
NB.FundingDate =LNB.FundingDate,
NB.AltIndexName =LNB.AltIndexName,
NB.AltIntPct =LNB.AltIntPct,
NB.BondEquivPct =LNB.BondEquivPct,
NB.IOCostPct =LNB.IOCostPct,
NB.AMBenefitPct =LNB.AMBenefitPct,
NB.FloorBenefitPct =LNB.FloorBenefitPct,
NB.MiscSpreadPct =LNB.MiscSpreadPct,
NB.FreeRLPct =LNB.FreeRLPct,
NB.RLChargeBenefitPct =LNB.RLChargeBenefitPct,
NB.fundedAmount =LNB.fundedAmount,
NB.NoteNumber =LNB.NoteNumber,
NB.InterestRateLockedPercent =LNB.InterestRateLockedPercent,
NB.DV01Amount =LNB.DV01Amount,
NB.TolRel2InitDepositPct =LNB.TolRel2InitDepositPct,
NB.CurrentDepositAmount =LNB.CurrentDepositAmount,
NB.NoteCurrencyCD_F =LNB.NoteCurrencyCD_F,
NB.InterimServContact_UserID_F =LNB.InterimServContact_UserID_F,
NB.SyndicateSell =LNB.SyndicateSell,
NB.DMCDO =LNB.DMCDO,
NB.DMREPO =LNB.DMREPO,
NB.Controlling =LNB.Controlling,
NB.InterimServicer_ContactID_F =LNB.InterimServicer_ContactID_F,
NB.MonthlyDebtServiceIO =LNB.MonthlyDebtServiceIO,
NB.MonthlyDebtServiceFinal =LNB.MonthlyDebtServiceFinal,
NB.isLocked =LNB.isLocked,
NB.FinancingSource =LNB.FinancingSource,
NB.AdvanceRate =LNB.AdvanceRate,
NB.CovenantISCR =LNB.CovenantISCR,
NB.CovenantDSCR =LNB.CovenantDSCR,
NB.LTV =LNB.LTV,
NB.LTC =LNB.LTC,
NB.ELClass =LNB.ELClass,
NB.IRRBaselI =LNB.IRRBaselI,
NB.IRRBaselII =LNB.IRRBaselII,
NB.LGD =LNB.LGD,
NB.LTVCovenantAsStabilized =LNB.LTVCovenantAsStabilized,
NB.LTCCovenantAsStabilized =LNB.LTCCovenantAsStabilized,
NB.DSCRCovenantAsIsStressed =LNB.DSCRCovenantAsIsStressed,
NB.DSCRCovenantAsStabilized =LNB.DSCRCovenantAsStabilized,
NB.ISCRCovenantAsStabilized =LNB.ISCRCovenantAsStabilized,
NB.MinimumDebtYield =LNB.MinimumDebtYield,
NB.LGDPct =LNB.LGDPct,
NB.ELPct =LNB.ELPct,
NB.AgentBank_OrgId_F =LNB.AgentBank_OrgId_F,
NB.AgentBank_ContactId_F =LNB.AgentBank_ContactId_F,
NB.CoAgentBank_OrgId_F =LNB.CoAgentBank_OrgId_F,
NB.CoAgentBank_ContactId_F =LNB.CoAgentBank_ContactId_F,
NB.LoanAdminCostRate =LNB.LoanAdminCostRate,
NB.InvestmentGrade =LNB.InvestmentGrade,
NB.StartLTV =LNB.StartLTV,
NB.StartLTC =LNB.StartLTC,
NB.StartDSCR =LNB.StartDSCR,
NB.StartISCR =LNB.StartISCR,
NB.ASRNoteComments =LNB.ASRNoteComments,
NB.ActualRepaymentDate =LNB.ActualRepaymentDate,
NB.StubInterestAmt =LNB.StubInterestAmt,
NB.NegAmTreatmentCd_F =LNB.NegAmTreatmentCd_F,
NB.MpCallOptionDate =LNB.MpCallOptionDate,
NB.MonthlyDebtServiceIOFinal =LNB.MonthlyDebtServiceIOFinal,
NB.ModifiedNoteSw =LNB.ModifiedNoteSw,
NB.ModificationParentNoteId_F =LNB.ModificationParentNoteId_F,
NB.SystemCodeCd_F =LNB.SystemCodeCd_F,
NB.FacilityTypeCd_F =LNB.FacilityTypeCd_F,
NB.isPrimaryDebtFlag =LNB.isPrimaryDebtFlag,
NB.EstFundDate =LNB.EstFundDate,
NB.ClientIdentifier =LNB.ClientIdentifier,
NB.PropertyContainerID_F =LNB.PropertyContainerID_F,
NB.InitialFixedPeriod =LNB.InitialFixedPeriod,
NB.FacilityTypeOtherCd_F =LNB.FacilityTypeOtherCd_F,
NB.IncrementalRenewalRevenue =LNB.IncrementalRenewalRevenue,
NB.InterestRateForUnderwritingSave =LNB.InterestRateForUnderwritingSave,
NB.NoteIDAsString =LNB.NoteIDAsString,
NB.PreviousNoteDate =LNB.PreviousNoteDate,
NB.ExtensionFee =LNB.ExtensionFee,
NB.AllocationDate =LNB.AllocationDate,
NB.OrigFundingDate =LNB.OrigFundingDate,
NB.StubAmortSchedDate =LNB.StubAmortSchedDate,
NB.StubAmortInterestAmt =LNB.StubAmortInterestAmt,
NB.StubAmortDaysInPeriod =LNB.StubAmortDaysInPeriod,
NB.StubAmortInterestRate =LNB.StubAmortInterestRate,
NB.StubAmortBalanceAmt =LNB.StubAmortBalanceAmt,
NB.InvestorSpread =LNB.InvestorSpread,
NB.ClientNoteName =LNB.ClientNoteName,
NB.SyncFundingDate =LNB.SyncFundingDate,
NB.TotalCommitment =LNB.TotalCommitment,
NB.TotalCurrentAdjustedCommitment =LNB.TotalCurrentAdjustedCommitment,
NB.PastFunding =LNB.PastFunding,
NB.FutureFunding =LNB.FutureFunding

WHEN NOT MATCHED THEN

INSERT 
(NoteId	 ,
ControlId_F	 ,
PrimaryDebtFlag	 ,
LienPositionCd_F	 ,
IntCalcMethodCd_F	 ,
RateTypeCd_F	 ,
PaymentFreqCd_F	 ,
InterestCollectionTypeCd_F	 ,
AmortizationCd_F	 ,
InterimServ_OrgId_F	 ,
InterimCustodian_OrgId_F	 ,
NoteName	 ,
NoteDate	 ,
NoteDateApproximateSw	 ,
Priority	 ,
ProjectedFundingDate	 ,
IndexName	 ,
IndexSource	 ,
IndexPercent	 ,
IndexAsOfDate	 ,
HyerAmortizationFlag	 ,
HyperAmortizationTerm	 ,
HyperAmortizationDate	 ,
OrigLoanAmount	 ,
FirstPIPaymentDate	 ,
InterestSpread	 ,
OrigIntRate	 ,
InterestRateForAmortization	 ,
MonthlyDebtService	 ,
PaymentOverride	 ,
PaymentOverrideAmount	 ,
DSCROverride	 ,
DSCROverrideAmount	 ,
LoanTerm	 ,
ARDTerm	 ,
ARDLoanBalance	 ,
StatedMaturityDate	 ,
LoanConstant	 ,
MaxIntAmount	 ,
AmountToBeFunded	 ,
BalloonARDAmount	 ,
FutureFundingPurpose	 ,
PrincipalBalance	 ,
AmortizationTerm	 ,
AmortizationComments	 ,
HyperAmortComments	 ,
AmortFixedDefaultIfNotPaidSw	 ,
AmortFixedDefaultIfNotPaidAmt	 ,
AmortIOPeriod	 ,
AmortFixedPrincipleAmt	 ,
OriginationFee	 ,
OriginationFeePct	 ,
InterestRateLock	 ,
InterestRateLockDate	 ,
InterestRateFloorSw	 ,
InterestRateFloorPct	 ,
InterestRateFloorPortion	 ,
InterestRateFloorComments	 ,
InterestRateLockExpiration	 ,
MatrixSpreadAtClose	 ,
MatrixSpreadAtCloseComments	 ,
ServicingStrip	 ,
InitialIoInterestRate	 ,
InterimServFee	 ,
InterimServType	 ,
PayAndAccrueSw	 ,
PayRate	 ,
PayAndAccrueComment	 ,
TrapExcessCasflowSw	 ,
TrapExcessCashflowComments	 ,
PerformanceHoldbackType	 ,
SecondayFinancing	 ,
ExitFee	 ,
ExitFeePct	 ,
ExitFeeReducedIfFinSw	 ,
ExitFeeReducedIfFinComment	 ,
MpCallOption	 ,
MpCallOptionDesc	 ,
MpAllowFutAdvances	 ,
MpAllowFutAdvancesDesc	 ,
MpStandstill	 ,
MpComment	 ,
ArmLoanInternallyCappedSw	 ,
ArmInterestRateCappedReqSw	 ,
ArmLiborCap	 ,
ArmIntRateCapDesc	 ,
ArmLiborDefinition	 ,
ArmLiborDeterminationDate	 ,
GCM_Cusip	 ,
GCM_TradeAccount	 ,
GCM_IkonBoxNum	 ,
GCM_IkonCopyStatus	 ,
GCM_OriginalsOutDate	 ,
GCM_AccountantsCopyDate	 ,
GCM_SandPCopyDate	 ,
GCM_FitchCopyDate	 ,
GCM_MoodysCopyDate	 ,
GCM_BBuyerCopyDate	 ,
GCM_ServicerCopyDate	 ,
GCM_TabNumber	 ,
GCM_BoxContent	 ,
GCM_BoxNumber	 ,
GCM_ArchieveSerialNumber	 ,
GCM_ArchieveDate	 ,
GCM_DestroyedDate	 ,
GCM_InternalComments	 ,
AuditAddDate	 ,
AuditAddUserId	 ,
AuditUpdateDate	 ,
AuditUpdateUserId	 ,
DaysofFreeLock	 ,
NoteComments	 ,
AverageLife	 ,
Duration	 ,
FundingDate	 ,
AltIndexName	 ,
AltIntPct	 ,
BondEquivPct	 ,
IOCostPct	 ,
AMBenefitPct	 ,
FloorBenefitPct	 ,
MiscSpreadPct	 ,
FreeRLPct	 ,
RLChargeBenefitPct	 ,
fundedAmount	 ,
NoteNumber	 ,
InterestRateLockedPercent	 ,
DV01Amount	 ,
TolRel2InitDepositPct	 ,
CurrentDepositAmount	 ,
NoteCurrencyCD_F	 ,
InterimServContact_UserID_F	 ,
SyndicateSell	 ,
DMCDO	 ,
DMREPO	 ,
Controlling	 ,
InterimServicer_ContactID_F	 ,
MonthlyDebtServiceIO	 ,
MonthlyDebtServiceFinal	 ,
isLocked	 ,
FinancingSource	 ,
AdvanceRate	 ,
CovenantISCR	 ,
CovenantDSCR	 ,
LTV	 ,
LTC	 ,
ELClass	 ,
IRRBaselI	 ,
IRRBaselII	 ,
LGD	 ,
LTVCovenantAsStabilized	 ,
LTCCovenantAsStabilized	 ,
DSCRCovenantAsIsStressed	 ,
DSCRCovenantAsStabilized	 ,
ISCRCovenantAsStabilized	 ,
MinimumDebtYield	 ,
LGDPct	 ,
ELPct	 ,
AgentBank_OrgId_F	 ,
AgentBank_ContactId_F	 ,
CoAgentBank_OrgId_F	 ,
CoAgentBank_ContactId_F	 ,
LoanAdminCostRate	 ,
InvestmentGrade	 ,
StartLTV	 ,
StartLTC	 ,
StartDSCR	 ,
StartISCR	 ,
ASRNoteComments	 ,
ActualRepaymentDate	 ,
StubInterestAmt	 ,
NegAmTreatmentCd_F	 ,
MpCallOptionDate	 ,
MonthlyDebtServiceIOFinal	 ,
ModifiedNoteSw	 ,
ModificationParentNoteId_F	 ,
SystemCodeCd_F	 ,
FacilityTypeCd_F	 ,
isPrimaryDebtFlag	 ,
EstFundDate	 ,
ClientIdentifier	 ,
PropertyContainerID_F	 ,
InitialFixedPeriod	 ,
FacilityTypeOtherCd_F	 ,
IncrementalRenewalRevenue	 ,
InterestRateForUnderwritingSave	 ,
NoteIDAsString	 ,
PreviousNoteDate	 ,
ExtensionFee	 ,
AllocationDate	 ,
OrigFundingDate	 ,
StubAmortSchedDate	 ,
StubAmortInterestAmt	 ,
StubAmortDaysInPeriod	 ,
StubAmortInterestRate	 ,
StubAmortBalanceAmt	 ,
InvestorSpread	 ,
ClientNoteName	 ,
SyncFundingDate	,
TotalCommitment,
TotalCurrentAdjustedCommitment,
PastFunding,
FutureFunding
)

VALUES (LNB.NoteId,
LNB.ControlId_F,
LNB.PrimaryDebtFlag,
LNB.LienPositionCd_F,
LNB.IntCalcMethodCd_F,
LNB.RateTypeCd_F,
LNB.PaymentFreqCd_F,
LNB.InterestCollectionTypeCd_F,
LNB.AmortizationCd_F,
LNB.InterimServ_OrgId_F,
LNB.InterimCustodian_OrgId_F,
LNB.NoteName,
LNB.NoteDate,
LNB.NoteDateApproximateSw,
LNB.Priority,
LNB.ProjectedFundingDate,
LNB.IndexName,
LNB.IndexSource,
LNB.IndexPercent,
LNB.IndexAsOfDate,
LNB.HyerAmortizationFlag,
LNB.HyperAmortizationTerm,
LNB.HyperAmortizationDate,
LNB.OrigLoanAmount,
LNB.FirstPIPaymentDate,
LNB.InterestSpread,
LNB.OrigIntRate,
LNB.InterestRateForAmortization,
LNB.MonthlyDebtService,
LNB.PaymentOverride,
LNB.PaymentOverrideAmount,
LNB.DSCROverride,
LNB.DSCROverrideAmount,
LNB.LoanTerm,
LNB.ARDTerm,
LNB.ARDLoanBalance,
LNB.StatedMaturityDate,
LNB.LoanConstant,
LNB.MaxIntAmount,
LNB.AmountToBeFunded,
LNB.BalloonARDAmount,
LNB.FutureFundingPurpose,
LNB.PrincipalBalance,
LNB.AmortizationTerm,
LNB.AmortizationComments,
LNB.HyperAmortComments,
LNB.AmortFixedDefaultIfNotPaidSw,
LNB.AmortFixedDefaultIfNotPaidAmt,
LNB.AmortIOPeriod,
LNB.AmortFixedPrincipleAmt,
LNB.OriginationFee,
LNB.OriginationFeePct,
LNB.InterestRateLock,
LNB.InterestRateLockDate,
LNB.InterestRateFloorSw,
LNB.InterestRateFloorPct,
LNB.InterestRateFloorPortion,
LNB.InterestRateFloorComments,
LNB.InterestRateLockExpiration,
LNB.MatrixSpreadAtClose,
LNB.MatrixSpreadAtCloseComments,
LNB.ServicingStrip,
LNB.InitialIoInterestRate,
LNB.InterimServFee,
LNB.InterimServType,
LNB.PayAndAccrueSw,
LNB.PayRate,
LNB.PayAndAccrueComment,
LNB.TrapExcessCasflowSw,
LNB.TrapExcessCashflowComments,
LNB.PerformanceHoldbackType,
LNB.SecondayFinancing,
LNB.ExitFee,
LNB.ExitFeePct,
LNB.ExitFeeReducedIfFinSw,
LNB.ExitFeeReducedIfFinComment,
LNB.MpCallOption,
LNB.MpCallOptionDesc,
LNB.MpAllowFutAdvances,
LNB.MpAllowFutAdvancesDesc,
LNB.MpStandstill,
LNB.MpComment,
LNB.ArmLoanInternallyCappedSw,
LNB.ArmInterestRateCappedReqSw,
LNB.ArmLiborCap,
LNB.ArmIntRateCapDesc,
LNB.ArmLiborDefinition,
LNB.ArmLiborDeterminationDate,
LNB.GCM_Cusip,
LNB.GCM_TradeAccount,
LNB.GCM_IkonBoxNum,
LNB.GCM_IkonCopyStatus,
LNB.GCM_OriginalsOutDate,
LNB.GCM_AccountantsCopyDate,
LNB.GCM_SandPCopyDate,
LNB.GCM_FitchCopyDate,
LNB.GCM_MoodysCopyDate,
LNB.GCM_BBuyerCopyDate,
LNB.GCM_ServicerCopyDate,
LNB.GCM_TabNumber,
LNB.GCM_BoxContent,
LNB.GCM_BoxNumber,
LNB.GCM_ArchieveSerialNumber,
LNB.GCM_ArchieveDate,
LNB.GCM_DestroyedDate,
LNB.GCM_InternalComments,
LNB.AuditAddDate,
LNB.AuditAddUserId,
LNB.AuditUpdateDate,
LNB.AuditUpdateUserId,
LNB.DaysofFreeLock,
LNB.NoteComments,
LNB.AverageLife,
LNB.Duration,
LNB.FundingDate,
LNB.AltIndexName,
LNB.AltIntPct,
LNB.BondEquivPct,
LNB.IOCostPct,
LNB.AMBenefitPct,
LNB.FloorBenefitPct,
LNB.MiscSpreadPct,
LNB.FreeRLPct,
LNB.RLChargeBenefitPct,
LNB.fundedAmount,
LNB.NoteNumber,
LNB.InterestRateLockedPercent,
LNB.DV01Amount,
LNB.TolRel2InitDepositPct,
LNB.CurrentDepositAmount,
LNB.NoteCurrencyCD_F,
LNB.InterimServContact_UserID_F,
LNB.SyndicateSell,
LNB.DMCDO,
LNB.DMREPO,
LNB.Controlling,
LNB.InterimServicer_ContactID_F,
LNB.MonthlyDebtServiceIO,
LNB.MonthlyDebtServiceFinal,
LNB.isLocked,
LNB.FinancingSource,
LNB.AdvanceRate,
LNB.CovenantISCR,
LNB.CovenantDSCR,
LNB.LTV,
LNB.LTC,
LNB.ELClass,
LNB.IRRBaselI,
LNB.IRRBaselII,
LNB.LGD,
LNB.LTVCovenantAsStabilized,
LNB.LTCCovenantAsStabilized,
LNB.DSCRCovenantAsIsStressed,
LNB.DSCRCovenantAsStabilized,
LNB.ISCRCovenantAsStabilized,
LNB.MinimumDebtYield,
LNB.LGDPct,
LNB.ELPct,
LNB.AgentBank_OrgId_F,
LNB.AgentBank_ContactId_F,
LNB.CoAgentBank_OrgId_F,
LNB.CoAgentBank_ContactId_F,
LNB.LoanAdminCostRate,
LNB.InvestmentGrade,
LNB.StartLTV,
LNB.StartLTC,
LNB.StartDSCR,
LNB.StartISCR,
LNB.ASRNoteComments,
LNB.ActualRepaymentDate,
LNB.StubInterestAmt,
LNB.NegAmTreatmentCd_F,
LNB.MpCallOptionDate,
LNB.MonthlyDebtServiceIOFinal,
LNB.ModifiedNoteSw,
LNB.ModificationParentNoteId_F,
LNB.SystemCodeCd_F,
LNB.FacilityTypeCd_F,
LNB.isPrimaryDebtFlag,
LNB.EstFundDate,
LNB.ClientIdentifier,
LNB.PropertyContainerID_F,
LNB.InitialFixedPeriod,
LNB.FacilityTypeOtherCd_F,
LNB.IncrementalRenewalRevenue,
LNB.InterestRateForUnderwritingSave,
LNB.NoteIDAsString,
LNB.PreviousNoteDate,
LNB.ExtensionFee,
LNB.AllocationDate,
LNB.OrigFundingDate,
LNB.StubAmortSchedDate,
LNB.StubAmortInterestAmt,
LNB.StubAmortDaysInPeriod,
LNB.StubAmortInterestRate,
LNB.StubAmortBalanceAmt,
LNB.InvestorSpread,
LNB.ClientNoteName,
LNB.SyncFundingDate,
LNB.TotalCommitment,
LNB.TotalCurrentAdjustedCommitment,
LNB.PastFunding,
LNB.FutureFunding

);



DECLARE @RowCount int
SET @RowCount = @@ROWCOUNT

UPDATE [DW].BatchDetail
SET
BIEndTime = GETDATE(),
BIRecordCount = @RowCount
WHERE BatchLogId = @BatchLogId and LandingTableName = 'L_UwNoteBI'

Print(char(9) +'usp_MergeUwNote - ROWCOUNT = '+cast(@RowCount  as varchar(100)));


END

