
CREATE PROCEDURE [DW].[usp_ImportUwProperty]
	@BatchLogId int,@LastBatchStart datetime, @CurrentBatchStart datetime
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO [DW].BatchDetail (BatchLogId,LandingTableName,LandingStartTime)
	VALUES (@BatchLogId,'L_UwPropertyBI',GETDATE())

	DECLARE @id int,@RowCount int
	SET @id = (SELECT @@IDENTITY)


IF(@LastBatchStart is null)
BEGIN

	Declare @minUpdatedDatesrcTable as table
	(
		[MinUpdatedDate] datetime null,
		ShardName nvarchar(max)  NULL
	)
	insert into @minUpdatedDatesrcTable([MinUpdatedDate],ShardName)
	EXEC sp_execute_remote @data_source_name  = N'RemoteReferenceData', @stmt = N'Select MIN(AuditaddDate) as AuditUpdateDate from tblproperty '


	SET @LastBatchStart = (Select [MinUpdatedDate] from @minUpdatedDatesrcTable)
END


DECLARE @query nvarchar(MAX) = N'Select 
p.PropertyId,
p.ControlId_F,
p.PropertyNumber,
p.PropertyName,
LPropertyTypeMajorCd_F.PropertyTypeMajorDesc as PropertyTypeMajorCd_F,
LPropertyTypeMinorCd_F.PropertyTypeMinorDesc as PropertyTypeMinorCd_F,
LSecondaryPropTypeMajCd_F.PropertyTypeMajorDesc as SecondaryPropTypeMajCd_F,
LManagementCoId_F.ManagementCoName as ManagementCoId_F,
LFeeLeaseHoldCd_F.PropertyFeeLeaseHoldDesc as FeeLeaseHoldCd_F,
p.StreetAddress,
p.City,
p.State,
p.ZipCode,
p.County,
p.Country,
p.InspectionDate,
p.LandArea,
p.UnitMeasurePrimary,
p.NumberOfUnitsPrimary,
p.GSFPrimary,
p.NRSFPrimary,
p.UnitMeasureSecondary,
p.NumberOfUnitsSecondary,
p.GSFSecondary,
p.NRSFSecondary,
p.NumberOfBuildings,
p.NumberOfStories,
p.NumberOfPads,
p.NumberOfElevators,
p.NumberOfParkingSpaces,
p.Security,
p.OnSiteMan,
p.Tenancy,
p.PercentOwnOcc,
p.LocationType,
p.DateAcquired,
p.YearBuilt,
p.YearRenovated,
p.Zoning,
p.LegallyConformingUse,
LPropertyPositionCd_F.PropertyPositionDesc as PropertyPositionCd_F,
p.PropertyPositionStatus,
p.AcquisitionAmount,
p.BorrowerEquity,
p.TitleCompany,
p.TitleVesting,
p.TitlePolicyDate,
p.TitleARMEndorsement,
p.PolicyAmount,
p.TitleNegAmortizationEnd,
p.TitleFutAdvancesEnd,
p.OwnershipInterest,
p.GroundLeaseFlag,
p.CrossCollateralized,
p.NumberGroundLeases,
p.CrossDefaulted,
Cast(p.CrossDefaultedComment as nvarchar(max)) as CrossDefaultedComment,
p.DescriptionOfOtherLiens,
p.DescriptionOfAddCollateral,
p.TitlePolicyType,
p.TitleCom,
p.LienPosition,
p.SubFin,
p.UnsecDebtAllow,
Cast(p.PropertyComment as nvarchar(max)) as PropertyComment,
p.DealAllocationAmt,
p.DealAllocatedPctSecondary,
p.PropertyClass,
p.NewConstruction,
p.SingleTennant,
p.EstValue,
p.EstNCF,
p.EstNOI,
p.WindHailInsSw,
p.WindHailInsAmt,
p.FloodInsSw,
p.FloodInsAmt,
p.HurricaneInsSw,
p.HurricaneInsAmt,
Cast(p.NonConformingComment as nvarchar(max)) as NonConformingComment,
p.OccupancyVsMarket,
p.MarketForecast,
p.EstimatedMarketValue,
p.LandOInsuranceReq,
p.ProjectedMoodysCapRate,
p.ActualMoodysCapRate,
p.ApprovedNCF,
p.ApprovedBy_UserId_F,
p.ApprovalDate,
p.AlliedStressPct,
p.DefaultRiskRating,
p.HardEquity,
p.LenderPropertyIdentifier,
p.ManRelated,
p.ManAgreeAssgnable,
p.ManAgreeExpireDate,
p.ManAgreeFee,
p.ManFeeCollectedOn,
p.ManAgreeSubordinate,
p.ManAgreeCure,
p.ManLeasingAgent,
Cast(p.ManLeasingCommission as nvarchar(max)) as ManLeasingCommission,
Cast(p.ManAgreementComment as nvarchar(max)) as ManAgreementComment,
p.ManContactName,
p.ManYearsManageProp,
p.ManAgreementDate,
p.ManAgreementRenewal,
p.ManOwnerRightToTerminate,
Cast(p.ManTerminationCond as nvarchar(max)) as ManTerminationCond,
p.ManLenderRightToTerminate,
p.ManIncentiveFee,
p.ManChangeConditions,
Cast(p.ManChangeConditionsComment as nvarchar(max)) as ManChangeConditionsComment,
p.ManIncentiveFeeSub,
Cast(p.ManIncentiveFeeComment as nvarchar(max)) as ManIncentiveFeeComment,
p.LoanCondVacancyAllowance,
p.LoanCondManagementFee,
p.LoanCondFranchiseFee,
p.LoanCondAdvertisingFee,
Cast(p.LoanCondReplacementReserves as nvarchar(max)) as LoanCondReplacementReserves,
Cast(p.LoanCondRolloverCosts as nvarchar(max)) as LoanCondRolloverCosts,
p.MpDueOnSale,
Cast(p.MpDueOnSaleDesc as nvarchar(max)) as MpDueOnSaleDesc,
p.MpDueOnEncumbrance,
Cast(p.MpDueOnEncumbranceDesc as nvarchar(max)) as MpDueOnEncumbranceDesc,
p.MpCashAudit,
Cast(p.MpCashAuditDesc as nvarchar(max)) as MpCashAuditDesc,
p.MpPartialRelease,
Cast(p.MpPartialReleaseDesc as nvarchar(max)) as MpPartialReleaseDesc,
p.MpPartialReleaseAmt,
p.MpRightToInspectProperty,
p.MpOpStatementFrequency,
p.MpRentRollFrequency,
p.MpUnsecuredDebtAllowed,
p.MpMaxUnsecuredDebtAmt,
p.MpTradePayablesMaxAmt,
p.MpTradePayablesDaysOut,
Cast(p.MpComment as nvarchar(max)) as MpComment,
p.MarketCapRate,
p.LenderCapRate,
p.PhotoLink,
Cast(p.DirctionsLink as nvarchar(max)) as DirctionsLink,
p.AuditAddDate,
p.AuditAddUserId,
p.AuditUpdateDate,
p.AuditUpdateUserId,
p.DealAllocationAmtPCT,
LPropertyCurrencyCD_F.CurrencyDesc as PropertyCurrencyCD_F,
p.CeilingHeight,
LRegionCD_F.RegionDesc as RegionCD_F,
p.TerrorInsSw,
p.TerrorInsAmt,
LMarketCd_F.MarketDesc as MarketCd_F,
p.ReleaseCollateralSW,
p.TotalCostBasis,
p.ExternalPropertyNumber,
p.MpSubstitutionAllowed,
Cast(p.MpSubstitutionAllowedDesc as nvarchar(max)) as MpSubstitutionAllowedDesc,
p.ManAgreeAmount,
Cast(p.SubMarketManComment as nvarchar(max)) as SubMarketManComment,
p.ManFeeType,
p.ParkingSpacesCovered,
p.ParkingSpacesUncovered,
p.MANSFUnitsRmsUnderManinSubMarket,
LSubMarketId_F.SubMarketDesc as SubMarketId_F,
p.Latitude,
p.Longitude,
p.UnderwrittenManagementFee,
p.ClientIdentifier,
p.DealAllocationTotalCommitmentAmt,
LBorrowerId_F.LastNameOrOrgName as BorrowerId_F,
p.AllocatedNoteID_F,
p.DealAllocationTotalCommitmentAmtConverted,
p.DealAllocationAmtConverted,
p.PropertyForSale,
orgBrokerOrgId_F.OrganizationName as BrokerOrgId_F,
orgPreliminarySponsorOrgId_F.OrganizationName as  PreliminarySponsorOrgId_F,
p.DepositAmount,
p.ProspectivePropertySaleDate,
CntManagementCo_ContactID_F.FirstName+'' ''+CntManagementCo_ContactID_F.LastName as ManagementCo_ContactID_F,
p.PropertyPositionLastChangedDate,
p.ExcludeProperty,
LDownPaymentSourceCD_F.DownpaymentSourceDesc as DownPaymentSourceCD_F,
p.ExistingDebt
from tblproperty p
left join tblzCdPropertyTypeMajor LPropertyTypeMajorCd_F on  LPropertyTypeMajorCd_F.PropertyTypeMajorCd = p.PropertyTypeMajorCd_F
left join tblzCdPropertyTypeMinor LPropertyTypeMinorCd_F on  LPropertyTypeMinorCd_F.PropertyTypeMinorCd = p.PropertyTypeMinorCd_F
left join tblzCdPropertyTypeMajor LSecondaryPropTypeMajCd_F on  LSecondaryPropTypeMajCd_F.PropertyTypeMajorCd = p.SecondaryPropTypeMajCd_F
left join tblManagementCompany LManagementCoId_F on  LManagementCoId_F.ManagementCoId = p.ManagementCoId_F
left join tblzCdPropertyFeeLeaseHold LFeeLeaseHoldCd_F on  LFeeLeaseHoldCd_F.PropertyFeeLeaseHoldCd = p.FeeLeaseHoldCd_F
left join tblzCdPropertyPosition LPropertyPositionCd_F on  LPropertyPositionCd_F.PropertyPositionCd = p.PropertyPositionCd_F	
left join tblzCDCurrencyCd LPropertyCurrencyCD_F on LPropertyCurrencyCD_F.CurrencyCd = p.PropertyCurrencyCD_F	
left join tblzCdRegion LRegionCD_F on LRegionCD_F.RegionCD = p.RegionCD_F	
left join tblzCdMarket LMarketCd_F on LMarketCd_F.MarketCd = p.MarketCd_F
left join tblzCdSubMarket LSubMarketId_F on LSubMarketId_F.SubMarketId = p.SubMarketId_F	
left join tblBorrower LBorrowerId_F on LBorrowerId_F.BorrowerId = p.BorrowerId_F
left join tblOrganization orgBrokerOrgId_F on orgBrokerOrgId_F.OrganizationID = p.BrokerOrgId_F

left join tblOrganization orgPreliminarySponsorOrgId_F on orgPreliminarySponsorOrgId_F.OrganizationID = p.PreliminarySponsorOrgId_F

left join tblContact CntManagementCo_ContactID_F on CntManagementCo_ContactID_F.contactid = p.ManagementCo_ContactID_F
left join tblzCDDownpaymentSource LDownPaymentSourceCD_F on LDownPaymentSourceCD_F.DownPaymentSourceCD = p.DownPaymentSourceCD_F

WHERE (p.AuditAddDate > '''+Convert(Nvarchar(max),@LastBatchStart,121)+'''
				and p.AuditAddDate <  '''+Convert(Nvarchar(max),@CurrentBatchStart,121)+'''  ) 
				OR 
				(p.AuditUpdateDate > '''+Convert(Nvarchar(max),@LastBatchStart,121)+'''
				and p.AuditUpdateDate < '''+Convert(Nvarchar(max),@CurrentBatchStart,121)+''' )
'


--===================================
Declare @BSProperty as Table(
 PropertyId	int NULL ,
  ControlId_F	nvarchar(256)  NULL ,
  PropertyNumber	nvarchar(20)  NULL ,
  PropertyName	nvarchar(100)  NULL ,
  PropertyTypeMajorCd_F	nvarchar(256)  NULL ,
  PropertyTypeMinorCd_F	nvarchar(256)  NULL ,
  SecondaryPropTypeMajCd_F	nvarchar(256)  NULL ,
  ManagementCoId_F	nvarchar(256)  NULL ,
  FeeLeaseHoldCd_F	nvarchar(256)  NULL ,
  StreetAddress	nvarchar(150)  NULL ,
  City	nvarchar(50)  NULL ,
  State	nvarchar(10)  NULL ,
  ZipCode	nvarchar(15)  NULL ,
  County	nvarchar(50)  NULL ,
  Country	nvarchar(50)  NULL ,
  InspectionDate	datetime  NULL ,
  LandArea	float  NULL ,
  UnitMeasurePrimary	nvarchar(10)  NULL ,
  NumberOfUnitsPrimary	int  NULL ,
  GSFPrimary	int  NULL ,
  NRSFPrimary	int  NULL ,
  UnitMeasureSecondary	nvarchar(10)  NULL ,
  NumberOfUnitsSecondary	int  NULL ,
  GSFSecondary	int  NULL ,
  NRSFSecondary	int  NULL ,
  NumberOfBuildings	int  NULL ,
  NumberOfStories	int  NULL ,
  NumberOfPads	int  NULL ,
  NumberOfElevators	int  NULL ,
  NumberOfParkingSpaces	int  NULL ,
  Security	nvarchar(3)  NULL ,
  OnSiteMan	nvarchar(10)  NULL ,
  Tenancy	nvarchar(10)  NULL ,
  PercentOwnOcc	float  NULL ,
  LocationType	nvarchar(10)  NULL ,
  DateAcquired	datetime  NULL ,
  YearBuilt	int  NULL ,
  YearRenovated	int  NULL ,
  Zoning	varchar(1000)  NULL ,
  LegallyConformingUse	nvarchar(3)  NULL ,
  PropertyPositionCd_F	nvarchar(256)  NULL ,
  PropertyPositionStatus	nvarchar(500)  NULL ,
  AcquisitionAmount	decimal(28, 15)  NULL ,
  BorrowerEquity	decimal(28, 15)  NULL ,
  TitleCompany	nvarchar(100)  NULL ,
  TitleVesting	nvarchar(50)  NULL ,
  TitlePolicyDate	datetime  NULL ,
  TitleARMEndorsement	nvarchar(3)  NULL ,
  PolicyAmount	float  NULL ,
  TitleNegAmortizationEnd	nvarchar(3)  NULL ,
  TitleFutAdvancesEnd	nvarchar(3)  NULL ,
  OwnershipInterest	nvarchar(15)  NULL ,
  GroundLeaseFlag	nvarchar(3)  NULL ,
  CrossCollateralized	nvarchar(3)  NULL ,
  NumberGroundLeases	int  NULL ,
  CrossDefaulted	nvarchar(3)  NULL ,
  CrossDefaultedComment	nvarchar(max)  NULL ,
  DescriptionOfOtherLiens	nvarchar(255)  NULL ,
  DescriptionOfAddCollateral	nvarchar(255)  NULL ,
  TitlePolicyType	nvarchar(20)  NULL ,
  TitleCom	nvarchar(255)  NULL ,
  LienPosition	nvarchar(25)  NULL ,
  SubFin	nvarchar(50)  NULL ,
  UnsecDebtAllow	nvarchar(5)  NULL ,
  PropertyComment	nvarchar(max)  NULL ,
  DealAllocationAmt	decimal(28, 15)  NULL ,
  DealAllocatedPctSecondary	float  NULL ,
  PropertyClass	nvarchar(20)  NULL ,
  NewConstruction	nvarchar(3)  NULL ,
  SingleTennant	nvarchar(3)  NULL ,
  EstValue	decimal(28, 15)  NULL ,
  EstNCF	decimal(28, 15)  NULL ,
  EstNOI	decimal(28, 15)  NULL ,
  WindHailInsSw	nvarchar(3)  NULL ,
  WindHailInsAmt	decimal(28, 15)  NULL ,
  FloodInsSw	nvarchar(3)  NULL ,
  FloodInsAmt	decimal(28, 15)  NULL ,
  HurricaneInsSw	nvarchar(3)  NULL ,
  HurricaneInsAmt	decimal(28, 15)  NULL ,
  NonConformingComment	nvarchar(max)  NULL ,
  OccupancyVsMarket	nvarchar(20)  NULL ,
  MarketForecast	nvarchar(20)  NULL ,
  EstimatedMarketValue	decimal(28, 15)  NULL ,
  LandOInsuranceReq	nvarchar(3)  NULL ,
  ProjectedMoodysCapRate	float  NULL ,
  ActualMoodysCapRate	float  NULL ,
  ApprovedNCF	decimal(28, 15)  NULL ,
  ApprovedBy_UserId_F	nvarchar(256)  NULL ,
  ApprovalDate	datetime  NULL ,
  AlliedStressPct	float  NULL ,
  DefaultRiskRating	smallint  NULL ,
  HardEquity	decimal(28, 15)  NULL ,
  LenderPropertyIdentifier	nvarchar(20)  NULL ,
  ManRelated	nvarchar(3)  NULL ,
  ManAgreeAssgnable	nvarchar(3)  NULL ,
  ManAgreeExpireDate	datetime  NULL ,
  ManAgreeFee	float  NULL ,
  ManFeeCollectedOn	nvarchar(30)  NULL ,
  ManAgreeSubordinate	nvarchar(3)  NULL ,
  ManAgreeCure	nvarchar(3)  NULL ,
  ManLeasingAgent	nvarchar(30)  NULL ,
  ManLeasingCommission	nvarchar(max)  NULL ,
  ManAgreementComment	nvarchar(max)  NULL ,
  ManContactName	nvarchar(30)  NULL ,
  ManYearsManageProp	int  NULL ,
  ManAgreementDate	datetime  NULL ,
  ManAgreementRenewal	nvarchar(50)  NULL ,
  ManOwnerRightToTerminate	nvarchar(3)  NULL ,
  ManTerminationCond	nvarchar(max)  NULL ,
  ManLenderRightToTerminate	nvarchar(3)  NULL ,
  ManIncentiveFee	nvarchar(3)  NULL ,
  ManChangeConditions	nvarchar(3)  NULL ,
  ManChangeConditionsComment	nvarchar(max)  NULL ,
  ManIncentiveFeeSub	nvarchar(3)  NULL ,
  ManIncentiveFeeComment	nvarchar(max)  NULL ,
  LoanCondVacancyAllowance	nvarchar(30)  NULL ,
  LoanCondManagementFee	float  NULL ,
  LoanCondFranchiseFee	float  NULL ,
  LoanCondAdvertisingFee	float  NULL ,
  LoanCondReplacementReserves	nvarchar(max)  NULL ,
  LoanCondRolloverCosts	nvarchar(max)  NULL ,
  MpDueOnSale	nvarchar(3)  NULL ,
  MpDueOnSaleDesc	nvarchar(max)  NULL ,
  MpDueOnEncumbrance	nvarchar(3)  NULL ,
  MpDueOnEncumbranceDesc	nvarchar(max)  NULL ,
  MpCashAudit	nvarchar(3)  NULL ,
  MpCashAuditDesc	nvarchar(max)  NULL ,
  MpPartialRelease	nvarchar(3)  NULL ,
  MpPartialReleaseDesc	nvarchar(max)  NULL ,
  MpPartialReleaseAmt	decimal(28, 15)  NULL ,
  MpRightToInspectProperty	nvarchar(100)  NULL ,
  MpOpStatementFrequency	nvarchar(100)  NULL ,
  MpRentRollFrequency	nvarchar(100)  NULL ,
  MpUnsecuredDebtAllowed	nvarchar(3)  NULL ,
  MpMaxUnsecuredDebtAmt	decimal(28, 15)  NULL ,
  MpTradePayablesMaxAmt	decimal(28, 15)  NULL ,
  MpTradePayablesDaysOut	int  NULL ,
  MpComment	nvarchar(max)  NULL ,
  MarketCapRate	float  NULL ,
  LenderCapRate	float  NULL ,
  PhotoLink	nvarchar(100)  NULL ,
  DirctionsLink	nvarchar(max)  NULL ,
  AuditAddDate	datetime  NULL ,
  AuditAddUserId	nvarchar(150)  NULL ,
  AuditUpdateDate	datetime  NULL ,
  AuditUpdateUserId	nvarchar(150)  NULL ,
  DealAllocationAmtPCT	float  NULL ,
  PropertyCurrencyCD_F	nvarchar(256)  NULL ,
  CeilingHeight	decimal  NULL ,
  RegionCD_F	nvarchar(256)  NULL ,
  TerrorInsSw	nvarchar(3)  NULL ,
  TerrorInsAmt	decimal(28, 15)  NULL ,
  MarketCd_F	nvarchar(256)  NULL ,
  ReleaseCollateralSW	bit  NULL ,
  TotalCostBasis	decimal  NULL ,
  ExternalPropertyNumber	nvarchar(20)  NULL ,
  MpSubstitutionAllowed	nvarchar(3)  NULL ,
  MpSubstitutionAllowedDesc	nvarchar(max)  NULL ,
  ManAgreeAmount	decimal(28, 15)  NULL ,
  SubMarketManComment	nvarchar(max)  NULL ,
  ManFeeType	nvarchar(3)  NULL ,
  ParkingSpacesCovered	int  NULL ,
  ParkingSpacesUncovered	int  NULL ,
  MANSFUnitsRmsUnderManinSubMarket	bigint  NULL ,
  SubMarketId_F	nvarchar(256)  NULL ,
  Latitude	decimal  NULL ,
  Longitude	decimal  NULL ,
  UnderwrittenManagementFee	float  NULL ,
  ClientIdentifier	nvarchar(50)  NULL ,
  DealAllocationTotalCommitmentAmt	decimal(30, 15)  NULL ,
  BorrowerId_F	nvarchar(256)  NULL ,
  AllocatedNoteID_F	nvarchar(256)  NULL ,
  DealAllocationTotalCommitmentAmtConverted	decimal(30, 15)  NULL ,
  DealAllocationAmtConverted	decimal(30, 15)  NULL ,
  PropertyForSale	nvarchar(3)  NULL ,
  BrokerOrgId_F	nvarchar(256)  NULL ,
  PreliminarySponsorOrgId_F	nvarchar(256)  NULL ,
  DepositAmount	decimal(28, 15)  NULL ,
  ProspectivePropertySaleDate	datetime  NULL ,
  ManagementCo_ContactID_F	nvarchar(256)  NULL ,
  PropertyPositionLastChangedDate	datetime  NULL ,
  ExcludeProperty	bit  NULL ,
  DownPaymentSourceCD_F	nvarchar(256)  NULL ,
  ExistingDebt	decimal(28, 15)  NULL,
  ShardName nvarchar(max)  NULL 
)

INSERT INTO @BSProperty
(
  PropertyId,
  ControlId_F,
  PropertyNumber,
  PropertyName,
  PropertyTypeMajorCd_F,
  PropertyTypeMinorCd_F,
  SecondaryPropTypeMajCd_F,
  ManagementCoId_F,
  FeeLeaseHoldCd_F,
  StreetAddress,
  City,
  State,
  ZipCode,
  County,
  Country,
  InspectionDate,
  LandArea,
  UnitMeasurePrimary,
  NumberOfUnitsPrimary,
  GSFPrimary,
  NRSFPrimary,
  UnitMeasureSecondary,
  NumberOfUnitsSecondary,
  GSFSecondary,
  NRSFSecondary,
  NumberOfBuildings,
  NumberOfStories,
  NumberOfPads,
  NumberOfElevators,
  NumberOfParkingSpaces,
  Security,
  OnSiteMan,
  Tenancy,
  PercentOwnOcc,
  LocationType,
  DateAcquired,
  YearBuilt,
  YearRenovated,
  Zoning,
  LegallyConformingUse,
  PropertyPositionCd_F,
  PropertyPositionStatus,
  AcquisitionAmount,
  BorrowerEquity,
  TitleCompany,
  TitleVesting,
  TitlePolicyDate,
  TitleARMEndorsement,
  PolicyAmount,
  TitleNegAmortizationEnd,
  TitleFutAdvancesEnd,
  OwnershipInterest,
  GroundLeaseFlag,
  CrossCollateralized,
  NumberGroundLeases,
  CrossDefaulted,
  CrossDefaultedComment,
  DescriptionOfOtherLiens,
  DescriptionOfAddCollateral,
  TitlePolicyType,
  TitleCom,
  LienPosition,
  SubFin,
  UnsecDebtAllow,
  PropertyComment,
  DealAllocationAmt,
  DealAllocatedPctSecondary,
  PropertyClass,
  NewConstruction,
  SingleTennant,
  EstValue,
  EstNCF,
  EstNOI,
  WindHailInsSw,
  WindHailInsAmt,
  FloodInsSw,
  FloodInsAmt,
  HurricaneInsSw,
  HurricaneInsAmt,
  NonConformingComment,
  OccupancyVsMarket,
  MarketForecast,
  EstimatedMarketValue,
  LandOInsuranceReq,
  ProjectedMoodysCapRate,
  ActualMoodysCapRate,
  ApprovedNCF,
  ApprovedBy_UserId_F,
  ApprovalDate,
  AlliedStressPct,
  DefaultRiskRating,
  HardEquity,
  LenderPropertyIdentifier,
  ManRelated,
  ManAgreeAssgnable,
  ManAgreeExpireDate,
  ManAgreeFee,
  ManFeeCollectedOn,
  ManAgreeSubordinate,
  ManAgreeCure,
  ManLeasingAgent,
  ManLeasingCommission,
  ManAgreementComment,
  ManContactName,
  ManYearsManageProp,
  ManAgreementDate,
  ManAgreementRenewal,
  ManOwnerRightToTerminate,
  ManTerminationCond,
  ManLenderRightToTerminate,
  ManIncentiveFee,
  ManChangeConditions,
  ManChangeConditionsComment,
  ManIncentiveFeeSub,
  ManIncentiveFeeComment,
  LoanCondVacancyAllowance,
  LoanCondManagementFee,
  LoanCondFranchiseFee,
  LoanCondAdvertisingFee,
  LoanCondReplacementReserves,
  LoanCondRolloverCosts,
  MpDueOnSale,
  MpDueOnSaleDesc,
  MpDueOnEncumbrance,
  MpDueOnEncumbranceDesc,
  MpCashAudit,
  MpCashAuditDesc,
  MpPartialRelease,
  MpPartialReleaseDesc,
  MpPartialReleaseAmt,
  MpRightToInspectProperty,
  MpOpStatementFrequency,
  MpRentRollFrequency,
  MpUnsecuredDebtAllowed,
  MpMaxUnsecuredDebtAmt,
  MpTradePayablesMaxAmt,
  MpTradePayablesDaysOut,
  MpComment,
  MarketCapRate,
  LenderCapRate,
  PhotoLink,
  DirctionsLink,
  AuditAddDate,
  AuditAddUserId,
  AuditUpdateDate,
  AuditUpdateUserId,
  DealAllocationAmtPCT,
  PropertyCurrencyCD_F,
  CeilingHeight,
  RegionCD_F,
  TerrorInsSw,
  TerrorInsAmt,
  MarketCd_F,
  ReleaseCollateralSW,
  TotalCostBasis,
  ExternalPropertyNumber,
  MpSubstitutionAllowed,
  MpSubstitutionAllowedDesc,
  ManAgreeAmount,
  SubMarketManComment,
  ManFeeType,
  ParkingSpacesCovered,
  ParkingSpacesUncovered,
  MANSFUnitsRmsUnderManinSubMarket,
  SubMarketId_F,
  Latitude,
  Longitude,
  UnderwrittenManagementFee,
  ClientIdentifier,
  DealAllocationTotalCommitmentAmt,
  BorrowerId_F,
  AllocatedNoteID_F,
  DealAllocationTotalCommitmentAmtConverted,
  DealAllocationAmtConverted,
  PropertyForSale,
  BrokerOrgId_F,
  PreliminarySponsorOrgId_F,
  DepositAmount,
  ProspectivePropertySaleDate,
  ManagementCo_ContactID_F,
  PropertyPositionLastChangedDate,
  ExcludeProperty,
  DownPaymentSourceCD_F,
  ExistingDebt,
  ShardName
)
EXEC sp_execute_remote @data_source_name  = N'RemoteReferenceData', @stmt = @query



--===================================

Truncate table [DW].[L_UwPropertyBI]

INSERT INTO [DW].[L_UwPropertyBI]
( PropertyId,
  ControlId_F,
  PropertyNumber,
  PropertyName,
  PropertyTypeMajorCd_F,
  PropertyTypeMinorCd_F,
  SecondaryPropTypeMajCd_F,
  ManagementCoId_F,
  FeeLeaseHoldCd_F,
  StreetAddress,
  City,
  State,
  ZipCode,
  County,
  Country,
  InspectionDate,
  LandArea,
  UnitMeasurePrimary,
  NumberOfUnitsPrimary,
  GSFPrimary,
  NRSFPrimary,
  UnitMeasureSecondary,
  NumberOfUnitsSecondary,
  GSFSecondary,
  NRSFSecondary,
  NumberOfBuildings,
  NumberOfStories,
  NumberOfPads,
  NumberOfElevators,
  NumberOfParkingSpaces,
  Security,
  OnSiteMan,
  Tenancy,
  PercentOwnOcc,
  LocationType,
  DateAcquired,
  YearBuilt,
  YearRenovated,
  Zoning,
  LegallyConformingUse,
  PropertyPositionCd_F,
  PropertyPositionStatus,
  AcquisitionAmount,
  BorrowerEquity,
  TitleCompany,
  TitleVesting,
  TitlePolicyDate,
  TitleARMEndorsement,
  PolicyAmount,
  TitleNegAmortizationEnd,
  TitleFutAdvancesEnd,
  OwnershipInterest,
  GroundLeaseFlag,
  CrossCollateralized,
  NumberGroundLeases,
  CrossDefaulted,
  CrossDefaultedComment,
  DescriptionOfOtherLiens,
  DescriptionOfAddCollateral,
  TitlePolicyType,
  TitleCom,
  LienPosition,
  SubFin,
  UnsecDebtAllow,
  PropertyComment,
  DealAllocationAmt,
  DealAllocatedPctSecondary,
  PropertyClass,
  NewConstruction,
  SingleTennant,
  EstValue,
  EstNCF,
  EstNOI,
  WindHailInsSw,
  WindHailInsAmt,
  FloodInsSw,
  FloodInsAmt,
  HurricaneInsSw,
  HurricaneInsAmt,
  NonConformingComment,
  OccupancyVsMarket,
  MarketForecast,
  EstimatedMarketValue,
  LandOInsuranceReq,
  ProjectedMoodysCapRate,
  ActualMoodysCapRate,
  ApprovedNCF,
  ApprovedBy_UserId_F,
  ApprovalDate,
  AlliedStressPct,
  DefaultRiskRating,
  HardEquity,
  LenderPropertyIdentifier,
  ManRelated,
  ManAgreeAssgnable,
  ManAgreeExpireDate,
  ManAgreeFee,
  ManFeeCollectedOn,
  ManAgreeSubordinate,
  ManAgreeCure,
  ManLeasingAgent,
  ManLeasingCommission,
  ManAgreementComment,
  ManContactName,
  ManYearsManageProp,
  ManAgreementDate,
  ManAgreementRenewal,
  ManOwnerRightToTerminate,
  ManTerminationCond,
  ManLenderRightToTerminate,
  ManIncentiveFee,
  ManChangeConditions,
  ManChangeConditionsComment,
  ManIncentiveFeeSub,
  ManIncentiveFeeComment,
  LoanCondVacancyAllowance,
  LoanCondManagementFee,
  LoanCondFranchiseFee,
  LoanCondAdvertisingFee,
  LoanCondReplacementReserves,
  LoanCondRolloverCosts,
  MpDueOnSale,
  MpDueOnSaleDesc,
  MpDueOnEncumbrance,
  MpDueOnEncumbranceDesc,
  MpCashAudit,
  MpCashAuditDesc,
  MpPartialRelease,
  MpPartialReleaseDesc,
  MpPartialReleaseAmt,
  MpRightToInspectProperty,
  MpOpStatementFrequency,
  MpRentRollFrequency,
  MpUnsecuredDebtAllowed,
  MpMaxUnsecuredDebtAmt,
  MpTradePayablesMaxAmt,
  MpTradePayablesDaysOut,
  MpComment,
  MarketCapRate,
  LenderCapRate,
  PhotoLink,
  DirctionsLink,
  AuditAddDate,
  AuditAddUserId,
  AuditUpdateDate,
  AuditUpdateUserId,
  DealAllocationAmtPCT,
  PropertyCurrencyCD_F,
  CeilingHeight,
  RegionCD_F,
  TerrorInsSw,
  TerrorInsAmt,
  MarketCd_F,
  ReleaseCollateralSW,
  TotalCostBasis,
  ExternalPropertyNumber,
  MpSubstitutionAllowed,
  MpSubstitutionAllowedDesc,
  ManAgreeAmount,
  SubMarketManComment,
  ManFeeType,
  ParkingSpacesCovered,
  ParkingSpacesUncovered,
  MANSFUnitsRmsUnderManinSubMarket,
  SubMarketId_F,
  Latitude,
  Longitude,
  UnderwrittenManagementFee,
  ClientIdentifier,
  DealAllocationTotalCommitmentAmt,
  BorrowerId_F,
  AllocatedNoteID_F,
  DealAllocationTotalCommitmentAmtConverted,
  DealAllocationAmtConverted,
  PropertyForSale,
  BrokerOrgId_F,
  PreliminarySponsorOrgId_F,
  DepositAmount,
  ProspectivePropertySaleDate,
  ManagementCo_ContactID_F,
  PropertyPositionLastChangedDate,
  ExcludeProperty,
  DownPaymentSourceCD_F,
  ExistingDebt)

Select
  PropertyId,
  ControlId_F,
  PropertyNumber,
  PropertyName,
  PropertyTypeMajorCd_F,
  PropertyTypeMinorCd_F,
  SecondaryPropTypeMajCd_F,
  ManagementCoId_F,
  FeeLeaseHoldCd_F,
  StreetAddress,
  City,
  State,
  ZipCode,
  County,
  Country,
  InspectionDate,
  LandArea,
  UnitMeasurePrimary,
  NumberOfUnitsPrimary,
  GSFPrimary,
  NRSFPrimary,
  UnitMeasureSecondary,
  NumberOfUnitsSecondary,
  GSFSecondary,
  NRSFSecondary,
  NumberOfBuildings,
  NumberOfStories,
  NumberOfPads,
  NumberOfElevators,
  NumberOfParkingSpaces,
  Security,
  OnSiteMan,
  Tenancy,
  PercentOwnOcc,
  LocationType,
  DateAcquired,
  YearBuilt,
  YearRenovated,
  Zoning,
  LegallyConformingUse,
  PropertyPositionCd_F,
  PropertyPositionStatus,
  AcquisitionAmount,
  BorrowerEquity,
  TitleCompany,
  TitleVesting,
  TitlePolicyDate,
  TitleARMEndorsement,
  PolicyAmount,
  TitleNegAmortizationEnd,
  TitleFutAdvancesEnd,
  OwnershipInterest,
  GroundLeaseFlag,
  CrossCollateralized,
  NumberGroundLeases,
  CrossDefaulted,
  CrossDefaultedComment,
  DescriptionOfOtherLiens,
  DescriptionOfAddCollateral,
  TitlePolicyType,
  TitleCom,
  LienPosition,
  SubFin,
  UnsecDebtAllow,
  PropertyComment,
  DealAllocationAmt,
  DealAllocatedPctSecondary,
  PropertyClass,
  NewConstruction,
  SingleTennant,
  EstValue,
  EstNCF,
  EstNOI,
  WindHailInsSw,
  WindHailInsAmt,
  FloodInsSw,
  FloodInsAmt,
  HurricaneInsSw,
  HurricaneInsAmt,
  NonConformingComment,
  OccupancyVsMarket,
  MarketForecast,
  EstimatedMarketValue,
  LandOInsuranceReq,
  ProjectedMoodysCapRate,
  ActualMoodysCapRate,
  ApprovedNCF,
  ApprovedBy_UserId_F,
  ApprovalDate,
  AlliedStressPct,
  DefaultRiskRating,
  HardEquity,
  LenderPropertyIdentifier,
  ManRelated,
  ManAgreeAssgnable,
  ManAgreeExpireDate,
  ManAgreeFee,
  ManFeeCollectedOn,
  ManAgreeSubordinate,
  ManAgreeCure,
  ManLeasingAgent,
  ManLeasingCommission,
  ManAgreementComment,
  ManContactName,
  ManYearsManageProp,
  ManAgreementDate,
  ManAgreementRenewal,
  ManOwnerRightToTerminate,
  ManTerminationCond,
  ManLenderRightToTerminate,
  ManIncentiveFee,
  ManChangeConditions,
  ManChangeConditionsComment,
  ManIncentiveFeeSub,
  ManIncentiveFeeComment,
  LoanCondVacancyAllowance,
  LoanCondManagementFee,
  LoanCondFranchiseFee,
  LoanCondAdvertisingFee,
  LoanCondReplacementReserves,
  LoanCondRolloverCosts,
  MpDueOnSale,
  MpDueOnSaleDesc,
  MpDueOnEncumbrance,
  MpDueOnEncumbranceDesc,
  MpCashAudit,
  MpCashAuditDesc,
  MpPartialRelease,
  MpPartialReleaseDesc,
  MpPartialReleaseAmt,
  MpRightToInspectProperty,
  MpOpStatementFrequency,
  MpRentRollFrequency,
  MpUnsecuredDebtAllowed,
  MpMaxUnsecuredDebtAmt,
  MpTradePayablesMaxAmt,
  MpTradePayablesDaysOut,
  MpComment,
  MarketCapRate,
  LenderCapRate,
  PhotoLink,
  DirctionsLink,
  AuditAddDate,
  AuditAddUserId,
  AuditUpdateDate,
  AuditUpdateUserId,
  DealAllocationAmtPCT,
  PropertyCurrencyCD_F,
  CeilingHeight,
  RegionCD_F,
  TerrorInsSw,
  TerrorInsAmt,
  MarketCd_F,
  ReleaseCollateralSW,
  TotalCostBasis,
  ExternalPropertyNumber,
  MpSubstitutionAllowed,
  MpSubstitutionAllowedDesc,
  ManAgreeAmount,
  SubMarketManComment,
  ManFeeType,
  ParkingSpacesCovered,
  ParkingSpacesUncovered,
  MANSFUnitsRmsUnderManinSubMarket,
  SubMarketId_F,
  Latitude,
  Longitude,
  UnderwrittenManagementFee,
  ClientIdentifier,
  DealAllocationTotalCommitmentAmt,
  BorrowerId_F,
  AllocatedNoteID_F,
  DealAllocationTotalCommitmentAmtConverted,
  DealAllocationAmtConverted,
  PropertyForSale,
  BrokerOrgId_F,
  PreliminarySponsorOrgId_F,
  DepositAmount,
  ProspectivePropertySaleDate,
  ManagementCo_ContactID_F,
  PropertyPositionLastChangedDate,
  ExcludeProperty,
  DownPaymentSourceCD_F,
  ExistingDebt
From @BSProperty d
--where PropertyId <> 17225




SET @RowCount = @@ROWCOUNT
Print(char(9) +'usp_ImportUwProperty - ROWCOUNT = '+cast(@RowCount  as varchar(100)));





UPDATE [DW].BatchDetail
SET
LandingEndTime = GETDATE(),
LandingRecordCount = @RowCount
WHERE BatchDetailId = @id

END
