

GO

Print('Drop Note Column')
DROP INDEX nci_wi_Note_5B01D5D239DCA23B4AE9F241C5EF292D ON CRE.NOTE

ALTER TABLE CRE.NOTE DROP COLUMN ExtendedMaturityScenario1
ALTER TABLE CRE.NOTE DROP COLUMN ExtendedMaturityScenario2
ALTER TABLE CRE.NOTE DROP COLUMN ExtendedMaturityScenario3