--Drop TABLE [IO].[L_Remittance]
CREATE TABLE [IO].[L_Remittance] (
    [LandingID]            UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [FileBatchlogid]       INT              NULL,
    [PayeeHolder]         NVARCHAR (256)   NULL,
    [InvestorNo]           NVARCHAR (256)   NULL,
    [LoanNo]               NVARCHAR (256)   NULL,
    [NoteID]               NVARCHAR (256)   NULL,
    [BorrowerName]         NVARCHAR (256)   NULL,
    [DueDate]              DATE         NULL,
    [PaidThroughDate]      DATE        NULL,
    [BegBalance]           DECIMAL (28, 15) NULL,
    [ScheduledInterestAmount]     DECIMAL (28, 15) NULL,
    [ScheduledPrincipalAmount]     DECIMAL (28, 15) NULL,
    [TotalScheduledPIDue]           DECIMAL (28, 15) NULL,
    [PIDue]                DECIMAL (28, 15) NULL,
    [Principal]            DECIMAL (28, 15) NULL,
    [Interest]             DECIMAL (28, 15) NULL,
    [InterestRate]         DECIMAL (28, 15) NULL,
    [ServiceFeeRate]       DECIMAL (28, 15) NULL,
    [NetYield]             DECIMAL (28, 15) NULL,
    [ServiceFee]           DECIMAL (28, 15) NULL,
    [AdditionalFees]           DECIMAL (28, 15) NULL,
    [NetInterest]          DECIMAL (28, 15) NULL,
    [ExitFees]             DECIMAL (28, 15) NULL,
    [ExtensionFees]        DECIMAL (28, 15) NULL,
    [PrepaymentYMFees]     DECIMAL (28, 15) NULL,
    [OtherFees]            DECIMAL (28, 15) NULL,
    [AddlPrincipal]        DECIMAL (28, 15) NULL,
    [AddlInt]              DECIMAL (28, 15) NULL,
    [TotalRemit]           DECIMAL (28, 15) NULL,
    [OtherPrincipalAdjustments]     DECIMAL (28, 15) NULL,
    [CurrentMonthFundings]           DECIMAL (28, 15) NULL,
    [CurrentFundingDate]    DATE NULL,
    [PrincipalAdjNonCash]  DECIMAL (28, 15) NULL,
    [EndingBalance]        DECIMAL (28, 15) NULL,
    [TranDate]             DATE         NULL,
    [AccrualDays]          INT              NULL,
    [NOTEDATE]             DATE        NULL,
    [MaturityDate]         DATE        NULL,
    [Comments]             NVARCHAR (256)   NULL,
    [CurrentDIAL]          DECIMAL (28, 15) NULL,
    [PropertyName]         NVARCHAR (512)   NULL,
    [RemitDate]            DATE        NULL,
    [Exception]            NVARCHAR (256)   NULL,
    [ExceptionFee]            NVARCHAR (256)   NULL,
     L_Remittance_AutoID int IDENTITY(1,1)
);


go
ALTER TABLE [IO].[L_Remittance]
ADD CONSTRAINT PK_L_Remittance_L_Remittance_AutoID PRIMARY KEY (L_Remittance_AutoID);
