# Staging-calc

trigger:
  branches:
    include:
      - Staging
  paths:
    include:
      - src/CRES.NoteCalculatorServiceMVC/*

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:

- script: echo Hello, world!
  displayName: 'Run script for Calc API'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/CRES.NoteCalculatorServiceMVC/CRES.NoteCalculatorServiceMVC.csproj'
    workingDirectory: 'src/CRES.NoteCalculatorServiceMVC'
    
# Delete previous zip files
- script: del /s /q $(System.DefaultWorkingDirectory)\*.zip
  displayName: "Delete previous zip files"

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/CRES.NoteCalculatorServiceMVC/CRES.NoteCalculatorServiceMVC.csproj'
    workingDirectory: 'src/CRES.NoteCalculatorServiceMVC'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Microsoft Partner Network 3'
    appType: 'webApp'
    WebAppName: 'StagingCres4Calculator'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'