
#Pipeline for Stagging

trigger:
  branches:
    include:
      - Staging 
  paths:
    include:
      - src/CRES.WebClient.V1/*

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'


steps:

- script: echo Hello, world!
  displayName: 'Run script for Web'

- task: UseNode@1
  inputs:
     version: '14.2.0'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: 'src/CRES.WebClient.V1/ClientApp'
    verbose: false

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    workingDir: 'src/CRES.WebClient.V1/ClientApp'
    verbose: false
    customCommand: 'run build'

# Delete previous zip files
- script: del /s /q $(System.DefaultWorkingDirectory)\*.zip
  displayName: "Delete previous zip files"
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/CRES.WebClient.V1/CRES.WebClient.V1.csproj'
    workingDirectory: 'src/CRES.WebClient.V1'
 
  
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Microsoft Partner Network 3'
    appType: 'webApp'
    WebAppName: 'stagingcres4'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
 