CREATE PROCEDURE [dbo].[usp_GetDiscrepancyForWireConfirmed] 
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED


	Select Distinct d.DealName as [Deal Name]
	,d.CREDealID as [Deal ID]
	--,COUNT(df.DealFundingID) [No of Record]
	,df.Date
	,Cast(ROUND(df.Amount,2) as decimal(28,2)) as Amount
	,Cast(ROUND(df.RequiredEquity,2) as decimal(28,2)) as [Required Equity]
	,Cast(ROUND(df.AdditionalEquity,2) as decimal(28,2)) as [Additional Equity]
	,lpurpose.Name as Purpose
	,lGeneratedBy.Name as [Generated By]
	,tblWF.WF_CurrentStatusDisplayName as [Status]
	,df.Comment

	from cre.dealfunding df
	inner join cre.deal d on d.dealid = df.dealid
	Left Join core.lookup lpurpose on lpurpose.lookupid = df.purposeid
	Left Join core.lookup lGeneratedBy on lGeneratedBy.lookupid = df.GeneratedBy
	Left Join(
		Select TaskId,StatusName as WF_CurrentStatus,WF_CurrentStatusDisplayName,WF_isParticipate,OrderIndex
		From(
			SELECT td.TaskId
			,sm.StatusName
			,td.WFTaskDetailID	
			,(Case WHEN tblNoti.taskid is not null and sm.StatusName='Completed' then 'Completed' 
				when (lPurposeType.Value1='WF_UNDERREVIEW' or df.[Amount] = 0) then sm.WFUnderReviewDisplayName 
				else sm.DealFundingDisplayName end) as WF_CurrentStatusDisplayName
			,ROW_NUMBER() OVER(Partition by td.TaskId order by td.TaskId,td.WFTaskDetailID desc) rno
			,COUNT( td.WFTaskDetailID ) OVER(Partition by td.TaskId) WF_isParticipate
			,spm.OrderIndex

			FROM [CRE].[WFTaskDetail] td       
			INNER JOIN [CRE].[WFStatusPurposeMapping] spm ON spm.WFStatusPurposeMappingID = td.WFStatusPurposeMappingID      
			INNER JOIN [CRE].[WFStatusMaster] sm ON sm.WFStatusMasterID = spm.WFStatusMasterID    
			left JOin(
				select TaskID from cre.WFNotification where WFNotificationMasterID=2 and ActionType=577
			)tblNoti on tblNoti.taskid = td.taskid	
			LEFT JOIN cre.dealfunding df on df.dealfundingid = td.taskid
			LEFT JOIN core.Lookup lPurposeType on lPurposeType.LookupID = df.PurposeID and lPurposeType.ParentID = 50	
			WHERE td.TaskId in (Select dealfundingid from cre.dealfunding )	
		)a
		where rno = 1
   )tblWF on tblWF.TaskId = df.dealfundingid


	where d.isdeleted <> 1
	and Applied <> 1
	and d.[status] =323
	and df.date <= CAST(getdate() as Date)
	and d.DealName NOT LIKE '%copy%'

	Group by d.DealName,d.CREDealID,df.Date
	,df.Amount
	,lpurpose.Name
	,lGeneratedBy.Name
	,df.Comment
	,tblWF.WF_CurrentStatusDisplayName
	,df.RequiredEquity
	,df.AdditionalEquity

	
	Order by d.DealName,d.CREDealID,df.Date
	





 	SET TRANSACTION ISOLATION LEVEL READ COMMITTED

END

