CREATE PROCEDURE [dbo].[usp_GetXIRRFilters] 
AS  
BEGIN  
  
SET NOCOUNT ON;  
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  

 Select RowNumber, XIRRConfigID, XIRRFilterSetupID, FilterDropDownValue from [CRE].[XIRRConfigFilter]

SET TRANSACTION ISOLATION LEVEL READ COMMITTED  
END 