CREATE PROCEDURE [dbo].[usp_DeleteTagMasterXIRR]   
	@TagMasterXIRRID int,
	@UserID uniqueidentifier
AS  
BEGIN    
  
SET NOCOUNT ON;  
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  

	DELETE FROM CRE.TagMasterXIRR WHERE TagMasterXIRRID = @TagMasterXIRRID

SET TRANSACTION ISOLATION LEVEL READ COMMITTED 
END