CREATE Procedure [dbo].[usp_LCGetAccrualFieldsFromNotePeriodicByCRENoteID]  --'2307' ,''
(
@CRENoteID nvarchar(256),
@AnalysisName nvarchar(256)
)
AS

BEGIN
	SET NOCOUNT ON;
    
	Declare @NoteID UNIQUEIDENTIFIER = (select noteid from cre.note where crenoteid =@CRENoteID);
	Declare @AnalysisID UNIQUEIDENTIFIER = (select AnalysisID from  Core.Analysis where [name] = @AnalysisName);
    Declare @PeriodID UNIQUEIDENTIFIER = (Select Top 1 PeriodID from core.[Period] where IsDeleted <> 1 order by CloseDate desc)

	IF EXISTS(select al.AnalysisID from Core.Analysis al
				left join Core.AnalysisParameter ap on al.AnalysisID = ap.AnalysisID
				LEFT Join Core.Lookup lCalculationMode on lCalculationMode.LookupID=ap.CalculationMode and lCalculationMode.ParentID = 79
				Where lCalculationMode.Name like '%Prospective%'
				and al.AnalysisID = @AnalysisID	)
	BEGIN
		Select 
		[PeriodID]           
		,[NotePeriodicCalcID]
		,[NoteID]    
		,[PeriodEndDate]
		,[Month]
		,[ActualCashFlows] 
		,[GAAPCashFlows]   
		,[EndingGAAPBookValue]
		--,[TotalGAAPIncomeforthePeriod] 
		--,[InterestAccrualforthePeriod] 
		--,[PIKInterestAccrualforthePeriod]           
		,[TotalAmortAccrualForPeriod]  
		,[AccumulatedAmort]
		,[BeginningBalance]
		,[TotalFutureAdvancesForThePeriod]          
		,[TotalDiscretionaryCurtailmentsforthePeriod] 
		,[InterestPaidOnPaymentDate]   
		,[TotalCouponStrippedforthePeriod]          
		,[CouponStrippedonPaymentDate] 
		,[ScheduledPrincipal] 
		,[PrincipalPaid]   
		,[BalloonPayment]  
		,[EndingBalance]   
		,[ExitFeeIncludedInLevelYield] 
		,[ExitFeeExcludedFromLevelYield]            
		,[AdditionalFeesIncludedInLevelYield]       
		,[AdditionalFeesExcludedFromLevelYield]     
		,[OriginationFeeStripping]     
		,[ExitFeeStrippingIncldinLevelYield]        
		,[ExitFeeStrippingExcldfromLevelYield]      
		,[AddlFeesStrippingIncldinLevelYield]       
		,[AddlFeesStrippingExcldfromLevelYield]     
		,[EndOfPeriodWAL]  
		,[PIKInterestFromPIKSourceNote]
		,[PIKInterestTransferredToRelatedNote]      
		,[PIKInterestForThePeriod]     
		,[BeginningPIKBalanceNotInsideLoanBalance]  
		,[PIKInterestForPeriodNotInsideLoanBalance] 
		,[PIKBalanceBalloonPayment]    
		,[EndingPIKBalanceNotInsideLoanBalance]     
		,[CostBasis]       
		,[PreCapBasis]     
		,[BasisCap]        
		,[AmortAccrualLevelYield]      
		,[ScheduledPrincipalShortfall] 
		,[PrincipalShortfall] 
		,[PrincipalLoss]   
		,[InterestForPeriodShortfall]  
		,[InterestPaidOnPMTDateShortfall]           
		,[CumulativeInterestPaidOnPMTDateShortfall] 
		,[InterestShortfallLoss]       
		,[InterestShortfallRecovery]   
		,[BeginningFinancingBalance]   
		,[TotalFinancingDrawsCurtailmentsForPeriod] 
		,[FinancingBalloon]
		,[EndingFinancingBalance]      
		,[FinancingInterestPaid]       
		,[FinancingFeesPaid]  
		,[PeriodLeveredYield] 
		,[OrigFeeAccrual]  
		,[DiscountPremiumAccrual]      
		,[ExitFeeAccrual]  
		,[AllInCouponRate] 
		,[GrossDeferredFees]  
		,[DeferredFeesReceivable]      
		,[CleanCostPrice]  
		,[AmortizedCostPrice] 
		,[AdditionalFeeAccrual]        
		,[CapitalizedCostAccrual]      
		,[DailySpreadInterestbeforeStrippingRule]   
		,[DailyLiborInterestbeforeStrippingRule]    
		,[ReversalofPriorInterestAccrual]           
		,[InterestReceivedinCurrentPeriod]          
		,[CurrentPeriodInterestAccrual]
		,[TotalGAAPInterestFortheCurrentPeriod]     
		,[CleanCost]       
		,[InvestmentBasis] 
		,[CurrentPeriodInterestAccrualPeriodEnddate]
		,[LIBORPercentage] 
		,[SpreadPercentage]
		,[AnalysisID]
		,[FeeStrippedforthePeriod]     
		,[PIKInterestPercentage]       
		,[AmortizedCost]   
		,[InterestSuspenseAccountActivityforthePeriod]
		,[InterestSuspenseAccountBalance]           
		,[AllInBasisValuation]
		,[AllInPIKRate]    
		,[CurrentPeriodPIKInterestAccrualPeriodEnddate]
		,[PIKInterestPaidForThePeriod] 
		,[PIKInterestAppliedForThePeriod]           
		,[EndingPreCapPVBasis]
		,[LevelYieldIncomeForThePeriod]
		,[PVAmortTotalIncomeMethod]    
		,[EndingCleanCostLY]  
		,[EndingAccumAmort]
		,[PVAmortForThePeriod]
		,[EndingSLBasis]   
		,[SLAmortForThePeriod]
		,[SLAmortOfTotalFeesInclInLY]  
		,[SLAmortOfDiscountPremium]    
		,[SLAmortOfCapCost]
		,[EndingAccumSLAmort] 
		,[EndingPreCapGAAPBasis]       
		,[PIKPrincipalPaidForThePeriod]
		,[RemainingUnfundedCommitment]
		,CalcEngineType
		,[IsDeleted]
		,[CreatedBy]
		,[CreatedDate]
		,[UpdatedBy]
		,[UpdatedDate]
		,CurrentPeriodPIKInterestAccrual
		FROM Core.AccountingClosePeriodicArchive
		where NoteID = @NoteID 		
		and PeriodID = @PeriodID
		order by  PeriodEndDate 
	END
	ELSE
	BEGIN
		Select 
		[PeriodID]           
		,[NotePeriodicCalcID]
		,[NoteID]    
		,[PeriodEndDate]
		,[Month]
		,[ActualCashFlows] 
		,[GAAPCashFlows]   
		,[EndingGAAPBookValue]
		--,[TotalGAAPIncomeforthePeriod] 
		--,[InterestAccrualforthePeriod] 
		--,[PIKInterestAccrualforthePeriod]           
		,[TotalAmortAccrualForPeriod]  
		,[AccumulatedAmort]
		,[BeginningBalance]
		,[TotalFutureAdvancesForThePeriod]          
		,[TotalDiscretionaryCurtailmentsforthePeriod] 
		,[InterestPaidOnPaymentDate]   
		,[TotalCouponStrippedforthePeriod]          
		,[CouponStrippedonPaymentDate] 
		,[ScheduledPrincipal] 
		,[PrincipalPaid]   
		,[BalloonPayment]  
		,[EndingBalance]   
		,[ExitFeeIncludedInLevelYield] 
		,[ExitFeeExcludedFromLevelYield]            
		,[AdditionalFeesIncludedInLevelYield]       
		,[AdditionalFeesExcludedFromLevelYield]     
		,[OriginationFeeStripping]     
		,[ExitFeeStrippingIncldinLevelYield]        
		,[ExitFeeStrippingExcldfromLevelYield]      
		,[AddlFeesStrippingIncldinLevelYield]       
		,[AddlFeesStrippingExcldfromLevelYield]     
		,[EndOfPeriodWAL]  
		,[PIKInterestFromPIKSourceNote]
		,[PIKInterestTransferredToRelatedNote]      
		,[PIKInterestForThePeriod]     
		,[BeginningPIKBalanceNotInsideLoanBalance]  
		,[PIKInterestForPeriodNotInsideLoanBalance] 
		,[PIKBalanceBalloonPayment]    
		,[EndingPIKBalanceNotInsideLoanBalance]     
		,[CostBasis]       
		,[PreCapBasis]     
		,[BasisCap]        
		,[AmortAccrualLevelYield]      
		,[ScheduledPrincipalShortfall] 
		,[PrincipalShortfall] 
		,[PrincipalLoss]   
		,[InterestForPeriodShortfall]  
		,[InterestPaidOnPMTDateShortfall]           
		,[CumulativeInterestPaidOnPMTDateShortfall] 
		,[InterestShortfallLoss]       
		,[InterestShortfallRecovery]   
		,[BeginningFinancingBalance]   
		,[TotalFinancingDrawsCurtailmentsForPeriod] 
		,[FinancingBalloon]
		,[EndingFinancingBalance]      
		,[FinancingInterestPaid]       
		,[FinancingFeesPaid]  
		,[PeriodLeveredYield] 
		,[OrigFeeAccrual]  
		,[DiscountPremiumAccrual]      
		,[ExitFeeAccrual]  
		,[AllInCouponRate] 
		,[GrossDeferredFees]  
		,[DeferredFeesReceivable]      
		,[CleanCostPrice]  
		,[AmortizedCostPrice] 
		,[AdditionalFeeAccrual]        
		,[CapitalizedCostAccrual]      
		,[DailySpreadInterestbeforeStrippingRule]   
		,[DailyLiborInterestbeforeStrippingRule]    
		,[ReversalofPriorInterestAccrual]           
		,[InterestReceivedinCurrentPeriod]          
		,[CurrentPeriodInterestAccrual]
		,[TotalGAAPInterestFortheCurrentPeriod]     
		,[CleanCost]       
		,[InvestmentBasis] 
		--,[CurrentPeriodInterestAccrualPeriodEnddate]
		,[LIBORPercentage] 
		,[SpreadPercentage]
		,[AnalysisID]
		,[FeeStrippedforthePeriod]     
		,[PIKInterestPercentage]       
		,[AmortizedCost]   
		,[InterestSuspenseAccountActivityforthePeriod]
		,[InterestSuspenseAccountBalance]           
		,[AllInBasisValuation]
		,[AllInPIKRate]    
		,CurrentPeriodPIKInterestAccrual ---as [CurrentPeriodPIKInterestAccrualPeriodEnddate]
		,[PIKInterestPaidForThePeriod] 
		,[PIKInterestAppliedForThePeriod]           
		,[EndingPreCapPVBasis]
		,[LevelYieldIncomeForThePeriod]
		,[PVAmortTotalIncomeMethod]    
		,[EndingCleanCostLY]  
		,[EndingAccumAmort]
		,[PVAmortForThePeriod]
		,[EndingSLBasis]   
		,[SLAmortForThePeriod]
		,[SLAmortOfTotalFeesInclInLY]  
		,[SLAmortOfDiscountPremium]    
		,[SLAmortOfCapCost]
		,[EndingAccumSLAmort] 
		,[EndingPreCapGAAPBasis]       
		,[PIKPrincipalPaidForThePeriod]
		,[RemainingUnfundedCommitment]
		,CalcEngineType
		,[IsDeleted]
		,[CreatedBy]
		,[CreatedDate]
		,[UpdatedBy]
		,[UpdatedDate]
		FROM Core.AccountingClosePeriodicArchive
		where NoteID = @NoteID 
		and AnalysisID = @AnalysisID 	
		and PeriodID = @PeriodID
		and 1 = 0
		order by  PeriodEndDate 
	END
	
END

 
