
-- [dbo].[usp_GetHolidayMaster]  'B0E6697B-3534-4C09-BE0A-04473401AB93'
CREATE PROCEDURE [dbo].[usp_GetHolidayMaster] 
(
	@UserID UNIQUEIDENTIFIER
)
AS
BEGIN
 SET NOCOUNT ON;
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
  

   SELECT  CalendarName,HolidayMasterID
   from [App].[HoliDaysMaster] 
    
	
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED
END
