

CREATE PROCEDURE [dbo].[usp_ImportCashflowAndTranEntryDataFromCRESProdToIntegration]
AS
BEGIN
    SET NOCOUNT ON;
	
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

truncate table [DW].[Prod_Cashflow]
truncate table [DW].[Prod_TransactionEntry]



INSERT INTO [DW].[Prod_Cashflow]
           ([NotePeriodicCalcID]
           ,[NoteID]
           ,[CRENoteID]
           ,[PeriodEndDate]
           ,[Month]
           ,[ActualCashFlows]
           ,[GAAPCashFlows]
           ,[EndingGAAPBookValue]
           ,[TotalGAAPIncomeforthePeriod]
           ,[InterestAccrualforthePeriod]
           ,[PIKInterestAccrualforthePeriod]
           ,[TotalAmortAccrualForPeriod]
           ,[AccumulatedAmort]
           ,[BeginningBalance]
           ,[TotalFutureAdvancesForThePeriod]
           ,[TotalDiscretionaryCurtailmentsforthePeriod]
           ,[InterestPaidOnPaymentDate]
           ,[TotalCouponStrippedforthePeriod]
           ,[CouponStrippedonPaymentDate]
           ,[ScheduledPrincipal]
           ,[PrincipalPaid]
           ,[BalloonPayment]
           ,[EndingBalance]
           ,[ExitFeeIncludedInLevelYield]
           ,[ExitFeeExcludedFromLevelYield]
           ,[AdditionalFeesIncludedInLevelYield]
           ,[AdditionalFeesExcludedFromLevelYield]
           ,[OriginationFeeStripping]
           ,[ExitFeeStrippingIncldinLevelYield]
           ,[ExitFeeStrippingExcldfromLevelYield]
           ,[AddlFeesStrippingIncldinLevelYield]
           ,[AddlFeesStrippingExcldfromLevelYield]
           ,[EndOfPeriodWAL]
           ,[PIKInterestFromPIKSourceNote]
           ,[PIKInterestTransferredToRelatedNote]
           ,[PIKInterestForThePeriod]
           ,[BeginningPIKBalanceNotInsideLoanBalance]
           ,[PIKInterestForPeriodNotInsideLoanBalance]
           ,[PIKBalanceBalloonPayment]
           ,[EndingPIKBalanceNotInsideLoanBalance]
           ,[CostBasis]
           ,[PreCapBasis]
           ,[BasisCap]
           ,[AmortAccrualLevelYield]
           ,[ScheduledPrincipalShortfall]
           ,[PrincipalShortfall]
           ,[PrincipalLoss]
           ,[InterestForPeriodShortfall]
           ,[InterestPaidOnPMTDateShortfall]
           ,[CumulativeInterestPaidOnPMTDateShortfall]
           ,[InterestShortfallLoss]
           ,[InterestShortfallRecovery]
           ,[BeginningFinancingBalance]
           ,[TotalFinancingDrawsCurtailmentsForPeriod]
           ,[FinancingBalloon]
           ,[EndingFinancingBalance]
           ,[FinancingInterestPaid]
           ,[FinancingFeesPaid]
           ,[PeriodLeveredYield]
           ,[OrigFeeAccrual]
           ,[DiscountPremiumAccrual]
           ,[ExitFeeAccrual]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[UpdatedBy]
           ,[UpdatedDate]
           ,[AllInCouponRate]
           ,[CleanCost]
           ,[GrossDeferredFees]
           ,[DeferredFeesReceivable]
           ,[CleanCostPrice]
           ,[AmortizedCostPrice]
           ,[AdditionalFeeAccrual]
           ,[CapitalizedCostAccrual]
           ,[DailySpreadInterestbeforeStrippingRule]
           ,[DailyLiborInterestbeforeStrippingRule]
           ,[ReversalofPriorInterestAccrual]
           ,[InterestReceivedinCurrentPeriod]
           ,[CurrentPeriodInterestAccrual]
           ,[TotalGAAPInterestFortheCurrentPeriod])
SELECT [NotePeriodicCalcID]
      ,cf.[NoteID]
      ,n.[CRENoteID]
      ,[PeriodEndDate]
      ,[Month]
      ,[ActualCashFlows]
      ,[GAAPCashFlows]
      ,[EndingGAAPBookValue]
      ,[TotalGAAPIncomeforthePeriod]
      ,[InterestAccrualforthePeriod]
      ,[PIKInterestAccrualforthePeriod]
      ,[TotalAmortAccrualForPeriod]
      ,[AccumulatedAmort]
      ,[BeginningBalance]
      ,[TotalFutureAdvancesForThePeriod]
      ,[TotalDiscretionaryCurtailmentsforthePeriod]
      ,[InterestPaidOnPaymentDate]
      ,[TotalCouponStrippedforthePeriod]
      ,[CouponStrippedonPaymentDate]
      ,[ScheduledPrincipal]
      ,[PrincipalPaid]
      ,[BalloonPayment]
      ,[EndingBalance]
      ,[ExitFeeIncludedInLevelYield]
      ,[ExitFeeExcludedFromLevelYield]
      ,[AdditionalFeesIncludedInLevelYield]
      ,[AdditionalFeesExcludedFromLevelYield]
      ,[OriginationFeeStripping]
      ,[ExitFeeStrippingIncldinLevelYield]
      ,[ExitFeeStrippingExcldfromLevelYield]
      ,[AddlFeesStrippingIncldinLevelYield]
      ,[AddlFeesStrippingExcldfromLevelYield]
      ,[EndOfPeriodWAL]
      ,[PIKInterestFromPIKSourceNote]
      ,[PIKInterestTransferredToRelatedNote]
      ,[PIKInterestForThePeriod]
      ,[BeginningPIKBalanceNotInsideLoanBalance]
      ,[PIKInterestForPeriodNotInsideLoanBalance]
      ,[PIKBalanceBalloonPayment]
      ,[EndingPIKBalanceNotInsideLoanBalance]
      ,[CostBasis]
      ,[PreCapBasis]
      ,[BasisCap]
      ,[AmortAccrualLevelYield]
      ,[ScheduledPrincipalShortfall]
      ,[PrincipalShortfall]
      ,[PrincipalLoss]
      ,[InterestForPeriodShortfall]
      ,[InterestPaidOnPMTDateShortfall]
      ,[CumulativeInterestPaidOnPMTDateShortfall]
      ,[InterestShortfallLoss]
      ,[InterestShortfallRecovery]
      ,[BeginningFinancingBalance]
      ,[TotalFinancingDrawsCurtailmentsForPeriod]
      ,[FinancingBalloon]
      ,[EndingFinancingBalance]
      ,[FinancingInterestPaid]
      ,[FinancingFeesPaid]
      ,[PeriodLeveredYield]
      ,[OrigFeeAccrual]
      ,[DiscountPremiumAccrual]
      ,[ExitFeeAccrual]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[UpdatedBy]
      ,[UpdatedDate]
      ,[AllInCouponRate]
      ,[CleanCost]
      ,[GrossDeferredFees]
      ,[DeferredFeesReceivable]
      ,[CleanCostPrice]
      ,[AmortizedCostPrice]
      ,[AdditionalFeeAccrual]
      ,[CapitalizedCostAccrual]
      ,[DailySpreadInterestbeforeStrippingRule]
      ,[DailyLiborInterestbeforeStrippingRule]
      ,[ReversalofPriorInterestAccrual]
      ,[InterestReceivedinCurrentPeriod]
      ,[CurrentPeriodInterestAccrual]
      ,[TotalGAAPInterestFortheCurrentPeriod]
  FROM [dbo].[Ex_Prod_NotePeriodicCalc] cf
  Inner Join [dbo].[Ex_Prod_Note] n on n.noteid = cf.noteid

 ---------------------------------------

  INSERT INTO [DW].[Prod_TransactionEntry]
           ([TransactionEntryID]
           ,[NoteID]
           ,[CRENoteID]
           ,[Date]
           ,[Amount]
           ,[Type]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[UpdatedBy]
           ,[UpdatedDate])

SELECT [TransactionEntryID]
      ,tr.[NoteID]
      ,n.[CRENoteID]
      ,tr.[Date]
      ,tr.[Amount]
      ,tr.[Type]
      ,tr.[CreatedBy]
      ,tr.[CreatedDate]
      ,tr.[UpdatedBy]
      ,tr.[UpdatedDate]
  FROM [dbo].[Ex_Prod_TransactionEntry] tr
  Inner Join [dbo].[Ex_Prod_Note] n on n.noteid = tr.noteid

SET TRANSACTION ISOLATION LEVEL READ COMMITTED



END


