

CREATE PROCEDURE [DBO].[usp_getScenarioDownload] --'0FFB2916-876A-4E3C-AE6D-86672AA1508D','0FFB2916-876A-4E3C-AE6D-86672AA1508D',NULL
(
	@USERID UNIQUEIDENTIFIER,
	@SCENARIOID UNIQUEIDENTIFIER,
	@TOTALCOUNT INT OUTPUT 
) 
AS
BEGIN

  SET NOCOUNT ON;
  SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	DECLARE @COLS AS NVARCHAR(MAX);
	DECLARE @COLS1 AS NVARCHAR(MAX),
	@QUERY  AS NVARCHAR(MAX),
	@INDEXLOOKUPID INT,
	@ROWCOUNT INT,
	@DAYSINTERVAL INT=30


	
	SET @INDEXLOOKUPID=32

	SELECT @COLS = STUFF((SELECT ',ISNULL(' + QUOTENAME( COL.NAME ) +','''') AS [' +COL.NAME +']'       
	FROM(
	SELECT NAME FROM CORE.LOOKUP WHERE PARENTID=@INDEXLOOKUPID AND NAME <>'N/A' 
	)COL
				   
		FOR XML PATH(''), TYPE
		).value('.', 'NVARCHAR(MAX)') 
	,1,1,'')


	SELECT @COLS1 = STUFF((SELECT ',' + QUOTENAME( COL.NAME )       
	FROM(
	SELECT NAME FROM CORE.LOOKUP WHERE PARENTID=@INDEXLOOKUPID AND NAME <>'N/A' 
	)COL
				   
		FOR XML PATH(''), TYPE
		).value('.', 'NVARCHAR(MAX)') 
	,1,1,'')




    BEGIN
	
	 
		
	SET @QUERY = N' 
	SELECT LEFT(CONVERT(VARCHAR, ISNULL(DATE,''''), 101), 10) AS DATE ,' + @COLS + N'
	FROM (SELECT 				
		  IND.DATE      
		  ,L.NAME
		  ,(CAST(CAST(ISNULL(IND.VALUE,0) AS NUMERIC(18,15))  AS VARCHAR) ) AS VALUE
			 FROM CORE.INDEXES IND 
			 LEFT JOIN CORE.LOOKUP L ON IND.INDEXTYPE =L.LOOKUPID
			 Inner Join COre.IndexesMaster im on im.IndexesMasterID = IND.IndexesMasterID
			 Inner Join COre.AnalysisParameter ap on ap.IndexScenarioOverride =  im.IndexesMasterID
			 WHERE ap.ANALYSISID='''+CONVERT(VARCHAR(300),@SCENARIOID)+'''
			  UNION 
			SELECT 				
		  NULL DATE      
		  ,L.NAME
		  ,'''' VALUE
		 FROM CORE.LOOKUP L WHERE PARENTID='''+CONVERT(VARCHAR(MAX),@INDEXLOOKUPID)+'''  AND NAME <>''N/A'' 
		  AND NOT EXISTS (SELECT *
			 FROM CORE.INDEXES IND 
			 LEFT JOIN CORE.LOOKUP L ON IND.INDEXTYPE =L.LOOKUPID
			 Inner Join COre.IndexesMaster im on im.IndexesMasterID = IND.IndexesMasterID
			 Inner Join COre.AnalysisParameter ap on ap.IndexScenarioOverride =  im.IndexesMasterID
			 WHERE ap.ANALYSISID='''+CONVERT(VARCHAR(300),@SCENARIOID)+''')

	) AS SQ_UP
	PIVOT (
	MIN([VALUE])
	FOR [NAME] IN (' + @COLS1 + N')
	) AS P ORDER BY P.DATE ASC'
	
PRINT(@QUERY)
EXEC SP_EXECUTESQL @QUERY;

	END


  
  SET TRANSACTION ISOLATION LEVEL READ COMMITTED 

 END


 

