

 
CREATE PROCEDURE [dbo].[usp_GetScenarioList]
	
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED   
     	 select [Name] from Core.Analysis 			  
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED
END

