

CREATE PROCEDURE [dbo].[usp_GetNotePeriodicCalcVSTOByBatchLogID] --12
 @BatchLogID int

AS  
BEGIN  
  
 SET NOCOUNT ON;  
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  
 
	Select  
CRENoteID
,PeriodEndDate
,Month
,ActualCashFlows
,GAAPCashFlows
,EndingGAAPBookValue
,TotalGAAPIncomeforthePeriod
,InterestAccrualforthePeriod
,PIKInterestAccrualforthePeriod
,TotalAmortAccrualForPeriod
,AccumulatedAmort
,BeginningBalance
,TotalFutureAdvancesForThePeriod
,TotalDiscretionaryCurtailmentsforthePeriod
,InterestPaidOnPaymentDate
,TotalCouponStrippedforthePeriod
,CouponStrippedonPaymentDate
,ScheduledPrincipal
,PrincipalPaid
,BalloonPayment
,EndingBalance
,ExitFeeIncludedInLevelYield
,ExitFeeExcludedFromLevelYield
,AdditionalFeesIncludedInLevelYield
,AdditionalFeesExcludedFromLevelYield
,OriginationFeeStripping
,ExitFeeStrippingIncldinLevelYield
,ExitFeeStrippingExcldfromLevelYield
,AddlFeesStrippingIncldinLevelYield
,AddlFeesStrippingExcldfromLevelYield
,EndOfPeriodWAL
,PIKInterestFromPIKSourceNote
,PIKInterestTransferredToRelatedNote
,PIKInterestForThePeriod
,BeginningPIKBalanceNotInsideLoanBalance
,PIKInterestForPeriodNotInsideLoanBalance
,PIKBalanceBalloonPayment
,EndingPIKBalanceNotInsideLoanBalance
,CostBasis
,PreCapBasis
,BasisCap
,AmortAccrualLevelYield
,ScheduledPrincipalShortfall
,PrincipalShortfall
,PrincipalLoss
,InterestForPeriodShortfall
,InterestPaidOnPMTDateShortfall
,CumulativeInterestPaidOnPMTDateShortfall
,InterestShortfallLoss
,InterestShortfallRecovery
,BeginningFinancingBalance
,TotalFinancingDrawsCurtailmentsForPeriod
,FinancingBalloon
,EndingFinancingBalance
,FinancingInterestPaid
,FinancingFeesPaid
,PeriodLeveredYield 
,OrigFeeAccrual
,DiscountPremiumAccrual
,ExitFeeAccrual
,AllInCouponRate
,GrossDeferredFees
,DeferredFeesReceivable
,CleanCostPrice
,AmortizedCostPrice
,AdditionalFeeAccrual
,CapitalizedCostAccrual
,DailySpreadInterestbeforeStrippingRule
,DailyLiborInterestbeforeStrippingRule
,ReversalofPriorInterestAccrual
,InterestReceivedinCurrentPeriod
,CurrentPeriodInterestAccrual
,TotalGAAPInterestFortheCurrentPeriod
,CleanCost
,InvestmentBasis
,CurrentPeriodInterestAccrualPeriodEnddate
,LIBORPercentage
,SpreadPercentage
,AnalysisID
,FeeStrippedforthePeriod
,PIKInterestPercentage
,AmortizedCost
,InterestSuspenseAccountActivityforthePeriod
,InterestSuspenseAccountBalance
,AllInBasisValuation
,AllInPIKRate
,CurrentPeriodPIKInterestAccrualPeriodEnddate
,PIKInterestPaidForThePeriod
,PIKInterestAppliedForThePeriod
,SizerScenario  
 from CRE.NotePeriodicCalcVSTO 
	where BatchDetailAsyncCalcVSTOId in (Select BatchDetailAsyncCalcVSTOId from [CRE].BatchDetailAsyncCalcVSTO where BatchLogAsyncCalcVSTOID = @BatchLogID)


 SET TRANSACTION ISOLATION LEVEL READ COMMITTED  
END  
