
CREATE PROCEDURE [dbo].[usp_CreateBatchCalculationTag] --'EE1EAE55-C8D9-4B79-94AF-3EC6DC7F6211','EE1EAE55-C8D9-4B79-94AF-3EC6DC7F6211','Running','StartTime'
AS
BEGIN
	declare @tBatchCalculationMasterID as table
	(
		ID int Identity(1,1),
		BatchCalculationMasterID int,
		UserID uniqueidentifier,
		BatchType varchar(50),
		AnalysisID uniqueidentifier,
		PortfolioMasterID int null
	)

	 DECLARE @ID int=1,
	 @BatchCalculationMasterID int,
	 @UserID uniqueidentifier,
	 @BatchType varchar(50),
	 @AnalysisID uniqueidentifier,
     @PortfolioMasterID int=null

		
		
		insert into @tBatchCalculationMasterID
		select BatchCalculationMasterID,UserID,BatchType,AnalysisID,PortfolioMasterID from [Core].[BatchCalculationMaster]  
		where [Status]='In-Process' and EndTime is not null and BatchType='AllWithTag'
		
		update [Core].[BatchCalculationMaster] set [Status]='Tag-Creation' where  BatchCalculationMasterID in 
		(
			select BatchCalculationMasterID FROM @tBatchCalculationMasterID
		)
		
		--create autogenerated tag for batch type 'ALL'
		WHILE EXISTS (SELECT * FROM @tBatchCalculationMasterID  where ID=@ID)
		 BEGIN 
			select @BatchCalculationMasterID = BatchCalculationMasterID,@UserID=UserID,@BatchType=BatchType,@AnalysisID=AnalysisID,@PortfolioMasterID = PortfolioMasterID FROM @tBatchCalculationMasterID where ID=@ID
			EXEC [dbo].[usp_CreateAutoTag] @AnalysisID,'PortfolioRun','System generated tag from portfolio run.',@UserID,@PortfolioMasterID,@BatchCalculationMasterID
			--Mark Status from 'In-Process' to 'Completed'
			update [Core].[BatchCalculationMaster] set [Status]='Completed' where BatchCalculationMasterID=@BatchCalculationMasterID
			SET @ID+=1
		 END

END



