 
CREATE PROCEDURE [dbo].[usp_InsertUpdateNotePeriodicCalcByNoteIDVSTO] 
	@noteAdditinallist tempNotePeriodicCalcVSTO READONLY,
	@CreatedBy nvarchar(256)	
AS
BEGIN
 

	Declare @CRENoteID nvarchar(256) = (select Top 1 CRENoteID from @noteAdditinallist)

	DELETE FROM CRE.NotePeriodicCalcVSTO WHERE CRENoteID = @CRENoteID 

		INSERT INTO [CRE].NotePeriodicCalcVSTO
		(
		 BatchDetailAsyncCalcVSTOId
		,CRENoteID
		,[PeriodEndDate]
		,[Month]
		,[ActualCashFlows]
		,[GAAPCashFlows]
		,[EndingGAAPBookValue]	 
		,[PIKInterestAccrualforthePeriod]
		,[TotalAmortAccrualForPeriod]
		,[AccumulatedAmort]
		,[BeginningBalance]
		,[TotalFutureAdvancesForThePeriod]
		,[TotalDiscretionaryCurtailmentsforthePeriod]	
		,[TotalCouponStrippedforthePeriod]
		,[CouponStrippedonPaymentDate]
		,[ScheduledPrincipal]
		,[PrincipalPaid]
		,[BalloonPayment]
		,[EndingBalance]		 
		,[EndOfPeriodWAL]
		,[PIKInterestFromPIKSourceNote]
		,[PIKInterestTransferredToRelatedNote]
		,[PIKInterestForThePeriod]
		,[BeginningPIKBalanceNotInsideLoanBalance]
		,[PIKInterestForPeriodNotInsideLoanBalance]
		,[PIKBalanceBalloonPayment]
		,[EndingPIKBalanceNotInsideLoanBalance]	
		,[AmortAccrualLevelYield]
		,[ScheduledPrincipalShortfall]
		,[PrincipalShortfall]
		,[PrincipalLoss]
		,[InterestForPeriodShortfall]
		,[InterestPaidOnPMTDateShortfall]
		,[CumulativeInterestPaidOnPMTDateShortfall]
		,[InterestShortfallLoss]
		,[InterestShortfallRecovery]
		,[BeginningFinancingBalance]
		,[TotalFinancingDrawsCurtailmentsForPeriod]
		,[FinancingBalloon]
		,[EndingFinancingBalance]
		,[FinancingInterestPaid]
		,[FinancingFeesPaid]
		,[PeriodLeveredYield]
		,[OrigFeeAccrual] 
		,[DiscountPremiumAccrual] 
		,[ExitFeeAccrual] 
		,[AllInCouponRate]
		,[CreatedBy]
		,[CreatedDate]
		,[UpdatedBy]
		,[UpdatedDate]
		,[CleanCost]
		,[GrossDeferredFees]
		,[DeferredFeesReceivable]
		,[CleanCostPrice]
		,[AmortizedCostPrice]
		,[AdditionalFeeAccrual]
		,[CapitalizedCostAccrual]	 
		,ReversalofPriorInterestAccrual
		,InterestReceivedinCurrentPeriod
		,CurrentPeriodInterestAccrual
		,TotalGAAPInterestFortheCurrentPeriod	 
		,InvestmentBasis
		,CurrentPeriodInterestAccrualPeriodEnddate
		,AnalysisID
		,FeeStrippedforthePeriod
		,PIKInterestPercentage
		,AmortizedCost
		,InterestSuspenseAccountActivityforthePeriod
		,InterestSuspenseAccountBalance
		,AllInBasisValuation
		,AllInPIKRate
		,CurrentPeriodPIKInterestAccrualPeriodEnddate
		,PIKInterestPaidForThePeriod
		,PIKInterestAppliedForThePeriod
		,SizerScenario
		--,EndingPreCapPVBasis
		--,LevelYieldIncomeForThePeriod
		--,PVAmortTotalIncomeMethod
		--,EndingCleanCostLY
		--,EndingAccumAmort
		--,PVAmortForThePeriod
		--,EndingSLBasis
		--,SLAmortForThePeriod
		--,SLAmortOfTotalFeesInclInLY
		--,SLAmortOfDiscountPremium
		--,SLAmortOfCapCost
		--,EndingAccumSLAmort
		--,EndingPreCapGAAPBasis
		
		)

		Select 
		BatchDetailAsyncCalcVSTOId
		,CRENoteID
		,[PeriodEndDate]
		,[Month]
		,[ActualCashFlows]
		,[GAAPCashFlows]
		,[EndingGAAPBookValue]			
		,[PIKInterestAccrualforthePeriod]
		,[TotalAmortAccrualForPeriod]
		,[AccumulatedAmort]
		,[BeginningBalance]
		,[TotalFutureAdvancesForThePeriod]
		,[TotalDiscretionaryCurtailmentsforthePeriod]			
		,[TotalCouponStrippedforthePeriod]
		,[CouponStrippedonPaymentDate]
		,[ScheduledPrincipal]
		,[PrincipalPaid]
		,[BalloonPayment]
		,[EndingBalance]				 
		,[EndOfPeriodWAL]
		,[PIKInterestFromPIKSourceNote]
		,[PIKInterestTransferredToRelatedNote]
		,[PIKInterestForThePeriod]
		,[BeginningPIKBalanceNotInsideLoanBalance]
		,[PIKInterestForPeriodNotInsideLoanBalance]
		,[PIKBalanceBalloonPayment]
		,[EndingPIKBalanceNotInsideLoanBalance]			
		,[AmortAccrualLevelYield]
		,[ScheduledPrincipalShortfall]
		,[PrincipalShortfall]
		,[PrincipalLoss]
		,[InterestForPeriodShortfall]
		,[InterestPaidOnPMTDateShortfall]
		,[CumulativeInterestPaidOnPMTDateShortfall]
		,[InterestShortfallLoss]
		,[InterestShortfallRecovery]
		,[BeginningFinancingBalance]
		,[TotalFinancingDrawsCurtailmentsForPeriod]
		,[FinancingBalloon]
		,[EndingFinancingBalance]
		,[FinancingInterestPaid]
		,[FinancingFeesPaid]
		,[PeriodLeveredYield]
		,[OrigFeeAccrual] 
		,[DiscountPremiumAccrual] 
		,[ExitFeeAccrual] 
		,[AllInCouponRate]
		,@CreatedBy
		,GETDATE()
		,@CreatedBy
		,GETDATE()
		,[CleanCost]
		,[GrossDeferredFees]
		,[DeferredFeesReceivable]
		,[CleanCostPrice]
		,[AmortizedCostPrice]
		,[AdditionalFeeAccrual]
		,[CapitalizedCostAccrual]			
		,ReversalofPriorInterestAccrual
		,InterestReceivedinCurrentPeriod
		,CurrentPeriodInterestAccrual
		,TotalGAAPInterestFortheCurrentPeriod
		,InvestmentBasis
		,CurrentPeriodInterestAccrualPeriodEnddate			
		,AnalysisID
		,FeeStrippedforthePeriod
		,PIKInterestPercentage
		,AmortizedCost
		,InterestSuspenseAccountActivityforthePeriod
		,InterestSuspenseAccountBalance
		,AllInBasisValuation
		,AllInPIKRate
		,CurrentPeriodPIKInterestAccrualPeriodEnddate
		,PIKInterestPaidForThePeriod
		,PIKInterestAppliedForThePeriod		
		,SizerScenario			 
		--,EndingPreCapPVBasis
		--,LevelYieldIncomeForThePeriod
		--,PVAmortTotalIncomeMethod
		--,EndingCleanCostLY
		--,EndingAccumAmort
		--,PVAmortForThePeriod
		--,EndingSLBasis
		--,SLAmortForThePeriod
		--,SLAmortOfTotalFeesInclInLY
		--,SLAmortOfDiscountPremium
		--,SLAmortOfCapCost
		--,EndingAccumSLAmort
		--,EndingPreCapGAAPBasis				
		From  @noteAdditinallist


END


