CREATE TABLE [CRE].[Note] (
    [NoteID]                                               UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [Account_AccountID]                                    UNIQUEIDENTIFIER NOT NULL,
    [DealID]                                               UNIQUEIDENTIFIER NOT NULL,
    [CRENoteID]                                            NVARCHAR (256)   NULL,
    [ClientNoteID]                                         NVARCHAR (256)   NULL,
    [Comments]                                             NVARCHAR (256)   NULL,
    [InitialInterestAccrualEndDate]                        DATE             NULL,
    [AccrualFrequency]                                     INT              NULL,
    [DeterminationDateLeadDays]                            INT              NULL,
    [DeterminationDateReferenceDayoftheMonth]              INT              NULL,
    [DeterminationDateInterestAccrualPeriod]               INT              NULL,
    [DeterminationDateHolidayList]                         INT              NULL,
    [FirstPaymentDate]                                     DATE             NULL,
    [InitialMonthEndPMTDateBiWeekly]                       DATE             NULL,
    [PaymentDateBusinessDayLag]                            INT              NULL,
    [IOTerm]                                               INT              NULL,
    [AmortTerm]                                            INT              NULL,
    [PIKSeparateCompounding]                               INT              NULL,
    [MonthlyDSOverridewhenAmortizing]                      DECIMAL (28, 15) NULL,
    [AccrualPeriodPaymentDayWhenNotEOMonth]                INT              NULL,
    [FirstPeriodInterestPaymentOverride]                   DECIMAL (28, 15) NULL,
    [FirstPeriodPrincipalPaymentOverride]                  DECIMAL (28, 15) NULL,
    [FinalInterestAccrualEndDateOverride]                  DATE             NULL,
    [AmortType]                                            INT              NULL,
    [RateType]                                             INT              NULL,
    [ReAmortizeMonthly]                                    INT              NULL,
    [ReAmortizeatPMTReset]                                 INT              NULL,
    [StubPaidInArrears]                                    INT              NULL,
    [RelativePaymentMonth]                                 INT              NULL,
    [SettleWithAccrualFlag]                                INT              NULL,
    [InterestDueAtMaturity]                                INT              NULL,
    [RateIndexResetFreq]                                   DECIMAL (28, 15) NULL,
    [FirstRateIndexResetDate]                              DATE             NULL,
    [LoanPurchase]                                         INT              NULL,
    [AmortIntCalcDayCount]                                 INT              NULL,
    [StubPaidinAdvanceYN]                                  INT              NULL,
    [FullPeriodInterestDueatMaturity]                      INT              NULL,
    [ProspectiveAccountingMode]                            INT              NULL,
    [IsCapitalized]                                        INT              NULL,
    [SelectedMaturityDateScenario]                         INT              NULL,
    [SelectedMaturityDate]                                 DATE             NULL,
    [InitialMaturityDate]                                  DATE             NULL,
    [ExpectedMaturityDate]                                 DATE             NULL,
    [OpenPrepaymentDate]                                   DATE             NULL,
    [CashflowEngineID]                                     INT              NULL,
    [LoanType]                                             INT              NULL,
    [Classification]                                       INT              NULL,
    [SubClassification]                                    INT              NULL,
    [GAAPDesignation]                                      INT              NULL,
    [PortfolioID]                                          INT              NULL,
    [GeographicLocation]                                   INT              NULL,
    [PropertyType]                                         INT              NULL,
    [RatingAgency]                                         INT              NULL,
    [RiskRating]                                           INT              NULL,
    [PurchasePrice]                                        DECIMAL (28, 15) NULL,
    [FutureFeesUsedforLevelYeild]                          DECIMAL (28, 15) NULL,
    [TotalToBeAmortized]                                   DECIMAL (28, 15) NULL,
    [StubPeriodInterest]                                   DECIMAL (28, 15) NULL,
    [WDPAssetMultiple]                                     DECIMAL (28, 15) NULL,
    [WDPEquityMultiple]                                    DECIMAL (28, 15) NULL,
    [PurchaseBalance]                                      DECIMAL (28, 15) NULL,
    [DaysofAccrued]                                        INT              NULL,
    [InterestRate]                                         DECIMAL (28, 15) NULL,
    [PurchasedInterestCalc]                                DECIMAL (28, 15) NULL,
    [ModelFinancingDrawsForFutureFundings]                 INT              NULL,
    [NumberOfBusinessDaysLagForFinancingDraw]              INT              NULL,
    [FinancingFacilityID]                                  UNIQUEIDENTIFIER NULL,
    [FinancingInitialMaturityDate]                         DATE             NULL,
    [FinancingExtendedMaturityDate]                        DATE             NULL,
    [FinancingPayFrequency]                                INT              NULL,
    [FinancingInterestPaymentDay]                          INT              NULL,
    [ClosingDate]                                          DATE             NULL,
    [InitialFundingAmount]                                 DECIMAL (28, 15) NULL,
    [Discount]                                             DECIMAL (28, 15) NULL,
    [OriginationFee]                                       DECIMAL (28, 15) NULL,
    [CapitalizedClosingCosts]                              DECIMAL (28, 15) NULL,
    [PurchaseDate]                                         DATE             NULL,
    [PurchaseAccruedFromDate]                              DECIMAL (28, 15) NULL,
    [PurchasedInterestOverride]                            DECIMAL (28, 15) NULL,
    [DiscountRate]                                         DECIMAL (28, 15) NULL,
    [ValuationDate]                                        DATE             NULL,
    [FairValue]                                            DECIMAL (28, 15) NULL,
    [DiscountRatePlus]                                     DECIMAL (28, 15) NULL,
    [FairValuePlus]                                        DECIMAL (28, 15) NULL,
    [DiscountRateMinus]                                    DECIMAL (28, 15) NULL,
    [FairValueMinus]                                       DECIMAL (28, 15) NULL,
    [InitialIndexValueOverride]                            DECIMAL (28, 15) NULL,
    [IncludeServicingPaymentOverrideinLevelYield]          INT              NULL,
    [OngoingAnnualizedServicingFee]                        DECIMAL (28, 15) NULL,
    [IndexRoundingRule]                                    INT              NULL,
    [RoundingMethod]                                       INT              NULL,
    [StubInterestPaidonFutureAdvances]                     INT              NULL,
    [TaxAmortCheck]                                        NVARCHAR (256)   NULL,
    [PIKWoCompCheck]                                       NVARCHAR (256)   NULL,
    [GAAPAmortCheck]                                       NVARCHAR (256)   NULL,
    [StubIntOverride]                                      DECIMAL (28, 15) NULL,
    [PurchasedIntOverride]                                 DECIMAL (28, 15) NULL,
    [ExitFeeFreePrepayAmt]                                 DECIMAL (28, 15) NULL,
    [ExitFeeBaseAmountOverride]                            DECIMAL (28, 15) NULL,
    [ExitFeeAmortCheck]                                    INT              NULL,
    [FixedAmortScheduleCheck]                              INT              NULL,
    [GeneratedBy]                                          INT              NULL,
    [UseRuletoDetermineNoteFunding]                        INT              NULL,
    [NoteFundingRule]                                      INT              NULL,
    [FundingPriority]                                      INT              NULL,
    [NoteBalanceCap]                                       DECIMAL (28, 15) NULL,
    [RepaymentPriority]                                    INT              NULL,
    [NoofdaysrelPaymentDaterollnextpaymentcycle]           INT              NULL,
    [CreatedBy]                                            NVARCHAR (256)   NULL,
    [CreatedDate]                                          DATETIME         NULL,
    [UpdatedBy]                                            NVARCHAR (256)   NULL,
    [UpdatedDate]                                          DATETIME         NULL,
    [UseIndexOverrides]                                    BIT              NULL,
    [IndexNameID]                                          INT              NULL,
    [ServicerID]                                           NVARCHAR (256)   NULL,
    [TotalCommitment]                                      DECIMAL (28, 15) NULL,
    [ClientName]                                           NVARCHAR (256)   NULL,
    [Portfolio]                                            NVARCHAR (256)   NULL,
    [Tag1]                                                 NVARCHAR (256)   NULL,
    [Tag2]                                                 NVARCHAR (256)   NULL,
    [Tag3]                                                 NVARCHAR (256)   NULL,
    [Tag4]                                                 NVARCHAR (256)   NULL,
    [ExtendedMaturityScenario1]                            DATE             NULL,
    [ExtendedMaturityScenario2]                            DATE             NULL,
    [ExtendedMaturityScenario3]                            DATE             NULL,
    [ActualPayoffDate]                                     DATE             NULL,
    [FullyExtendedMaturityDate]                            DATE             NULL,
    [TotalCommitmentExtensionFeeisBasedOn]                 DECIMAL (28, 15) NULL,
    [LienPriority]                                         INT              NULL,
    [UnusedFeeThresholdBalance]                            DECIMAL (28, 15) NULL,
    [UnusedFeePaymentFrequency]                            INT              NULL,
    [lienposition]                                         INT              NULL,
    [priority]                                             INT              NULL,
    [Servicer]                                             INT              NULL,
    [FullInterestAtPPayoff]                                INT              NULL,
    [NoteRule]                                             NVARCHAR (2000)  NULL,
    [ClientID]                                             INT              NULL,
    [FinancingSourceID]                                    INT              NULL,
    [DebtTypeID]                                           INT              NULL,
    [BillingNotesID]                                       INT              NULL,
    [CapStack]                                             INT              NULL,
    [FundID]                                               INT              NULL,
    [PoolID]                                               INT              NULL,
    [TaxVendorLoanNumber]                                  NVARCHAR (256)   NULL,
    [TAXBILLSTATUS]                                        NVARCHAR (256)   NULL,
    [CURRTAXCONSTANT]                                      INT              NULL,
    [InsuranceBillStatusCode]                              NVARCHAR (256)   NULL,
    [RESERVETYPE]                                          NVARCHAR (256)   NULL,
    [ResDescOwnName]                                       NVARCHAR (256)   NULL,
    [MONTHLYPAYMENTAMT]                                    INT              NULL,
    [IORPLANCODE]                                          NVARCHAR (256)   NULL,
    [NoDaysbeforeAssessment]                               DECIMAL (28, 15) NULL,
    [LateChargeRateorFee]                                  DECIMAL (28, 15) NULL,
    [DefaultOfDaysto]                                      DECIMAL (28, 15) NULL,
    [OddDaysIntAmount]                                     DECIMAL (28, 15) NULL,
    [InterestRateFloor]                                    DECIMAL (28, 15) NULL,
    [InterestRateCeiling]                                  DECIMAL (28, 15) NULL,
    [Dayslookback]                                         NVARCHAR (256)   NULL,
    [CurrentBls]                                           DECIMAL (28, 15) NULL,
    [WF_Companyname]                                       NVARCHAR (256)   NULL,
    [WF_FirstName]                                         NVARCHAR (256)   NULL,
    [WF_Lastname]                                          NVARCHAR (256)   NULL,
    [WF_StreetName]                                        NVARCHAR (256)   NULL,
    [WF_ZipCodePostal]                                     NVARCHAR (256)   NULL,
    [WF_PayeeName]                                         NVARCHAR (256)   NULL,
    [WF_TelephoneNumber1]                                  NVARCHAR (256)   NULL,
    [WF_FederalID1]                                        NVARCHAR (MAX)   NULL,
    [WF_City]                                              NVARCHAR (256)   NULL,
    [WF_State]                                             NVARCHAR (256)   NULL,
    [StubInterestRateOverride]                             DECIMAL (28, 15) NULL,
    [LiborDataAsofDate]                                    DATETIME         NULL,
    [ServicerNameID]                                       INT              NULL,
    [InterestCalculationRuleForPaydowns]                   INT              NULL,
    [PIKInterestAddedToBalanceBasedOnBusinessAdjustedDate] INT              NULL,
    [BusinessdaylafrelativetoPMTDate]                      INT              NULL,
    [DayoftheMonth]                                        INT              NULL,
    [FundedAndOwnedByThirdParty]                           BIT              DEFAULT ((0)) NULL,
    [InterestCalculationRuleForPaydownsAmort]              INT              NULL,
    [RepaymentDayoftheMonth]                               INT              NULL,
    [FutureFundingBillingCutoffDay]                        INT              NULL,
    [CurtailmentBillingCutoffDay]                          INT              NULL,
    [AdjustedTotalCommitment]                              DECIMAL (28, 15) NULL,
    [AggregatedTotal]                                      DECIMAL (28, 15) NULL,
    [RoundingNote]                                         INT              NULL,
    [StraightLineAmortOverride]                            DECIMAL (28, 15) NULL,
    [UseRuletoDetermineAmortization]                       INT              NULL,
    [RSLIC]                                                DECIMAL (28, 15) NULL,
    [SNCC]                                                 DECIMAL (28, 15) NULL,
    [PIIC]                                                 DECIMAL (28, 15) NULL,
    [TMR]                                                  DECIMAL (28, 15) NULL,
    [HCC]                                                  DECIMAL (28, 15) NULL,
    [USSIC]                                                DECIMAL (28, 15) NULL,
    [TMNF]                                                 DECIMAL (28, 15) NULL,
    [HAIH]                                                 DECIMAL (28, 15) NULL,
    [TotalParticipation]                                   DECIMAL (28, 15) NULL,
    [MKT_PRICE]                                            DECIMAL (28, 15) NULL,
    [OriginalTotalCommitment]                              DECIMAL (28, 15) NULL,
    [StrategyCode]                                         INT              NULL,
    [NoteTransferDate]                                     DATE             NULL,
    [EnableM61Calculations]                                INT              NULL,
    [CalculationTimeInMin]                                 INT              CONSTRAINT [DF__Note__Calculatio__3EA8151D] DEFAULT ((10)) NULL,
    [InitialRequiredEquity]                                DECIMAL (28, 15) NULL,
    [InitialAdditionalEquity]                              DECIMAL (28, 15) NULL,
    [originaltotalcommitment_BK]                           DECIMAL (28, 15) NULL,
    [OriginationFeePercentageRP]                           DECIMAL (28, 15) NULL,
    [CommitmentUsedInFFDistribution]                       DECIMAL (28, 15) NULL,
    [ExtendedMaturityCurrent]                              DATE             NULL,
    [MaturityGroupName]                                    NVARCHAR (256)   NULL,
    [MaturityMethodID]                                     INT              NULL,
    [ImpactCommitmentCalc]                                 INT              NULL,
    CONSTRAINT [PK_NoteID] PRIMARY KEY CLUSTERED ([NoteID] ASC),
    CONSTRAINT [FK_Note_Account_AccountID] FOREIGN KEY ([Account_AccountID]) REFERENCES [Core].[Account] ([AccountID]),
    CONSTRAINT [FK_Note_DealID] FOREIGN KEY ([DealID]) REFERENCES [CRE].[Deal] ([DealID])
);


GO
ALTER TABLE [CRE].[Note] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);




GO


GO
CREATE NONCLUSTERED INDEX [nci_wi_Note_8D0C12D920037CACAD4AE542CB3F5207]
    ON [CRE].[Note]([Account_AccountID] ASC, [CashflowEngineID] ASC)
    INCLUDE([CRENoteID], [DealID], [UseRuletoDetermineNoteFunding]);


GO
CREATE NONCLUSTERED INDEX [nci_wi_Note_BF4DCF47C600ECDBF3BF8B73F42C45F9]
    ON [CRE].[Note]([ServicerNameID] ASC)
    INCLUDE([DealID]);


GO
CREATE NONCLUSTERED INDEX [IX_Note_CashflowEngineID]
    ON [CRE].[Note]([CashflowEngineID] ASC)
    INCLUDE([Account_AccountID], [DealID]);


GO
CREATE NONCLUSTERED INDEX [IX_Note_CRENoteID]
    ON [CRE].[Note]([CRENoteID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_Note_CRENoteID_NoteID]
    ON [CRE].[Note]([CRENoteID] ASC, [NoteID] ASC);

