  
CREATE View [dbo].[NotePeriodicCalcByEntity]  
as  

select   
NPC.NoteID as NoteKey,  
CRENoteID as NoteID,  
PeriodEndDate,  
EntityName as Entity,  
[Month],  
ActualCashFlows   ActualCashFlows ,  
GAAPCashFlows   GAAPCashFlows ,  
EndingGAAPBookValue   EndingGAAPBookValue ,  
TotalGAAPIncomeforthePeriod   TotalGAAPIncomeforthePeriod ,  
InterestAccrualforthePeriod   InterestAccrualforthePeriod ,  
PIKInterestAccrualforthePeriod   PIKInterestAccrualforthePeriod ,  
TotalAmortAccrualForPeriod   TotalAmortAccrualForPeriod ,  
AccumulatedAmort   AccumulatedAmort ,  
BeginningBalance   BeginningBalance ,  
TotalFutureAdvancesForThePeriod   TotalFutureAdvancesForThePeriod ,  
TotalDiscretionaryCurtailmentsforthePeriod   TotalDiscretionaryCurtailmentsforthePeriod ,  
InterestPaidOnPaymentDate   InterestPaidOnPaymentDate ,  
TotalCouponStrippedforthePeriod   TotalCouponStrippedforthePeriod ,  
CouponStrippedonPaymentDate   CouponStrippedonPaymentDate ,  
ScheduledPrincipal   ScheduledPrincipal ,  
PrincipalPaid   PrincipalPaid ,  
BalloonPayment   BalloonPayment ,  
EndingBalance   EndingBalance ,  
ExitFeeIncludedInLevelYield   ExitFeeIncludedInLevelYield ,  
ExitFeeExcludedFromLevelYield   ExitFeeExcludedFromLevelYield ,  
AdditionalFeesIncludedInLevelYield   AdditionalFeesIncludedInLevelYield ,  
AdditionalFeesExcludedFromLevelYield   AdditionalFeesExcludedFromLevelYield ,  
OriginationFeeStripping   OriginationFeeStripping ,  
ExitFeeStrippingIncldinLevelYield   ExitFeeStrippingIncldinLevelYield ,  
ExitFeeStrippingExcldfromLevelYield   ExitFeeStrippingExcldfromLevelYield ,  
AddlFeesStrippingIncldinLevelYield   AddlFeesStrippingIncldinLevelYield ,  
AddlFeesStrippingExcldfromLevelYield   AddlFeesStrippingExcldfromLevelYield ,  
EndOfPeriodWAL   EndOfPeriodWAL ,  
PIKInterestFromPIKSourceNote   PIKInterestFromPIKSourceNote ,  
PIKInterestTransferredToRelatedNote   PIKInterestTransferredToRelatedNote ,  
PIKInterestForThePeriod   PIKInterestForThePeriod ,  
BeginningPIKBalanceNotInsideLoanBalance   BeginningPIKBalanceNotInsideLoanBalance ,  
PIKInterestForPeriodNotInsideLoanBalance   PIKInterestForPeriodNotInsideLoanBalance ,  
PIKBalanceBalloonPayment   PIKBalanceBalloonPayment ,  
EndingPIKBalanceNotInsideLoanBalance   EndingPIKBalanceNotInsideLoanBalance ,  
CostBasis   CostBasis ,  
PreCapBasis   PreCapBasis ,  
BasisCap   BasisCap ,  
AmortAccrualLevelYield   AmortAccrualLevelYield ,  
ScheduledPrincipalShortfall   ScheduledPrincipalShortfall ,  
PrincipalShortfall   PrincipalShortfall ,  
PrincipalLoss   PrincipalLoss ,  
InterestForPeriodShortfall   InterestForPeriodShortfall ,  
InterestPaidOnPMTDateShortfall   InterestPaidOnPMTDateShortfall ,  
CumulativeInterestPaidOnPMTDateShortfall   CumulativeInterestPaidOnPMTDateShortfall ,  
InterestShortfallLoss   InterestShortfallLoss ,  
InterestShortfallRecovery   InterestShortfallRecovery ,  
BeginningFinancingBalance   BeginningFinancingBalance ,  
TotalFinancingDrawsCurtailmentsForPeriod   TotalFinancingDrawsCurtailmentsForPeriod ,  
FinancingBalloon   FinancingBalloon ,  
EndingFinancingBalance   EndingFinancingBalance ,  
FinancingInterestPaid   FinancingInterestPaid ,  
FinancingFeesPaid   FinancingFeesPaid ,  
PeriodLeveredYield   PeriodLeveredYield ,  
OrigFeeAccrual    OrigFeeAccrual  ,  
DiscountPremiumAccrual     DiscountPremiumAccrual   ,  
ExitFeeAccrual     ExitFeeAccrual   ,  
AllInCouponRate AS  AllInCouponRate   
, AnalysisID  
,AnalysisName ScenarioName  
  
From DW.NotePeriodicCalcByEntityBI NPC 

 
--select   
--NPC.NoteID as NoteKey,  
--CRENoteID as NoteID,  
--PeriodEndDate,  
--P.Entity,  
--[Month],  
--ActualCashFlows * P.Participation AS  ActualCashFlows ,  
--GAAPCashFlows * P.Participation AS  GAAPCashFlows ,  
--EndingGAAPBookValue * P.Participation AS  EndingGAAPBookValue ,  
--TotalGAAPIncomeforthePeriod * P.Participation AS  TotalGAAPIncomeforthePeriod ,  
--InterestAccrualforthePeriod * P.Participation AS  InterestAccrualforthePeriod ,  
--PIKInterestAccrualforthePeriod * P.Participation AS  PIKInterestAccrualforthePeriod ,  
--TotalAmortAccrualForPeriod * P.Participation AS  TotalAmortAccrualForPeriod ,  
--AccumulatedAmort * P.Participation AS  AccumulatedAmort ,  
--BeginningBalance * P.Participation AS  BeginningBalance ,  
--TotalFutureAdvancesForThePeriod * P.Participation AS  TotalFutureAdvancesForThePeriod ,  
--TotalDiscretionaryCurtailmentsforthePeriod * P.Participation AS  TotalDiscretionaryCurtailmentsforthePeriod ,  
--InterestPaidOnPaymentDate * P.Participation AS  InterestPaidOnPaymentDate ,  
--TotalCouponStrippedforthePeriod * P.Participation AS  TotalCouponStrippedforthePeriod ,  
--CouponStrippedonPaymentDate * P.Participation AS  CouponStrippedonPaymentDate ,  
--ScheduledPrincipal * P.Participation AS  ScheduledPrincipal ,  
--PrincipalPaid * P.Participation AS  PrincipalPaid ,  
--BalloonPayment * P.Participation AS  BalloonPayment ,  
--EndingBalance * P.Participation AS  EndingBalance ,  
--ExitFeeIncludedInLevelYield * P.Participation AS  ExitFeeIncludedInLevelYield ,  
--ExitFeeExcludedFromLevelYield * P.Participation AS  ExitFeeExcludedFromLevelYield ,  
--AdditionalFeesIncludedInLevelYield * P.Participation AS  AdditionalFeesIncludedInLevelYield ,  
--AdditionalFeesExcludedFromLevelYield * P.Participation AS  AdditionalFeesExcludedFromLevelYield ,  
--OriginationFeeStripping * P.Participation AS  OriginationFeeStripping ,  
--ExitFeeStrippingIncldinLevelYield * P.Participation AS  ExitFeeStrippingIncldinLevelYield ,  
--ExitFeeStrippingExcldfromLevelYield * P.Participation AS  ExitFeeStrippingExcldfromLevelYield ,  
--AddlFeesStrippingIncldinLevelYield * P.Participation AS  AddlFeesStrippingIncldinLevelYield ,  
--AddlFeesStrippingExcldfromLevelYield * P.Participation AS  AddlFeesStrippingExcldfromLevelYield ,  
--EndOfPeriodWAL * P.Participation AS  EndOfPeriodWAL ,  
--PIKInterestFromPIKSourceNote * P.Participation AS  PIKInterestFromPIKSourceNote ,  
--PIKInterestTransferredToRelatedNote * P.Participation AS  PIKInterestTransferredToRelatedNote ,  
--PIKInterestForThePeriod * P.Participation AS  PIKInterestForThePeriod ,  
--BeginningPIKBalanceNotInsideLoanBalance * P.Participation AS  BeginningPIKBalanceNotInsideLoanBalance ,  
--PIKInterestForPeriodNotInsideLoanBalance * P.Participation AS  PIKInterestForPeriodNotInsideLoanBalance ,  
--PIKBalanceBalloonPayment * P.Participation AS  PIKBalanceBalloonPayment ,  
--EndingPIKBalanceNotInsideLoanBalance * P.Participation AS  EndingPIKBalanceNotInsideLoanBalance ,  
--CostBasis * P.Participation AS  CostBasis ,  
--PreCapBasis * P.Participation AS  PreCapBasis ,  
--BasisCap * P.Participation AS  BasisCap ,  
--AmortAccrualLevelYield * P.Participation AS  AmortAccrualLevelYield ,  
--ScheduledPrincipalShortfall * P.Participation AS  ScheduledPrincipalShortfall ,  
--PrincipalShortfall * P.Participation AS  PrincipalShortfall ,  
--PrincipalLoss * P.Participation AS  PrincipalLoss ,  
--InterestForPeriodShortfall * P.Participation AS  InterestForPeriodShortfall ,  
--InterestPaidOnPMTDateShortfall * P.Participation AS  InterestPaidOnPMTDateShortfall ,  
--CumulativeInterestPaidOnPMTDateShortfall * P.Participation AS  CumulativeInterestPaidOnPMTDateShortfall ,  
--InterestShortfallLoss * P.Participation AS  InterestShortfallLoss ,  
--InterestShortfallRecovery * P.Participation AS  InterestShortfallRecovery ,  
--BeginningFinancingBalance * P.Participation AS  BeginningFinancingBalance ,  
--TotalFinancingDrawsCurtailmentsForPeriod * P.Participation AS  TotalFinancingDrawsCurtailmentsForPeriod ,  
--FinancingBalloon * P.Participation AS  FinancingBalloon ,  
--EndingFinancingBalance * P.Participation AS  EndingFinancingBalance ,  
--FinancingInterestPaid * P.Participation AS  FinancingInterestPaid ,  
--FinancingFeesPaid * P.Participation AS  FinancingFeesPaid ,  
--PeriodLeveredYield * P.Participation AS  PeriodLeveredYield ,  
--OrigFeeAccrual  * P.Participation AS  OrigFeeAccrual  ,  
--DiscountPremiumAccrual   * P.Participation AS  DiscountPremiumAccrual   ,  
--ExitFeeAccrual   * P.Participation AS  ExitFeeAccrual   ,  
--AllInCouponRate AS  AllInCouponRate   
--, AnalysisID  
--, A.Name ScenarioName  
  
-- From [DW].[NotePeriodicCalcBI] NPC  
-- LEFT JOIN dbo.[ParticipationBI] P  ON P.NoteID = NPC.CRENoteID  
-- Left Join DW.AnalysisBI A on NPC.AnalysisID =  A.AnalysisKey  
  
  
  
  