CREATE VIEW [dbo].[vw_LiabilityNoteAssetMappingBI]
AS
SELECT [LiabilityNoteAssetMappingID]
      ,[LiabilityNoteAssetMappingGuid]
      ,[DealAccountId]
      ,[DealID]
      ,[LiabilityNoteAccountId]
      ,[AssetAccountId]
      ,[NoteID]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[UpdatedBy]
      ,[UpdatedDate]
  FROM [DW].[LiabilityNoteAssetMappingBI]
