CREATE VIEW [dbo].[vw_TransactionEntryLiabilityBI]
AS
SELECT [TransactionEntryLiabilityID]
,[TransactionEntryLiabilityAutoID]
,[LiabilityAccountID]
,[LiabilityTypeName]
,[LiabilityNoteAccountID]
,[LiabilityNoteID]
,[Date]
,[Amount]
,[TransactionType]
,[AnalysisID]
,[AnalysisName]
,[EndingBalance]
,[AssetAccountID]
,[NoteID]
,[AssetDate]
,[AssetAmount]
,[AssetTransactionType]
,[CreatedBy]
,[CreatedDate]
,[UpdatedBy]
,[UpdatedDate]
,[ParentAccountId]
,[Flag]
,NoteEndingBalance
,NotePIKBalance
FROM [DW].[TransactionEntryLiabilityBI]
