-- View


CREATE VIEW [dbo].[vwTransactionActuals] AS  
SELECT NoteId	,
	Name	,
	DealID	,
	DealName	,
	Date	,
	DueDate	,
	RemitDate	,
	TransactionDate	,
	TransactionType	,
	CalculatedAmount	,
	ServicingAmount	,
	OverrideValue	,
	CalculateDelta	,
	Adjustment	,
	M61	,
	Servicer	,
	Ignore	,
	Exception	,
	comments	,
	SourceType	,
	UsedInCalc	,
	ActualDelta	,
	ServicerName	,
	Status	,
	OverrideReason	,
	CapitalizedInterest	,
	CashInterest	,
	BatchLogID	,
	FileName	,
	FinancingSource,

	IndexValue,
	SpreadPercentage,
	[OriginalIndex],
	EffectiveRate,
	WatchlistStatus,
	PIKType,
	(CASE WHEN [FileName] like 'CashFlow_Data%' THEN SUBSTRING([FileName],1,Len([FileName])-9) ELSE [FileName] END) [FileName_woTime]
	from [DW].[TransactionActuals]