  
CREATE View [dbo].[WorkFlow]  
as   
SELECT [dealid]  
      ,[dealfundingid]  
      ,[CREDealID]  
      ,[DealName]  
      ,[Deadline]  
      ,[Fundingdate]  
      ,[Amount]  
      ,[StatusName]  
      ,[Username]  
      ,[wf_isAllow]  
      ,[UpdatedDate]  
      ,[WorkFlowComment]  
      ,[PurposeIDText]  
      ,[Applied]  
      ,[dealfunComment]  
      ,[DrawFundingID]  
      ,[WFTaskDetailID]  
      ,[TaskID]  
      ,[TaskTypeID]  
      ,[SubmitType]  
      ,[WFStatusPurposeMappingID]  
      ,[PurposeTypeId]  
      ,[OrderIndex]  
      ,[WFStatusMasterID]  
      ,[TaskTypeIDText]  
      ,[SubmitTypeText]  
      ,[PurposeID]  
   ,StatusNamebi = case when (statusname = 'Under Review' and Amount < 0 )then 'Requested' else StatusName end  
   ,GeneratedByBI as GeneratedBy
  FROM [DW].[WorkFlowBI]  
  