Print ('Insert state master')
GO
Truncate table [App].[StatesMaster]

INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Alabama','AL')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Alaska','AK')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Arizona','AZ')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Arkansas','AR')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','California','CA')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Colorado','CO')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Connecticut','CT')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Delaware','DE')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Florida','FL')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Georgia','GA')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Hawaii','HI')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Idaho','ID')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Illinois','IL')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Indiana','IN')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Iowa','IA')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Kansas','KS')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Kentucky','KY')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Louisiana','LA')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Maine','ME')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Maryland','MD')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Massachusetts','MA')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Michigan','MI')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Minnesota','MN')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Mississippi','MS')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Missouri','MO')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Montana','MT')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Nebraska','NE')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Nevada','NV')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','New Hampshire','NH')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','New Jersey','NJ')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','New Mexico','NM')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','New York','NY')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','North Carolina','NC')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','North Dakota','ND')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Ohio','OH')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Oklahoma','OK')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Oregon','OR')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Pennsylvania','PA')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Rhode Island','RI')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','South Carolina','SC')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','South Dakota','SD')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Tennessee','TN')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Texas','TX')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Utah','UT')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Vermont','VT')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Virginia','VA')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Washington','WA')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','West Virginia','WV')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Wisconsin','WI')
INSERT INTO APP.StatesMaster(CountryName,StatesName,StatesAbbreviation)VALUES('US','Wyoming','WY')

GO