Truncate table CRE.[ReserveAccountMaster]
go
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Approved Budgeted CapEx Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Budgeted Capital Expenditures Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / CapEx Advance Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Commercial Capital Expenditure Reserve Account.')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Near-Term Capital Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Planned Capital Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Casualty Condemnation')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Construction Draw Reserve / Construction Completion Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Construction Draw Reserve / The Construction Cost Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Aggregate Debt Service and Operating Shortfall')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service & Operat')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service & Operating Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service and Carry Costs Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service and Operating Expense Shortfall')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service and Operating Shortfall Reserve  Ac')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service and Operating Shortfalls Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service Shortfall Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service Shortfalls Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service/NOI Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Interest & Carry')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Interest and Operating Expense Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / The Debt Service and Operating Shortfall Reserve A')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Environmental Reserve / Environmental Remediation Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Environmental Reserve / Environmental Repair Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Environmental Reserve / The Environmental Remediation Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Excess Cash Flow')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Excess Cash Flow / Cash Flow Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Excess Cash Flow / Cash Management Additional Deposit Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Excess Cash Flow / Cash Sweep Tenant Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('FF & E Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('FF & E Reserve / Deferred FF&E')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('FF & E Reserve / The FF&E Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Free Rent Reserve / Rent Abatement Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Holdback / Rent Abatement Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Immediate Repairs / DACA Receipts Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Immediate Repairs / IMMEDIATE REPAIR RESERVE')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Immediate Repairs / Immediate Repair Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Immediate Repairs / Repair Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Immediate Repairs / Restoration Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Insurance / Insurance Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Carrying Cost Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest and Carry Costs')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest and Carry Costs Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest and Carry Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest and Operating Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Carry')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Rate Cap Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Rate Cap Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / The Interest and Carry Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / The Interest Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / The Interest Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Leasing Commissions / Cash Sweep Tenant Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Loss Draft Account / LOSS DRAFT RESERVE')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Net Proceeds / Net Proceeds Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Net Proceeds / Net Proceeds to servicer')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Debt Service and Operating Shortfall Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Interest and Carry')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Interest and operating expense reserve account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Operating Expense Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Pre-Development Cost Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Additional Collateral Reserves')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Amazon Pre-Paid Rent Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Building Loan Documents Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Capital Improvements')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Carry Cost Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Cash Collateral Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Common Charges Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Condominium Unit Acquisition Costs')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Cooperative Maintenance Charges')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / DACA / CMA')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / DACA Receipt Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / DACA Receipts Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Deficiency Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / 205 Riverside Capital Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Capital Expenditure Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Concourse Renovation Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Crescent Austin Capital Expenditure Reserve Accoun')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / CUP Capital Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Hotel Predevelopment Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Project Expenditure')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / The Capital Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / The Capital/FF&E Reserve Account,')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Construction Draw Reserve / Collateral Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Construction Draw Reserve / Hard Costs Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Construction Draw Reserve / Oregon Construction Retainage Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Construction Draw Reserve / Oregon Construction Retainage Escrow Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Construction Draw Reserve / The Construction Completion Reserve Account,')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Cash Management Additional Deposit Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service & Operating')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service and Operating Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service and Operating Shortfall Reserv')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service and Operating Shortfall Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service and Operating Shortfall Reserve Acc')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service and Operating Shortfall Reserve Accou')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / ebt Service and Operating Expense Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Mortgage Property  Debt Service Reserve Fund')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / The Debt Service and Carry Costs Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / The Debt Service and Operating Shortfall Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Deferred Maintenance / Immediate Repair Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Excess Cash Flow / Excess Cash Flow Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Excess Cash Flow / Excess Cash Flow Subaccount')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('FF & E Reserve / Mortgage Property FF&E Reserve Funds')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Free Rent Reserve / The Free Rent Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Ground Rent / Ground Lease Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Ground Rent / Ground Rent Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Ground Rent / The Ground Rent Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Holdback / Beck and Guild Rent Commencement Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Holdback / Tennessee Retainage Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Immediate Repairs / Immediate Repairs')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Immediate Repairs / Repair Escrow')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Insurance')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest & Carry Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest and Carry Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest and Carry Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest and carry shortfall funds')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest and Carry Shortfall Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Costs and Carrv Costs Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Costs and Carry Costs Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Operating Shortfall Force Funded Account,')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Operating Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Rate Cap Proceeds')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Reserve Funds/Debt Service Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Mezzanine Interest Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Liquidity Reserve / Liquidity Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Net Proceeds')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Net Proceeds / Loss Proceeds')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Carry Cost Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Carry Cost Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Common Charges Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Debt Service and Operating Shortfalls Reserve Acco')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Shortfall')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / 205 Riverside Required Capital Work')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / ADA Compliance Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Additional Advance Reserve Funds')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Additional Contingency Proceeds Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Balancing Event Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / BlueGreen Marketing Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Borrower Required Equity Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Broker Fee Credit')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Approved Capital Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Cap Ex for Park Place')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Capital Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Capital Expense Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Capital Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Elevator Modernization and Interiors Reserve Accou')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('CapEx / Residential Capital Expenditure Reserve Account.')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Casualty Condemnation / Casualty/Condemnation Subaccount')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Construction Draw Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Construction Draw Reserve / Construction Closeout Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Construction Draw Reserve / Construction Funds Subaccount')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Construction Draw Reserve / Soft Costs Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service & Operating Shortfall Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service and Operating Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt service and Operating shortfall')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service and Reserve Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service Costs Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service MM')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service Reserve Funds')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service Shortfall Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Debt Service Subaccount')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Interest and Operating Expense Shortfall Reserve A')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Mezzanine Debt Service Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / the Debt Service and Operating Shortfall Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / The Debt Service Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Debt Service / WEWORK DEBT SERVICE AND F')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Deferred Maintenance / IMMEDIATE REPAIRS')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Environmental Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Excess Cash Flow / Excess Cash Flow')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Excess Cash Flow / Key Tenant Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('FF & E Reserve / FF&E Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Free Rent Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Free Rent Reserve / Rent  Abatement Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Free Rent Reserve / The Rent Abatement Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Ground Rent')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Ground Rent / Ground Rent Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Immediate Repairs')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Immediate Repairs / Immediate Repairs Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Immediate Repairs / Short Term Repair Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Immediate Repairs / The Immediate Repair Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Insurance / Insurance')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Insurance / Mezzanine Insurance Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Deferred Interest Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Costs and Carry Costs Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest costs reserve account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Rate Cap Agreement Reserve Agreement')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Rate Cap Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / INTEREST RESERVES ACCOUNT')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Shortfall Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Interest / Interest/Carry Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Loss Draft Account / DOL 1/6/22')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Net Proceeds / Net Proceeds')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Advance Payment Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Building Loan Interest Cost and Property Tax Reser')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Carry Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Condominium Costs Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Operating Shortfall Credit')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Prepaid Rent Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Operating Reserve / Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / (f) Construction Close-Out Reserve Account. Borrow')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / 255 Julian Deposit Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Advance Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / AMC/Target Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Annual Supplemental Fee')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Association Assessment Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Balancing Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Borrower Distribution Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Carry Cost Shortfall Reserve Account. Funds deposi')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Cash Flow Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Cash Management Additional Deposit')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Cash Management Additional Deposit Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Chevron Security Deposit')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Condominium Unit Escrow Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Construction Closeout Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Contingency Reserve Account.')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Debt Service Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / DirectTV Termination Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / DOL 10/17/22 Water Damage')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Earnout Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Flood  Damage Repair Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Free Rent Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Future Draws')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Guarantor Cash Collateral')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Hilton Termination Reserv')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / HTC Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Income Tax Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Int Rate Cap Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Interest Carry Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Leasing Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Liquidity Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Loss Proceeds')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Minimum Multiple (Spread)')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Miscellaneous Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Mobile Home Purchase Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / NYU Expansion Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Operating Shortfall')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Other Proj RE Tax 2015 Supplemental')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Other Reserves')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / PFC Tax Abatement Reimbursement Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Phase II Pre-Development Reserve.')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Predevelopment  Expenditure  Reserve  Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Predevelopment Expenditure Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Pre-Development Expenditure Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Prepaid Revenue Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Put Option Deposit Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Rate Cap Escrow Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Rate Cap Funds')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / REA Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Rent Abatement Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Rent Escrow')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Repair Escrow')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Repair Escrow Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Repair Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Required Equity Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Retainage 2')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / RS Tenant Buyout Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Starz Leasing Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Tax Escrow Surplus')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / The Balancing Event Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / The Cash Collateral Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / the Cash Collateral Reserve (Guaranty)')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / The Core Guestroom Reno Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / The Debt Yield Earn-out Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / The Hotel Expansion Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / The PBS Leasing Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / The Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / The Top Gun House Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Unused Fee Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('PIP Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('PIP Reserve / Asheville PIP Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('PIP Reserve / Interest and Carry Cost Reserve Acct')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('PIP Reserve / Mortgage Property PIP Reserve Fund')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Project Balancing Event Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Project Expenditure')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Project Expenditure Res')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Project Expenditure Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Project Expenditures (Parcel B) Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / the Project Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / The Project Expenditures Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Yorba Linda Project Expenditure Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Replacement Reserves')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Replacement Reserves / Partner Loan Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Replacement Reserves / Replacement Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Retention Reserve / Westlake Required Equity Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Rollover Reserve / EPA ROLLOVER RESERVE ACCO')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Rollover Reserve / Urban Outfitters Rollover Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Security Deposit / Terra Security Deposit Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Taxes')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Taxes / Tax Funds')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Taxes / Tax Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Tenant Improvements / Outstanding Atlantic Capital Bank TI Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Tenant Improvements / Outstanding BofA TI Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / 1D Houston')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / 3C Kansas City')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / CHUBB TI/LC RESERVE ACCOUNT')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Cleveland Electric TI')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Extraordinary TI/LC Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / HENKEL RESERVE ACCOUNT')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Outstanding TI/LC Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Palladian TI/LC Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Tenant Improvements')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / The TI/LC Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / VG Supply Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Building Loan Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / CapEx Force Funding')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Carry Cost Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Carry Cost Subaccount')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Carry Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Cash Collateral Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Cash Management Additional  Deposit Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / City of San Francisco Funds Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Common Charge Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Condominium Association Fee Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Construction Cost Rebalancing Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Construction Future Draw Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Costs to Complete Credit')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / DACA Receipts')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Debt Yield Trigger Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Deferred Market Ready Expenditures Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Excess Sales Proceeds Reserve Account (Palazzo)')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Extension  Debt Yield Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Extraordinary Lease Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Fee Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Fire Alarm Upgrade Reserve Account.')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Forced Funded Building Loan (Leasing Expenditures)')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Gottlieb Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Guild Default Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / HOA Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Horizontal Improvements and Carry Costs Reserve Ac')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Immediate Repair Escrow')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Impositions Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Industrious Settlement')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Initial Market Ready Expenditures Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Interest and Carry Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Interest and Carry Short')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Interest and Carry Shortfall Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Key Money Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Lease Sweep Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Lease Termination Additional Equity Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Lease Termination Proceeds')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Maxar Lease Buyout Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Omnibus Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Outstanding Lien Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Preferred Equity Recognition Agreement')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Project Expenditure MM Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Rebalancing Subaccount')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Relocation Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Retainage Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Security Deposits Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Seller Credit reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Service Fee')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Servicing Fee')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Sewer  Agreement  LOC  Reserve  Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Significant Alteration Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Significant Alteration Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Termination Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / The Pre-Development Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / TILC Force Funding')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Tommy Bahama Conversion')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('PIP Reserve / PIP/Renovation Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('PIP Reserve / The Walnut Creek PIP Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / BALANCING EVENT RESERVE A')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Borrower Funded Project Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Oakhurst Apartments Project Expenditure Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Project and Leasing Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Project Completion Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Project Expenditure Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Project Expenditures (Phase II) Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Project Loan Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Replacement Reserves / Replacement Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Retention Reserve / Oregon Construction Retainage Escrow Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Retention Reserve / Outstanding Clubhouse Retainage Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Rollover Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Rollover Reserve / Free Rent Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Security Deposit / CZI Security Deposit Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Security Deposit / Kaufman Rossin Security Deposit Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Taxes / Mezzanine Tax Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Taxes / Taxes')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Tenant Improvements / Adtalem Outstanding TI Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Tenant Improvements / Outstanding Project Lead The Way TI Reserve Accoun')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Tenant Improvements / Reliable Outstanding TI Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Tenant Improvements / Second Floor Tenant Lounge and Conference Center R')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / 1565 BARBER LEASING RESER')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / 2B Dallas')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / 501 SYCAMORE SPECTRA SPAC')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / 525 SYCAMORE SPECTRA SPAC')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Amcor Lease')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Ana Mendez Ti/LC Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Capital Improvement and Leasing Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Cash Sweep Lease TI/LC Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Cox TILC Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Federal Reserve TI/LC')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / L-3 COMMUNICATIONS TI/LC')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Leasing Expenditures Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / North Loop TILC')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / OTHER TI/LC RESERVE ACCOU')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / RSM RESERVE ACCOUNT')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Signed Tenant TI/LC Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / the Atlantic Council Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / The Ready Spaces TI/LC')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / TI/LC RESERVE')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Unit Turnover Expense Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Earnout Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Elevator Modernization Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Entitlement and Predevelopment Costs')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Excess Sales Proceeds Reserve Account (Fiddler’s)')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Extraordinary Lease Payment Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Franchise Expiration Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Gallows Ongoing Work Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / General Contractor Settlement Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Ground Rent  Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Interest Rate Cap Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Leasing Expenditure Advan')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Leasing Expenditures Advance')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Loan Advance Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Mortgage Property Lease Termination Funds')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / National Securities Outstanding TI Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Ongoing Leasing Cost Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Pepsi Allowance Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Predevelopment Costs Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Pre-Development Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Pre-Development Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Project Expenditure')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Project Expenditure Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Project Expense Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Purchaser Upgrade Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Ready Spaces')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Rebalancing Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Release Price Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Reliable Holdover Rent Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Required Repair Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Required Repairs Reserve Account.')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Retainage 1')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Shortfall Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Soft Costs Developer fee reserve account:')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / The 2023 Property Tax Appeal Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / the Impositions Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / The Individual Property Acquisition Reserve Accoun')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / The Remediation Reserve Account,')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / TIF Obligations Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Unused Fee')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / VALA Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Vivarium Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / WEWORK TERMINATION PROCEEDS')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Working Capital Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Working Capital Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Other / Yoga Studio Rent Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('PIP Reserve / Purchaser Upgrade Reserve/ Options & Upgrades Acco')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Balancing Event Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Predevelopment Proiect Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Project (Building) Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Project Expenditure and Leasing Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / PROJECT EXPENDITURE RESER')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Project Reserve / Project Expenditures (Phase I) Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Replacement Reserves / Unit Turnover Expense Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Rollover Reserve / Rollover Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Rollover Reserve / UBS and BofA Rollover Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Seasonality')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Seasonality / Seasonality Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Security Deposit / Liquidity Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Security Deposit / Security Deposit Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Taxes / Tax and Assessment Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Tenant Improvements')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Tenant Improvements / 3A Durango')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Tenant Improvements / Outstanding Peachtree Investments TI Reserve')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Tenant Improvements / Pearson Koutcher Outstanding TI Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('Tenant Improvements / TI Allowance Credit')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / 1H Philadelphia')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / 400 Westlake TI/LC')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / 475 SYCAMORE LEASING RESE')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Adyen TI, TelepacificTI, Inteliquent LC')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Charles River Lease')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Gilead Sciences TI/LC')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Mt. Pocono TI/LC Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / Reckitt Benckiser Leasing Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / TCB TI/LC Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / The SABIC TI/LC Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / The Tl/LC Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / TI/LC Reserve Account')
Insert into CRE.[ReserveAccountMaster]([ReserveAccountName]) values('TI and LC / WEWORK TI/LC RESERVE')