
CREATE PROCEDURE [DW].[usp_ImportUwNote]
	@BatchLogId int,@LastBatchStart datetime, @CurrentBatchStart datetime
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO [DW].BatchDetail (BatchLogId,LandingTableName,LandingStartTime)
	VALUES (@BatchLogId,'L_UwNoteBI',GETDATE())

	DECLARE @id int,@RowCount int
	SET @id = (SELECT @@IDENTITY)



IF(@LastBatchStart is null)
BEGIN

	Declare @minUpdatedDatesrcTable as table
	(
		[MinUpdatedDate] datetime null,
		ShardName nvarchar(max)  NULL
	)
	insert into @minUpdatedDatesrcTable([MinUpdatedDate],ShardName)
	EXEC sp_execute_remote @data_source_name  = N'RemoteReferenceData', @stmt = N'Select MIN(AuditaddDate) as AuditaddDate from tblNote '


	SET @LastBatchStart = (Select [MinUpdatedDate] from @minUpdatedDatesrcTable)
END

DECLARE @query nvarchar(MAX) = N'
Select 
Distinct n.NoteId,
n.ControlId_F,
n.PrimaryDebtFlag,
LLienPositionCd_F.LienPositionDesc as LienPositionCd_F,
LIntCalcMethodCd_F.IntCalcMethodDesc as IntCalcMethodCd_F,
LRateTypeCd_F.RateTypeDesc as RateTypeCd_F,
LPaymentFreqCd_F.PaymentFreqDesc as PaymentFreqCd_F,
LInterestCollectionTypeCd_F.InterestCollectionTypeDesc as InterestCollectionTypeCd_F,
LAmortizationCd_F.AmortizationTypeName as AmortizationCd_F,
orgInterimServ_OrgId_F.OrganizationName as InterimServ_OrgId_F,
orgInterimCustodian_OrgId_F.OrganizationName as  InterimCustodian_OrgId_F,
n.NoteName,
n.NoteDate,
n.NoteDateApproximateSw,
n.Priority,
n.ProjectedFundingDate,
n.IndexName,
n.IndexSource,
n.IndexPercent,
n.IndexAsOfDate,
n.HyerAmortizationFlag,
n.HyperAmortizationTerm,
n.HyperAmortizationDate,
n.OrigLoanAmount,
n.FirstPIPaymentDate,
n.InterestSpread,
n.OrigIntRate,
n.InterestRateForAmortization,
n.MonthlyDebtService,
n.PaymentOverride,
n.PaymentOverrideAmount,
n.DSCROverride,
n.DSCROverrideAmount,
n.LoanTerm,
n.ARDTerm,
n.ARDLoanBalance,
n.StatedMaturityDate,
n.LoanConstant,
n.MaxIntAmount,
n.AmountToBeFunded,
n.BalloonARDAmount,
n.FutureFundingPurpose,
n.PrincipalBalance,
n.AmortizationTerm,
CAST(n.AmortizationComments as nvarchar(max)) as AmortizationComments,
CAST(n.HyperAmortComments as nvarchar(max)) as HyperAmortComments,
n.AmortFixedDefaultIfNotPaidSw,
n.AmortFixedDefaultIfNotPaidAmt,
n.AmortIOPeriod,
n.AmortFixedPrincipleAmt,
n.OriginationFee,
n.OriginationFeePct,
n.InterestRateLock,
n.InterestRateLockDate,
n.InterestRateFloorSw,
n.InterestRateFloorPct,
n.InterestRateFloorPortion,
CAST(n.InterestRateFloorComments as nvarchar(max)) as InterestRateFloorComments,

n.InterestRateLockExpiration,
n.MatrixSpreadAtClose,
CAST(n.MatrixSpreadAtCloseComments as nvarchar(max)) as MatrixSpreadAtCloseComments,

n.ServicingStrip,
n.InitialIoInterestRate,
n.InterimServFee,
n.InterimServType,
n.PayAndAccrueSw,
n.PayRate,
CAST(n.PayAndAccrueComment as nvarchar(max)) as PayAndAccrueComment,

n.TrapExcessCasflowSw,
CAST(n.TrapExcessCashflowComments as nvarchar(max)) as TrapExcessCashflowComments,
 
n.PerformanceHoldbackType,
n.SecondayFinancing,
n.ExitFee,
n.ExitFeePct,
n.ExitFeeReducedIfFinSw,
CAST(n.ExitFeeReducedIfFinComment as nvarchar(max)) as ExitFeeReducedIfFinComment,

n.MpCallOption,
CAST(n.MpCallOptionDesc as nvarchar(max)) as MpCallOptionDesc,

n.MpAllowFutAdvances,
CAST(n.MpAllowFutAdvancesDesc as nvarchar(max)) as MpAllowFutAdvancesDesc,

n.MpStandstill,
CAST(n.MpComment as nvarchar(max)) as MpComment,

n.ArmLoanInternallyCappedSw,
n.ArmInterestRateCappedReqSw,
n.ArmLiborCap,
CAST(n.ArmIntRateCapDesc as nvarchar(max)) as ArmIntRateCapDesc,

CAST(n.ArmLiborDefinition as nvarchar(max)) as ArmLiborDefinition,
CAST(n.ArmLiborDeterminationDate as nvarchar(max)) as ArmLiborDeterminationDate,

n.GCM_Cusip,
n.GCM_TradeAccount,
n.GCM_IkonBoxNum,
n.GCM_IkonCopyStatus,
n.GCM_OriginalsOutDate,
n.GCM_AccountantsCopyDate,
n.GCM_SandPCopyDate,
n.GCM_FitchCopyDate,
n.GCM_MoodysCopyDate,
n.GCM_BBuyerCopyDate,
n.GCM_ServicerCopyDate,
n.GCM_TabNumber,
CAST(n.GCM_BoxContent as nvarchar(max)) as GCM_BoxContent,

n.GCM_BoxNumber,
n.GCM_ArchieveSerialNumber,
n.GCM_ArchieveDate,
n.GCM_DestroyedDate,
CAST(n.GCM_InternalComments as nvarchar(max)) as GCM_InternalComments,

n.AuditAddDate,
n.AuditAddUserId,
n.AuditUpdateDate,
n.AuditUpdateUserId,
n.DaysofFreeLock,

CAST(n.NoteComments as nvarchar(max)) as NoteComments,

n.AverageLife,
n.Duration,
n.FundingDate,
n.AltIndexName,
n.AltIntPct,
n.BondEquivPct,
n.IOCostPct,
n.AMBenefitPct,
n.FloorBenefitPct,
n.MiscSpreadPct,
n.FreeRLPct,
n.RLChargeBenefitPct,
n.fundedAmount,
n.NoteNumber,
n.InterestRateLockedPercent,
n.DV01Amount,
n.TolRel2InitDepositPct,
n.CurrentDepositAmount,
LNoteCurrencyCD_F.CurrencyDesc as NoteCurrencyCD_F,
n.InterimServContact_UserID_F,
n.SyndicateSell,
n.DMCDO,
n.DMREPO,
n.Controlling,
LInterimServicer_ContactID_F.FirstName+'' ''+LInterimServicer_ContactID_F.LastName  as InterimServicer_ContactID_F,
n.MonthlyDebtServiceIO,
n.MonthlyDebtServiceFinal,
n.isLocked,
n.FinancingSource,
n.AdvanceRate,
n.CovenantISCR,
n.CovenantDSCR,
n.LTV,
n.LTC,
n.ELClass,
n.IRRBaselI,
n.IRRBaselII,
n.LGD,
n.LTVCovenantAsStabilized,
n.LTCCovenantAsStabilized,
n.DSCRCovenantAsIsStressed,
n.DSCRCovenantAsStabilized,
n.ISCRCovenantAsStabilized,
n.MinimumDebtYield,
n.LGDPct,
n.ELPct,
orgAgentBank_OrgId_F.OrganizationName as AgentBank_OrgId_F,
LAgentBank_ContactId_F.FirstName+'' ''+LAgentBank_ContactId_F.LastName  as  AgentBank_ContactId_F,
orgCoAgentBank_OrgId_F.OrganizationName as  CoAgentBank_OrgId_F,
LCoAgentBank_ContactId_F.FirstName+'' ''+LCoAgentBank_ContactId_F.LastName  as CoAgentBank_ContactId_F,
n.LoanAdminCostRate,
n.InvestmentGrade,
n.StartLTV,
n.StartLTC,
n.StartDSCR,
n.StartISCR,
CAST(n.ASRNoteComments as nvarchar(max)) as ASRNoteComments,

n.ActualRepaymentDate,
n.StubInterestAmt,
LNegAmTreatmentCd_F.NegAmTreatmentDesc as NegAmTreatmentCd_F,
n.MpCallOptionDate,
n.MonthlyDebtServiceIOFinal,
n.ModifiedNoteSw,
n.ModificationParentNoteId_F,

LSystemCodeCd_F.SystemCodeDesc as SystemCodeCd_F,
LFacilityTypeCd_F.FacilityTypeDesc as FacilityTypeCd_F,
n.isPrimaryDebtFlag,
n.EstFundDate,
n.ClientIdentifier,
LPropertyContainerID_F.ContainerName as PropertyContainerID_F,
n.InitialFixedPeriod,
LFacilityTypeOtherCd_F.FacilityTypeDesc as FacilityTypeOtherCd_F,
n.IncrementalRenewalRevenue,
n.InterestRateForUnderwritingSave,
n.NoteIDAsString,
n.PreviousNoteDate,
n.ExtensionFee,
n.AllocationDate,
n.OrigFundingDate,
n.StubAmortSchedDate,
n.StubAmortInterestAmt,
n.StubAmortDaysInPeriod,
n.StubAmortInterestRate,
n.StubAmortBalanceAmt,
n.InvestorSpread,
n.ClientNoteName,
n.SyncFundingDate,
vw_AcctNote.TotalCommitment,
vw_AcctNote.TotalCurrentAdjustedCommitment,
0.0 as PastFunding,
0.0 as FutureFunding
from tblNote n
left join tblzCdLienPosition LLienPositionCd_F on LLienPositionCd_F.LienPositionCd = n.LienPositionCd_F
left join tblzCdIntCalcMethod LIntCalcMethodCd_F on LIntCalcMethodCd_F.IntCalcMethodCd = n.IntCalcMethodCd_F
left join tblzCdRateType LRateTypeCd_F on LRateTypeCd_F.RateTypeCode = n.RateTypeCd_F
left join tblzCdPaymentFreq LPaymentFreqCd_F on LPaymentFreqCd_F.PaymentFreqCd = n.PaymentFreqCd_F
left join tblzCdInterestCollectionType LInterestCollectionTypeCd_F on LInterestCollectionTypeCd_F.InterestCollectonTypeCd = n.InterestCollectionTypeCd_F
left join tblzCdAmortizationType LAmortizationCd_F on LAmortizationCd_F.AmortizationCd = n.AmortizationCd_F	
left join tblOrganization orgInterimServ_OrgId_F on orgInterimServ_OrgId_F.OrganizationID = n.InterimServ_OrgId_F
left join tblOrganization orgInterimCustodian_OrgId_F on orgInterimCustodian_OrgId_F.OrganizationID = n.InterimCustodian_OrgId_F	
left join tblzCDCurrencyCd LNoteCurrencyCD_F on LNoteCurrencyCD_F.CurrencyCd = n.NoteCurrencyCD_F
left join tblContact LInterimServicer_ContactID_F on LInterimServicer_ContactID_F.contactid = n.InterimServicer_ContactID_F
left join tblOrganization orgAgentBank_OrgId_F on orgAgentBank_OrgId_F.OrganizationID = n.AgentBank_OrgId_F	
left join tblContact LAgentBank_ContactId_F on LAgentBank_ContactId_F.contactid = n.AgentBank_ContactId_F	
left join tblOrganization orgCoAgentBank_OrgId_F on orgCoAgentBank_OrgId_F.OrganizationID = n.CoAgentBank_OrgId_F	
left join tblContact LCoAgentBank_ContactId_F on LCoAgentBank_ContactId_F.contactid = n.CoAgentBank_ContactId_F		
left join tblzcdNegAmTreatment LNegAmTreatmentCd_F on LNegAmTreatmentCd_F.NegAmTreatmentCD = n.NegAmTreatmentCd_F	
left join tblzCdNoteSystemCode LSystemCodeCd_F on LSystemCodeCd_F.SystemCodeCd = n.SystemCodeCd_F
left join tblzCdFacilityType LFacilityTypeCd_F on LFacilityTypeCd_F.FacilityTypeCd = n.FacilityTypeCd_F
left join tblzCdFacilityTypeOther LFacilityTypeOtherCd_F on LFacilityTypeOtherCd_F.FacilityTypeOtherCd = n.FacilityTypeOtherCd_F
left join tblPropertyContainer LPropertyContainerID_F on LPropertyContainerID_F.PropertyContainerID = n.PropertyContainerID_F
left join [acore].[vw_AcctNote] vw_AcctNote on vw_AcctNote.NoteID = n.noteid
WHERE (n.AuditAddDate > '''+Convert(Nvarchar(max),@LastBatchStart,121)+'''
				and n.AuditAddDate <  '''+Convert(Nvarchar(max),@CurrentBatchStart,121)+'''  ) 
				OR 
				(n.AuditUpdateDate > '''+Convert(Nvarchar(max),@LastBatchStart,121)+'''
				and n.AuditUpdateDate < '''+Convert(Nvarchar(max),@CurrentBatchStart,121)+''' )
'
--================================
Declare @BSNote as Table(
NoteId	 int NULL ,
ControlId_F	 nvarchar(10)  NULL ,
PrimaryDebtFlag	 nvarchar(3)  NULL ,
LienPositionCd_F	 nvarchar(256)  NULL ,
IntCalcMethodCd_F	 nvarchar(256)  NULL ,
RateTypeCd_F	 nvarchar(256)  NULL ,
PaymentFreqCd_F	 nvarchar(256)  NULL ,
InterestCollectionTypeCd_F	 nvarchar(256)  NULL ,
AmortizationCd_F	 nvarchar(256)  NULL ,
InterimServ_OrgId_F	 nvarchar(256)  NULL ,
InterimCustodian_OrgId_F	 nvarchar(256)  NULL ,
NoteName	 nvarchar(60)  NULL ,
NoteDate	 datetime  NULL ,
NoteDateApproximateSw	 bit  NULL ,
Priority	 int  NULL ,
ProjectedFundingDate	 datetime  NULL ,
IndexName	 nvarchar(20)  NULL ,
IndexSource	 nvarchar(30)  NULL ,
IndexPercent	 float  NULL ,
IndexAsOfDate	 datetime  NULL ,
HyerAmortizationFlag	 nvarchar(3)  NULL ,
HyperAmortizationTerm	 int  NULL ,
HyperAmortizationDate	 datetime  NULL ,
OrigLoanAmount	decimal(28,15)  NULL ,
FirstPIPaymentDate	 datetime  NULL ,
InterestSpread	 float  NULL ,
OrigIntRate	 float  NULL ,
InterestRateForAmortization	 float  NULL ,
MonthlyDebtService	decimal(28,15)  NULL ,
PaymentOverride	 bit  NULL ,
PaymentOverrideAmount	decimal(28,15)  NULL ,
DSCROverride	 bit  NULL ,
DSCROverrideAmount	decimal(28,15)  NULL ,
LoanTerm	 int  NULL ,
ARDTerm	 int  NULL ,
ARDLoanBalance	decimal(28,15)  NULL ,
StatedMaturityDate	 datetime  NULL ,
LoanConstant	 float  NULL ,
MaxIntAmount	decimal(28,15)  NULL ,
AmountToBeFunded	decimal(28,15)  NULL ,
BalloonARDAmount	decimal(28,15)  NULL ,
FutureFundingPurpose	 nvarchar(50)  NULL ,
PrincipalBalance	decimal(28,15)  NULL ,
AmortizationTerm	 int  NULL ,
AmortizationComments	nvarchar(256)  NULL ,
HyperAmortComments	nvarchar(MAX)  NULL ,
AmortFixedDefaultIfNotPaidSw	 nvarchar(3)  NULL ,
AmortFixedDefaultIfNotPaidAmt	decimal(28,15)  NULL ,
AmortIOPeriod	 int  NULL ,
AmortFixedPrincipleAmt	decimal(28,15)  NULL ,
OriginationFee	decimal(28,15)  NULL ,
OriginationFeePct	 float  NULL ,
InterestRateLock	 nvarchar(3)  NULL ,
InterestRateLockDate	 datetime  NULL ,
InterestRateFloorSw	 nvarchar(3)  NULL ,
InterestRateFloorPct	 float  NULL ,
InterestRateFloorPortion	 float  NULL ,
InterestRateFloorComments	nvarchar(MAX)  NULL ,
InterestRateLockExpiration	 datetime  NULL ,
MatrixSpreadAtClose	 float  NULL ,
MatrixSpreadAtCloseComments	nvarchar(MAX)  NULL ,
ServicingStrip	 float  NULL ,
InitialIoInterestRate	 float  NULL ,
InterimServFee	 float  NULL ,
InterimServType	 nvarchar(15)  NULL ,
PayAndAccrueSw	 nvarchar(3)  NULL ,
PayRate	 float  NULL ,
PayAndAccrueComment	nvarchar(MAX)  NULL ,
TrapExcessCasflowSw	 nvarchar(3)  NULL ,
TrapExcessCashflowComments	nvarchar(MAX)  NULL ,
PerformanceHoldbackType	 nvarchar(150)  NULL ,
SecondayFinancing	 nvarchar(3)  NULL ,
ExitFee	decimal(28,15)  NULL ,
ExitFeePct	 float  NULL ,
ExitFeeReducedIfFinSw	 nvarchar(3)  NULL ,
ExitFeeReducedIfFinComment	nvarchar(MAX)  NULL ,
MpCallOption	 nvarchar(3)  NULL ,
MpCallOptionDesc	nvarchar(MAX)  NULL ,
MpAllowFutAdvances	 nvarchar(3)  NULL ,
MpAllowFutAdvancesDesc	nvarchar(MAX)  NULL ,
MpStandstill	 nvarchar(3)  NULL ,
MpComment	nvarchar(MAX)  NULL ,
ArmLoanInternallyCappedSw	 nvarchar(3)  NULL ,
ArmInterestRateCappedReqSw	 nvarchar(3)  NULL ,
ArmLiborCap	 float  NULL ,
ArmIntRateCapDesc	nvarchar(MAX)  NULL ,
ArmLiborDefinition	nvarchar(MAX)  NULL ,
ArmLiborDeterminationDate	nvarchar(MAX)  NULL ,
GCM_Cusip	 nvarchar(9)  NULL ,
GCM_TradeAccount	 nvarchar(5)  NULL ,
GCM_IkonBoxNum	 int  NULL ,
GCM_IkonCopyStatus	 nvarchar(50)  NULL ,
GCM_OriginalsOutDate	 datetime  NULL ,
GCM_AccountantsCopyDate	 datetime  NULL ,
GCM_SandPCopyDate	 datetime  NULL ,
GCM_FitchCopyDate	 datetime  NULL ,
GCM_MoodysCopyDate	 datetime  NULL ,
GCM_BBuyerCopyDate	 datetime  NULL ,
GCM_ServicerCopyDate	 datetime  NULL ,
GCM_TabNumber	 int  NULL ,
GCM_BoxContent	nvarchar(MAX)  NULL ,
GCM_BoxNumber	 int  NULL ,
GCM_ArchieveSerialNumber	 int  NULL ,
GCM_ArchieveDate	 datetime  NULL ,
GCM_DestroyedDate	 datetime  NULL ,
GCM_InternalComments	nvarchar(MAX)  NULL ,
AuditAddDate	 datetime  NULL ,
AuditAddUserId	 nvarchar(150)  NULL ,
AuditUpdateDate	 datetime  NULL ,
AuditUpdateUserId	 nvarchar(150)  NULL ,
DaysofFreeLock	 int  NULL ,
NoteComments	nvarchar(MAX)  NULL ,
AverageLife	 decimal(28,15)  NULL ,
Duration	 decimal(28,15)  NULL ,
FundingDate	 datetime  NULL ,
AltIndexName	 nvarchar(20)  NULL ,
AltIntPct	 float  NULL ,
BondEquivPct	 float  NULL ,
IOCostPct	 float  NULL ,
AMBenefitPct	 float  NULL ,
FloorBenefitPct	 float  NULL ,
MiscSpreadPct	 float  NULL ,
FreeRLPct	 float  NULL ,
RLChargeBenefitPct	 float  NULL ,
fundedAmount	decimal(28,15)  NULL ,
NoteNumber	 nvarchar(20)  NULL ,
InterestRateLockedPercent	decimal(28,15)  NULL ,
DV01Amount	decimal(28,15)  NULL ,
TolRel2InitDepositPct	 float  NULL ,
CurrentDepositAmount	decimal(28,15)  NULL ,
NoteCurrencyCD_F	 nvarchar(256)  NULL ,
InterimServContact_UserID_F	 int  NULL ,
SyndicateSell	decimal(28,15)  NULL ,
DMCDO	 float  NULL ,
DMREPO	 float  NULL ,
Controlling	 bit  NULL ,
InterimServicer_ContactID_F	 nvarchar(256)  NULL ,
MonthlyDebtServiceIO	decimal(28,15)  NULL ,
MonthlyDebtServiceFinal	decimal(28,15)  NULL ,
isLocked	 int  NULL ,
FinancingSource	 nvarchar(50)  NULL ,
AdvanceRate	 float  NULL ,
CovenantISCR	 decimal(28,15)  NULL ,
CovenantDSCR	 decimal(28,15)  NULL ,
LTV	 float  NULL ,
LTC	 float  NULL ,
ELClass	 int  NULL ,
IRRBaselI	 float  NULL ,
IRRBaselII	 float  NULL ,
LGD	 float  NULL ,
LTVCovenantAsStabilized	 float  NULL ,
LTCCovenantAsStabilized	 float  NULL ,
DSCRCovenantAsIsStressed	 decimal(28,15)  NULL ,
DSCRCovenantAsStabilized	 decimal(28,15)  NULL ,
ISCRCovenantAsStabilized	 decimal(28,15)  NULL ,
MinimumDebtYield	 float  NULL ,
LGDPct	 float  NULL ,
ELPct	 float  NULL ,
AgentBank_OrgId_F	 nvarchar(256)  NULL ,
AgentBank_ContactId_F	 nvarchar(256)  NULL ,
CoAgentBank_OrgId_F	 nvarchar(256)  NULL ,
CoAgentBank_ContactId_F	 nvarchar(256)  NULL ,
LoanAdminCostRate	 float  NULL ,
InvestmentGrade	 nvarchar(3)  NULL ,
StartLTV	 float  NULL ,
StartLTC	 float  NULL ,
StartDSCR	 decimal(28,15)  NULL ,
StartISCR	 decimal(28,15)  NULL ,
ASRNoteComments	nvarchar(MAX)  NULL ,
ActualRepaymentDate	 datetime  NULL ,
StubInterestAmt	decimal(28,15)  NULL ,
NegAmTreatmentCd_F	 nvarchar(256)  NULL ,
MpCallOptionDate	 datetime  NULL ,
MonthlyDebtServiceIOFinal	decimal(28,15)  NULL ,
ModifiedNoteSw	 bit  NULL ,
ModificationParentNoteId_F	 int  NULL ,
SystemCodeCd_F	 nvarchar(256)  NULL ,
FacilityTypeCd_F	 nvarchar(256)  NULL ,
isPrimaryDebtFlag	 int  NULL ,
EstFundDate	 datetime  NULL ,
ClientIdentifier	 nvarchar(200)  NULL ,
PropertyContainerID_F	 nvarchar(256)  NULL ,
InitialFixedPeriod	 nvarchar(20)  NULL ,
FacilityTypeOtherCd_F	 nvarchar(256)  NULL ,
IncrementalRenewalRevenue	decimal(28,15)  NULL ,
InterestRateForUnderwritingSave	 decimal(28,15)  NULL ,
NoteIDAsString	 nvarchar(26)  NULL ,
PreviousNoteDate	 datetime  NULL ,
ExtensionFee	 float  NULL ,
AllocationDate	 date  NULL ,
OrigFundingDate	 date  NULL ,
StubAmortSchedDate	 date  NULL ,
StubAmortInterestAmt	 float  NULL ,
StubAmortDaysInPeriod	 int  NULL ,
StubAmortInterestRate	 float  NULL ,
StubAmortBalanceAmt	 float  NULL ,
InvestorSpread	 float  NULL ,
ClientNoteName	 nvarchar(60)  NULL ,
SyncFundingDate	 int  NULL ,

TotalCommitment decimal(28,15)  NULL ,
TotalCurrentAdjustedCommitment decimal(28,15)  NULL ,
PastFunding decimal(28,15)  NULL ,
FutureFunding decimal(28,15)  NULL,

ShardName nvarchar(max)  NULL
)

INSERT INTO @BSNote(
NoteId	 ,
ControlId_F	 ,
PrimaryDebtFlag	 ,
LienPositionCd_F	 ,
IntCalcMethodCd_F	 ,
RateTypeCd_F	 ,
PaymentFreqCd_F	 ,
InterestCollectionTypeCd_F	 ,
AmortizationCd_F	 ,
InterimServ_OrgId_F	 ,
InterimCustodian_OrgId_F	 ,
NoteName	 ,
NoteDate	 ,
NoteDateApproximateSw	 ,
Priority	 ,
ProjectedFundingDate	 ,
IndexName	 ,
IndexSource	 ,
IndexPercent	 ,
IndexAsOfDate	 ,
HyerAmortizationFlag	 ,
HyperAmortizationTerm	 ,
HyperAmortizationDate	 ,
OrigLoanAmount	 ,
FirstPIPaymentDate	 ,
InterestSpread	 ,
OrigIntRate	 ,
InterestRateForAmortization	 ,
MonthlyDebtService	 ,
PaymentOverride	 ,
PaymentOverrideAmount	 ,
DSCROverride	 ,
DSCROverrideAmount	 ,
LoanTerm	 ,
ARDTerm	 ,
ARDLoanBalance	 ,
StatedMaturityDate	 ,
LoanConstant	 ,
MaxIntAmount	 ,
AmountToBeFunded	 ,
BalloonARDAmount	 ,
FutureFundingPurpose	 ,
PrincipalBalance	 ,
AmortizationTerm	 ,
AmortizationComments	 ,
HyperAmortComments	 ,
AmortFixedDefaultIfNotPaidSw	 ,
AmortFixedDefaultIfNotPaidAmt	 ,
AmortIOPeriod	 ,
AmortFixedPrincipleAmt	 ,
OriginationFee	 ,
OriginationFeePct	 ,
InterestRateLock	 ,
InterestRateLockDate	 ,
InterestRateFloorSw	 ,
InterestRateFloorPct	 ,
InterestRateFloorPortion	 ,
InterestRateFloorComments	 ,
InterestRateLockExpiration	 ,
MatrixSpreadAtClose	 ,
MatrixSpreadAtCloseComments	 ,
ServicingStrip	 ,
InitialIoInterestRate	 ,
InterimServFee	 ,
InterimServType	 ,
PayAndAccrueSw	 ,
PayRate	 ,
PayAndAccrueComment	 ,
TrapExcessCasflowSw	 ,
TrapExcessCashflowComments	 ,
PerformanceHoldbackType	 ,
SecondayFinancing	 ,
ExitFee	 ,
ExitFeePct	 ,
ExitFeeReducedIfFinSw	 ,
ExitFeeReducedIfFinComment	 ,
MpCallOption	 ,
MpCallOptionDesc	 ,
MpAllowFutAdvances	 ,
MpAllowFutAdvancesDesc	 ,
MpStandstill	 ,
MpComment	 ,
ArmLoanInternallyCappedSw	 ,
ArmInterestRateCappedReqSw	 ,
ArmLiborCap	 ,
ArmIntRateCapDesc	 ,
ArmLiborDefinition	 ,
ArmLiborDeterminationDate	 ,
GCM_Cusip	 ,
GCM_TradeAccount	 ,
GCM_IkonBoxNum	 ,
GCM_IkonCopyStatus	 ,
GCM_OriginalsOutDate	 ,
GCM_AccountantsCopyDate	 ,
GCM_SandPCopyDate	 ,
GCM_FitchCopyDate	 ,
GCM_MoodysCopyDate	 ,
GCM_BBuyerCopyDate	 ,
GCM_ServicerCopyDate	 ,
GCM_TabNumber	 ,
GCM_BoxContent	 ,
GCM_BoxNumber	 ,
GCM_ArchieveSerialNumber	 ,
GCM_ArchieveDate	 ,
GCM_DestroyedDate	 ,
GCM_InternalComments	 ,
AuditAddDate	 ,
AuditAddUserId	 ,
AuditUpdateDate	 ,
AuditUpdateUserId	 ,
DaysofFreeLock	 ,
NoteComments	 ,
AverageLife	 ,
Duration	 ,
FundingDate	 ,
AltIndexName	 ,
AltIntPct	 ,
BondEquivPct	 ,
IOCostPct	 ,
AMBenefitPct	 ,
FloorBenefitPct	 ,
MiscSpreadPct	 ,
FreeRLPct	 ,
RLChargeBenefitPct	 ,
fundedAmount	 ,
NoteNumber	 ,
InterestRateLockedPercent	 ,
DV01Amount	 ,
TolRel2InitDepositPct	 ,
CurrentDepositAmount	 ,
NoteCurrencyCD_F	 ,
InterimServContact_UserID_F	 ,
SyndicateSell	 ,
DMCDO	 ,
DMREPO	 ,
Controlling	 ,
InterimServicer_ContactID_F	 ,
MonthlyDebtServiceIO	 ,
MonthlyDebtServiceFinal	 ,
isLocked	 ,
FinancingSource	 ,
AdvanceRate	 ,
CovenantISCR	 ,
CovenantDSCR	 ,
LTV	 ,
LTC	 ,
ELClass	 ,
IRRBaselI	 ,
IRRBaselII	 ,
LGD	 ,
LTVCovenantAsStabilized	 ,
LTCCovenantAsStabilized	 ,
DSCRCovenantAsIsStressed	 ,
DSCRCovenantAsStabilized	 ,
ISCRCovenantAsStabilized	 ,
MinimumDebtYield	 ,
LGDPct	 ,
ELPct	 ,
AgentBank_OrgId_F	 ,
AgentBank_ContactId_F	 ,
CoAgentBank_OrgId_F	 ,
CoAgentBank_ContactId_F	 ,
LoanAdminCostRate	 ,
InvestmentGrade	 ,
StartLTV	 ,
StartLTC	 ,
StartDSCR	 ,
StartISCR	 ,
ASRNoteComments	 ,
ActualRepaymentDate	 ,
StubInterestAmt	 ,
NegAmTreatmentCd_F	 ,
MpCallOptionDate	 ,
MonthlyDebtServiceIOFinal	 ,
ModifiedNoteSw	 ,
ModificationParentNoteId_F	 ,
SystemCodeCd_F	 ,
FacilityTypeCd_F	 ,
isPrimaryDebtFlag	 ,
EstFundDate	 ,
ClientIdentifier	 ,
PropertyContainerID_F	 ,
InitialFixedPeriod	 ,
FacilityTypeOtherCd_F	 ,
IncrementalRenewalRevenue	 ,
InterestRateForUnderwritingSave	 ,
NoteIDAsString	 ,
PreviousNoteDate	 ,
ExtensionFee	 ,
AllocationDate	 ,
OrigFundingDate	 ,
StubAmortSchedDate	 ,
StubAmortInterestAmt	 ,
StubAmortDaysInPeriod	 ,
StubAmortInterestRate	 ,
StubAmortBalanceAmt	 ,
InvestorSpread	 ,
ClientNoteName	 ,
SyncFundingDate	,
TotalCommitment,
TotalCurrentAdjustedCommitment,
PastFunding,
FutureFunding,
ShardName 
)
EXEC sp_execute_remote @data_source_name  = N'RemoteReferenceData', @stmt = @query
--================================


Truncate table [DW].[L_UwNoteBI]

INSERT INTO [DW].[L_UwNoteBI]
           (NoteId	 ,
ControlId_F	 ,
PrimaryDebtFlag	 ,
LienPositionCd_F	 ,
IntCalcMethodCd_F	 ,
RateTypeCd_F	 ,
PaymentFreqCd_F	 ,
InterestCollectionTypeCd_F	 ,
AmortizationCd_F	 ,
InterimServ_OrgId_F	 ,
InterimCustodian_OrgId_F	 ,
NoteName	 ,
NoteDate	 ,
NoteDateApproximateSw	 ,
Priority	 ,
ProjectedFundingDate	 ,
IndexName	 ,
IndexSource	 ,
IndexPercent	 ,
IndexAsOfDate	 ,
HyerAmortizationFlag	 ,
HyperAmortizationTerm	 ,
HyperAmortizationDate	 ,
OrigLoanAmount	 ,
FirstPIPaymentDate	 ,
InterestSpread	 ,
OrigIntRate	 ,
InterestRateForAmortization	 ,
MonthlyDebtService	 ,
PaymentOverride	 ,
PaymentOverrideAmount	 ,
DSCROverride	 ,
DSCROverrideAmount	 ,
LoanTerm	 ,
ARDTerm	 ,
ARDLoanBalance	 ,
StatedMaturityDate	 ,
LoanConstant	 ,
MaxIntAmount	 ,
AmountToBeFunded	 ,
BalloonARDAmount	 ,
FutureFundingPurpose	 ,
PrincipalBalance	 ,
AmortizationTerm	 ,
AmortizationComments	 ,
HyperAmortComments	 ,
AmortFixedDefaultIfNotPaidSw	 ,
AmortFixedDefaultIfNotPaidAmt	 ,
AmortIOPeriod	 ,
AmortFixedPrincipleAmt	 ,
OriginationFee	 ,
OriginationFeePct	 ,
InterestRateLock	 ,
InterestRateLockDate	 ,
InterestRateFloorSw	 ,
InterestRateFloorPct	 ,
InterestRateFloorPortion	 ,
InterestRateFloorComments	 ,
InterestRateLockExpiration	 ,
MatrixSpreadAtClose	 ,
MatrixSpreadAtCloseComments	 ,
ServicingStrip	 ,
InitialIoInterestRate	 ,
InterimServFee	 ,
InterimServType	 ,
PayAndAccrueSw	 ,
PayRate	 ,
PayAndAccrueComment	 ,
TrapExcessCasflowSw	 ,
TrapExcessCashflowComments	 ,
PerformanceHoldbackType	 ,
SecondayFinancing	 ,
ExitFee	 ,
ExitFeePct	 ,
ExitFeeReducedIfFinSw	 ,
ExitFeeReducedIfFinComment	 ,
MpCallOption	 ,
MpCallOptionDesc	 ,
MpAllowFutAdvances	 ,
MpAllowFutAdvancesDesc	 ,
MpStandstill	 ,
MpComment	 ,
ArmLoanInternallyCappedSw	 ,
ArmInterestRateCappedReqSw	 ,
ArmLiborCap	 ,
ArmIntRateCapDesc	 ,
ArmLiborDefinition	 ,
ArmLiborDeterminationDate	 ,
GCM_Cusip	 ,
GCM_TradeAccount	 ,
GCM_IkonBoxNum	 ,
GCM_IkonCopyStatus	 ,
GCM_OriginalsOutDate	 ,
GCM_AccountantsCopyDate	 ,
GCM_SandPCopyDate	 ,
GCM_FitchCopyDate	 ,
GCM_MoodysCopyDate	 ,
GCM_BBuyerCopyDate	 ,
GCM_ServicerCopyDate	 ,
GCM_TabNumber	 ,
GCM_BoxContent	 ,
GCM_BoxNumber	 ,
GCM_ArchieveSerialNumber	 ,
GCM_ArchieveDate	 ,
GCM_DestroyedDate	 ,
GCM_InternalComments	 ,
AuditAddDate	 ,
AuditAddUserId	 ,
AuditUpdateDate	 ,
AuditUpdateUserId	 ,
DaysofFreeLock	 ,
NoteComments	 ,
AverageLife	 ,
Duration	 ,
FundingDate	 ,
AltIndexName	 ,
AltIntPct	 ,
BondEquivPct	 ,
IOCostPct	 ,
AMBenefitPct	 ,
FloorBenefitPct	 ,
MiscSpreadPct	 ,
FreeRLPct	 ,
RLChargeBenefitPct	 ,
fundedAmount	 ,
NoteNumber	 ,
InterestRateLockedPercent	 ,
DV01Amount	 ,
TolRel2InitDepositPct	 ,
CurrentDepositAmount	 ,
NoteCurrencyCD_F	 ,
InterimServContact_UserID_F	 ,
SyndicateSell	 ,
DMCDO	 ,
DMREPO	 ,
Controlling	 ,
InterimServicer_ContactID_F	 ,
MonthlyDebtServiceIO	 ,
MonthlyDebtServiceFinal	 ,
isLocked	 ,
FinancingSource	 ,
AdvanceRate	 ,
CovenantISCR	 ,
CovenantDSCR	 ,
LTV	 ,
LTC	 ,
ELClass	 ,
IRRBaselI	 ,
IRRBaselII	 ,
LGD	 ,
LTVCovenantAsStabilized	 ,
LTCCovenantAsStabilized	 ,
DSCRCovenantAsIsStressed	 ,
DSCRCovenantAsStabilized	 ,
ISCRCovenantAsStabilized	 ,
MinimumDebtYield	 ,
LGDPct	 ,
ELPct	 ,
AgentBank_OrgId_F	 ,
AgentBank_ContactId_F	 ,
CoAgentBank_OrgId_F	 ,
CoAgentBank_ContactId_F	 ,
LoanAdminCostRate	 ,
InvestmentGrade	 ,
StartLTV	 ,
StartLTC	 ,
StartDSCR	 ,
StartISCR	 ,
ASRNoteComments	 ,
ActualRepaymentDate	 ,
StubInterestAmt	 ,
NegAmTreatmentCd_F	 ,
MpCallOptionDate	 ,
MonthlyDebtServiceIOFinal	 ,
ModifiedNoteSw	 ,
ModificationParentNoteId_F	 ,
SystemCodeCd_F	 ,
FacilityTypeCd_F	 ,
isPrimaryDebtFlag	 ,
EstFundDate	 ,
ClientIdentifier	 ,
PropertyContainerID_F	 ,
InitialFixedPeriod	 ,
FacilityTypeOtherCd_F	 ,
IncrementalRenewalRevenue	 ,
InterestRateForUnderwritingSave	 ,
NoteIDAsString	 ,
PreviousNoteDate	 ,
ExtensionFee	 ,
AllocationDate	 ,
OrigFundingDate	 ,
StubAmortSchedDate	 ,
StubAmortInterestAmt	 ,
StubAmortDaysInPeriod	 ,
StubAmortInterestRate	 ,
StubAmortBalanceAmt	 ,
InvestorSpread	 ,
ClientNoteName	 ,
SyncFundingDate	,
TotalCommitment,
TotalCurrentAdjustedCommitment,
PastFunding,
FutureFunding
)

Select
NoteId	 ,
ControlId_F	 ,
PrimaryDebtFlag	 ,
LienPositionCd_F	 ,
IntCalcMethodCd_F	 ,
RateTypeCd_F	 ,
PaymentFreqCd_F	 ,
InterestCollectionTypeCd_F	 ,
AmortizationCd_F	 ,
InterimServ_OrgId_F	 ,
InterimCustodian_OrgId_F	 ,
NoteName	 ,
NoteDate	 ,
NoteDateApproximateSw	 ,
Priority	 ,
ProjectedFundingDate	 ,
IndexName	 ,
IndexSource	 ,
IndexPercent	 ,
IndexAsOfDate	 ,
HyerAmortizationFlag	 ,
HyperAmortizationTerm	 ,
HyperAmortizationDate	 ,
OrigLoanAmount	 ,
FirstPIPaymentDate	 ,
InterestSpread	 ,
OrigIntRate	 ,
InterestRateForAmortization	 ,
MonthlyDebtService	 ,
PaymentOverride	 ,
PaymentOverrideAmount	 ,
DSCROverride	 ,
DSCROverrideAmount	 ,
LoanTerm	 ,
ARDTerm	 ,
ARDLoanBalance	 ,
StatedMaturityDate	 ,
LoanConstant	 ,
MaxIntAmount	 ,
AmountToBeFunded	 ,
BalloonARDAmount	 ,
FutureFundingPurpose	 ,
PrincipalBalance	 ,
AmortizationTerm	 ,
AmortizationComments	 ,
HyperAmortComments	 ,
AmortFixedDefaultIfNotPaidSw	 ,
AmortFixedDefaultIfNotPaidAmt	 ,
AmortIOPeriod	 ,
AmortFixedPrincipleAmt	 ,
OriginationFee	 ,
OriginationFeePct	 ,
InterestRateLock	 ,
InterestRateLockDate	 ,
InterestRateFloorSw	 ,
InterestRateFloorPct	 ,
InterestRateFloorPortion	 ,
InterestRateFloorComments	 ,
InterestRateLockExpiration	 ,
MatrixSpreadAtClose	 ,
MatrixSpreadAtCloseComments	 ,
ServicingStrip	 ,
InitialIoInterestRate	 ,
InterimServFee	 ,
InterimServType	 ,
PayAndAccrueSw	 ,
PayRate	 ,
PayAndAccrueComment	 ,
TrapExcessCasflowSw	 ,
TrapExcessCashflowComments	 ,
PerformanceHoldbackType	 ,
SecondayFinancing	 ,
ExitFee	 ,
ExitFeePct	 ,
ExitFeeReducedIfFinSw	 ,
ExitFeeReducedIfFinComment	 ,
MpCallOption	 ,
MpCallOptionDesc	 ,
MpAllowFutAdvances	 ,
MpAllowFutAdvancesDesc	 ,
MpStandstill	 ,
MpComment	 ,
ArmLoanInternallyCappedSw	 ,
ArmInterestRateCappedReqSw	 ,
ArmLiborCap	 ,
ArmIntRateCapDesc	 ,
ArmLiborDefinition	 ,
ArmLiborDeterminationDate	 ,
GCM_Cusip	 ,
GCM_TradeAccount	 ,
GCM_IkonBoxNum	 ,
GCM_IkonCopyStatus	 ,
GCM_OriginalsOutDate	 ,
GCM_AccountantsCopyDate	 ,
GCM_SandPCopyDate	 ,
GCM_FitchCopyDate	 ,
GCM_MoodysCopyDate	 ,
GCM_BBuyerCopyDate	 ,
GCM_ServicerCopyDate	 ,
GCM_TabNumber	 ,
GCM_BoxContent	 ,
GCM_BoxNumber	 ,
GCM_ArchieveSerialNumber	 ,
GCM_ArchieveDate	 ,
GCM_DestroyedDate	 ,
GCM_InternalComments	 ,
AuditAddDate	 ,
AuditAddUserId	 ,
AuditUpdateDate	 ,
AuditUpdateUserId	 ,
DaysofFreeLock	 ,
NoteComments	 ,
AverageLife	 ,
Duration	 ,
FundingDate	 ,
AltIndexName	 ,
AltIntPct	 ,
BondEquivPct	 ,
IOCostPct	 ,
AMBenefitPct	 ,
FloorBenefitPct	 ,
MiscSpreadPct	 ,
FreeRLPct	 ,
RLChargeBenefitPct	 ,
fundedAmount	 ,
NoteNumber	 ,
InterestRateLockedPercent	 ,
DV01Amount	 ,
TolRel2InitDepositPct	 ,
CurrentDepositAmount	 ,
NoteCurrencyCD_F	 ,
InterimServContact_UserID_F	 ,
SyndicateSell	 ,
DMCDO	 ,
DMREPO	 ,
Controlling	 ,
InterimServicer_ContactID_F	 ,
MonthlyDebtServiceIO	 ,
MonthlyDebtServiceFinal	 ,
isLocked	 ,
FinancingSource	 ,
AdvanceRate	 ,
CovenantISCR	 ,
CovenantDSCR	 ,
LTV	 ,
LTC	 ,
ELClass	 ,
IRRBaselI	 ,
IRRBaselII	 ,
LGD	 ,
LTVCovenantAsStabilized	 ,
LTCCovenantAsStabilized	 ,
DSCRCovenantAsIsStressed	 ,
DSCRCovenantAsStabilized	 ,
ISCRCovenantAsStabilized	 ,
MinimumDebtYield	 ,
LGDPct	 ,
ELPct	 ,
AgentBank_OrgId_F	 ,
AgentBank_ContactId_F	 ,
CoAgentBank_OrgId_F	 ,
CoAgentBank_ContactId_F	 ,
LoanAdminCostRate	 ,
InvestmentGrade	 ,
StartLTV	 ,
StartLTC	 ,
StartDSCR	 ,
StartISCR	 ,
ASRNoteComments	 ,
ActualRepaymentDate	 ,
StubInterestAmt	 ,
NegAmTreatmentCd_F	 ,
MpCallOptionDate	 ,
MonthlyDebtServiceIOFinal	 ,
ModifiedNoteSw	 ,
ModificationParentNoteId_F	 ,
SystemCodeCd_F	 ,
FacilityTypeCd_F	 ,
isPrimaryDebtFlag	 ,
EstFundDate	 ,
ClientIdentifier	 ,
PropertyContainerID_F	 ,
InitialFixedPeriod	 ,
FacilityTypeOtherCd_F	 ,
IncrementalRenewalRevenue	 ,
InterestRateForUnderwritingSave	 ,
NoteIDAsString	 ,
PreviousNoteDate	 ,
ExtensionFee	 ,
AllocationDate	 ,
OrigFundingDate	 ,
StubAmortSchedDate	 ,
StubAmortInterestAmt	 ,
StubAmortDaysInPeriod	 ,
StubAmortInterestRate	 ,
StubAmortBalanceAmt	 ,
InvestorSpread	 ,
ClientNoteName	 ,
SyncFundingDate	,
TotalCommitment,
TotalCurrentAdjustedCommitment,
PastFunding,
FutureFunding
from @BSNote n

--WHERE (n.AuditAddDate  > @LastBatchStart 
--				and n.AuditAddDate  < @CurrentBatchStart) 
--				OR 
--				(n.AuditUpdateDate  > @LastBatchStart 
--				and n.AuditUpdateDate  < @CurrentBatchStart)


SET @RowCount = @@ROWCOUNT
Print(char(9) +'usp_ImportUwNote - ROWCOUNT = '+cast(@RowCount  as varchar(100)));



UPDATE [DW].BatchDetail
SET
LandingEndTime = GETDATE(),
LandingRecordCount = @RowCount
WHERE BatchDetailId = @id





END


