

CREATE PROCEDURE [DW].[usp_ImportNotePeriodicCalcByEntity]
AS
BEGIN
	SET NOCOUNT ON;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 

--Declare @analysisID UNIQUEIDENTIFIER  = (Select analysisID from core.analysis where [Name] = 'Default')


Truncate table [DW].[NotePeriodicCalcByEntityBI] 


INSERT INTO [DW].[NotePeriodicCalcByEntityBI]
(NotePeriodicCalcID,
NotePeriodicCalcAutoID ,
NoteID,
CRENoteID,
EntityName,
PctAllocation,
PeriodEndDate,
[Month],
ActualCashFlows,
GAAPCashFlows,
EndingGAAPBookValue,
TotalGAAPIncomeforthePeriod,
InterestAccrualforthePeriod,
PIKInterestAccrualforthePeriod,
TotalAmortAccrualForPeriod,
AccumulatedAmort,
BeginningBalance,
TotalFutureAdvancesForThePeriod,
TotalDiscretionaryCurtailmentsforthePeriod,
InterestPaidOnPaymentDate,
TotalCouponStrippedforthePeriod,
CouponStrippedonPaymentDate,
ScheduledPrincipal,
PrincipalPaid,
BalloonPayment,
EndingBalance,
--ExitFeeIncludedInLevelYield,
--ExitFeeExcludedFromLevelYield,
--AdditionalFeesIncludedInLevelYield,
--AdditionalFeesExcludedFromLevelYield,
--OriginationFeeStripping,
--ExitFeeStrippingIncldinLevelYield,
--ExitFeeStrippingExcldfromLevelYield,
--AddlFeesStrippingIncldinLevelYield,
--AddlFeesStrippingExcldfromLevelYield,
EndOfPeriodWAL,
PIKInterestFromPIKSourceNote,
PIKInterestTransferredToRelatedNote,
PIKInterestForThePeriod,
BeginningPIKBalanceNotInsideLoanBalance,
PIKInterestForPeriodNotInsideLoanBalance,
PIKBalanceBalloonPayment,
EndingPIKBalanceNotInsideLoanBalance,
CostBasis,
PreCapBasis,
BasisCap,
AmortAccrualLevelYield,
ScheduledPrincipalShortfall,
PrincipalShortfall,
PrincipalLoss,
InterestForPeriodShortfall,
InterestPaidOnPMTDateShortfall,
CumulativeInterestPaidOnPMTDateShortfall,
InterestShortfallLoss,
InterestShortfallRecovery,
BeginningFinancingBalance,
TotalFinancingDrawsCurtailmentsForPeriod,
FinancingBalloon,
EndingFinancingBalance,
FinancingInterestPaid,
FinancingFeesPaid,
PeriodLeveredYield,
OrigFeeAccrual ,
DiscountPremiumAccrual  ,
ExitFeeAccrual  ,
AllInCouponRate,
[CleanCost],
[GrossDeferredFees],
[DeferredFeesReceivable],
[CleanCostPrice],
[AmortizedCostPrice],
[AdditionalFeeAccrual],
[CapitalizedCostAccrual],
DailySpreadInterestbeforeStrippingRule,
DailyLiborInterestbeforeStrippingRule,
ReversalofPriorInterestAccrual,
InterestReceivedinCurrentPeriod,
CurrentPeriodInterestAccrual,
TotalGAAPInterestFortheCurrentPeriod,
InvestmentBasis,
CurrentPeriodInterestAccrualPeriodEnddate,
AccruedInterestBI ,
LIBORPercentage,
SpreadPercentage,
CreatedBy,
CreatedDate,
UpdatedBy,
UpdatedDate,
AnalysisID,
AnalysisName,
FeeStrippedforthePeriod,
PIKInterestPercentage
)

Select
cf.NotePeriodicCalcID,
cf.NotePeriodicCalcAutoID ,
na.NoteID,n.crenoteid CRENoteID,
e.EntityName,
na.PctAllocation,
cf.PeriodEndDate,
cf.[Month],
(cf.ActualCashFlows  * PctAllocation)  as ActualCashFlows,
(cf.GAAPCashFlows  * PctAllocation)  as GAAPCashFlows,
(cf.EndingGAAPBookValue  * PctAllocation)  as EndingGAAPBookValue,

null as TotalGAAPIncomeforthePeriod,
null as InterestAccrualforthePeriod,
null as PIKInterestAccrualforthePeriod,

(cf.TotalAmortAccrualForPeriod  * PctAllocation)  as TotalAmortAccrualForPeriod,
(cf.AccumulatedAmort  * PctAllocation)  as AccumulatedAmort,
(cf.BeginningBalance  * PctAllocation)  as BeginningBalance,
(cf.TotalFutureAdvancesForThePeriod  * PctAllocation)  as TotalFutureAdvancesForThePeriod,
(cf.TotalDiscretionaryCurtailmentsforthePeriod  * PctAllocation)  as TotalDiscretionaryCurtailmentsforthePeriod,
(cf.InterestPaidOnPaymentDate  * PctAllocation)  as InterestPaidOnPaymentDate,
(cf.TotalCouponStrippedforthePeriod  * PctAllocation)  as TotalCouponStrippedforthePeriod,
(cf.CouponStrippedonPaymentDate  * PctAllocation)  as CouponStrippedonPaymentDate,
(cf.ScheduledPrincipal  * PctAllocation)  as ScheduledPrincipal,
(cf.PrincipalPaid  * PctAllocation)  as PrincipalPaid,
(cf.BalloonPayment  * PctAllocation)  as BalloonPayment,
(cf.EndingBalance  * PctAllocation)  as EndingBalance,
--(cf.ExitFeeIncludedInLevelYield  * PctAllocation)  as ExitFeeIncludedInLevelYield,
--(cf.ExitFeeExcludedFromLevelYield  * PctAllocation)  as ExitFeeExcludedFromLevelYield,
--(cf.AdditionalFeesIncludedInLevelYield  * PctAllocation)  as AdditionalFeesIncludedInLevelYield,
--(cf.AdditionalFeesExcludedFromLevelYield  * PctAllocation)  as AdditionalFeesExcludedFromLevelYield,
--(cf.OriginationFeeStripping  * PctAllocation)  as OriginationFeeStripping,
--(cf.ExitFeeStrippingIncldinLevelYield  * PctAllocation)  as ExitFeeStrippingIncldinLevelYield,
--(cf.ExitFeeStrippingExcldfromLevelYield  * PctAllocation)  as ExitFeeStrippingExcldfromLevelYield,
--(cf.AddlFeesStrippingIncldinLevelYield  * PctAllocation)  as AddlFeesStrippingIncldinLevelYield,
--(cf.AddlFeesStrippingExcldfromLevelYield  * PctAllocation)  as AddlFeesStrippingExcldfromLevelYield,
(cf.EndOfPeriodWAL  * PctAllocation)  as EndOfPeriodWAL,
(cf.PIKInterestFromPIKSourceNote  * PctAllocation)  as PIKInterestFromPIKSourceNote,
(cf.PIKInterestTransferredToRelatedNote  * PctAllocation)  as PIKInterestTransferredToRelatedNote,
(cf.PIKInterestForThePeriod  * PctAllocation)  as PIKInterestForThePeriod,
(cf.BeginningPIKBalanceNotInsideLoanBalance  * PctAllocation)  as BeginningPIKBalanceNotInsideLoanBalance,
(cf.PIKInterestForPeriodNotInsideLoanBalance  * PctAllocation)  as PIKInterestForPeriodNotInsideLoanBalance,
(cf.PIKBalanceBalloonPayment  * PctAllocation)  as PIKBalanceBalloonPayment,
(cf.EndingPIKBalanceNotInsideLoanBalance  * PctAllocation)  as EndingPIKBalanceNotInsideLoanBalance,
(cf.CostBasis  * PctAllocation)  as CostBasis,
(cf.PreCapBasis  * PctAllocation)  as PreCapBasis,
(cf.BasisCap  * PctAllocation)  as BasisCap,
(cf.AmortAccrualLevelYield  * PctAllocation)  as AmortAccrualLevelYield,
(cf.ScheduledPrincipalShortfall  * PctAllocation)  as ScheduledPrincipalShortfall,
(cf.PrincipalShortfall  * PctAllocation)  as PrincipalShortfall,
(cf.PrincipalLoss  * PctAllocation)  as PrincipalLoss,
(cf.InterestForPeriodShortfall  * PctAllocation)  as InterestForPeriodShortfall,
(cf.InterestPaidOnPMTDateShortfall  * PctAllocation)  as InterestPaidOnPMTDateShortfall,
(cf.CumulativeInterestPaidOnPMTDateShortfall  * PctAllocation)  as CumulativeInterestPaidOnPMTDateShortfall,
(cf.InterestShortfallLoss  * PctAllocation)  as InterestShortfallLoss,
(cf.InterestShortfallRecovery  * PctAllocation)  as InterestShortfallRecovery,
(cf.BeginningFinancingBalance  * PctAllocation)  as BeginningFinancingBalance,
(cf.TotalFinancingDrawsCurtailmentsForPeriod  * PctAllocation)  as TotalFinancingDrawsCurtailmentsForPeriod,
(cf.FinancingBalloon  * PctAllocation)  as FinancingBalloon,
(cf.EndingFinancingBalance  * PctAllocation)  as EndingFinancingBalance,
(cf.FinancingInterestPaid  * PctAllocation)  as FinancingInterestPaid,
(cf.FinancingFeesPaid  * PctAllocation)  as FinancingFeesPaid,
(cf.PeriodLeveredYield  * PctAllocation)  as PeriodLeveredYield,
(cf.OrigFeeAccrual   * PctAllocation)  as OrigFeeAccrual ,
(cf.DiscountPremiumAccrual    * PctAllocation)  as DiscountPremiumAccrual  ,
(cf.ExitFeeAccrual    * PctAllocation)  as ExitFeeAccrual  ,
(cf.AllInCouponRate  * PctAllocation)  as AllInCouponRate,
(cf.CleanCost  * PctAllocation)  as CleanCost,
(cf.GrossDeferredFees  * PctAllocation)  as GrossDeferredFees,
(cf.DeferredFeesReceivable  * PctAllocation)  as DeferredFeesReceivable,
(cf.CleanCostPrice  * PctAllocation)  as CleanCostPrice,
(cf.AmortizedCostPrice  * PctAllocation)  as AmortizedCostPrice,
(cf.AdditionalFeeAccrual  * PctAllocation)  as AdditionalFeeAccrual,
(cf.CapitalizedCostAccrual  * PctAllocation)  as CapitalizedCostAccrual,
(cf.DailySpreadInterestbeforeStrippingRule  * PctAllocation)  as DailySpreadInterestbeforeStrippingRule,
(cf.DailyLiborInterestbeforeStrippingRule  * PctAllocation)  as DailyLiborInterestbeforeStrippingRule,
(cf.ReversalofPriorInterestAccrual  * PctAllocation)  as ReversalofPriorInterestAccrual,
(cf.InterestReceivedinCurrentPeriod  * PctAllocation)  as InterestReceivedinCurrentPeriod,
(cf.CurrentPeriodInterestAccrual  * PctAllocation)  as CurrentPeriodInterestAccrual,
(cf.TotalGAAPInterestFortheCurrentPeriod  * PctAllocation)  as TotalGAAPInterestFortheCurrentPeriod,
(cf.InvestmentBasis  * PctAllocation)  as InvestmentBasis,
 
(cf.CurrentPeriodInterestAccrualPeriodEnddate  * PctAllocation)  as CurrentPeriodInterestAccrualPeriodEnddate,   ----(cf.CurrentPeriodInterestAccrual  * PctAllocation) 

(cf.AccruedInterestBI  * PctAllocation)  as AccruedInterestBI,
(cf.LIBORPercentage  * PctAllocation)  as LIBORPercentage,
(cf.SpreadPercentage  * PctAllocation)  as SpreadPercentage,
cf.CreatedBy,
cf.CreatedDate,
cf.UpdatedBy,
cf.UpdatedDate,
cf.AnalysisID,
cf.AnalysisName,
(cf.FeeStrippedforthePeriod  * PctAllocation)  as FeeStrippedforthePeriod, 
(cf.PIKInterestPercentage  * PctAllocation)  as PIKInterestPercentage

from CRE.NoteEntityAllocation na
inner join cre.note n on n.noteid = na.noteid
inner join cre.Entity e on e.entityID= na.entityID and e.EntityName in ('RSLIC','SNCC' ,'PIIC' ,'TMR' ,'HCC' ,'USSIC' ,'TMNF' ,'HAIH')
inner join DW.NotePeriodicCalcBI cf on cf.noteid = n.noteid and cf.analysisID in (Select analysisID from core.analysis where [Name] in ('Default','Expected Maturity Date (with Prepay, Index Flat)') )
and cf.PeriodEndDate >= CAST(DateADD(year,-1,getdate())  as Date) ---and cf.PeriodEndDate <= CAST(getdate() as Date))

Where cf.analysisID in (Select analysisID from core.analysis where [Name] in ('Default','Expected Maturity Date (with Prepay, Index Flat)') )
and cf.PeriodEndDate >= CAST(DateADD(year,-1,getdate())  as Date) 
and cf.[Month] is not null 



---and cf.PeriodEndDate <= CAST(getdate() as Date))


--Delete ncBI from [DW].[NotePeriodicCalcByEntityBI] ncBI
--inner join 
--(
--	Select Distinct NoteID,AnalysisID from [DW].[L_NotePeriodicCalcBI]

--)L on L.Noteid = ncBI.Noteid and ncBI.AnalysisID = L.AnalysisID

--INSERT INTO [DW].[NotePeriodicCalcByEntityBI]
--(NotePeriodicCalcID,
--NotePeriodicCalcAutoID ,
--NoteID,
--CRENoteID,
--EntityName,
--PctAllocation,
--PeriodEndDate,
--[Month],
--ActualCashFlows,
--GAAPCashFlows,
--EndingGAAPBookValue,
--TotalGAAPIncomeforthePeriod,
--InterestAccrualforthePeriod,
--PIKInterestAccrualforthePeriod,
--TotalAmortAccrualForPeriod,
--AccumulatedAmort,
--BeginningBalance,
--TotalFutureAdvancesForThePeriod,
--TotalDiscretionaryCurtailmentsforthePeriod,
--InterestPaidOnPaymentDate,
--TotalCouponStrippedforthePeriod,
--CouponStrippedonPaymentDate,
--ScheduledPrincipal,
--PrincipalPaid,
--BalloonPayment,
--EndingBalance,
----ExitFeeIncludedInLevelYield,
----ExitFeeExcludedFromLevelYield,
----AdditionalFeesIncludedInLevelYield,
----AdditionalFeesExcludedFromLevelYield,
----OriginationFeeStripping,
----ExitFeeStrippingIncldinLevelYield,
----ExitFeeStrippingExcldfromLevelYield,
----AddlFeesStrippingIncldinLevelYield,
----AddlFeesStrippingExcldfromLevelYield,
--EndOfPeriodWAL,
--PIKInterestFromPIKSourceNote,
--PIKInterestTransferredToRelatedNote,
--PIKInterestForThePeriod,
--BeginningPIKBalanceNotInsideLoanBalance,
--PIKInterestForPeriodNotInsideLoanBalance,
--PIKBalanceBalloonPayment,
--EndingPIKBalanceNotInsideLoanBalance,
--CostBasis,
--PreCapBasis,
--BasisCap,
--AmortAccrualLevelYield,
--ScheduledPrincipalShortfall,
--PrincipalShortfall,
--PrincipalLoss,
--InterestForPeriodShortfall,
--InterestPaidOnPMTDateShortfall,
--CumulativeInterestPaidOnPMTDateShortfall,
--InterestShortfallLoss,
--InterestShortfallRecovery,
--BeginningFinancingBalance,
--TotalFinancingDrawsCurtailmentsForPeriod,
--FinancingBalloon,
--EndingFinancingBalance,
--FinancingInterestPaid,
--FinancingFeesPaid,
--PeriodLeveredYield,
--OrigFeeAccrual ,
--DiscountPremiumAccrual  ,
--ExitFeeAccrual  ,
--AllInCouponRate,
--[CleanCost],
--[GrossDeferredFees],
--[DeferredFeesReceivable],
--[CleanCostPrice],
--[AmortizedCostPrice],
--[AdditionalFeeAccrual],
--[CapitalizedCostAccrual],
--DailySpreadInterestbeforeStrippingRule,
--DailyLiborInterestbeforeStrippingRule,
--ReversalofPriorInterestAccrual,
--InterestReceivedinCurrentPeriod,
--CurrentPeriodInterestAccrual,
--TotalGAAPInterestFortheCurrentPeriod,
--InvestmentBasis,
--CurrentPeriodInterestAccrualPeriodEnddate,
--AccruedInterestBI ,
--LIBORPercentage,
--SpreadPercentage,
--CreatedBy,
--CreatedDate,
--UpdatedBy,
--UpdatedDate,
--AnalysisID,
--AnalysisName,
--FeeStrippedforthePeriod,
--PIKInterestPercentage
--)

--Select
--cf.NotePeriodicCalcID,
--cf.NotePeriodicCalcAutoID ,
--na.NoteID,n.crenoteid CRENoteID,
--e.EntityName,
--na.PctAllocation,
--cf.PeriodEndDate,
--cf.[Month],
--(cf.ActualCashFlows  * PctAllocation)  as ActualCashFlows,
--(cf.GAAPCashFlows  * PctAllocation)  as GAAPCashFlows,
--(cf.EndingGAAPBookValue  * PctAllocation)  as EndingGAAPBookValue,
--(cf.TotalGAAPIncomeforthePeriod  * PctAllocation)  as TotalGAAPIncomeforthePeriod,
--(cf.InterestAccrualforthePeriod  * PctAllocation)  as InterestAccrualforthePeriod,
--(cf.PIKInterestAccrualforthePeriod  * PctAllocation)  as PIKInterestAccrualforthePeriod,
--(cf.TotalAmortAccrualForPeriod  * PctAllocation)  as TotalAmortAccrualForPeriod,
--(cf.AccumulatedAmort  * PctAllocation)  as AccumulatedAmort,
--(cf.BeginningBalance  * PctAllocation)  as BeginningBalance,
--(cf.TotalFutureAdvancesForThePeriod  * PctAllocation)  as TotalFutureAdvancesForThePeriod,
--(cf.TotalDiscretionaryCurtailmentsforthePeriod  * PctAllocation)  as TotalDiscretionaryCurtailmentsforthePeriod,
--(cf.InterestPaidOnPaymentDate  * PctAllocation)  as InterestPaidOnPaymentDate,
--(cf.TotalCouponStrippedforthePeriod  * PctAllocation)  as TotalCouponStrippedforthePeriod,
--(cf.CouponStrippedonPaymentDate  * PctAllocation)  as CouponStrippedonPaymentDate,
--(cf.ScheduledPrincipal  * PctAllocation)  as ScheduledPrincipal,
--(cf.PrincipalPaid  * PctAllocation)  as PrincipalPaid,
--(cf.BalloonPayment  * PctAllocation)  as BalloonPayment,
--(cf.EndingBalance  * PctAllocation)  as EndingBalance,
----(cf.ExitFeeIncludedInLevelYield  * PctAllocation)  as ExitFeeIncludedInLevelYield,
----(cf.ExitFeeExcludedFromLevelYield  * PctAllocation)  as ExitFeeExcludedFromLevelYield,
----(cf.AdditionalFeesIncludedInLevelYield  * PctAllocation)  as AdditionalFeesIncludedInLevelYield,
----(cf.AdditionalFeesExcludedFromLevelYield  * PctAllocation)  as AdditionalFeesExcludedFromLevelYield,
----(cf.OriginationFeeStripping  * PctAllocation)  as OriginationFeeStripping,
----(cf.ExitFeeStrippingIncldinLevelYield  * PctAllocation)  as ExitFeeStrippingIncldinLevelYield,
----(cf.ExitFeeStrippingExcldfromLevelYield  * PctAllocation)  as ExitFeeStrippingExcldfromLevelYield,
----(cf.AddlFeesStrippingIncldinLevelYield  * PctAllocation)  as AddlFeesStrippingIncldinLevelYield,
----(cf.AddlFeesStrippingExcldfromLevelYield  * PctAllocation)  as AddlFeesStrippingExcldfromLevelYield,
--(cf.EndOfPeriodWAL  * PctAllocation)  as EndOfPeriodWAL,
--(cf.PIKInterestFromPIKSourceNote  * PctAllocation)  as PIKInterestFromPIKSourceNote,
--(cf.PIKInterestTransferredToRelatedNote  * PctAllocation)  as PIKInterestTransferredToRelatedNote,
--(cf.PIKInterestForThePeriod  * PctAllocation)  as PIKInterestForThePeriod,
--(cf.BeginningPIKBalanceNotInsideLoanBalance  * PctAllocation)  as BeginningPIKBalanceNotInsideLoanBalance,
--(cf.PIKInterestForPeriodNotInsideLoanBalance  * PctAllocation)  as PIKInterestForPeriodNotInsideLoanBalance,
--(cf.PIKBalanceBalloonPayment  * PctAllocation)  as PIKBalanceBalloonPayment,
--(cf.EndingPIKBalanceNotInsideLoanBalance  * PctAllocation)  as EndingPIKBalanceNotInsideLoanBalance,
--(cf.CostBasis  * PctAllocation)  as CostBasis,
--(cf.PreCapBasis  * PctAllocation)  as PreCapBasis,
--(cf.BasisCap  * PctAllocation)  as BasisCap,
--(cf.AmortAccrualLevelYield  * PctAllocation)  as AmortAccrualLevelYield,
--(cf.ScheduledPrincipalShortfall  * PctAllocation)  as ScheduledPrincipalShortfall,
--(cf.PrincipalShortfall  * PctAllocation)  as PrincipalShortfall,
--(cf.PrincipalLoss  * PctAllocation)  as PrincipalLoss,
--(cf.InterestForPeriodShortfall  * PctAllocation)  as InterestForPeriodShortfall,
--(cf.InterestPaidOnPMTDateShortfall  * PctAllocation)  as InterestPaidOnPMTDateShortfall,
--(cf.CumulativeInterestPaidOnPMTDateShortfall  * PctAllocation)  as CumulativeInterestPaidOnPMTDateShortfall,
--(cf.InterestShortfallLoss  * PctAllocation)  as InterestShortfallLoss,
--(cf.InterestShortfallRecovery  * PctAllocation)  as InterestShortfallRecovery,
--(cf.BeginningFinancingBalance  * PctAllocation)  as BeginningFinancingBalance,
--(cf.TotalFinancingDrawsCurtailmentsForPeriod  * PctAllocation)  as TotalFinancingDrawsCurtailmentsForPeriod,
--(cf.FinancingBalloon  * PctAllocation)  as FinancingBalloon,
--(cf.EndingFinancingBalance  * PctAllocation)  as EndingFinancingBalance,
--(cf.FinancingInterestPaid  * PctAllocation)  as FinancingInterestPaid,
--(cf.FinancingFeesPaid  * PctAllocation)  as FinancingFeesPaid,
--(cf.PeriodLeveredYield  * PctAllocation)  as PeriodLeveredYield,
--(cf.OrigFeeAccrual   * PctAllocation)  as OrigFeeAccrual ,
--(cf.DiscountPremiumAccrual    * PctAllocation)  as DiscountPremiumAccrual  ,
--(cf.ExitFeeAccrual    * PctAllocation)  as ExitFeeAccrual  ,
--(cf.AllInCouponRate  * PctAllocation)  as AllInCouponRate,
--(cf.CleanCost  * PctAllocation)  as CleanCost,
--(cf.GrossDeferredFees  * PctAllocation)  as GrossDeferredFees,
--(cf.DeferredFeesReceivable  * PctAllocation)  as DeferredFeesReceivable,
--(cf.CleanCostPrice  * PctAllocation)  as CleanCostPrice,
--(cf.AmortizedCostPrice  * PctAllocation)  as AmortizedCostPrice,
--(cf.AdditionalFeeAccrual  * PctAllocation)  as AdditionalFeeAccrual,
--(cf.CapitalizedCostAccrual  * PctAllocation)  as CapitalizedCostAccrual,
--(cf.DailySpreadInterestbeforeStrippingRule  * PctAllocation)  as DailySpreadInterestbeforeStrippingRule,
--(cf.DailyLiborInterestbeforeStrippingRule  * PctAllocation)  as DailyLiborInterestbeforeStrippingRule,
--(cf.ReversalofPriorInterestAccrual  * PctAllocation)  as ReversalofPriorInterestAccrual,
--(cf.InterestReceivedinCurrentPeriod  * PctAllocation)  as InterestReceivedinCurrentPeriod,
--(cf.CurrentPeriodInterestAccrual  * PctAllocation)  as CurrentPeriodInterestAccrual,
--(cf.TotalGAAPInterestFortheCurrentPeriod  * PctAllocation)  as TotalGAAPInterestFortheCurrentPeriod,
--(cf.InvestmentBasis  * PctAllocation)  as InvestmentBasis,
--(cf.CurrentPeriodInterestAccrualPeriodEnddate  * PctAllocation)  as CurrentPeriodInterestAccrualPeriodEnddate,
--(cf.AccruedInterestBI  * PctAllocation)  as AccruedInterestBI,
--(cf.LIBORPercentage  * PctAllocation)  as LIBORPercentage,
--(cf.SpreadPercentage  * PctAllocation)  as SpreadPercentage,
--cf.CreatedBy,
--cf.CreatedDate,
--cf.UpdatedBy,
--cf.UpdatedDate,
--cf.AnalysisID,
--cf.AnalysisName,
--(cf.FeeStrippedforthePeriod  * PctAllocation)  as FeeStrippedforthePeriod, 
--(cf.PIKInterestPercentage  * PctAllocation)  as PIKInterestPercentage
--from CRE.NoteEntityAllocation na
--inner join cre.note n on n.noteid = na.noteid
--inner join cre.Entity e on e.entityID= na.entityID
--inner join DW.NotePeriodicCalcBI cf on cf.noteid = n.noteid
--Inner join (
--	Select Distinct NoteID,AnalysisID from [DW].[L_NotePeriodicCalcBI] 
--)Landing on Landing.NoteID = cf.Noteid and Landing.AnalysisID = cf.AnalysisID








SET TRANSACTION ISOLATION LEVEL READ COMMITTED 

END


