

CREATE PROCEDURE [DW].[usp_MergeUwDeal]

@BatchLogId int

AS
BEGIN

SET NOCOUNT ON


UPDATE [DW].BatchDetail
SET
BITableName = 'UwDealBI',
BIStartTime = GETDATE()
WHERE BatchLogId = @BatchLogId and LandingTableName = 'L_UwDealBI'


MERGE [DW].UwDealBI DB
USING [DW].L_UwDealBI LDB
ON DB.controlmasterID = LDB.controlmasterID
WHEN MATCHED THEN
	UPDATE 
	SET 
DB.LoanNumber = LDB.LoanNumber,
DB.LoanStatusCd_F = LDB.LoanStatusCd_F,
DB.BrokerName_OrgId_F = LDB.BrokerName_OrgId_F,
DB.LendorName_OrgId_F = LDB.LendorName_OrgId_F,
DB.LawFirm_OrgId_F = LDB.LawFirm_OrgId_F,
DB.Office_OrgId_F = LDB.Office_OrgId_F,
DB.DealRelatedId_F = LDB.DealRelatedId_F,
DB.Competition_Org_Id_F = LDB.Competition_Org_Id_F,
DB.DueDiligenceProvider_OrgId_F = LDB.DueDiligenceProvider_OrgId_F,
DB.OriginalDataSource_F = LDB.OriginalDataSource_F,
DB.MinimumDSCR = LDB.MinimumDSCR,
DB.MinimumDSCRatConstant = LDB.MinimumDSCRatConstant,
DB.MaximumLTV = LDB.MaximumLTV,
DB.MinimumConstantDeal = LDB.MinimumConstantDeal,
DB.PrimaryBanker_UserId_F = LDB.PrimaryBanker_UserId_F,
DB.SecondaryBanker_UserId_F = LDB.SecondaryBanker_UserId_F,
DB.Underwriter_UserID_F = LDB.Underwriter_UserID_F,
DB.ServicersLoanNumber = LDB.ServicersLoanNumber,
DB.DealName = LDB.DealName,
DB.CreditApprovedBy = LDB.CreditApprovedBy,
DB.CreditApprovedComment = LDB.CreditApprovedComment,
DB.SpreadApprovedBy = LDB.SpreadApprovedBy,
DB.SpreadApprovedComment = LDB.SpreadApprovedComment,
DB.Correspondent = LDB.Correspondent,
DB.CorrUW = LDB.CorrUW,
DB.CollateralType = LDB.CollateralType,
DB.DebtServiceAllocated = LDB.DebtServiceAllocated,
DB.LoanPurpose = LDB.LoanPurpose,
DB.LoanProbability = LDB.LoanProbability,
DB.ApplicationReceiveDate = LDB.ApplicationReceiveDate,
DB.ApplicationDate = LDB.ApplicationDate,
DB.LenderRightToMatch = LDB.LenderRightToMatch,
DB.ApplicationDeposit = LDB.ApplicationDeposit,
DB.LockBox = LDB.LockBox,
DB.LockBoxComment = LDB.LockBoxComment,
DB.HardCashManagement = LDB.HardCashManagement,
DB.Recourse = LDB.Recourse,
DB.ClosingConditions = LDB.ClosingConditions,
DB.EstClosingCosts = LDB.EstClosingCosts,
DB.EarnOut = LDB.EarnOut,
DB.IndDirectorReqSw = LDB.IndDirectorReqSw,
DB.NonConsolOpinionReqSw = LDB.NonConsolOpinionReqSw,
DB.OwnershipComments = LDB.OwnershipComments,
DB.BrokerFees = LDB.BrokerFees,
DB.Cashout = LDB.Cashout,
DB.PreliminarySponsor = LDB.PreliminarySponsor,
DB.OngoingDSCRTest = LDB.OngoingDSCRTest,
DB.SpecialPricingNotes = LDB.SpecialPricingNotes,
DB.HardEquityComment = LDB.HardEquityComment,
DB.MatrixSpreadAtClose = LDB.MatrixSpreadAtClose,
DB.MatrixSpreadAtCloseComments = LDB.MatrixSpreadAtCloseComments,
DB.CommitmentExpDate = LDB.CommitmentExpDate,
DB.Comments = LDB.Comments,
DB.TICSw = LDB.TICSw,
DB.MpIsLoanAssumable = LDB.MpIsLoanAssumable,
DB.MpIsLoanAssumableDesc = LDB.MpIsLoanAssumableDesc,
DB.MpEquityParticipation = LDB.MpEquityParticipation,
DB.MpEquityParticipationDesc = LDB.MpEquityParticipationDesc,
DB.MpAllowFutAdvances = LDB.MpAllowFutAdvances,
DB.MpAllowFutAdvancesDesc = LDB.MpAllowFutAdvancesDesc,
DB.MpMaxFutureAdvances = LDB.MpMaxFutureAdvances,
DB.MpFutAdvancesToDate = LDB.MpFutAdvancesToDate,
DB.MpAssumptionFeePct = LDB.MpAssumptionFeePct,
DB.MpAssumptionFeeAmt = LDB.MpAssumptionFeeAmt,
DB.MpAssumptionFee = LDB.MpAssumptionFee,
DB.MpAssumptionFeeDesc = LDB.MpAssumptionFeeDesc,
DB.MpParticipationPercent = LDB.MpParticipationPercent,
DB.MpParticipationPercentDesc = LDB.MpParticipationPercentDesc,
DB.MpRightToInspectRecords = LDB.MpRightToInspectRecords,
DB.MpUnsecuredDebtAllowed = LDB.MpUnsecuredDebtAllowed,
DB.MpMaxUnsecuredDebtAmt = LDB.MpMaxUnsecuredDebtAmt,
DB.MpTradePayablesMaxAmt = LDB.MpTradePayablesMaxAmt,
DB.MpTradePayablesDaysOut = LDB.MpTradePayablesDaysOut,
DB.MpPartialReleasePercent = LDB.MpPartialReleasePercent,
DB.MpPartialReleaseDesc = LDB.MpPartialReleaseDesc,
DB.MpComment = LDB.MpComment,
DB.GCM_DealCounterpartyCode = LDB.GCM_DealCounterpartyCode,
DB.AuditAddDate = LDB.AuditAddDate,
DB.AuditAddUserId = LDB.AuditAddUserId,
DB.AuditUpdateDate = LDB.AuditUpdateDate,
DB.AuditUpdateUserId = LDB.AuditUpdateUserId,
DB.PatriotActApprovedSw = LDB.PatriotActApprovedSw,
DB.OwnerOrgId_F = LDB.OwnerOrgId_F,
DB.BrokerFeesComment = LDB.BrokerFeesComment,
DB.ArchiveInvestorFileSw = LDB.ArchiveInvestorFileSw,
DB.ArchiveLegalBinderSw = LDB.ArchiveLegalBinderSw,
DB.ArchiveComment = LDB.ArchiveComment,
DB.LoanProgramCD_F = LDB.LoanProgramCD_F,
DB.LenderRoleCD_F = LDB.LenderRoleCD_F,
DB.TargetLoan = LDB.TargetLoan,
DB.EstAppraisedCollateralValue = LDB.EstAppraisedCollateralValue,
DB.EstStressedCollateralValue = LDB.EstStressedCollateralValue,
DB.AcquisitionCostofCollateral = LDB.AcquisitionCostofCollateral,
DB.Matrix = LDB.Matrix,
DB.CompetitionComments = LDB.CompetitionComments,
DB.HardEquityAmount = LDB.HardEquityAmount,
DB.DealLocked = LDB.DealLocked,
DB.DealCurrencyCD_F = LDB.DealCurrencyCD_F,
DB.Originator = LDB.Originator,
DB.SourceUsesComment = LDB.SourceUsesComment,
DB.StartLTV = LDB.StartLTV,
DB.FirstLossComment = LDB.FirstLossComment,
DB.Change2TicAfterCloseSw = LDB.Change2TicAfterCloseSw,
DB.SpringingLockBoxComment = LDB.SpringingLockBoxComment,
DB.BrokerFeesPct = LDB.BrokerFeesPct,
DB.CommitmentAmount = LDB.CommitmentAmount,
DB.Analyst_UserId_F = LDB.Analyst_UserId_F,
DB.LoanTypeCD_F = LDB.LoanTypeCD_F,
DB.CreditApprovedDate = LDB.CreditApprovedDate,
DB.SpreadApprovedDate = LDB.SpreadApprovedDate,
DB.DDP_ContactID_F = LDB.DDP_ContactID_F,
DB.Broker_ContactID_F = LDB.Broker_ContactID_F,
DB.Cocounsel_ContactID_F = LDB.Cocounsel_ContactID_F,
DB.Counsel_ContactID_F = LDB.Counsel_ContactID_F,
DB.Paralegal_ContactID_F = LDB.Paralegal_ContactID_F,
DB.RequestedLoanTerm = LDB.RequestedLoanTerm,
DB.RequestedAmortTerm = LDB.RequestedAmortTerm,
DB.RequestedSpread = LDB.RequestedSpread,
DB.RequestedIndex = LDB.RequestedIndex,
DB.RequestedLTV = LDB.RequestedLTV,
DB.RequestedLTC = LDB.RequestedLTC,
DB.TransactionManager_Userid_F = LDB.TransactionManager_Userid_F,
DB.HUDLoanNumber = LDB.HUDLoanNumber,
DB.ApprovalLevel = LDB.ApprovalLevel,
DB.ExistingDebt = LDB.ExistingDebt,
DB.ExistingDebtLender = LDB.ExistingDebtLender,
DB.ExistingDebtAmount = LDB.ExistingDebtAmount,
DB.EarnOutAmount = LDB.EarnOutAmount,
DB.MarketEquityComments = LDB.MarketEquityComments,
DB.BookingLocation_OrgId_F = LDB.BookingLocation_OrgId_F,
DB.PortfolioManager_Userid_F = LDB.PortfolioManager_Userid_F,
DB.PrivateSW = LDB.PrivateSW,
DB.CMBSLoanStatusCd_F = LDB.CMBSLoanStatusCd_F,
DB.CMBSDealGUID = LDB.CMBSDealGUID,
DB.MPFutureAdditionalDebtPermitted = LDB.MPFutureAdditionalDebtPermitted,
DB.NDCApprovedCd_F = LDB.NDCApprovedCd_F,
DB.NDCApprovedBy = LDB.NDCApprovedBy,
DB.NDCApprovedComment = LDB.NDCApprovedComment,
DB.NDCSecuritization = LDB.NDCSecuritization,
DB.NDCSyndication = LDB.NDCSyndication,
DB.NDCApprovedDate = LDB.NDCApprovedDate,
DB.CreditApproved = LDB.CreditApproved,
DB.SpreadApproved = LDB.SpreadApproved,
DB.SecondaryPortfolioManager_UserId_F = LDB.SecondaryPortfolioManager_UserId_F,
DB.Legal_UserId_F = LDB.Legal_UserId_F,
DB.IRRBaselI = LDB.IRRBaselI,
DB.IRRBaselII = LDB.IRRBaselII,
DB.ListedCompany = LDB.ListedCompany,
DB.PriceSensitive = LDB.PriceSensitive,
DB.Confidentiality = LDB.Confidentiality,
DB.Exclusivity = LDB.Exclusivity,
DB.ShareDeal = LDB.ShareDeal,
DB.RequestedPaymentFreqCd_F = LDB.RequestedPaymentFreqCd_F,
DB.RequestedIOTerm = LDB.RequestedIOTerm,
DB.RequestedLTVasStabilzed = LDB.RequestedLTVasStabilzed,
DB.RequestedRateTypeCd_F = LDB.RequestedRateTypeCd_F,
DB.BorrowerImputedEquity = LDB.BorrowerImputedEquity,
DB.LoanSizer_UserId_F = LDB.LoanSizer_UserId_F,
DB.ConstructionManager_UserId_F = LDB.ConstructionManager_UserId_F,
DB.InsuranceManager_UserId_F = LDB.InsuranceManager_UserId_F,
DB.DealIntroducedById_F = LDB.DealIntroducedById_F,
DB.CoCounselCompany_OrgId_F = LDB.CoCounselCompany_OrgId_F,
DB.CoCounselCompany_ContactId_F = LDB.CoCounselCompany_ContactId_F,
DB.SecondaryLawFirm_OrgId_F = LDB.SecondaryLawFirm_OrgId_F,
DB.SecondaryCounsel_ContactID_F = LDB.SecondaryCounsel_ContactID_F,
DB.SpecificDealTeamRequest = LDB.SpecificDealTeamRequest,
DB.QCAnalyst_UserID_F = LDB.QCAnalyst_UserID_F,
DB.OriginatorAssociate = LDB.OriginatorAssociate,
DB.ClosingCoordinator_UserID_F = LDB.ClosingCoordinator_UserID_F,
DB.AssetManager_UserID_F = LDB.AssetManager_UserID_F,
DB.NDCSecuritizationRequiredAmt = LDB.NDCSecuritizationRequiredAmt,
DB.NDCSyndicationRequiredAmt = LDB.NDCSyndicationRequiredAmt,
DB.BrokeredDeal = LDB.BrokeredDeal,
DB.DataTapeFootNotes = LDB.DataTapeFootNotes,
DB.MortgageOriginatingEntityCD_F = LDB.MortgageOriginatingEntityCD_F,
DB.DealSourceCD_F = LDB.DealSourceCD_F,
DB.ProgramManager_UserId_F = LDB.ProgramManager_UserId_F,
DB.SmallLoanPM_UserId_F = LDB.SmallLoanPM_UserId_F,
DB.UnderwritingManager_UserId_F = LDB.UnderwritingManager_UserId_F,
DB.Servicer_UserId_F = LDB.Servicer_UserId_F,
DB.QALead_UserId_F = LDB.QALead_UserId_F,
DB.QAAssociate_UserId_F = LDB.QAAssociate_UserId_F,
DB.ReportManager_UserId_F = LDB.ReportManager_UserId_F,
DB.BorrowerLawFirm_OrgId_F = LDB.BorrowerLawFirm_OrgId_F,
DB.BorrowerInsuranceCo_OrgId_F = LDB.BorrowerInsuranceCo_OrgId_F,
DB.BorrowerCounsel_ContactID_F = LDB.BorrowerCounsel_ContactID_F,
DB.BorrowerInsAgent_ContactID_F = LDB.BorrowerInsAgent_ContactID_F,
DB.Holdback = LDB.Holdback,
DB.HoldbackAmount = LDB.HoldbackAmount,
DB.EstimatedCreditDate = LDB.EstimatedCreditDate,
DB.Secondary_BrokerName_OrgId_F = LDB.Secondary_BrokerName_OrgId_F,
DB.Secondary_Broker_ContactID_F = LDB.Secondary_Broker_ContactID_F,
DB.RepeatSponsorComment = LDB.RepeatSponsorComment,
DB.KickOffEmailSent = LDB.KickOffEmailSent,
DB.ExpirationStatus = LDB.ExpirationStatus,
DB.ApplicationDepositFeePct = LDB.ApplicationDepositFeePct,
DB.EarnOutComment = LDB.EarnOutComment,
DB.RealizedLossToTrust = LDB.RealizedLossToTrust,
DB.NonRecoverability = LDB.NonRecoverability,
DB.LastSetupChangeDate = LDB.LastSetupChangeDate,
DB.LastLoanContributionDate = LDB.LastLoanContributionDate,
DB.LastPropContributionDate = LDB.LastPropContributionDate,
DB.AssumptionDate = LDB.AssumptionDate,
DB.LockBoxAtClosing = LDB.LockBoxAtClosing,
DB.BrokerFeesPctTypeCd_F = LDB.BrokerFeesPctTypeCd_F,
DB.BrokerFeesPctPaymentCd_F = LDB.BrokerFeesPctPaymentCd_F,
DB.Recovery = LDB.Recovery,
DB.USTL_UserId_F = LDB.USTL_UserId_F,
DB.USQCAnalyst_UserId_F = LDB.USQCAnalyst_UserId_F,
DB.Sponsor_OrgId_F = LDB.Sponsor_OrgId_F,
DB.AvailabilityCd_F = LDB.AvailabilityCd_F,
DB.AvailabilityDate = LDB.AvailabilityDate,
DB.ForeignInvestorsMore = LDB.ForeignInvestorsMore,
DB.PCAccountingContact = LDB.PCAccountingContact,
DB.PCAccountingContactNumber = LDB.PCAccountingContactNumber,
DB.PCServicingContact = LDB.PCServicingContact,
DB.PCServicingContactNumber = LDB.PCServicingContactNumber,
DB.MinimumNCF = LDB.MinimumNCF,
DB.AssetManagementStatusCd_F = LDB.AssetManagementStatusCd_F,
DB.ConditionalCommitmentDeposit = LDB.ConditionalCommitmentDeposit,
DB.CouponCurrent = LDB.CouponCurrent,
DB.CouponBase = LDB.CouponBase,
DB.CouponStress = LDB.CouponStress,
DB.ConstantCurrent = LDB.ConstantCurrent,
DB.ConstantBase = LDB.ConstantBase,
DB.ConstantStress = LDB.ConstantStress,
DB.StressedCapRate = LDB.StressedCapRate,
DB.StressedConstant = LDB.StressedConstant,
DB.BankNumberCD_F = LDB.BankNumberCD_F,
DB.OCCLoanPurposeCD_F = LDB.OCCLoanPurposeCD_F,
DB.GeneralLedgerCD_F = LDB.GeneralLedgerCD_F,
DB.CustomerId_F = LDB.CustomerId_F,
DB.NextAnnualReviewDate = LDB.NextAnnualReviewDate,
DB.Exempt = LDB.Exempt,
DB.First12MonthsRevenue = LDB.First12MonthsRevenue,
DB.LastAnnualReviewDate = LDB.LastAnnualReviewDate,
DB.BusinessLineManager_UserId_F = LDB.BusinessLineManager_UserId_F,
DB.WDP = LDB.WDP,
DB.WDPx = LDB.WDPx,
DB.AdditionalCollateral = LDB.AdditionalCollateral,
DB.InvestmentLeverage = LDB.InvestmentLeverage,
DB.BorrowerSecondaryLawFirm_OrgId_F = LDB.BorrowerSecondaryLawFirm_OrgId_F,
DB.BorrowerSecondaryCounsel_ContactId_F = LDB.BorrowerSecondaryCounsel_ContactId_F,
DB.PROOwnerInvestor_OrgId_F = LDB.PROOwnerInvestor_OrgId_F,
DB.PROSponsorDeveloper_OrgId_F = LDB.PROSponsorDeveloper_OrgId_F,
DB.PROBrokerDebt_OrgId_F = LDB.PROBrokerDebt_OrgId_F,
DB.PROBrokerEquity_OrgId_F = LDB.PROBrokerEquity_OrgId_F,
DB.PROBrokerLeasing_OrgId_F = LDB.PROBrokerLeasing_OrgId_F,
DB.PROLender_OrgId_F = LDB.PROLender_OrgId_F,
DB.PRODueDiligence_OrgId_F = LDB.PRODueDiligence_OrgId_F,
DB.PROAppraiser_OrgId_F = LDB.PROAppraiser_OrgId_F,
DB.PROLawFirm_OrgId_F = LDB.PROLawFirm_OrgId_F,
DB.SecondaryOfficeCd_F = LDB.SecondaryOfficeCd_F,
DB.LoanPurposeComments = LDB.LoanPurposeComments,
DB.AdditionalCollateralTypeCd_F = LDB.AdditionalCollateralTypeCd_F,
DB.DealLevelMarketComments = LDB.DealLevelMarketComments,
DB.UnderwritingGuidelineDeviationComments = LDB.UnderwritingGuidelineDeviationComments,
DB.AdministrationVarianceComments = LDB.AdministrationVarianceComments,
DB.Active = LDB.Active,
DB.StabilizedDebtYield = LDB.StabilizedDebtYield,
DB.WorkflowTemplateTypeCd_F = LDB.WorkflowTemplateTypeCd_F,
DB.ExistingDebtMaturityDate = LDB.ExistingDebtMaturityDate,
DB.Market = LDB.Market,
DB.MarketTotalSF = LDB.MarketTotalSF,
DB.MarketVacancy = LDB.MarketVacancy,
DB.PurchasePrice = LDB.PurchasePrice,
DB.TILC = LDB.TILC,
DB.Capex = LDB.Capex,
DB.ClosingCosts = LDB.ClosingCosts,
DB.ROA = LDB.ROA,
DB.LPDRCD_F = LDB.LPDRCD_F,
DB.SPDRCD_F = LDB.SPDRCD_F,
DB.AssetManagementStatusColorCd_F = LDB.AssetManagementStatusColorCd_F,
DB.CommunityLendingDevelopmentPurposeCd_F = LDB.CommunityLendingDevelopmentPurposeCd_F,
DB.AlternateDealNumber = LDB.AlternateDealNumber,
DB.MortgageLoanOriginator_OrgId_F = LDB.MortgageLoanOriginator_OrgId_F,
DB.MortgageLoanSeller_OrgId_F = LDB.MortgageLoanSeller_OrgId_F,
DB.SEREFAllocation = LDB.SEREFAllocation,
DB.StarFinAllocation = LDB.StarFinAllocation,
DB.SEREFStarFinIRR = LDB.SEREFStarFinIRR,
DB.ServicerWillSpreadFinancials = LDB.ServicerWillSpreadFinancials,
DB.FirmProductionDate = LDB.FirmProductionDate,
DB.CreditRiskApprovalDate = LDB.CreditRiskApprovalDate,
DB.CreditRiskDeniedDate = LDB.CreditRiskDeniedDate,
DB.ReferralFee = LDB.ReferralFee,
DB.FANumber = LDB.FANumber,
DB.LegalFeeAmount = LDB.LegalFeeAmount,
DB.QuotedDate = LDB.QuotedDate,
DB.PrelimPricingBucket = LDB.PrelimPricingBucket,
DB.PrelimPricingBucketComments = LDB.PrelimPricingBucketComments,
DB.ReferralIDNumber = LDB.ReferralIDNumber,
DB.CopyDealOptionCd_F = LDB.CopyDealOptionCd_F,
DB.CurrentLPDRCD_F = LDB.CurrentLPDRCD_F,
DB.GPDRCD_F = LDB.GPDRCD_F,
DB.ProbabilityCD_F = LDB.ProbabilityCD_F,
DB.CapitalMarketProductSW = LDB.CapitalMarketProductSW,
DB.MortgageBroker_OrgId_F = LDB.MortgageBroker_OrgId_F,
DB.DealSponsor_OrgId_F = LDB.DealSponsor_OrgId_F,
DB.MortgageBroker_ContactId_F = LDB.MortgageBroker_ContactId_F,
DB.isMUV = LDB.isMUV,
DB.ClientIdentifier = LDB.ClientIdentifier,
DB.DueDiligencePeriod = LDB.DueDiligencePeriod,
DB.PrincipalNetWorthGreaterThanLoan = LDB.PrincipalNetWorthGreaterThanLoan,
DB.PrincipalLiquidityGreaterThanDebtService = LDB.PrincipalLiquidityGreaterThanDebtService,
DB.PrincipalsFreeOfBankruptcyForeclosureDIL = LDB.PrincipalsFreeOfBankruptcyForeclosureDIL,
DB.PrincipalsFreeOfLitigation = LDB.PrincipalsFreeOfLitigation,
DB.WithholdingTaxExemptionRequired = LDB.WithholdingTaxExemptionRequired,
DB.DealSourceFirm = LDB.DealSourceFirm,
DB.DealSourceContact = LDB.DealSourceContact,
DB.CMBSControlMasterID = LDB.CMBSControlMasterID,
DB.TeamLeader_UserID_F = LDB.TeamLeader_UserID_F,
DB.SecondaryCounsel_Contact2ID_F = LDB.SecondaryCounsel_Contact2ID_F,
DB.SecondaryCounsel_Contact3ID_F = LDB.SecondaryCounsel_Contact3ID_F,
DB.BorrowerCounsel_Contact2ID_F = LDB.BorrowerCounsel_Contact2ID_F,
DB.BorrowerCounsel_Contact3ID_F = LDB.BorrowerCounsel_Contact3ID_F,
DB.SecondaryBorrowerFirm_OrgId_F = LDB.SecondaryBorrowerFirm_OrgId_F,
DB.SecondaryBorrowerFirm_ContactID_F = LDB.SecondaryBorrowerFirm_ContactID_F,
DB.MasterServicer_OrgId_F = LDB.MasterServicer_OrgId_F,
DB.DealBorrower_OrgId_F = LDB.DealBorrower_OrgId_F,
DB.TertiaryLawFirm_OrgId_F = LDB.TertiaryLawFirm_OrgId_F,
DB.DealBorrowerContact1_ContactId_F = LDB.DealBorrowerContact1_ContactId_F,
DB.DealBorrowerContact2_ContactId_F = LDB.DealBorrowerContact2_ContactId_F,
DB.DealBorrowerContact3_ContactId_F = LDB.DealBorrowerContact3_ContactId_F,
DB.DealBorrowerContact4_ContactId_F = LDB.DealBorrowerContact4_ContactId_F,
DB.DealBorrowerContact5_ContactId_F = LDB.DealBorrowerContact5_ContactId_F,
DB.DealBorrowerContact6_ContactId_F = LDB.DealBorrowerContact6_ContactId_F,
DB.TertiaryCounsel_ContactId_F = LDB.TertiaryCounsel_ContactId_F,
DB.TertiaryCoCounsel_ContactId_F = LDB.TertiaryCoCounsel_ContactId_F,
DB.UnleveredMultipleNetAtOrigination = LDB.UnleveredMultipleNetAtOrigination,
DB.LeveredIRRGrossAtOrigination = LDB.LeveredIRRGrossAtOrigination,
DB.LeveredIRRNetAtOrigination = LDB.LeveredIRRNetAtOrigination,
DB.LeveredProfitGrossAtOrigination = LDB.LeveredProfitGrossAtOrigination,
DB.LeveredProfitNetAtOrigination = LDB.LeveredProfitNetAtOrigination,
DB.LeveredMultipleGrossAtOrigination = LDB.LeveredMultipleGrossAtOrigination,
DB.LeveredMultipleNetAtOrigination = LDB.LeveredMultipleNetAtOrigination,
DB.InitialDebtYield = LDB.InitialDebtYield,
DB.ClosedDealLockSW = LDB.ClosedDealLockSW,
DB.StrategyTypeCD_F = LDB.StrategyTypeCD_F,
DB.PNAStatus = LDB.PNAStatus,
DB.LoanDefaultDate = LDB.LoanDefaultDate,
DB.DefaultLetterSentDate = LDB.DefaultLetterSentDate,
DB.ForclosureFiledExpectedDate = LDB.ForclosureFiledExpectedDate,
DB.LastPatriotActChecked = LDB.LastPatriotActChecked,
DB.FreeofJrSubDebt = LDB.FreeofJrSubDebt,
DB.AnticipatedPayoffComment = LDB.AnticipatedPayoffComment,
DB.AnticipatedActualCofODate = LDB.AnticipatedActualCofODate,
DB.OrganizationDealStatusID_F = LDB.OrganizationDealStatusID_F,
DB.RiskMatrixCd_F = LDB.RiskMatrixCd_F,
DB.DispositionMethodCd_F = LDB.DispositionMethodCd_F,
DB.PriorOutlookColorCd_F = LDB.PriorOutlookColorCd_F,
DB.AssetManagementLTVorLTC = LDB.AssetManagementLTVorLTC,
DB.BusinessPlanCd_F = LDB.BusinessPlanCd_F,
DB.AssetMgmtMarketCd_F = LDB.AssetMgmtMarketCd_F,
DB.ReviewRotationCd_F = LDB.ReviewRotationCd_F,
DB.AssetManagementRecourseCd_F = LDB.AssetManagementRecourseCd_F,
DB.PipelineReportReview = LDB.PipelineReportReview,
DB.DACABank_OrgId_F = LDB.DACABank_OrgId_F,
DB.CMABank_OrgId_F = LDB.CMABank_OrgId_F,
DB.LenderCashMgmtSuspended = LDB.LenderCashMgmtSuspended,
DB.LenderCashMgmtSuspendedUntilDate = LDB.LenderCashMgmtSuspendedUntilDate,
DB.TriggersEventOfDefault = LDB.TriggersEventOfDefault,
DB.TriggersDSCROperator = LDB.TriggersDSCROperator,
DB.TriggersDSCRValue = LDB.TriggersDSCRValue,
DB.TriggersDebtYieldOperator = LDB.TriggersDebtYieldOperator,
DB.TriggersDebtYieldValue = LDB.TriggersDebtYieldValue,
DB.TriggersOtherCondition1 = LDB.TriggersOtherCondition1,
DB.CureEventOfDefault = LDB.CureEventOfDefault,
DB.CureDSCROperator = LDB.CureDSCROperator,
DB.CureDSCRValue = LDB.CureDSCRValue,
DB.CureDSCRNumOfConsecutivePeriods = LDB.CureDSCRNumOfConsecutivePeriods,
DB.CureDSCRDurationCd_F = LDB.CureDSCRDurationCd_F,
DB.CureDebtYieldOperator = LDB.CureDebtYieldOperator,
DB.CureDebtYieldValue = LDB.CureDebtYieldValue,
DB.CureDebtYieldNumOfConsecutivePeriods = LDB.CureDebtYieldNumOfConsecutivePeriods,
DB.CureDebtYieldDurationCd_F = LDB.CureDebtYieldDurationCd_F,
DB.CureOtherCondition1 = LDB.CureOtherCondition1,
DB.CureOtherCondition2 = LDB.CureOtherCondition2,
DB.CureOtherCondition3 = LDB.CureOtherCondition3,
DB.TriggersOtherCondition2 = LDB.TriggersOtherCondition2,
DB.TriggersOtherCondition3 = LDB.TriggersOtherCondition3,
DB.DealBorrower2_OrgId_F = LDB.DealBorrower2_OrgId_F,
DB.DealBorrower3_OrgId_F = LDB.DealBorrower3_OrgId_F,
DB.DealBorrower4_OrgId_F = LDB.DealBorrower4_OrgId_F,
DB.DealBorrower5_OrgId_F = LDB.DealBorrower5_OrgId_F,
DB.DealBorrower6_OrgId_F = LDB.DealBorrower6_OrgId_F,
DB.REITPropertyTypeCd_F = LDB.REITPropertyTypeCd_F,
DB.REITSectorTypeCd_F = LDB.REITSectorTypeCd_F,
DB.UWLTCatOrigination = LDB.UWLTCatOrigination,
DB.UWLTVatOrigination = LDB.UWLTVatOrigination,
DB.DSCRatOrigination = LDB.DSCRatOrigination,
DB.DebtYieldAsIs = LDB.DebtYieldAsIs,
DB.UnleveredIRRGross = LDB.UnleveredIRRGross,
DB.UnleveredProfitGross = LDB.UnleveredProfitGross,
DB.UnleveredMultipleGross = LDB.UnleveredMultipleGross,
DB.LeveredIRRGross = LDB.LeveredIRRGross,
DB.LeveredProfitGross = LDB.LeveredProfitGross,
DB.LeveredMultipleGross = LDB.LeveredMultipleGross,
DB.StabilizedLTV = LDB.StabilizedLTV,
DB.StabilizedLTC = LDB.StabilizedLTC,
DB.SecuritizationID_F = LDB.SecuritizationID_F,
DB.InvestmentTypeCD_F = LDB.InvestmentTypeCD_F,
DB.LTCFullyFunded = LDB.LTCFullyFunded,
DB.LTVAtStab = LDB.LTVAtStab,
DB.AllocationDate = LDB.AllocationDate,
DB.AcoreRating = LDB.AcoreRating,
DB.OrigFundingDate = LDB.OrigFundingDate,
DB.ModifiedFrom = LDB.ModifiedFrom,
DB.GLStatusDate = LDB.GLStatusDate,
DB.CurrentLPDRDate = LDB.CurrentLPDRDate,
DB.ReferredByUsername = LDB.ReferredByUsername,
DB.InitialLTCPct = LDB.InitialLTCPct,
DB.EndLTCPct = LDB.EndLTCPct,
DB.NonRefundableProcessingFee = LDB.NonRefundableProcessingFee,
DB.TermSheetExclusivePeriod = LDB.TermSheetExclusivePeriod,
DB.BreakUpFee = LDB.BreakUpFee,
DB.PrincipalGuarantee = LDB.PrincipalGuarantee,
DB.ClosingEquityRequired = LDB.ClosingEquityRequired,
DB.ReferralChannel = LDB.ReferralChannel,
DB.HMDASw = LDB.HMDASw,
DB.RecourseTypeCD_F = LDB.RecourseTypeCD_F,
DB.ApprovedByCd_F = LDB.ApprovedByCd_F,
DB.EstimateCashOut = LDB.EstimateCashOut,
DB.ChangesInConditionalApproval = LDB.ChangesInConditionalApproval,
DB.ChangesInTermsAndConditions = LDB.ChangesInTermsAndConditions,
DB.SeniorReportManager_UserId_F = LDB.SeniorReportManager_UserId_F,
DB.CoLendApprovedSw = LDB.CoLendApprovedSw,
DB.PropertyAQR = LDB.PropertyAQR,
DB.GuarantorAQR = LDB.GuarantorAQR,
DB.DealAQR = LDB.DealAQR,
DB.OriginalLoanTerm = LDB.OriginalLoanTerm,
DB.DebtYieldStabilization = LDB.DebtYieldStabilization,
DB.AMTeamLeader_UserId_F = LDB.AMTeamLeader_UserId_F

WHEN NOT MATCHED THEN
	
	INSERT 
	(ControlId	,
LoanNumber	,
LoanStatusCd_F	,
BrokerName_OrgId_F	,
LendorName_OrgId_F	,
LawFirm_OrgId_F	,
Office_OrgId_F	,
DealRelatedId_F	,
Competition_Org_Id_F	,
DueDiligenceProvider_OrgId_F	,
OriginalDataSource_F	,
MinimumDSCR	,
MinimumDSCRatConstant	,
MaximumLTV	,
MinimumConstantDeal	,
PrimaryBanker_UserId_F	,
SecondaryBanker_UserId_F	,
Underwriter_UserID_F	,
ServicersLoanNumber	,
DealName	,
CreditApprovedBy	,
CreditApprovedComment	,
SpreadApprovedBy	,
SpreadApprovedComment	,
Correspondent	,
CorrUW	,
CollateralType	,
DebtServiceAllocated	,
LoanPurpose	,
LoanProbability	,
ApplicationReceiveDate	,
ApplicationDate	,
LenderRightToMatch	,
ApplicationDeposit	,
LockBox	,
LockBoxComment	,
HardCashManagement	,
Recourse	,
ClosingConditions	,
EstClosingCosts	,
EarnOut	,
IndDirectorReqSw	,
NonConsolOpinionReqSw	,
OwnershipComments	,
BrokerFees	,
Cashout	,
PreliminarySponsor	,
OngoingDSCRTest	,
SpecialPricingNotes	,
HardEquityComment	,
MatrixSpreadAtClose	,
MatrixSpreadAtCloseComments	,
CommitmentExpDate	,
Comments	,
TICSw	,
MpIsLoanAssumable	,
MpIsLoanAssumableDesc	,
MpEquityParticipation	,
MpEquityParticipationDesc	,
MpAllowFutAdvances	,
MpAllowFutAdvancesDesc	,
MpMaxFutureAdvances	,
MpFutAdvancesToDate	,
MpAssumptionFeePct	,
MpAssumptionFeeAmt	,
MpAssumptionFee	,
MpAssumptionFeeDesc	,
MpParticipationPercent	,
MpParticipationPercentDesc	,
MpRightToInspectRecords	,
MpUnsecuredDebtAllowed	,
MpMaxUnsecuredDebtAmt	,
MpTradePayablesMaxAmt	,
MpTradePayablesDaysOut	,
MpPartialReleasePercent	,
MpPartialReleaseDesc	,
MpComment	,
GCM_DealCounterpartyCode	,
AuditAddDate	,
AuditAddUserId	,
AuditUpdateDate	,
AuditUpdateUserId	,
PatriotActApprovedSw	,
OwnerOrgId_F	,
BrokerFeesComment	,
ArchiveInvestorFileSw	,
ArchiveLegalBinderSw	,
ArchiveComment	,
LoanProgramCD_F	,
LenderRoleCD_F	,
TargetLoan	,
EstAppraisedCollateralValue	,
EstStressedCollateralValue	,
AcquisitionCostofCollateral	,
Matrix	,
CompetitionComments	,
HardEquityAmount	,
DealLocked	,
DealCurrencyCD_F	,
Originator	,
SourceUsesComment	,
StartLTV	,
FirstLossComment	,
Change2TicAfterCloseSw	,
SpringingLockBoxComment	,
BrokerFeesPct	,
CommitmentAmount	,
Analyst_UserId_F	,
LoanTypeCD_F	,
CreditApprovedDate	,
SpreadApprovedDate	,
DDP_ContactID_F	,
Broker_ContactID_F	,
Cocounsel_ContactID_F	,
Counsel_ContactID_F	,
Paralegal_ContactID_F	,
RequestedLoanTerm	,
RequestedAmortTerm	,
RequestedSpread	,
RequestedIndex	,
RequestedLTV	,
RequestedLTC	,
TransactionManager_Userid_F	,
HUDLoanNumber	,
ApprovalLevel	,
ExistingDebt	,
ExistingDebtLender	,
ExistingDebtAmount	,
EarnOutAmount	,
MarketEquityComments	,
BookingLocation_OrgId_F	,
PortfolioManager_Userid_F	,
PrivateSW	,
CMBSLoanStatusCd_F	,
CMBSDealGUID	,
MPFutureAdditionalDebtPermitted	,
NDCApprovedCd_F	,
NDCApprovedBy	,
NDCApprovedComment	,
NDCSecuritization	,
NDCSyndication	,
NDCApprovedDate	,
CreditApproved	,
SpreadApproved	,
SecondaryPortfolioManager_UserId_F	,
Legal_UserId_F	,
IRRBaselI	,
IRRBaselII	,
ListedCompany	,
PriceSensitive	,
Confidentiality	,
Exclusivity	,
ShareDeal	,
RequestedPaymentFreqCd_F	,
RequestedIOTerm	,
RequestedLTVasStabilzed	,
RequestedRateTypeCd_F	,
BorrowerImputedEquity	,
LoanSizer_UserId_F	,
ConstructionManager_UserId_F	,
InsuranceManager_UserId_F	,
DealIntroducedById_F	,
CoCounselCompany_OrgId_F	,
CoCounselCompany_ContactId_F	,
SecondaryLawFirm_OrgId_F	,
SecondaryCounsel_ContactID_F	,
SpecificDealTeamRequest	,
QCAnalyst_UserID_F	,
OriginatorAssociate	,
ClosingCoordinator_UserID_F	,
AssetManager_UserID_F	,
NDCSecuritizationRequiredAmt	,
NDCSyndicationRequiredAmt	,
BrokeredDeal	,
DataTapeFootNotes	,
MortgageOriginatingEntityCD_F	,
DealSourceCD_F	,
ProgramManager_UserId_F	,
SmallLoanPM_UserId_F	,
UnderwritingManager_UserId_F	,
Servicer_UserId_F	,
QALead_UserId_F	,
QAAssociate_UserId_F	,
ReportManager_UserId_F	,
BorrowerLawFirm_OrgId_F	,
BorrowerInsuranceCo_OrgId_F	,
BorrowerCounsel_ContactID_F	,
BorrowerInsAgent_ContactID_F	,
Holdback	,
HoldbackAmount	,
EstimatedCreditDate	,
Secondary_BrokerName_OrgId_F	,
Secondary_Broker_ContactID_F	,
RepeatSponsorComment	,
KickOffEmailSent	,
ExpirationStatus	,
ApplicationDepositFeePct	,
EarnOutComment	,
RealizedLossToTrust	,
NonRecoverability	,
LastSetupChangeDate	,
LastLoanContributionDate	,
LastPropContributionDate	,
AssumptionDate	,
LockBoxAtClosing	,
BrokerFeesPctTypeCd_F	,
BrokerFeesPctPaymentCd_F	,
ControlMasterID	,
Recovery	,
USTL_UserId_F	,
USQCAnalyst_UserId_F	,
Sponsor_OrgId_F	,
AvailabilityCd_F	,
AvailabilityDate	,
ForeignInvestorsMore	,
PCAccountingContact	,
PCAccountingContactNumber	,
PCServicingContact	,
PCServicingContactNumber	,
MinimumNCF	,
AssetManagementStatusCd_F	,
ConditionalCommitmentDeposit	,
CouponCurrent	,
CouponBase	,
CouponStress	,
ConstantCurrent	,
ConstantBase	,
ConstantStress	,
StressedCapRate	,
StressedConstant	,
BankNumberCD_F	,
OCCLoanPurposeCD_F	,
GeneralLedgerCD_F	,
CustomerId_F	,
NextAnnualReviewDate	,
Exempt	,
First12MonthsRevenue	,
LastAnnualReviewDate	,
BusinessLineManager_UserId_F	,
WDP	,
WDPx	,
AdditionalCollateral	,
InvestmentLeverage	,
BorrowerSecondaryLawFirm_OrgId_F	,
BorrowerSecondaryCounsel_ContactId_F	,
PROOwnerInvestor_OrgId_F	,
PROSponsorDeveloper_OrgId_F	,
PROBrokerDebt_OrgId_F	,
PROBrokerEquity_OrgId_F	,
PROBrokerLeasing_OrgId_F	,
PROLender_OrgId_F	,
PRODueDiligence_OrgId_F	,
PROAppraiser_OrgId_F	,
PROLawFirm_OrgId_F	,
SecondaryOfficeCd_F	,
LoanPurposeComments	,
AdditionalCollateralTypeCd_F	,
DealLevelMarketComments	,
UnderwritingGuidelineDeviationComments	,
AdministrationVarianceComments	,
Active	,
StabilizedDebtYield	,
WorkflowTemplateTypeCd_F	,
ExistingDebtMaturityDate	,
Market	,
MarketTotalSF	,
MarketVacancy	,
PurchasePrice	,
TILC	,
Capex	,
ClosingCosts	,
ROA	,
LPDRCD_F	,
SPDRCD_F	,
AssetManagementStatusColorCd_F	,
CommunityLendingDevelopmentPurposeCd_F	,
AlternateDealNumber	,
MortgageLoanOriginator_OrgId_F	,
MortgageLoanSeller_OrgId_F	,
SEREFAllocation	,
StarFinAllocation	,
SEREFStarFinIRR	,
ServicerWillSpreadFinancials	,
FirmProductionDate	,
CreditRiskApprovalDate	,
CreditRiskDeniedDate	,
ReferralFee	,
FANumber	,
LegalFeeAmount	,
QuotedDate	,
PrelimPricingBucket	,
PrelimPricingBucketComments	,
ReferralIDNumber	,
CopyDealOptionCd_F	,
CurrentLPDRCD_F	,
GPDRCD_F	,
ProbabilityCD_F	,
CapitalMarketProductSW	,
MortgageBroker_OrgId_F	,
DealSponsor_OrgId_F	,
MortgageBroker_ContactId_F	,
isMUV	,
ClientIdentifier	,
DueDiligencePeriod	,
PrincipalNetWorthGreaterThanLoan	,
PrincipalLiquidityGreaterThanDebtService	,
PrincipalsFreeOfBankruptcyForeclosureDIL	,
PrincipalsFreeOfLitigation	,
WithholdingTaxExemptionRequired	,
DealSourceFirm	,
DealSourceContact	,
CMBSControlMasterID	,
TeamLeader_UserID_F	,
SecondaryCounsel_Contact2ID_F	,
SecondaryCounsel_Contact3ID_F	,
BorrowerCounsel_Contact2ID_F	,
BorrowerCounsel_Contact3ID_F	,
SecondaryBorrowerFirm_OrgId_F	,
SecondaryBorrowerFirm_ContactID_F	,
MasterServicer_OrgId_F	,
DealBorrower_OrgId_F	,
TertiaryLawFirm_OrgId_F	,
DealBorrowerContact1_ContactId_F	,
DealBorrowerContact2_ContactId_F	,
DealBorrowerContact3_ContactId_F	,
DealBorrowerContact4_ContactId_F	,
DealBorrowerContact5_ContactId_F	,
DealBorrowerContact6_ContactId_F	,
TertiaryCounsel_ContactId_F	,
TertiaryCoCounsel_ContactId_F	,
UnleveredMultipleNetAtOrigination	,
LeveredIRRGrossAtOrigination	,
LeveredIRRNetAtOrigination	,
LeveredProfitGrossAtOrigination	,
LeveredProfitNetAtOrigination	,
LeveredMultipleGrossAtOrigination	,
LeveredMultipleNetAtOrigination	,
InitialDebtYield	,
ClosedDealLockSW	,
StrategyTypeCD_F	,
PNAStatus	,
LoanDefaultDate	,
DefaultLetterSentDate	,
ForclosureFiledExpectedDate	,
LastPatriotActChecked	,
FreeofJrSubDebt	,
AnticipatedPayoffComment	,
AnticipatedActualCofODate	,
OrganizationDealStatusID_F	,
RiskMatrixCd_F	,
DispositionMethodCd_F	,
PriorOutlookColorCd_F	,
AssetManagementLTVorLTC	,
BusinessPlanCd_F	,
AssetMgmtMarketCd_F	,
ReviewRotationCd_F	,
AssetManagementRecourseCd_F	,
PipelineReportReview	,
DACABank_OrgId_F	,
CMABank_OrgId_F	,
LenderCashMgmtSuspended	,
LenderCashMgmtSuspendedUntilDate	,
TriggersEventOfDefault	,
TriggersDSCROperator	,
TriggersDSCRValue	,
TriggersDebtYieldOperator	,
TriggersDebtYieldValue	,
TriggersOtherCondition1	,
CureEventOfDefault	,
CureDSCROperator	,
CureDSCRValue	,
CureDSCRNumOfConsecutivePeriods	,
CureDSCRDurationCd_F	,
CureDebtYieldOperator	,
CureDebtYieldValue	,
CureDebtYieldNumOfConsecutivePeriods	,
CureDebtYieldDurationCd_F	,
CureOtherCondition1	,
CureOtherCondition2	,
CureOtherCondition3	,
TriggersOtherCondition2	,
TriggersOtherCondition3	,
DealBorrower2_OrgId_F	,
DealBorrower3_OrgId_F	,
DealBorrower4_OrgId_F	,
DealBorrower5_OrgId_F	,
DealBorrower6_OrgId_F	,
REITPropertyTypeCd_F	,
REITSectorTypeCd_F	,
UWLTCatOrigination	,
UWLTVatOrigination	,
DSCRatOrigination	,
DebtYieldAsIs	,
UnleveredIRRGross	,
UnleveredProfitGross	,
UnleveredMultipleGross	,
LeveredIRRGross	,
LeveredProfitGross	,
LeveredMultipleGross	,
StabilizedLTV	,
StabilizedLTC	,
SecuritizationID_F	,
InvestmentTypeCD_F	,
LTCFullyFunded	,
LTVAtStab	,
AllocationDate	,
AcoreRating	,
OrigFundingDate	,
ModifiedFrom	,
GLStatusDate	,
CurrentLPDRDate	,
ReferredByUsername	,
InitialLTCPct	,
EndLTCPct	,
NonRefundableProcessingFee	,
TermSheetExclusivePeriod	,
BreakUpFee	,
PrincipalGuarantee	,
ClosingEquityRequired	,
ReferralChannel	,
HMDASw	,
RecourseTypeCD_F	,
ApprovedByCd_F	,
EstimateCashOut	,
ChangesInConditionalApproval	,
ChangesInTermsAndConditions	,
SeniorReportManager_UserId_F	,
CoLendApprovedSw	,
PropertyAQR	,
GuarantorAQR	,
DealAQR	,
OriginalLoanTerm	,
DebtYieldStabilization	,
AMTeamLeader_UserId_F	)

VALUES (LDB.ControlId,
LDB.LoanNumber,
LDB.LoanStatusCd_F,
LDB.BrokerName_OrgId_F,
LDB.LendorName_OrgId_F,
LDB.LawFirm_OrgId_F,
LDB.Office_OrgId_F,
LDB.DealRelatedId_F,
LDB.Competition_Org_Id_F,
LDB.DueDiligenceProvider_OrgId_F,
LDB.OriginalDataSource_F,
LDB.MinimumDSCR,
LDB.MinimumDSCRatConstant,
LDB.MaximumLTV,
LDB.MinimumConstantDeal,
LDB.PrimaryBanker_UserId_F,
LDB.SecondaryBanker_UserId_F,
LDB.Underwriter_UserID_F,
LDB.ServicersLoanNumber,
LDB.DealName,
LDB.CreditApprovedBy,
LDB.CreditApprovedComment,
LDB.SpreadApprovedBy,
LDB.SpreadApprovedComment,
LDB.Correspondent,
LDB.CorrUW,
LDB.CollateralType,
LDB.DebtServiceAllocated,
LDB.LoanPurpose,
LDB.LoanProbability,
LDB.ApplicationReceiveDate,
LDB.ApplicationDate,
LDB.LenderRightToMatch,
LDB.ApplicationDeposit,
LDB.LockBox,
LDB.LockBoxComment,
LDB.HardCashManagement,
LDB.Recourse,
LDB.ClosingConditions,
LDB.EstClosingCosts,
LDB.EarnOut,
LDB.IndDirectorReqSw,
LDB.NonConsolOpinionReqSw,
LDB.OwnershipComments,
LDB.BrokerFees,
LDB.Cashout,
LDB.PreliminarySponsor,
LDB.OngoingDSCRTest,
LDB.SpecialPricingNotes,
LDB.HardEquityComment,
LDB.MatrixSpreadAtClose,
LDB.MatrixSpreadAtCloseComments,
LDB.CommitmentExpDate,
LDB.Comments,
LDB.TICSw,
LDB.MpIsLoanAssumable,
LDB.MpIsLoanAssumableDesc,
LDB.MpEquityParticipation,
LDB.MpEquityParticipationDesc,
LDB.MpAllowFutAdvances,
LDB.MpAllowFutAdvancesDesc,
LDB.MpMaxFutureAdvances,
LDB.MpFutAdvancesToDate,
LDB.MpAssumptionFeePct,
LDB.MpAssumptionFeeAmt,
LDB.MpAssumptionFee,
LDB.MpAssumptionFeeDesc,
LDB.MpParticipationPercent,
LDB.MpParticipationPercentDesc,
LDB.MpRightToInspectRecords,
LDB.MpUnsecuredDebtAllowed,
LDB.MpMaxUnsecuredDebtAmt,
LDB.MpTradePayablesMaxAmt,
LDB.MpTradePayablesDaysOut,
LDB.MpPartialReleasePercent,
LDB.MpPartialReleaseDesc,
LDB.MpComment,
LDB.GCM_DealCounterpartyCode,
LDB.AuditAddDate,
LDB.AuditAddUserId,
LDB.AuditUpdateDate,
LDB.AuditUpdateUserId,
LDB.PatriotActApprovedSw,
LDB.OwnerOrgId_F,
LDB.BrokerFeesComment,
LDB.ArchiveInvestorFileSw,
LDB.ArchiveLegalBinderSw,
LDB.ArchiveComment,
LDB.LoanProgramCD_F,
LDB.LenderRoleCD_F,
LDB.TargetLoan,
LDB.EstAppraisedCollateralValue,
LDB.EstStressedCollateralValue,
LDB.AcquisitionCostofCollateral,
LDB.Matrix,
LDB.CompetitionComments,
LDB.HardEquityAmount,
LDB.DealLocked,
LDB.DealCurrencyCD_F,
LDB.Originator,
LDB.SourceUsesComment,
LDB.StartLTV,
LDB.FirstLossComment,
LDB.Change2TicAfterCloseSw,
LDB.SpringingLockBoxComment,
LDB.BrokerFeesPct,
LDB.CommitmentAmount,
LDB.Analyst_UserId_F,
LDB.LoanTypeCD_F,
LDB.CreditApprovedDate,
LDB.SpreadApprovedDate,
LDB.DDP_ContactID_F,
LDB.Broker_ContactID_F,
LDB.Cocounsel_ContactID_F,
LDB.Counsel_ContactID_F,
LDB.Paralegal_ContactID_F,
LDB.RequestedLoanTerm,
LDB.RequestedAmortTerm,
LDB.RequestedSpread,
LDB.RequestedIndex,
LDB.RequestedLTV,
LDB.RequestedLTC,
LDB.TransactionManager_Userid_F,
LDB.HUDLoanNumber,
LDB.ApprovalLevel,
LDB.ExistingDebt,
LDB.ExistingDebtLender,
LDB.ExistingDebtAmount,
LDB.EarnOutAmount,
LDB.MarketEquityComments,
LDB.BookingLocation_OrgId_F,
LDB.PortfolioManager_Userid_F,
LDB.PrivateSW,
LDB.CMBSLoanStatusCd_F,
LDB.CMBSDealGUID,
LDB.MPFutureAdditionalDebtPermitted,
LDB.NDCApprovedCd_F,
LDB.NDCApprovedBy,
LDB.NDCApprovedComment,
LDB.NDCSecuritization,
LDB.NDCSyndication,
LDB.NDCApprovedDate,
LDB.CreditApproved,
LDB.SpreadApproved,
LDB.SecondaryPortfolioManager_UserId_F,
LDB.Legal_UserId_F,
LDB.IRRBaselI,
LDB.IRRBaselII,
LDB.ListedCompany,
LDB.PriceSensitive,
LDB.Confidentiality,
LDB.Exclusivity,
LDB.ShareDeal,
LDB.RequestedPaymentFreqCd_F,
LDB.RequestedIOTerm,
LDB.RequestedLTVasStabilzed,
LDB.RequestedRateTypeCd_F,
LDB.BorrowerImputedEquity,
LDB.LoanSizer_UserId_F,
LDB.ConstructionManager_UserId_F,
LDB.InsuranceManager_UserId_F,
LDB.DealIntroducedById_F,
LDB.CoCounselCompany_OrgId_F,
LDB.CoCounselCompany_ContactId_F,
LDB.SecondaryLawFirm_OrgId_F,
LDB.SecondaryCounsel_ContactID_F,
LDB.SpecificDealTeamRequest,
LDB.QCAnalyst_UserID_F,
LDB.OriginatorAssociate,
LDB.ClosingCoordinator_UserID_F,
LDB.AssetManager_UserID_F,
LDB.NDCSecuritizationRequiredAmt,
LDB.NDCSyndicationRequiredAmt,
LDB.BrokeredDeal,
LDB.DataTapeFootNotes,
LDB.MortgageOriginatingEntityCD_F,
LDB.DealSourceCD_F,
LDB.ProgramManager_UserId_F,
LDB.SmallLoanPM_UserId_F,
LDB.UnderwritingManager_UserId_F,
LDB.Servicer_UserId_F,
LDB.QALead_UserId_F,
LDB.QAAssociate_UserId_F,
LDB.ReportManager_UserId_F,
LDB.BorrowerLawFirm_OrgId_F,
LDB.BorrowerInsuranceCo_OrgId_F,
LDB.BorrowerCounsel_ContactID_F,
LDB.BorrowerInsAgent_ContactID_F,
LDB.Holdback,
LDB.HoldbackAmount,
LDB.EstimatedCreditDate,
LDB.Secondary_BrokerName_OrgId_F,
LDB.Secondary_Broker_ContactID_F,
LDB.RepeatSponsorComment,
LDB.KickOffEmailSent,
LDB.ExpirationStatus,
LDB.ApplicationDepositFeePct,
LDB.EarnOutComment,
LDB.RealizedLossToTrust,
LDB.NonRecoverability,
LDB.LastSetupChangeDate,
LDB.LastLoanContributionDate,
LDB.LastPropContributionDate,
LDB.AssumptionDate,
LDB.LockBoxAtClosing,
LDB.BrokerFeesPctTypeCd_F,
LDB.BrokerFeesPctPaymentCd_F,
LDB.ControlMasterID,
LDB.Recovery,
LDB.USTL_UserId_F,
LDB.USQCAnalyst_UserId_F,
LDB.Sponsor_OrgId_F,
LDB.AvailabilityCd_F,
LDB.AvailabilityDate,
LDB.ForeignInvestorsMore,
LDB.PCAccountingContact,
LDB.PCAccountingContactNumber,
LDB.PCServicingContact,
LDB.PCServicingContactNumber,
LDB.MinimumNCF,
LDB.AssetManagementStatusCd_F,
LDB.ConditionalCommitmentDeposit,
LDB.CouponCurrent,
LDB.CouponBase,
LDB.CouponStress,
LDB.ConstantCurrent,
LDB.ConstantBase,
LDB.ConstantStress,
LDB.StressedCapRate,
LDB.StressedConstant,
LDB.BankNumberCD_F,
LDB.OCCLoanPurposeCD_F,
LDB.GeneralLedgerCD_F,
LDB.CustomerId_F,
LDB.NextAnnualReviewDate,
LDB.Exempt,
LDB.First12MonthsRevenue,
LDB.LastAnnualReviewDate,
LDB.BusinessLineManager_UserId_F,
LDB.WDP,
LDB.WDPx,
LDB.AdditionalCollateral,
LDB.InvestmentLeverage,
LDB.BorrowerSecondaryLawFirm_OrgId_F,
LDB.BorrowerSecondaryCounsel_ContactId_F,
LDB.PROOwnerInvestor_OrgId_F,
LDB.PROSponsorDeveloper_OrgId_F,
LDB.PROBrokerDebt_OrgId_F,
LDB.PROBrokerEquity_OrgId_F,
LDB.PROBrokerLeasing_OrgId_F,
LDB.PROLender_OrgId_F,
LDB.PRODueDiligence_OrgId_F,
LDB.PROAppraiser_OrgId_F,
LDB.PROLawFirm_OrgId_F,
LDB.SecondaryOfficeCd_F,
LDB.LoanPurposeComments,
LDB.AdditionalCollateralTypeCd_F,
LDB.DealLevelMarketComments,
LDB.UnderwritingGuidelineDeviationComments,
LDB.AdministrationVarianceComments,
LDB.Active,
LDB.StabilizedDebtYield,
LDB.WorkflowTemplateTypeCd_F,
LDB.ExistingDebtMaturityDate,
LDB.Market,
LDB.MarketTotalSF,
LDB.MarketVacancy,
LDB.PurchasePrice,
LDB.TILC,
LDB.Capex,
LDB.ClosingCosts,
LDB.ROA,
LDB.LPDRCD_F,
LDB.SPDRCD_F,
LDB.AssetManagementStatusColorCd_F,
LDB.CommunityLendingDevelopmentPurposeCd_F,
LDB.AlternateDealNumber,
LDB.MortgageLoanOriginator_OrgId_F,
LDB.MortgageLoanSeller_OrgId_F,
LDB.SEREFAllocation,
LDB.StarFinAllocation,
LDB.SEREFStarFinIRR,
LDB.ServicerWillSpreadFinancials,
LDB.FirmProductionDate,
LDB.CreditRiskApprovalDate,
LDB.CreditRiskDeniedDate,
LDB.ReferralFee,
LDB.FANumber,
LDB.LegalFeeAmount,
LDB.QuotedDate,
LDB.PrelimPricingBucket,
LDB.PrelimPricingBucketComments,
LDB.ReferralIDNumber,
LDB.CopyDealOptionCd_F,
LDB.CurrentLPDRCD_F,
LDB.GPDRCD_F,
LDB.ProbabilityCD_F,
LDB.CapitalMarketProductSW,
LDB.MortgageBroker_OrgId_F,
LDB.DealSponsor_OrgId_F,
LDB.MortgageBroker_ContactId_F,
LDB.isMUV,
LDB.ClientIdentifier,
LDB.DueDiligencePeriod,
LDB.PrincipalNetWorthGreaterThanLoan,
LDB.PrincipalLiquidityGreaterThanDebtService,
LDB.PrincipalsFreeOfBankruptcyForeclosureDIL,
LDB.PrincipalsFreeOfLitigation,
LDB.WithholdingTaxExemptionRequired,
LDB.DealSourceFirm,
LDB.DealSourceContact,
LDB.CMBSControlMasterID,
LDB.TeamLeader_UserID_F,
LDB.SecondaryCounsel_Contact2ID_F,
LDB.SecondaryCounsel_Contact3ID_F,
LDB.BorrowerCounsel_Contact2ID_F,
LDB.BorrowerCounsel_Contact3ID_F,
LDB.SecondaryBorrowerFirm_OrgId_F,
LDB.SecondaryBorrowerFirm_ContactID_F,
LDB.MasterServicer_OrgId_F,
LDB.DealBorrower_OrgId_F,
LDB.TertiaryLawFirm_OrgId_F,
LDB.DealBorrowerContact1_ContactId_F,
LDB.DealBorrowerContact2_ContactId_F,
LDB.DealBorrowerContact3_ContactId_F,
LDB.DealBorrowerContact4_ContactId_F,
LDB.DealBorrowerContact5_ContactId_F,
LDB.DealBorrowerContact6_ContactId_F,
LDB.TertiaryCounsel_ContactId_F,
LDB.TertiaryCoCounsel_ContactId_F,
LDB.UnleveredMultipleNetAtOrigination,
LDB.LeveredIRRGrossAtOrigination,
LDB.LeveredIRRNetAtOrigination,
LDB.LeveredProfitGrossAtOrigination,
LDB.LeveredProfitNetAtOrigination,
LDB.LeveredMultipleGrossAtOrigination,
LDB.LeveredMultipleNetAtOrigination,
LDB.InitialDebtYield,
LDB.ClosedDealLockSW,
LDB.StrategyTypeCD_F,
LDB.PNAStatus,
LDB.LoanDefaultDate,
LDB.DefaultLetterSentDate,
LDB.ForclosureFiledExpectedDate,
LDB.LastPatriotActChecked,
LDB.FreeofJrSubDebt,
LDB.AnticipatedPayoffComment,
LDB.AnticipatedActualCofODate,
LDB.OrganizationDealStatusID_F,
LDB.RiskMatrixCd_F,
LDB.DispositionMethodCd_F,
LDB.PriorOutlookColorCd_F,
LDB.AssetManagementLTVorLTC,
LDB.BusinessPlanCd_F,
LDB.AssetMgmtMarketCd_F,
LDB.ReviewRotationCd_F,
LDB.AssetManagementRecourseCd_F,
LDB.PipelineReportReview,
LDB.DACABank_OrgId_F,
LDB.CMABank_OrgId_F,
LDB.LenderCashMgmtSuspended,
LDB.LenderCashMgmtSuspendedUntilDate,
LDB.TriggersEventOfDefault,
LDB.TriggersDSCROperator,
LDB.TriggersDSCRValue,
LDB.TriggersDebtYieldOperator,
LDB.TriggersDebtYieldValue,
LDB.TriggersOtherCondition1,
LDB.CureEventOfDefault,
LDB.CureDSCROperator,
LDB.CureDSCRValue,
LDB.CureDSCRNumOfConsecutivePeriods,
LDB.CureDSCRDurationCd_F,
LDB.CureDebtYieldOperator,
LDB.CureDebtYieldValue,
LDB.CureDebtYieldNumOfConsecutivePeriods,
LDB.CureDebtYieldDurationCd_F,
LDB.CureOtherCondition1,
LDB.CureOtherCondition2,
LDB.CureOtherCondition3,
LDB.TriggersOtherCondition2,
LDB.TriggersOtherCondition3,
LDB.DealBorrower2_OrgId_F,
LDB.DealBorrower3_OrgId_F,
LDB.DealBorrower4_OrgId_F,
LDB.DealBorrower5_OrgId_F,
LDB.DealBorrower6_OrgId_F,
LDB.REITPropertyTypeCd_F,
LDB.REITSectorTypeCd_F,
LDB.UWLTCatOrigination,
LDB.UWLTVatOrigination,
LDB.DSCRatOrigination,
LDB.DebtYieldAsIs,
LDB.UnleveredIRRGross,
LDB.UnleveredProfitGross,
LDB.UnleveredMultipleGross,
LDB.LeveredIRRGross,
LDB.LeveredProfitGross,
LDB.LeveredMultipleGross,
LDB.StabilizedLTV,
LDB.StabilizedLTC,
LDB.SecuritizationID_F,
LDB.InvestmentTypeCD_F,
LDB.LTCFullyFunded,
LDB.LTVAtStab,
LDB.AllocationDate,
LDB.AcoreRating,
LDB.OrigFundingDate,
LDB.ModifiedFrom,
LDB.GLStatusDate,
LDB.CurrentLPDRDate,
LDB.ReferredByUsername,
LDB.InitialLTCPct,
LDB.EndLTCPct,
LDB.NonRefundableProcessingFee,
LDB.TermSheetExclusivePeriod,
LDB.BreakUpFee,
LDB.PrincipalGuarantee,
LDB.ClosingEquityRequired,
LDB.ReferralChannel,
LDB.HMDASw,
LDB.RecourseTypeCD_F,
LDB.ApprovedByCd_F,
LDB.EstimateCashOut,
LDB.ChangesInConditionalApproval,
LDB.ChangesInTermsAndConditions,
LDB.SeniorReportManager_UserId_F,
LDB.CoLendApprovedSw,
LDB.PropertyAQR,
LDB.GuarantorAQR,
LDB.DealAQR,
LDB.OriginalLoanTerm,
LDB.DebtYieldStabilization,
LDB.AMTeamLeader_UserId_F
);

DECLARE @RowCount int
SET @RowCount = @@ROWCOUNT

UPDATE [DW].BatchDetail
SET
BIEndTime = GETDATE(),
BIRecordCount = @RowCount
WHERE BatchLogId = @BatchLogId and LandingTableName = 'L_UwDealBI'

Print(char(9) +'usp_MergeUwDeal - ROWCOUNT = '+cast(@RowCount  as varchar(100)));


END

