  
  
  
CREATE PROCEDURE [DW].[usp_InsertNoteMatrixBI]  

  
AS  
BEGIN  
     SET NOCOUNT ON;  
	Truncate Table  [DW].[NoteMatrixBI]

	update [DW].[L_NoteMatrixBI] set IndexforStub=0,
								SeniorLoanSpread=0,
								SubLoanSpread=0							
	 where IndexforStub='N/A' or SeniorLoanSpread='N/A' or SubLoanSpread ='N/A'
 
  ---------------------------
  -------------------------------------Delphi - Note Matrix-----------------------------------
INSERT INTO [DW].[NoteMatrixBI]  
(  
		[DealID],  
		[DealGroupID],  
		[NoteID],  
		[Pri],  
		[DealName],  
		[NoteName],  
		[LoanStatus],  
		[Client],  
		[Fund],  
		[AssetManager],  
		[Banker],  
		[Credit],  
		[Pool],  
		[FinancingSource],  
		[DebtType],  
		[CapStack],  
		[BillingNote],  
		[Commitment],  
		[Spread],  
		IndexforStub,  
		[Floor],  
		AllInRate,  
		[Type],  
		[InitialFunding],  
		[InitialMaturity],    
		ExtendedMaturity1,  
		ExtendedMaturity2,  
		ExtendedMaturity3,  
		ExtendedMaturity4,  
		FullyExtendedMaturity,  
		CurrentMaturityDate,  
		CurrentMaturity,    
		[PaidOffSold],  
		[FeesStart],  
		[RSLIC],  
		[SNCC],  
		[PIIC],  
		[TMR],  
		[HCC],  
		[USSIC],  
		[TMNF],  
		[HAIH],  
		[Check],  
		[CAMRA],  
		[Servicer],  
		[ServicerID],  
		[PremDisc],  
		[OriginationFee],  
		FutureFundingsatParor99,  
		PaydownPayoffConvention,  
		PaymentDate,  
		[Other],    
		NoteClassification,  
		WholeLoanSpread,   
		[SeniorLoanSpread],  
		[SubLoanSpread],    
		ExtensionFee1,  
		ExtensionFee2,  
		ExtensionFee3,  
		ExtensionFee4,  
		ProductType,  
		MSA,  
		State,   
		DealType,  
		[InquiryYear],  
		[Location],  
		[UnderwrittenReturn])  
	SELECT 
				DealID ,  
				DealGroupID ,  
				NoteID ,  
				CONVERT(INT, Pri)	 ,  
				DealName ,  
				NoteName ,  
				LoanStatus ,  
				Client ,  
				Fund ,  
				AssetManager ,  
				Banker ,  
				Credit ,  
				[Pool] ,  
				FinancingSource ,  
				DebtType ,  
				CapStack ,  
				BillingNote ,  
				CAST(REPLACE(Commitment ,'N/A',0) AS DECIMAL(28, 15))  ,  
				Spread ,  
				CAST(REPLACE(IndexforStub ,'N/A',0) AS DECIMAL(28, 15))  , 	 
				CAST(REPLACE([Floor] ,'N/A',0) AS DECIMAL(28, 15))  , 	  
				CAST(REPLACE(AllInRate ,'N/A',0) AS DECIMAL(28, 15))  ,  
				[Type] ,  
				CONVERT(DATE,InitialFunding) ,  
				CONVERT(DATE,InitialMaturity) ,  	 				
				CONVERT(DATE,ExtendedMaturity1) ,  	
				CONVERT(DATE,ExtendedMaturity2) ,  	
				CONVERT(DATE,ExtendedMaturity3) ,  	
				CONVERT(DATE,ExtendedMaturity4) ,  	
				CONVERT(DATE,FullyExtendedMaturity) ,  	
				CONVERT(DATE,CurrentMaturityDate) ,  	
				CurrentMaturity,    
				CONVERT(DATE,PaidOffSold) ,  
				FeesStart ,  
				CAST(REPLACE(RSLIC ,'N/A',0) AS DECIMAL(28, 15))  ,   
				CAST(REPLACE(SNCC ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(PIIC ,'N/A',0) AS DECIMAL(28, 15))  ,   
				CAST(REPLACE(TMR ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(HCC ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(USSIC ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(TMNF ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(HAIH ,'N/A',0) AS DECIMAL(28, 15))  ,   
				CAST(REPLACE( [Check] ,'N/A',0) AS DECIMAL(28, 15))  , 
				CAMRA ,  
				Servicer ,  
				ServicerID ,  
				CAST(REPLACE( PremDisc ,'N/A',0) AS DECIMAL(28, 15))  ,  
				OriginationFee ,  
				FutureFundingsatParor99,  
				CONVERT(INT, PaydownPayoffConvention) ,    
				CONVERT(INT, PaymentDate) , 	
				CAST(REPLACE( Other ,'N/A',0) AS DECIMAL(28, 15))  ,   
				NoteClassification,  
				CAST(REPLACE( WholeLoanSpread ,'N/A',0) AS DECIMAL(28, 15))  , 	  
				CAST(REPLACE( SeniorLoanSpread ,'N/A',0) AS DECIMAL(28, 15))  , 
				CAST(REPLACE(SubLoanSpread ,'N/A',0) AS DECIMAL(28, 15))  , 	
				CAST(REPLACE( ExtensionFee1 ,'N/A',0) AS DECIMAL(28, 15))  , 	
				CAST(REPLACE( ExtensionFee2 ,'N/A',0) AS DECIMAL(28, 15))  , 	
				CAST(REPLACE( ExtensionFee3 ,'N/A',0) AS DECIMAL(28, 15))  , 	
				CAST(REPLACE( ExtensionFee4 ,'N/A',0) AS DECIMAL(28, 15))  , 	
				ProductType,  
				MSA,  
				[State],   
				DealType,  
				CONVERT(INT, InquiryYear) ,  
				[Location],  
				UnderwrittenReturn 
				 FROM [DW].[L_NoteMatrixBI]
				WHERE SheetName='Delphi - Note Matrix';

  ------------------------------------END --Delphi - Note Matrix-----------------------------------
  -------------------TRE ACR - Note Matrix-----------------------------------

INSERT INTO [DW].[NoteMatrixBI]  
(  
		[DealID],  
		[DealGroupID],  
		[NoteID],  
		[Pri],  
		[DealName],  
		[NoteName],  
		[LoanStatus],  
		[Client],  
		[Fund],  
		[AssetManager],  
		[Banker],  
		[Credit],  
		[Pool],  
		[FinancingSource],  
		[DebtType],  
		[CapStack],  
		[BillingNote],  
		[Commitment],  
		[Spread],  
		IndexforStub,  
		[Floor],  
		AllInRate,  
		[Type],  
		[InitialFunding],  
		[InitialMaturity],    
		ExtendedMaturity1,  
		ExtendedMaturity2,  
		ExtendedMaturity3,  
		ExtendedMaturity4,  
		FullyExtendedMaturity,  
		CurrentMaturityDate,  
		CurrentMaturity,    
		[PaidOffSold],  
		[FeesStart],  
		[RSLIC],  
		[SNCC],  
		[PIIC],  
		[TMR],  
		[HCC],  
		[USSIC],  
		[TMNF],  
		[HAIH],  
		[Check],  
		[CAMRA],  
		[Servicer],  
		[ServicerID],  
		[PremDisc],  
		[OriginationFee],  
		FutureFundingsatParor99,  
		PaydownPayoffConvention,  
		PaymentDate,  
		[Other],    
		NoteClassification,  
		WholeLoanSpread,   
		[SeniorLoanSpread],  
		[SubLoanSpread],    
		ExtensionFee1,  
		ExtensionFee2,  
		ExtensionFee3,  
		ExtensionFee4,  
		ProductType,  
		MSA,  
		State,   
		DealType,  
		[InquiryYear],  
		[Location],  
		[UnderwrittenReturn])  
	SELECT 
				DealID ,  
				DealGroupID1 ,  
				ACOREID ,  
				CONVERT(INT, Pri)	 ,  
				DealName ,  
				NoteName ,  
				LoanStatus1 ,  
				Client ,  
				Fund ,  
				AssetManager1 ,  
				Banker1 ,  
				Credit1 ,  
				[Pool] ,  
				FinancingSource1 ,  
				DebtType ,  
				CapStack ,  
				BillingNote ,  
				CAST(REPLACE(Commitment ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(Spread ,'N/A',0) AS DECIMAL(28, 15)) ,  
				CAST(REPLACE(IndexforStub ,'N/A',0) AS DECIMAL(28, 15))  , 	 
				CAST(REPLACE([Floor] ,'N/A',0) AS DECIMAL(28, 15))  , 	  
				CAST(REPLACE(AllInRate ,'N/A',0) AS DECIMAL(28, 15))  ,  
				[Type] ,  
				CONVERT(DATE,InitialFunding) ,  
				CONVERT(DATE,InitialMaturity) ,  	 				
				CONVERT(DATE,ExtendedMaturity1) ,  	
				CONVERT(DATE,ExtendedMaturity2) ,  	
				CONVERT(DATE,ExtendedMaturity3) ,  	
				CONVERT(DATE,ExtendedMaturity4) ,  	
				CONVERT(DATE,FullyExtendedMaturity) ,  	
				CONVERT(DATE,CurrentMaturityDate) ,  	
				CurrentMaturity,    
				CONVERT(DATE,PaidOffSold) ,  
				FeesStart ,  
				CAST(REPLACE(RSLIC ,'N/A',0) AS DECIMAL(28, 15))  ,   
				CAST(REPLACE(SNCC ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(PIIC ,'N/A',0) AS DECIMAL(28, 15))  ,   
				CAST(REPLACE(TMR ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(HCC ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(USSIC ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(TMNF ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(HAIH ,'N/A',0) AS DECIMAL(28, 15))  ,   
				CAST(REPLACE( [Check] ,'N/A',0) AS DECIMAL(28, 15))  , 
				CAMRA1 ,  
				Servicer ,  
				ServicerID ,  
				CAST(REPLACE( PremDisc ,'N/A',0) AS DECIMAL(28, 15))  ,  
				OriginationFee ,  
				FutureFundingsatParor99,  
				CONVERT(INT, PaydownPayoffConvention) ,    
				CONVERT(INT, PaymentDate) , 	
				CAST(REPLACE( Other ,'N/A',0) AS DECIMAL(28, 15))  ,   
				NoteClassification,  
				CAST(REPLACE( WholeLoanSpread ,'N/A',0) AS DECIMAL(28, 15))  , 	  
				CAST(REPLACE( SeniorLoanSpread ,'N/A',0) AS DECIMAL(28, 15))  , 
				CAST(REPLACE(SubLoanSpread ,'N/A',0) AS DECIMAL(28, 15))  , 	
				CAST(REPLACE( ExtensionFee1 ,'N/A',0) AS DECIMAL(28, 15))  , 	
				CAST(REPLACE( ExtensionFee2 ,'N/A',0) AS DECIMAL(28, 15))  , 	
				CAST(REPLACE( ExtensionFee3 ,'N/A',0) AS DECIMAL(28, 15))  , 	
				CAST(REPLACE( ExtensionFee4 ,'N/A',0) AS DECIMAL(28, 15))  , 	
				ProductType,  
				MSA,  
				[State],   
				DealType,  
				CONVERT(INT, InquiryYear) ,  
				[Location],  
				CAST(REPLACE( UnderwrittenReturn ,'N/A',0) AS DECIMAL(28, 15))  	 
				 FROM [DW].[L_NoteMatrixBI]
				WHERE SheetName='TRE ACR - Note Matrix'



				----------------------------	ACORE Credit IV - Note Matrix-----------------------------------------------

	INSERT INTO [DW].[NoteMatrixBI]  
			(  
			[DealID],  
			[DealGroupID],  
			[NoteID],  
			[Pri],  
			[DealName],  
			[NoteName],  
			[LoanStatus],  
			[Client],  
			[Fund],  
			[AssetManager],  
			[Banker],  
			[Credit],  
			[Pool],  
			[FinancingSource],  
			CurrentEntity,  
			[CapStack],  
			[BillingNote],  
			[Commitment],  
			[Spread],  
			IndexforStub,  
			[Floor],  
			[Type],  
			[InitialFunding],  
			[InitialMaturity],  
			ExtendedMaturity1,  
			ExtendedMaturity2,  
			ExtendedMaturity3,  
			ExtendedMaturity4,  
			FullyExtendedMaturity,  
			CurrentMaturityDate,  
			CurrentMaturity,  
			[PaidOffSold],  
			[FeesStart],  
			[RSLIC],  
			[SNCC],  
			[PIIC],  
			[TMR],  
			[HCC],  
			[USSIC],  
			[TMNF],  
			[HAIH],  
			[Check],  
			[CAMRA],  
			[Servicer],  
			[ServicerID],  
			[PremDisc],  
			OriginationFee,  
			ExitFee,  
			PaydownPayoffConvention,  
			PaymentDate,  
			WholeLoanSpread,  
			ExtensionFee1,  
			ExtensionFee2,  
			ExtensionFee3,  
			ExtensionFee4,  
			ProductType,  
			MSA,  
			[State],   
			DealType,  
			[InquiryYear],  
			[Location],  
			[UnderwrittenReturn]    
			)  
  
			SELECT
				DealID ,  
				DealGroupID1 ,  
				ACOREID ,  
				CONVERT(INT, Pri)	 ,    
				DealName ,  
				NoteName ,  
				LoanStatus1 ,  
				Client ,  
				Fund ,  
				AssetManager1,  
				Banker1 ,  
				Credit1 ,  
				Pool ,  
				FinancingSource1 , 
				CurrentEntity,  
				CapStack ,  
				BillingNote ,  
				CAST(REPLACE(Commitment ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(Spread ,'N/A',0) AS DECIMAL(28, 15)) ,  
				CAST(REPLACE(IndexforStub ,'N/A',0) AS DECIMAL(28, 15))  ,   
				CAST(REPLACE([Floor] ,'N/A',0) AS DECIMAL(28, 15))  ,   
				Type ,  
				CONVERT(DATE,InitialFunding) , 
				CONVERT(DATE,InitialMaturity) ,  	 				
				CONVERT(DATE,ExtendedMaturity1) ,  	
				CONVERT(DATE,ExtendedMaturity2) ,  	
				CONVERT(DATE,ExtendedMaturity3) ,  	
				CONVERT(DATE,ExtendedMaturity4) ,  	
				CONVERT(DATE,FullyExtendedMaturity) ,  	
				CONVERT(DATE,CurrentMaturityDate) ,   				  
				CurrentMaturity,    
				CONVERT(DATE,PaidOffSold) ,  
  
				FeesStart ,  
				CAST(REPLACE(RSLIC ,'N/A',0) AS DECIMAL(28, 15))  ,
				CAST(REPLACE(SNCC ,'N/A',0) AS DECIMAL(28, 15))  ,   
				CAST(REPLACE(PIIC ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(TMR ,'N/A',0) AS DECIMAL(28, 15))  ,   
				CAST(REPLACE(HCC ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(USSIC ,'N/A',0) AS DECIMAL(28, 15))  ,  
				CAST(REPLACE(TMNF ,'N/A',0) AS DECIMAL(28, 15))  ,
				CAST(REPLACE(HAIH ,'N/A',0) AS DECIMAL(28, 15))  ,   
				CAST(REPLACE( [Check] ,'N/A',0) AS DECIMAL(28, 15))  ,   
				CAMRA ,  
				Servicer ,  
				ServicerID ,  
				CAST(REPLACE( PremDisc ,'N/A',0) AS DECIMAL(28, 15)) ,
				OriginationFee,  
				ExitFee,  
				CONVERT(INT, PaydownPayoffConvention) ,    
				CONVERT(INT, PaymentDate) ,
				CAST(REPLACE( WholeLoanSpread ,'N/A',0) AS DECIMAL(28, 15))  ,
				CAST(REPLACE( ExtensionFee1 ,'N/A',0) AS DECIMAL(28, 15))  ,
				CAST(REPLACE( ExtensionFee2 ,'N/A',0) AS DECIMAL(28, 15))  , 
				CAST(REPLACE( ExtensionFee3 ,'N/A',0) AS DECIMAL(28, 15))  , 
				CAST(REPLACE( ExtensionFee4 ,'N/A',0) AS DECIMAL(28, 15))  , 
				ProductType,  
				MSA,  
				State,   
				DealType,  
				CONVERT(INT, InquiryYear) ,  
				Location,  
				UnderwrittenReturn    
				 FROM [DW].[L_NoteMatrixBI]
				WHERE SheetName='ACORE Credit IV - Note Matrix'
				 

    
	Truncate Table [DW].[L_NoteMatrixBI]
  
END  
