--[dbo].[usp_GetCalcJsonByFundName] 'ACP II','c10f3372-0fc2-4861-a9f5-148f1f80804f'

truncate table  [CRE].[JsonFormatCalcLiability]
go

INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES (N'root', N'Scenario', N'variable', N'nvarchar(256)', 1, NULL, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES (N'root', N'CalcAsOfDate', N'variable', N'date', 1, NULL, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES (N'root', N'Fund', N'json', N'', 1, NULL, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES (N'root', N'AssetNotes', N'array', N'', 1, NULL, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES (N'root', N'LiabilityNotes', N'array', N'', 1, NULL, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES (N'root', N'LiabilityLines', N'array', N'', 1, NULL, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES (N'root.Fund', N'EquityName', N'variable', N'nvarchar(256)', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES (N'root.Fund', N'EquityType', N'variable', N'nvarchar(256)', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES (N'root.Fund', N'Currency', N'variable', N'nvarchar(256)', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.Fund', N'InvestorCapital', N'variable', N'decimal(28,15)', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.Fund', N'CapitalReserveReq', N'variable', N'decimal(28,15)', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.Fund', N'ReserveReq', N'variable', N'decimal(28,15)', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.Fund', N'CapitalCallNoticeBusinessDays', N'variable', N'int', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.Fund', N'InceptionDate', N'variable', N'date', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.Fund', N'LastDatetoInvest', N'variable', N'date', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.Fund', N'LinkedShortTermBorrowingFacility', N'variable', N'nvarchar(256)', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.Fund', N'BalanceAsofCalcDate', N'variable', N'decimal(28,15)', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.Fund', N'LastLockedTransactionDate', N'variable', N'date', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.fund', N'FundUpdates', N'array', N'', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.Fund.FundUpdates', N'EffectiveDate', N'variable', N'date', 1, 19, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.Fund.FundUpdates', N'Commitment', N'variable', N'decimal(28,15)', 1, 19, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.Fund.FundUpdates', N'InitialMaturityDate', N'variable', N'date', 1, 19, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes', N'CreNoteID', N'variable', N'nvarchar(256)', 1, 4, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes', N'ClosingDate', N'variable', N'date', 1, 4, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes', N'AdjCommitment', N'variable', N'decimal(28,15)', 1, 4, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes', N'BalanceAsofCalcDate', N'variable', N'decimal(28,15)', 1, 4, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes', N'LastLockedTransactionDate', N'variable', N'date', 1, 4, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes', N'Transactions', N'array', N'', 1, 4, N'AssetAccountID')


INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes.Transactions', N'date', N'variable', N'date', 1, 28, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes.Transactions', N'Amount', N'variable', N'decimal(28,15)', 1, 28, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes.Transactions', N'Type', N'variable', N'nvarchar(256)', 1, 28, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes', N'LiabilityNoteID', N'variable', N'nvarchar(256)', 1, 5, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes', N'LiabilityID', N'variable', N'nvarchar(256)', 1, 5, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes', N'AssetID', N'variable', N'nvarchar(256)', 1, 5, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes', N'BalanceAsofCalcDate', N'variable', N'decimal(28,15)', 1, 5, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes', N'LastLockedTransactionDate', N'variable', N'date', 1, 5, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes', N'LiabilityNoteUpdates', N'array', N'', 1, 5, N'LiabilityNoteAccountId')
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes.LiabilityNoteUpdates', N'EffectiveDate', N'variable', N'date', 1, 37, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes.LiabilityNoteUpdates', N'PledgeDate', N'variable', N'date', 1, 37, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes.LiabilityNoteUpdates', N'TargetAdvanceRate', N'variable', N'decimal(28,15)', 1, 37, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes.LiabilityNoteUpdates', N'PaydownAdvanceRate', N'variable', N'decimal(28,15)', 1, 37, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes.LiabilityNoteUpdates', N'FundingAdvanceRate', N'variable', N'decimal(28,15)', 1, 37, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes.LiabilityNoteUpdates', N'MaturityDate', N'variable', N'date', 1, 37, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'LiabilityID', N'variable', N'nvarchar(256)', 1, 6, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'Type', N'variable', N'nvarchar(256)', 1, 6, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'MatchTerm', N'variable', N'nvarchar(256)', 1, 6, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'IsRevolving', N'variable', N'nvarchar(256)', 1, 6, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'Currency', N'variable', N'nvarchar(256)', 1, 6, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'FundingNoticeBusinessDays', N'variable', N'int', 1, 6, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'InitialFundingDelay', N'variable', N'int', 1, 6, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'MaxAdvanceRate', N'variable', N'decimal(28,15)', 1, 6, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'OriginationDate', N'variable', N'date', 1, 6, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'PaydownDelay', N'variable', N'int', 1, 6, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'BalanceAsofCalcDate', N'variable', N'decimal(28,15)', 1, 6, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'LastLockedTransactionDate', N'variable', N'date', 1, 6, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'LiabilityLineUpdates', N'array', N'', 1, 6, N'DebtAccountID')
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines.LiabilityLineUpdates', N'EffectiveDate', N'variable', N'date', 1, 56, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines.LiabilityLineUpdates', N'Commitment', N'variable', N'decimal(28,15)', 1, 56, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines.LiabilityLineUpdates', N'InitialMaturityDate', N'variable', N'date', 1, 56, NULL)

INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes', N'AssetAccountID', N'variable', N'nvarchar(256)', 1, 4, null)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes', N'LiabilityNoteAccountID', N'variable', N'nvarchar(256)', 1, 5, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES (N'root.Fund', N'EquityAccountID', N'variable', N'nvarchar(256)', 1, 3, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityLines', N'DebtAccountID', N'variable', N'nvarchar(256)', 1, 6, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES (N'root', N'AnalysisID', N'variable', N'nvarchar(256)', 1, NULL, NULL)

INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES (N'root', N'SubLines', N'array', N'', 1, NULL, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'DebtAccountID', N'variable', N'nvarchar(256)', 1, 65, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'LiabilityID', N'variable', N'nvarchar(256)', 1, 65, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'Type', N'variable', N'nvarchar(256)', 1, 65, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'MatchTerm', N'variable', N'nvarchar(256)', 1, 65, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'IsRevolving', N'variable', N'nvarchar(256)', 1, 65, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'Currency', N'variable', N'nvarchar(256)', 1, 65, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'FundingNoticeBusinessDays', N'variable', N'int', 1, 65, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'InitialFundingDelay', N'variable', N'int', 1, 65, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'MaxAdvanceRate', N'variable', N'decimal(28,15)', 1, 65, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'OriginationDate', N'variable', N'date', 1, 65, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'PaydownDelay', N'variable', N'int', 1, 65, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'BalanceAsofCalcDate', N'variable', N'decimal(28,15)', 1, 65, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'LastLockedTransactionDate', N'variable', N'date', 1, 65, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines', N'LiabilityLineUpdates', N'array', N'', 1, 65, N'DebtAccountID')

INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines.LiabilityLineUpdates', N'EffectiveDate', N'variable', N'date', 1, 79, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines.LiabilityLineUpdates', N'Commitment', N'variable', N'decimal(28,15)', 1, 79, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.SubLines.LiabilityLineUpdates', N'InitialMaturityDate', N'variable', N'date', 1, 79, NULL)

INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes.Transactions', N'TransactionEntryID', N'variable', N'nvarchar(256)', 1, 28, NULL)


INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES (N'root', N'CashflowConfig', N'json', N'', 1, NULL, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.CashflowConfig', N'OperationMode', N'variable', N'nvarchar(256)', 1, 84, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.CashflowConfig', N'EqDelayMonths', N'variable', N'int', 1, 84, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.CashflowConfig', N'FinDelayMonths', N'variable', N'int', 1, 84, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.CashflowConfig', N'MinEqBalForFinStart', N'variable', N'decimal(28,15)', 1, 84, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.CashflowConfig', N'SublineEqApplyMonths', N'variable', N'int', 1, 84, NULL)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.CashflowConfig', N'SublineFinApplyMonths', N'variable', N'int', 1, 84, NULL)

INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.CashflowConfig', N'DebtCallDaysOfTheMonth', N'SingleArray', N'', 1, 84, null)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.CashflowConfig', N'CapitalCallDaysOfTheMonth', N'SingleArray', N'', 1, 84, null)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.CashflowConfig.DebtCallDaysOfTheMonth', N'', N'', N'int', 1, 91, null)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.CashflowConfig.CapitalCallDaysOfTheMonth', N'', N'', N'int', 1, 92, null)



INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes', N'FinancingSourceName', N'variable', N'nvarchar(256)', 1, 4, null)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes', N'ParentClient', N'variable', N'nvarchar(256)', 1, 4, null)
INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.AssetNotes', N'Owned', N'variable', N'bool', 1, 4, null)

INSERT [CRE].[JsonFormatCalcLiability] ( [Position], [Key], [KeyFormat], [DataType], [IsActive], [ParentID], [FilterBy]) VALUES ( N'root.LiabilityNotes', N'Type', N'variable', N'nvarchar(256)', 1, 5, NULL)

--select * from [CRE].[JsonFormatCalcLiability]