
Truncate table [CRE].[TransactionTypesDecodeMapping]
go

INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('ASSU_FEE','Assumption Fee','AdditionalFeesExcludedFromLevelYield','Assumption Fee')
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('BANK_LOAN','Bank Loan Other Expense',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('CAP_CONTRIB','Capital Contribution',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('CAP_GAINS','Capital Gains Tax',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('CASH_TRANSFER','Cash Transfer',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('CFEE','Consent Fee',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('CLEAR_FEE','Clear Par Fees',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('CLOSE_FEE','Closing Fee',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('COLLAT_FEE','Collateral Release Fee',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('CUST_FEE','Custody Fee',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('DEFALT','Default Interest','AdditionalFeesExcludedFromLevelYield','Default Interest')
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('DIV','Dividend',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('DIV_ADJ','Dividend Adj',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('DIVDIFF','Dividend Pmt Diff',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('EARNING','Earning',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('ENVIRO_FEE','Environmental Fees',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('EXIT_FEE','Exit Fee','ExitFeeExcludedFromLevelYield',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('EXIT_FEE','Exit Fee','ExitFeeStrippingExcldfromLevelYield',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('EXIT_FEE','Exit Fee','ExitFeeStripReceivable',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('EXTEN_FEE','Extension Fee','ExtensionFeeExcludedFromLevelYield',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('EXTEN_FEE','Extension Fee','ExtensionFeeStrippingExcldfromLevelYield',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('EXTEN_FEE','Extension Fee','ExtensionFeeStripReceivable',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('EXTEN_FEEM','Extension Fee/Modification Fee','AdditionalFeesExcludedFromLevelYield','Mod Fee')
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('FAC_FEE','Facility Fee',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('FE_P_FEE','Front End /Participation Fee',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('FX','FX Net',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('INC_ACTUAL','Bank Loan Other Income',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('INTDIFF','Interest Pmt Diff',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('INTEREST','Interest','InterestPaid',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('INTEREST','Interest','PIKInterestPaid',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('INTEREST','Interest','PIKInterest',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('INTEREST','Interest','Purchased Interest',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('INTEREST','Interest','StubInterest',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('INTEREST','Interest','FloatInterest',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('LATE_FEE','Late Fees','AdditionalFeesExcludedFromLevelYield','Late Charge')
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('LEGAL_EXP','Legal Expenses',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('LIB_INT','LIBOR Interest',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('LIBOR_PAY','LIBOR Paydown',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('LOAN_DIS','Loan Disbursement',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('MGMT_FEE','Management Fee','ManagementFee',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('MGMT_FEE','Management Fee','AcoreOriginationFeeExcludedFromLevelYield',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('MISC_PNI','Misc Security Prin/Int',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('OD_FEE','Overdraft Fee',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('OPS_FEE','Operating Fees',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('ORIG_FEE','Origination Fees','OriginationFeeIncludedInLevelYield',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('ORIG_FEE','Origination Fees','OriginationFeeStripping',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('ORIG_FEE','Origination Fees','OriginationFeeStripReceivable',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('OTHR_FEE','Other Fee','OtherFeeExcludedFromLevelYield',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('OTHR_FEE','Other Fee','UnusedFeeExcludedFromLevelYield',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('OTHR_INC','Other Income',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('PNI_ACTUAL','Actual Principal/Interest',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('PNI_ACTUAL_F','Full Principal Paydown',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('PNI_ACTUAL_P','Partial Principal Paydown',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('PREPAY_FEE','Prepayment Fee','PrepaymentFeeExcludedFromLevelYield',null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('PRIM_INT','Prime Interest',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('PRIME_PAY','PRIME Paydown',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('PRINDIFF','Principal Pmt Diff',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('REALIZED_GL','Realized Gain/Loss',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('RECOV_EXP','Recovery of expenses',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('RECOV_PRO','Recovery of protective advances',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('REPO_MGN','Repo Margin',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('REPO_NET','Repo Netting',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('REPO_STL','Repo Settlement',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('RET_CAP','Return of Capital',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('SEC_LEND','Sec Lending Inc',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('STLMONEY','Settlement Money Diff',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('SWEEP_INT','Sweep Interest',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('TD','Time Deposit (No CM)',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('TICK_COMM','Ticking/Commitment Fee',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('TIME_DEPOSIT','Time Deposit',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('TITLE_FEE','Title Fees',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('TRANSF_FEE','Transfer Agent Fee',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('UNSETT_CASHTR','Unsettled Cash Transfer',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('UTILI_FEE','Utilization Fee',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('NEWCASHEST','Pending NEWCASH',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('PAIROFF','Pairoff Fail',null,null)
INSERT INTO  [CRE].[TransactionTypesDecodeMapping](DecodeName,[Decode_Definition],[TransactionName],FeeType)values('UNKNOWN','Unknown Cash Tran',null,null)

go

Delete from [CRE].[TransactionTypesDecodeMapping] where TransactionName is NULL