CREATE TABLE [CRE].[DealFundingLog] (
    [DealFundingLogID]          INT              IDENTITY (1, 1) NOT NULL,
    [DealFundingID]             UNIQUEIDENTIFIER NOT NULL,
    [DealID]                    UNIQUEIDENTIFIER NOT NULL,
    [Date]                      DATE             NULL,
    [Amount]                    DECIMAL (28, 15) NULL,
    [Comment]                   NVARCHAR (MAX)   NULL,
    [PurposeID]                 INT              NULL,
    [Applied]                   BIT              NULL,
    [Issaved]                   BIT              CONSTRAINT [DF__DealFundi__Issav__1B73E779] DEFAULT ((0)) NULL,
    [DealFundingRowno]          INT              NULL,
    [CreatedBy]                 NVARCHAR (256)   NULL,
    [CreatedDate]               DATETIME         NULL,
    [UpdatedBy]                 NVARCHAR (256)   NULL,
    [UpdatedDate]               DATETIME         NULL,
    [DrawFundingId]             NVARCHAR (256)   NULL,
    [DeadLineDate]              DATE             NULL,
    [EquityAmount]              DECIMAL (28, 15) CONSTRAINT [DF__DealFundi__Equit__1C680BB2] DEFAULT ((0)) NULL,
    [RemainingFFCommitment]     DECIMAL (28, 15) CONSTRAINT [DF__DealFundi__Remai__1D5C2FEB] DEFAULT ((0)) NULL,
    [RemainingEquityCommitment] DECIMAL (28, 15) CONSTRAINT [DF__DealFundi__Remai__1E505424] DEFAULT ((0)) NULL,
    [SubPurposeType]            NVARCHAR (256)   NULL,
    [LegalDeal_DealFundingID]   UNIQUEIDENTIFIER NULL,
    [LogDate]                   DATETIME         NULL,
    CONSTRAINT [PK__DealFund__B0C451C4E9C4997E] PRIMARY KEY CLUSTERED ([DealFundingLogID] ASC)
);

