CREATE TABLE [CRE].[InvoiceDetail] (
    [InvoiceDetailID] INT              IDENTITY (1, 1) NOT NULL,
    [InvoiceNo]       NVARCHAR (256)   NULL,
    [TaskID]          UNIQUEIDENTIFIER NULL,
    [ObjectTypeID]    INT              NULL,
    [ObjectID]        NVARCHAR (256)   NULL,
    [Amount]          DECIMAL (28, 15) NULL,
    [AmountPaid]      DECIMAL (28, 15) NULL,
    [PaymentDate]     DATETIME         NULL,
    [AmountAdj]       DECIMAL (28, 15) NULL,
    [AdjComments]     NVARCHAR (2000)  NULL,
    [FirstName]       NVARCHAR (256)   NULL,
    [LastName]        NVARCHAR (256)   NULL,
    [Designation]     NVARCHAR (256)   NULL,
    [CompanyName]     NVARCHAR (256)   NULL,
    [Address]         NVARCHAR (256)   NULL,
    [City]            NVARCHAR (256)   NULL,
    [State]           NVARCHAR (256)   NULL,
    [Zip]             NVARCHAR (256)   NULL,
    [Email1]          NVARCHAR (256)   NULL,
    [Email2]          NVARCHAR (256)   NULL,
    [PhoneNo]         NVARCHAR (256)   NULL,
    [AlternatePhone]  NVARCHAR (256)   NULL,
    [Comment]         NVARCHAR (2000)  NULL,
    [AutoSendInvoice] INT              DEFAULT ((572)) NULL,
    [CreatedBy]       NVARCHAR (256)   NULL,
    [CreatedDate]     DATETIME         NULL,
    [UpdatedBy]       NVARCHAR (256)   NULL,
    [UpdatedDate]     DATETIME         NULL,
    [DrawFeeStatus]   INT              NULL,
    [FileName]        NVARCHAR (256)   NULL,
    [InvoiceTypeID]   INT              NULL,
	[StateID]         INT              NULL,
    [SystemInvoiceNo]   NVARCHAR (256)   NULL,
    [DealID]   UNIQUEIDENTIFIER   NULL,
    InvoiceComment nVarchar(2000),
    InvoiceDate	Date NULL,
    InvoiceDateOriginal	Date NULL,
    InvoiceDueDate	Date NULL,
    BatchUploadComment NVARCHAR (2000)  NULL,
    UploadedFrom nvarchar(256),
    EmailCC NVARCHAR (256)   NULL,
    SenderFirstName NVARCHAR (256)   NULL,
    SenderLastName NVARCHAR (256)   NULL,
    SenderEmail NVARCHAR (256)   NULL,
    [PreAssignedInvoiceNo]       NVARCHAR (256)   NULL,
    [InvoiceGuid] UNIQUEIDENTIFIER   NULL, 
    [InvoiceTypeName] nvarchar(256) NULL,
);

go
ALTER TABLE [CRE].[InvoiceDetail]
ADD CONSTRAINT PK_InvoiceDetail_InvoiceDetailID PRIMARY KEY (InvoiceDetailID);