CREATE TABLE [CRE].[TransactionEntryClose] (
    [TransactionEntryCloseID]     UNIQUEIDENTIFIER CONSTRAINT [DF__Transacti__Trans__75F77EB0] DEFAULT (newid()) NOT NULL,
    [NoteID]                      UNIQUEIDENTIFIER NOT NULL,
    [Date]                        DATETIME         NULL,
    [Amount]                      DECIMAL (28, 15) NULL,
    [Type]                        NVARCHAR (MAX)   NULL,
    [CreatedBy]                   NVARCHAR (256)   NULL,
    [CreatedDate]                 DATETIME         NULL,
    [UpdatedBy]                   NVARCHAR (256)   NULL,
    [UpdatedDate]                 DATETIME         NULL,
    [TransactionEntryCloseAutoID] INT              IDENTITY (1, 1) NOT NULL,
    [AnalysisID]                  UNIQUEIDENTIFIER NULL,
    [FeeName]                     NVARCHAR (256)   NULL,
    [PeriodID]                    UNIQUEIDENTIFIER NULL,
    [PeriodCloseEnd]              DATE             NULL,
    [TagMasterID]                 UNIQUEIDENTIFIER NULL,
    [StrCreatedBy]                NVARCHAR (256)   NULL,
    [TransactionDateByRule]       DATE             NULL,
    [TransactionDateServicingLog] DATE             NULL,
    [RemitDate]                   DATE             NULL,
    [FeeTypeName]                 NVARCHAR (256)   NULL,
    [Comment]                     NVARCHAR (MAX)   NULL,
    [PurposeType] NVARCHAR(256) NULL, 
    [Cash_NonCash] NVARCHAR(256) NULL, 
    CONSTRAINT [PK_TransactionEntryCloseAutoID] PRIMARY KEY CLUSTERED ([TransactionEntryCloseAutoID] ASC)
);

