CREATE TABLE [CRE].[XIRRCalculationInput] (
    [XIRRCalculationInputID]               INT              IDENTITY (1, 1) NOT NULL,
    [XIRRConfigID]                         INT              NULL,
    [AnalysisID]                           UNIQUEIDENTIFIER NULL,
    [DealAccountID]                        UNIQUEIDENTIFIER NULL,
    [ChildReturnName]                      NVARCHAR (256)   NULL,
    [CreatedBy]                            NVARCHAR (256)   NULL,
    [CreatedDate]                          DATETIME         NULL,
    [UpdatedBy]                            NVARCHAR (256)   NULL,
    [UpdatedDate]                          DATETIME         NULL,
    [Type]                                 NVARCHAR (256)   NULL,
    [NoteAccountID]                        UNIQUEIDENTIFIER NULL,
    [ReturnName]                           NVARCHAR (256)   NULL,
    [PoolID]                               NVARCHAR (256)   NULL,
    [ProductTypeID]                        NVARCHAR (256)   NULL,
    [State]                                NVARCHAR (256)   NULL,
    [DealTypeID]                           NVARCHAR (256)   NULL,
    [Group1]                               INT              NULL,
    [Group2]                               INT              NULL,
    [XIRRReturnGroupID]                    INT              NULL,
    [LoanStatus]                           NVARCHAR (256)   NULL,
    [MSA]                                  NVARCHAR (256)   NULL,
    [VintageYear]                          NVARCHAR (256)   NULL,
    [ChildReturnName_ColumnTotal]          NVARCHAR (256)   NULL,
    [ChildReturnName_RowTotal]             NVARCHAR (256)   NULL,
    [ChildReturnName_OverallTotal]         NVARCHAR (256)   NULL,
    [XIRRReturnGroupID_ColumnTotal]        NVARCHAR (256)   NULL,
    [XIRRReturnGroupID_RowTotal]           NVARCHAR (256)   NULL,
    [XIRRReturnGroupID_OverallTotal]       NVARCHAR (256)   NULL,
    [ChildReturnName_OverallColumnTotal]   NVARCHAR (256)   NULL,
    [XIRRReturnGroupID_OverallColumnTotal] NVARCHAR (256)   NULL,
    [ChildReturnName_GroupTotal]           NVARCHAR (256)   NULL,
    [XIRRReturnGroupID_GroupTotal]         NVARCHAR (256)   NULL,
    CONSTRAINT [PK_XIRRCalculationInputID] PRIMARY KEY CLUSTERED ([XIRRCalculationInputID] ASC),
    CONSTRAINT [FK_XIRRCalculationInput_XIRRConfigID] FOREIGN KEY ([XIRRConfigID]) REFERENCES [CRE].[XIRRConfig] ([XIRRConfigID])
);
GO

