/****** Object:  Table [dbo].[FacilityNameUpdate$]    Script Date: 7/22/2025 4:48:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

DROP TABLE [dbo].[FacilityNameUpdate$]
go
CREATE TABLE [dbo].[FacilityNameUpdate$](
	[FundName] [nvarchar](255) NULL,
	[FundShortName] [nvarchar](255) NULL,
	[FacilityName] [nvarchar](255) NULL,
	[FacilityShortName] [nvarchar](255) NULL,
	[FinancialInstitution] [nvarchar](255) NULL,
	[FacilityType] [nvarchar](255) NULL,
	[LiabilityID] [nvarchar](255) NULL,
	[Comments] [nvarchar](255) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'3rd Party', N'3rd Party', N'NA', N'Sale', N'ACPI-3rd Party-Sale', N'i don''t know which 3rd party this refers to, but for now  we can leave as a Sale')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'AXOS 2021-01', N'Axos', N'Axos Bank', N'NoN', N'ACPI-Axos-NoN', N'Axos in all lowercase, NoN not repo')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'Cap One 2017-SL', N'CONA', N'Capital One', N'Subline', N'ACPI-CONA-Subline', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'Cap One 2017-SL Cash', N'CONA', N'Capital One', N'NA', N'ACPI-CONA-NA', N'would this even have a Liability ID since it''s tied to the liability above?')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'DB Repo 2019-01', N'DB', N'Deutsche Bank', N'Repo', N'ACPI-DB-Repo', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'GS CLO 2018-01', N'GS', N'Goldman Sachs', N'CLO', N'ACPI-GS-CLO', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'MS Repo 2018-01', N'MS', N'Morgan Stanley', N'Repo', N'ACPI-MS-Repo', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'Prime Finance', N'Prime', N'Prime Finance', N'Mortgage', N'ACPI-Prime-Mortgage', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'Sunwest Bank', N'Sunwest', N'Sunwest Bank', N'NoN', N'ACPI-Sunwest-NoN', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'WF Repo 2020-01', N'WF', N'Wells Fargo', N'Repo', N'ACPI-WF-Repo', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'Axos Bank', N'Axos', N'Axos Bank', N'NoN', N'ACPII-Axos-NoN', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'Bank OZK', N'OZK', N'Bank OZK', N'Sale', N'ACPII-OZK-Sale', N'we should still discuss this, maybe we change the type to Sale/CoOrigination instead of "Sub Debt"; or we should jsut use "Sale"')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'Blackstone', N'BX', N'Blackstone', N'Sale', N'ACPII-BX-Sale', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'Cap One 2022-01', N'CONA', N'Capital One', N'Subline', N'ACPII-CONA-Subline', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'Cap One 2022-01 Cash', N'CONA', N'Capital One', N'NA', N'ACPII-CONA-NA', N'would this even have a Liability ID since it''s tied to the liability above?')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'CONA NoN', N'CONA', N'Capital One', N'NoN', N'ACPII-CONA-NoN', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'Customers', N'Customers', N'Customers Bank', N'NoN', N'ACPII-Customers-NoN', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'GS Repo', N'GS', N'Goldman Sachs', N'Repo', N'ACPII-GS-Repo', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'JP Morgan', N'JPM', N'JP Morgan', N'Sale', N'ACPII-JPM-Sale', N'we should still discuss this, maybe we change the type to Sale/CoOrigination instead of "Sub Debt"; or we should jsut use "Sale"')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'JPM Repo', N'JPM', N'JP Morgan', N'Repo', N'ACPII-JPM-Repo', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'MS Repo', N'MS', N'Morgan Stanley', N'Repo', N'ACPII-MS-Repo', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'TBD', N'TBD', N'TBD', N'TBD', N'ACPII-TBD-TBD', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'TBK Bank', N'TBK', N'TBK Bank', N'Sale', N'ACPII-TBK-Sale', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'WF Repo', N'WF', N'Wells Fargo', N'Repo', N'ACPII-WF-Repo', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit I', N'AOCI', N'3rd Party', N'3rd Party', N'NA', N'Sale', N'AOCI-3rd Party-Sale', N'i don''t know which 3rd party this refers to, but for now  we can leave as a Sale')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit I', N'AOCI', N'Aksia', N'Aksia', N'Aksia LLC', N'Repo', N'AOCI-Aksia-Repo', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit I', N'AOCI', N'Axos Bank', N'Axos', N'Axos Bank', N'NoN', N'AOCI-Axos-NoN', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit I', N'AOCI', N'Bank OZK', N'OZK', N'Bank OZK', N'Sale', N'AOCI-OZK-Sale', N'we should still discuss this, maybe we change the type to Sale/CoOrigination instead of "Sub Debt"; or we should jsut use "Sale"')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit I', N'AOCI', N'Customers', N'Customers', N'Customers Bank', N'NoN', N'AOCI-Customers-NoN', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit I', N'AOCI', N'SB 2021-01', N'Sunwest', N'Sunwest Bank', N'Subline', N'AOCI-Sunwest-Subline', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit I', N'AOCI', N'SB 2021-01 Cash', N'Sunwest', N'Sunwest Bank', N'NA', N'AOCI-Sunwest-NA', N'would this even have a Liability ID since it''s tied to the liability above?')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit I', N'AOCI', N'TBD', N'TBD', N'TBD', N'TBD', N'AOCI-TBD-TBD', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit I', N'AOCI', N'TBK Bank', N'TBK', N'TBK Bank', N'Sale', N'AOCI-TBK-Sale', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit II', N'AOCII', N'GS Repo', N'GS', N'Goldman Sachs', N'Repo', N'AOCII-GS-Repo', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit II', N'AOCII', N'SWB 2024-01', N'Sunwest', N'Sunwest Bank', N'Subline', N'AOCII-Sunwest-Subline', NULL)
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit II', N'AOCII', N'SWB 2024-01 Cash', N'Sunwest', N'Sunwest Bank', N'NA', N'AOCII-Sunwest-NA', N'would this even have a Liability ID since it''s tied to the liability above?')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners II', N'ACPII', N'TP Bank', N'TP', N'Torrey Pines Bank', N'Sale', N'ACPII-TP-Sale', N'deal associated: 300 Banyan & 111 Olive')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit I', N'AOCI', N'Churchill', N'Churchill', N'Churchill Real Estate', N'Repo', N'AOCI-Churchill-Repo', N'deals associated: Lake Tahoe Beach Club Phase II, Long Beach Superblock Condo, Holland Park')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'bcIMC JV', N'bcIMC', N'British Columbia Investment Management Corporation', N'Sale', N'ACPI-bcIMC-Sale', N'deals associated: Federal Reserve & 400 Westlake')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'C3', N'C3', N'C3 Bank', N'Sale', N'ACPI-C3-Sale', N'deal associated: Miramonte Indian Wells Resort & Spa')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'Hamburg', N'Hamburg', N'Bank of Hamburg', N'Sale', N'ACPI-Hamburg-Sale', N'deal associated: 810 7th Street')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'Torchlight', N'Torchlight', N'Torchlight Investors', N'Sale', N'ACPI-Torchlight-Sale', N'deal associated: 2 N LaSalle')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'Delphi', N'Delphi', N'Delphi Financial Group', N'Sale', N'ACPI-Delphi-Sale', N'deal assocaited: Northstar ALTO Portfolio')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Credit Partners I', N'ACPI', N'HarborOne', N'HarborOne', N'HarborOne Bank', N'Sale', N'ACPI-HarborOne-Sale', N'deal associated: Elm Street Labs')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit II', N'AOCII', N'JP Morgan', N'JPM', N'JP Morgan', N'Sale', N'AOCII-JPM-Sale', N'deal associated: Kuilei Place')
INSERT [dbo].[FacilityNameUpdate$] ([FundName], [FundShortName], [FacilityName], [FacilityShortName], [FinancialInstitution], [FacilityType], [LiabilityID], [Comments]) VALUES (N'ACORE Opportunistic Credit II', N'AOCII', N'PNC 2025-01', N'PNC', N'PNC Bank', N'Subline', N'AOCII-PNC-Subline', N'new subline with PNC')
GO
 