CREATE EXTERNAL TABLE [dbo].[Ex_Prod_NoteTransactionDetail] (
    [NoteTransactionDetailID] UNIQUEIDENTIFIER NOT NULL,
    [NoteID] UNIQUEIDENTIFIER NOT NULL,
    [TransactionDate] DATE NULL,
    [TransactionType] INT NULL,
    [Amount] DECIMAL (28, 15) NULL,
    [RelatedtoModeledPMTDate] DATE NULL,
    [ModeledPayment] DECIMAL (28, 15) NULL,
    [AmountOutstandingafterCurrentPayment] DECIMAL (28, 15) NULL,
    [ServicingAmount] DECIMAL (28, 15) NULL,
    [CalculatedAmount] DECIMAL (28, 15) NULL,
    [Delta] DECIMAL (28, 15) NULL,
    [M61Value] BIT NULL,
    [ServicerValue] BIT NULL,
    [Ignore] BIT NULL,
    [OverrideValue] DECIMAL (28, 15) NULL,
    [comments] NVARCHAR (MAX) NULL,
    [PostedDate] DATETIME NULL,
    [ServicerMasterID] INT NULL,
    [Deleted] BIT NULL,
    [CreatedBy] NVARCHAR (256) NULL,
    [CreatedDate] DATETIME NULL,
    [UpdatedBy] NVARCHAR (256) NULL,
    [UpdatedDate] DATETIME NULL,
    [TransactionTypeText] NVARCHAR (256) NULL,
    [TranscationReconciliationID] UNIQUEIDENTIFIER NULL,
    [RemittanceDate] DATETIME NULL,
    [Exception] NVARCHAR (256) NULL,
    [Adjustment] DECIMAL (28, 15) NULL,
    [ActualDelta] DECIMAL (28, 15) NULL,
    [OverrideReason] INT NULL,
    [NoteTransactionDetailAutoID] INT NOT NULL,
    [BerAddlint] DECIMAL (28, 15) NULL,
    [TransactionEntryAmount] DECIMAL (28, 15) NULL,
    [Orig_ServicerMasterID] INT NULL
)
    WITH (
    DATA_SOURCE = [RemoteReferenceCRESProduction],
    SCHEMA_NAME = N'CRE',
    OBJECT_NAME = N'NoteTransactionDetail'
    );

