CREATE EXTERNAL TABLE [dbo].[Ex_Prod_Deal] (
    [DealID] UNIQUEIDENTIFIER NULL,
    [DealName] NVARCHAR (256) NULL,
    [CREDealID] NVARCHAR (256) NULL,
    [SourceDealID] UNIQUEIDENTIFIER NULL,
    [DealType] INT NULL,
    [LoanProgram] INT NULL,
    [LoanPurpose] INT NULL,
    [Status] INT NULL,
    [AppReceived] DATE NULL,
    [EstClosingDate] DATE NULL,
    [BorrowerRequest] NVARCHAR (256) NULL,
    [RecommendedLoan] DECIMAL (28, 15) NULL,
    [TotalFutureFunding] DECIMAL (28, 15) NULL,
    [Source] INT NULL,
    [BrokerageFirm] NVARCHAR (256) NULL,
    [BrokerageContact] NVARCHAR (256) NULL,
    [Sponsor] NVARCHAR (256) NULL,
    [Principal] NVARCHAR (256) NULL,
    [NetWorth] DECIMAL (28, 15) NULL,
    [Liquidity] DECIMAL (28, 15) NULL,
    [ClientDealID] NVARCHAR (256) NULL,
    [GeneratedBy] INT NULL,
    [TotalCommitment] DECIMAL (28, 15) NULL,
    [AdjustedTotalCommitment] DECIMAL (28, 15) NULL,
    [AggregatedTotal] DECIMAL (28, 15) NULL,
    [AssetManagerComment] NVARCHAR (MAX) NULL,
    [DealComment] NVARCHAR (MAX) NULL,
    [AssetManager] NVARCHAR (256) NULL,
    [DealCity] NVARCHAR (256) NULL,
    [DealState] NVARCHAR (256) NULL,
    [DealPropertyType] NVARCHAR (256) NULL,
    [FullyExtMaturityDate] DATE NULL,
    [UnderwritingStatus] INT NULL,
    [LinkedDealID] NVARCHAR (256) NULL,
    [IsDeleted] BIT NULL,
    [AllowSizerUpload] INT NULL,
    [CreatedBy] NVARCHAR (256) NULL,
    [CreatedDate] DATETIME NULL,
    [UpdatedBy] NVARCHAR (256) NULL,
    [UpdatedDate] DATETIME NULL,
    [AMUserID] UNIQUEIDENTIFIER NULL,
    [DealRule] NVARCHAR (2000) NULL,
    [AMTeamLeadUserID] UNIQUEIDENTIFIER NULL,
    [AMSecondUserID] UNIQUEIDENTIFIER NULL
)
    WITH (
    DATA_SOURCE = [RemoteReferenceCRESProduction],
    SCHEMA_NAME = N'CRE',
    OBJECT_NAME = N'Deal'
    );

