CREATE EXTERNAL TABLE [dbo].[tblContact] (
    [ContactID] INT NULL,
    [OrganizationID_F] INT NOT NULL,
    [FirstName] NVARCHAR (50) NOT NULL,
    [LastName] NVARCHAR (50) NOT NULL,
    [AddressID_F] INT NULL,
    [HomeAddressID_F] INT NULL,
    [BusinessPhone] NVARCHAR (50) NULL,
    [BusinessPhoneExt] NVARCHAR (10) NULL,
    [HomePhone] NVARCHAR (50) NULL,
    [Mobile] NVARCHAR (50) NULL,
    [Fax] NVARCHAR (50) NULL,
    [Pager] NVARCHAR (50) NULL,
    [IPPhone] NVARCHAR (50) NULL,
    [IMUserName] NVARCHAR (50) NULL,
    [EmailAddress] NVARCHAR (128) NULL,
    [WebsiteURL] NVARCHAR (128) NULL,
    [DateofBirth] DATETIME NULL,
    [Initials] NVARCHAR (10) NULL,
    [Title] NVARCHAR (50) NULL,
    [IsDeleted] BIT NULL,
    [Tier] TINYINT NULL,
    [Ranking] TINYINT NULL,
    [Anniversary] DATETIME NULL,
    [SpouseName] NVARCHAR (50) NULL,
    [ChildrenName] NVARCHAR (50) NULL,
    [OptOutFromEmail] BIT NULL,
    [AuditAddDate] DATETIME NOT NULL,
    [AuditUpdateDate] DATETIME NULL,
    [AuditAddUserId] NVARCHAR (150) NULL,
    [AuditUpdateUserId] NVARCHAR (150) NULL,
    [UseOrgAddressSw] BIT NULL,
    [FormOfAddress] NVARCHAR (10) NULL,
    [AssistantName] NVARCHAR (50) NULL,
    [Department] NVARCHAR (50) NULL,
    [MismoPartyID] BIGINT NULL,
    [IsPrimary] BIT NULL,
    [OfficerId] NVARCHAR (30) NULL,
    [Comments] NVARCHAR (MAX) NULL,
    [ClientIdentifier] NVARCHAR (200) NULL,
    [GenderCode] INT NULL,
    [Salution] NVARCHAR (50) NULL,
    [AddressName] NVARCHAR (50) NULL,
    [AssistantPhone] NVARCHAR (50) NULL,
    [PersonalFax] NVARCHAR (50) NULL,
    [EmailAddress2] NVARCHAR (128) NULL,
    [EmailAddress3] NVARCHAR (128) NULL
)
    WITH (
    DATA_SOURCE = [RemoteReferenceData]
    );

