CREATE TABLE [DW].[L_DealBI] (
    [DealID]                  UNIQUEIDENTIFIER NOT NULL,
    [DealName]                NVARCHAR (256)   NULL,
    [CREDealID]               NVARCHAR (256)   NULL,
    [DealType]                INT              NULL,
    [LoanProgram]             INT              NULL,
    [LoanPurpose]             INT              NULL,
    [Status]                  INT              NULL,
    [AppReceived]             DATE             NULL,
    [EstClosingDate]          DATE             NULL,
    [BorrowerRequest]         NVARCHAR (256)   NULL,
    [RecommendedLoan]         DECIMAL (28, 15) NULL,
    [TotalFutureFunding]      DECIMAL (28, 15) NULL,
    [Source]                  INT              NULL,
    [BrokerageFirm]           NVARCHAR (256)   NULL,
    [BrokerageContact]        NVARCHAR (256)   NULL,
    [Sponsor]                 NVARCHAR (256)   NULL,
    [Principal]               NVARCHAR (256)   NULL,
    [NetWorth]                DECIMAL (28, 15) NULL,
    [Liquidity]               DECIMAL (28, 15) NULL,
    [ClientDealID]            NVARCHAR (256)   NULL,
    [GeneratedBy]             INT              NULL,
    [TotalCommitment]         DECIMAL (28, 15) NULL,
    [AdjustedTotalCommitment] DECIMAL (28, 15) NULL,
    [AggregatedTotal]         DECIMAL (28, 15) NULL,
    [AssetManagerComment]     NVARCHAR (MAX)   NULL,
    [AssetManager]            NVARCHAR (256)   NULL,
    [DealCity]                NVARCHAR (256)   NULL,
    [DealState]               NVARCHAR (256)   NULL,
    [DealPropertyType]        NVARCHAR (256)   NULL,
    [FullyExtMaturityDate]    DATE             NULL,
    [DealTypeBI]              NVARCHAR (256)   NULL,
    [LoanProgramBI]           NVARCHAR (256)   NULL,
    [LoanPurposeBI]           NVARCHAR (256)   NULL,
    [DealStatusBI]            NVARCHAR (256)   NULL,
    [SourceBI]                NVARCHAR (256)   NULL,
    [CreatedBy]               NVARCHAR (256)   NULL,
    [CreatedDate]             DATETIME         NULL,
    [UpdatedBy]               NVARCHAR (256)   NULL,
    [UpdatedDate]             DATETIME         NULL,
    [UnderwritingStatus]      INT              NULL,
    [UnderwritingStatusBI]    NVARCHAR (256)   NULL,
    [AMTeamLeadUserID]        UNIQUEIDENTIFIER NULL,
    [AMSecondUserID]          UNIQUEIDENTIFIER NULL,
    [AMTeamLeadUserBI]        NVARCHAR (256)   NULL,
    [AMSecondUserBI]          NVARCHAR (256)   NULL,
    [AMUserID]                UNIQUEIDENTIFIER NULL,
    [AMUserBI]                NVARCHAR (256)   NULL,

    DealTypeMasterID int null,
    DealTypeMasterBI nvarchar(256) null,
    InquiryDate	Datetime null,
    BalanceAware	bit null,
    BS_CollateralStatusDesc	nvarchar(256) null,
    BS_CollateralStatusDesclatest	nvarchar(256) null,
    PropertyTypeMajorID	int null,
    PropertyTypeMajorBI nvarchar(256) null,
    BSCity	nvarchar(256) null,
    BSState	nvarchar(256) null,
    MSA_NAME	nvarchar(256) null,
    LoanStatusID int null,
    LoanStatusBI nvarchar(256) null
);

