CREATE TABLE [DW].[L_NoteTransactionDetailBI] (
    [NoteTransactionDetailID]     UNIQUEIDENTIFIER NOT NULL,
    [NoteID]                      UNIQUEIDENTIFIER NOT NULL,
    [CRENoteID]                   NVARCHAR (256)   NULL,
    [TransactionDate]             DATE             NULL,
    [Amount]                      DECIMAL (28, 15) NULL,
    [RelatedtoModeledPMTDate]     DATE             NULL,
    [ServicingAmount]             DECIMAL (28, 15) NULL,
    [CalculatedAmount]            DECIMAL (28, 15) NULL,
    [Delta]                       DECIMAL (28, 15) NULL,
    [M61Value]                    BIT              DEFAULT ((0)) NULL,
    [ServicerValue]               BIT              DEFAULT ((0)) NULL,
    [Ignore]                      BIT              DEFAULT ((0)) NULL,
    [OverrideValue]               DECIMAL (28, 15) NULL,
    [comments]                    NVARCHAR (MAX)   NULL,
    [PostedDate]                  DATETIME         NULL,
    [ServicerMasterID]            INT              NULL,
    [ServicerMasterBI]            NVARCHAR (256)   NULL,
    [Deleted]                     BIT              DEFAULT ((0)) NULL,
    [CreatedBy]                   NVARCHAR (256)   NULL,
    [CreatedDate]                 DATETIME         NULL,
    [UpdatedBy]                   NVARCHAR (256)   NULL,
    [UpdatedDate]                 DATETIME         NULL,
    [TransactionTypeText]         NVARCHAR (256)   NULL,
    [TranscationReconciliationID] UNIQUEIDENTIFIER NULL,
    [RemittanceDate]              DATETIME         NULL,
    [Exception]                   NVARCHAR (256)   NULL,
    [Adjustment]                  DECIMAL (28, 15) NULL,
    [ActualDelta]                 DECIMAL (28, 15) NULL,
    [NoteTransactionDetailAutoID] INT              NOT NULL,
    [OverrideReason]              INT              NULL,
    [OverrideReasonBI]            NVARCHAR (256)   NULL,
    [BerAddlint]                  DECIMAL (28, 15) NULL,
    [InterestAdj]                 DECIMAL (28, 15) NULL,
    [AddlInterest]                DECIMAL (28, 15) NULL,
    [TotalInterest]               DECIMAL (28, 15) NULL,
    BatchLogID                  int null
);

