CREATE TABLE [DW].[Staging_Cashflow] (
    [NotePeriodicCalcID]                          UNIQUEIDENTIFIER NOT NULL,
    [NoteID]                                      UNIQUEIDENTIFIER NULL,
    [CRENoteID]                                   NVARCHAR (MAX)   NULL,
    [PeriodEndDate]                               DATE             NULL,
    [Month]                                       INT              NULL,
    [ActualCashFlows]                             DECIMAL (28, 15) NULL,
    [GAAPCashFlows]                               DECIMAL (28, 15) NULL,
    [EndingGAAPBookValue]                         DECIMAL (28, 15) NULL,
    [TotalGAAPIncomeforthePeriod]                 DECIMAL (28, 15) NULL,
    [InterestAccrualforthePeriod]                 DECIMAL (28, 15) NULL,
    [PIKInterestAccrualforthePeriod]              DECIMAL (28, 15) NULL,
    [TotalAmortAccrualForPeriod]                  DECIMAL (28, 15) NULL,
    [AccumulatedAmort]                            DECIMAL (28, 15) NULL,
    [BeginningBalance]                            DECIMAL (28, 15) NULL,
    [TotalFutureAdvancesForThePeriod]             DECIMAL (28, 15) NULL,
    [TotalDiscretionaryCurtailmentsforthePeriod]  DECIMAL (28, 15) NULL,
    [InterestPaidOnPaymentDate]                   DECIMAL (28, 15) NULL,
    [TotalCouponStrippedforthePeriod]             DECIMAL (28, 15) NULL,
    [CouponStrippedonPaymentDate]                 DECIMAL (28, 15) NULL,
    [ScheduledPrincipal]                          DECIMAL (28, 15) NULL,
    [PrincipalPaid]                               DECIMAL (28, 15) NULL,
    [BalloonPayment]                              DECIMAL (28, 15) NULL,
    [EndingBalance]                               DECIMAL (28, 15) NULL,
    [ExitFeeIncludedInLevelYield]                 DECIMAL (28, 15) NULL,
    [ExitFeeExcludedFromLevelYield]               DECIMAL (28, 15) NULL,
    [AdditionalFeesIncludedInLevelYield]          DECIMAL (28, 15) NULL,
    [AdditionalFeesExcludedFromLevelYield]        DECIMAL (28, 15) NULL,
    [OriginationFeeStripping]                     DECIMAL (28, 15) NULL,
    [ExitFeeStrippingIncldinLevelYield]           DECIMAL (28, 15) NULL,
    [ExitFeeStrippingExcldfromLevelYield]         DECIMAL (28, 15) NULL,
    [AddlFeesStrippingIncldinLevelYield]          DECIMAL (28, 15) NULL,
    [AddlFeesStrippingExcldfromLevelYield]        DECIMAL (28, 15) NULL,
    [EndOfPeriodWAL]                              DECIMAL (28, 15) NULL,
    [PIKInterestFromPIKSourceNote]                DECIMAL (28, 15) NULL,
    [PIKInterestTransferredToRelatedNote]         DECIMAL (28, 15) NULL,
    [PIKInterestForThePeriod]                     DECIMAL (28, 15) NULL,
    [BeginningPIKBalanceNotInsideLoanBalance]     DECIMAL (28, 15) NULL,
    [PIKInterestForPeriodNotInsideLoanBalance]    DECIMAL (28, 15) NULL,
    [PIKBalanceBalloonPayment]                    DECIMAL (28, 15) NULL,
    [EndingPIKBalanceNotInsideLoanBalance]        DECIMAL (28, 15) NULL,
    [CostBasis]                                   DECIMAL (28, 15) NULL,
    [PreCapBasis]                                 DECIMAL (28, 15) NULL,
    [BasisCap]                                    DECIMAL (28, 15) NULL,
    [AmortAccrualLevelYield]                      DECIMAL (28, 15) NULL,
    [ScheduledPrincipalShortfall]                 DECIMAL (28, 15) NULL,
    [PrincipalShortfall]                          DECIMAL (28, 15) NULL,
    [PrincipalLoss]                               DECIMAL (28, 15) NULL,
    [InterestForPeriodShortfall]                  DECIMAL (28, 15) NULL,
    [InterestPaidOnPMTDateShortfall]              DECIMAL (28, 15) NULL,
    [CumulativeInterestPaidOnPMTDateShortfall]    DECIMAL (28, 15) NULL,
    [InterestShortfallLoss]                       DECIMAL (28, 15) NULL,
    [InterestShortfallRecovery]                   DECIMAL (28, 15) NULL,
    [BeginningFinancingBalance]                   DECIMAL (28, 15) NULL,
    [TotalFinancingDrawsCurtailmentsForPeriod]    DECIMAL (28, 15) NULL,
    [FinancingBalloon]                            DECIMAL (28, 15) NULL,
    [EndingFinancingBalance]                      DECIMAL (28, 15) NULL,
    [FinancingInterestPaid]                       DECIMAL (28, 15) NULL,
    [FinancingFeesPaid]                           DECIMAL (28, 15) NULL,
    [PeriodLeveredYield]                          DECIMAL (28, 15) NULL,
    [OrigFeeAccrual]                              DECIMAL (28, 15) NULL,
    [DiscountPremiumAccrual]                      DECIMAL (28, 15) NULL,
    [ExitFeeAccrual]                              DECIMAL (28, 15) NULL,
    [CreatedBy]                                   NVARCHAR (256)   NULL,
    [CreatedDate]                                 DATETIME         NULL,
    [UpdatedBy]                                   NVARCHAR (256)   NULL,
    [UpdatedDate]                                 DATETIME         NULL,
    [AllInCouponRate]                             DECIMAL (28, 15) NULL,
    [CleanCost]                                   DECIMAL (28, 15) NULL,
    [GrossDeferredFees]                           DECIMAL (28, 15) NULL,
    [DeferredFeesReceivable]                      DECIMAL (28, 15) NULL,
    [CleanCostPrice]                              DECIMAL (28, 15) NULL,
    [AmortizedCostPrice]                          DECIMAL (28, 15) NULL,
    [AdditionalFeeAccrual]                        DECIMAL (28, 15) NULL,
    [CapitalizedCostAccrual]                      DECIMAL (28, 15) NULL,
    [DailySpreadInterestbeforeStrippingRule]      DECIMAL (28, 15) NULL,
    [DailyLiborInterestbeforeStrippingRule]       DECIMAL (28, 15) NULL,
    [ReversalofPriorInterestAccrual]              DECIMAL (28, 15) NULL,
    [InterestReceivedinCurrentPeriod]             DECIMAL (28, 15) NULL,
    [CurrentPeriodInterestAccrual]                DECIMAL (28, 15) NULL,
    [TotalGAAPInterestFortheCurrentPeriod]        DECIMAL (28, 15) NULL,
    [InvestmentBasis]                             DECIMAL (28, 15) NULL,
    [CurrentPeriodInterestAccrualPeriodEnddate]   DECIMAL (28, 15) NULL,
    [LIBORPercentage]                             DECIMAL (28, 15) NULL,
    [SpreadPercentage]                            DECIMAL (28, 15) NULL,
    [AnalysisID]                                  UNIQUEIDENTIFIER NULL,
    [FeeStrippedforthePeriod]                     DECIMAL (28, 15) NULL,
    [PIKInterestPercentage]                       DECIMAL (28, 15) NULL,
    [AmortizedCost]                               DECIMAL (28, 15) NULL,
    [InterestSuspenseAccountActivityforthePeriod] DECIMAL (28, 15) NULL,
    [InterestSuspenseAccountBalance]              DECIMAL (28, 15) NULL,
    [AccumaltedDiscountPremiumBI]                 DECIMAL (28, 15) NULL,
    [AccumalatedCapitalizedCostBI]                DECIMAL (28, 15) NULL,
    [NoteID_EODPeriodEndDateBI]                   NVARCHAR (256)   NULL,

    [AllInBasisValuation]                          DECIMAL (28, 15) NULL,
    [AllInPIKRate]                                 DECIMAL (28, 15) NULL,
    [CurrentPeriodPIKInterestAccrualPeriodEnddate] DECIMAL (28, 15) NULL,
    [PIKInterestPaidForThePeriod]                  DECIMAL (28, 15) NULL,
    [PIKInterestAppliedForThePeriod]               DECIMAL (28, 15) NULL,
    [EndingPreCapPVBasis]                          DECIMAL (28, 15) NULL,
    [LevelYieldIncomeForThePeriod]                 DECIMAL (28, 15) NULL,
    [PVAmortTotalIncomeMethod]                     DECIMAL (28, 15) NULL,
    [EndingCleanCostLY]                            DECIMAL (28, 15) NULL,
    [EndingAccumAmort]                             DECIMAL (28, 15) NULL,
    [PVAmortForThePeriod]                          DECIMAL (28, 15) NULL,
    [EndingSLBasis]                                DECIMAL (28, 15) NULL,
    [SLAmortForThePeriod]                          DECIMAL (28, 15) NULL,
    [SLAmortOfTotalFeesInclInLY]                   DECIMAL (28, 15) NULL,
    [SLAmortOfDiscountPremium]                     DECIMAL (28, 15) NULL,
    [SLAmortOfCapCost]                             DECIMAL (28, 15) NULL,
    [EndingAccumSLAmort]                           DECIMAL (28, 15) NULL,
    [EndingPreCapGAAPBasis]                        DECIMAL (28, 15) NULL,
    [PIKPrincipalPaidForThePeriod]                 DECIMAL (28, 15) NULL
    CONSTRAINT [PK_NotePeriodicCalcIDStaging] PRIMARY KEY CLUSTERED ([NotePeriodicCalcID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [iNotePeriodicCalcStaging_NoteID_PeriodEndDate]
    ON [DW].[Staging_Cashflow]([NoteID] ASC, [PeriodEndDate] ASC);

